### ISSUE TITLE
Building a common site with docs from different loklak repositories

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_server#1003]
We have a number projects repositories. If we want to keep the documentation in each project repo, how could we generate a common developers documentation website?

An idea would be to create a common repo and run a script regularly that takes the docs from different repos.

Or any other idea?

How can this be implemented using different repositories and GitHub pages?

**Comment by sudheesh001** [comment]
CoderDojo maintains a repo specifically for documentation which I think they periodically build and deploy, but the problem of breaking the documentation from the code would be that they'll quickly go out of sync.

**Comment by yukiisbored** [comment]
@mariobehling We can setup multiple gh-pages for them like what we did with this repository and just give the links on the Navigation section.

**Comment by mariobehling** [comment]
@yukiisbored Yes, that is alwasys possible, but I do not see how we can host them on one subdomain though with github pages.

**Comment by yukiisbored** [comment]
@mariobehling I think it's impossible to host them on one subdomain (unless we have a server that we can run `nginx` on).

**Comment by mariobehling** [comment]
@yukiisbored Sure, agree. Server would always be possible, but we don't want to administer a server to keep the systems we need to take care of as few as possible. How can we run subdirectories of one subdomain on different github repos? I think it is not possible.

**Comment by mariobehling** [comment]
Ok, so an idea could be: We run the script as of now, but we deploy a gh-pages branch in another repository here: https://github.com/loklak/loklak/ in the gh-pages repo. Then the Readme.md will be the index.rst and other repos can be deployed into a subdirectory,

**Comment by aviaryan** [comment]
> Ok, so an idea could be: We run the script as of now, but we deploy a gh-pages branch in another repository here: https://github.com/loklak/loklak/ in the gh-pages repo. Then the Readme.md will be the index.rst and other repos can be deployed into a subdirectory,

Agreed. Different servers and same sub-domain is not possible in my knowledge, especially when all we have is GitHub Pages. So yes, the only solution that seems possible at this point is having a central repo for docs that belong on a server (or in a sub-domain). **Since GitHub repos are free and easy, I don't see any issues with this idea.** 
For susi, we can use a new repo called `fossasia/susi` or `fossasia/susi_compiled_docs` or `fossasia/susi_website`. Similarly we can create *holder* repos for other *master* projects as well. 

Now as far as how to do this is concerned, a Travis build script will always do the job but if we want to make something more robust and dependable, we can learn from this situation and implement something in [Documentation Apps Project](https://github.com/fossasia/labs.fossasia.org/issues/210).
One idea that I had for the project and that I have also included in my [proposal](https://docs.google.com/document/d/1kjb9MgZKrDR5dNsiW-sKpa-9mf_IqzfjuU3JD021nFQ/edit?usp=gmail) is that we create a module/tool that will build the docs and push it to a certain folder in a certain branch in a certain repo. I think a feature like this will be able to solve our problems. What do you think? @mariobehling @yukiisbored 

Related: https://github.com/fossasia/open-event-orga-server/issues/2957#issuecomment-272936107

**Comment by yukiisbored** [comment]
Whoops forgot to close this issue, because it's already solved on github.com/loklak/dev.loklak.org

**Comment by mariobehling** [comment]
@yukiisbored I think you missed my comment above https://github.com/loklak/loklak_server/issues/1003#issuecomment-272901839

The idea was to create the documentation page in the repo at https://github.com/loklak/loklak/

You now created a new repo at dev.loklak.org. This is fine, but we don't need several repos duplicating things.

The issue is not solved yet as the other loklak subprojects are not included in the documentation. The Readme.md here: https://github.com/loklak/loklak/blob/master/README.md (needs refinement) should be the start page of the documentation. All projects should go into the subtree.

What do you suggest now? Move the Readme to the new repo and delete the loklak/loklak repo?

**Comment by mariobehling** [comment]
@yukiisbored Could you include info in the Readme, how the documentation script can be triggered, please?

**Comment by mariobehling** [comment]
@aviaryan 

> Travis build script will always do the job.

The documentation project will deliver documentation in months. A travis script could do it in a few days. So, we need better documentation urgently. Please help to make it work. 

We also need to consider in detail how the documentation project could be versatile enough to work for different cases. This discussion should take place elsewhere. Probably in the GSoC application.

**Comment by aviaryan** [comment]
> @mariobehling : The documentation project will deliver documentation in months. A travis script could do it in a few days. So, we need better documentation urgently. Please help to make it work.

👍 As you already pointed out, first we need to decide on a *central* repo for storing the compiled stuff. Suppose let's go with [dev.loklak.org](https://github.com/loklak/dev.loklak.org/tree/gh-pages). Now it has the server docs at [/server](https://github.com/loklak/dev.loklak.org/tree/gh-pages/server). 
That's good but we will have to add docs for other projects. 
I see at https://loklak.github.io/loklak/ that there was a plan to include loklak_search docs at http://dev.loklak.org/search/ , loklak_apps docs at http://dev.loklak.org/webapps/ and so on .

All of these project follow a different way to store dev docs. After viewing them, I feel like we can create a build script in the *central* repo and it will have functions on how to deal with each repo. The built docs of each repo will be forwarded to their respective folders and a root README file (index of dev.loklak.org) will host the links to each of these folders. 
Each of the children repos will call this build script and everything else will be automatically done by the build script. 
I will try this technique and see how it goes on my fork and will send a PR soon. 😄 

> @mariobehling : What do you suggest now? Move the Readme to the new repo and delete the loklak/loklak repo?

+1 for this. Yes that would be the best way to go.

**Comment by yukiisbored** [comment]
@aviaryan The system has already been made on github.com/loklak/dev.loklak.org. I just need to create an caller script to update the subtrees on that repository. Don't reinvent something that's already working.

**Comment by aviaryan** [comment]
@yukiisbored I know and I wasn't going to start from scratch. Sorry for not being clear in my post. I was just tracing the steps following which, one can solve this issue. 
What I see is that there are 2 main things left to do:
1. Updating the index page of dev.loklak.org to point to sub-projects.
2. Adding other sub-projects docs apart from the already existing [loklak_server](http://dev.loklak.org/server/). We need to be careful here about [loklak_search](https://github.com/fossasia/loklak_search/tree/master) and [loklak_apps](https://github.com/fossasia/apps.loklak.org) projects as they have docs defined in the README.md of the master branch (or maybe there are no docs ATM). They are not like loklak_server where docs are stored in gh-pages branch. So it won't be as simple as updating config.csv. BTW, this task is still pretty doable. We will also have to trigger the build when any of the sub-project is updated. 

@yukiisbored: From your statement, I infer that you plan to do it. Let me know if I can be of some help. Cheers 🍺

**Comment by yukiisbored** [comment]
@aviaryan You can help by finding a way to create a portal page. I was thinking about linking them to each other in the TOC as defined inside the `README.rst` file.

**Comment by aviaryan** [comment]
@yukiisbored That sounds good. Creating a Sphinx TOC at root page will ensure that all documentations are well connected to each other. The root page can also include some general info on loklak project. 
BTW, have you thought about how will `loklak_server` docs be connected with the root page. Will it stand as an independent Sphinx project OR will it be in it (i.e. root TOC = loklak_server TOC)? 
Keeping scalability in mind, I think first approach is better i.e. root TOC has just 3 or `X` sub-projects and loklak_server TOC has its existing TOC + `(X-1)` sub-projects which are (loklak_search, loklak_apps and so on).  

Thoughts??
