### ISSUE TITLE
Binary Distribution

### ISSUE THREAD

**Issue by yukiisbored** [loklak/loklak_server#1008]
Currently Loklak distributes via `git` and the source code. To make deployment easier, we can distribute the a single JAR file to run Loklak.

**Comment by sudheesh001** [comment]
I think it's best to use `git tag` and tag a release. Let me look into this today.

**Comment by sudheesh001** [comment]
Update: V1 Released https://github.com/loklak/loklak_server/releases/tag/v1.0

**Comment by yukiisbored** [comment]
euhm, I'm not done yet :sweat_smile: The JAR files doesn't contain the default configuration and the HTML pages.

**Comment by yukiisbored** [comment]
We have to solve this first: https://github.com/loklak/loklak_server/issues/1007

**Comment by yukiisbored** [comment]
Also you uploaded the wrong JAR file, the jar file is on `build/libs/loklak_server-all.jar` and it can be built with `gradle shadowJar`

**Comment by yukiisbored** [comment]
Anyway, I think we should release every time we rebase development to master, and nightlies on development.

**Comment by sudheesh001** [comment]
> Also you uploaded the wrong JAR file, the jar file is on build/libs/loklak_server-all.jar and it can be built with gradle shadowJar

Did you test by running the `jar` ? I used ant to build it instead of gradle and i understand that the gradle release moves to `build/libs/`. Can you run the jar and see if it's executing correctly.

I agree with the release pattern. Master merge should create release and every other development should create a pre-release nightly.

**Comment by sudheesh001** [comment]
Updated the release with a compressed `build` along with all required dependencies and added an extra item. 

>Allows configuration of log4j and other parameters.

**Comment by yukiisbored** [comment]
@sudheesh001 It runs and runs nicely! https://asciinema.org/a/99867

**Comment by yukiisbored** [comment]
I actually have no idea how to achieve the same thing with `ant` (like Service merging and properly correct conflicts)
