### ISSUE TITLE
Unify documentation and implement function in script to generate documentation from different repositories

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_server#1014]
The documentation currently generates the loklak server documentation at dev.loklak.org. There are other sub projects that are part of the loklak project. A list of projects has been started at https://github.com/loklak/loklak

Please adapt the script of the loklak_server project and make it to generate a new page on each PR just as is.

Please use [this repository](https://github.com/loklak/loklak) for a gh-pages branch where all the documentation is kept as one website as follows:
* [ ] Use https://github.com/loklak/loklak/blob/master/README.md as a index page of the site
* [ ] Add sub projects in subfolders
   * [ ] Implement the Readme.md of each repository as an index page for each subproject
   * [ ] Add the /docs folder of each project (if it exists)
* [ ] Ensure navigation works
* [ ] Ensure images are working
* [ ] Ensure search is working across all projects

**Comment by yukiisbored** [comment]
Working on this.
[Repository](github.com/loklak/dev.loklak.org)

**Comment by mariobehling** [comment]
I am still getting a 404 on http://dev.loklak.org. Any idea?

**Comment by yukiisbored** [comment]
@mariobehling I'll invoke GitHub pages to rebuild it.

**Comment by yukiisbored** [comment]
It's up now ❤
