### ISSUE TITLE
Versioning system

### ISSUE THREAD

**Issue by yukiisbored** [loklak/loklak_server#1016]
Since we're able to release binaries for Loklak, it's a good idea to think of a versioning system. We can do the usual [Semantic Versioning](http://semver.org/), but with a couple of rules:
  1. Append `-pre` for nightly releases and add a number with a period before it to indicate how many nightly releases we have for the upcoming version like `-pre.1` for the next nightly release.
  2. Append `-release` for stable releases.

Like usual the numbers will indicate `MAJOR.MINOR.PATCH` and will have the same rules as semver.org. 

What do you guys think? I'm open for opinions and discussions regarding this.

**Comment by mariobehling** [comment]
Nobody minds if you would like to introduce versioning. Therefore I see this issue can be closed. If you want to release a version feel free to do so. Cheers
