### ISSUE TITLE
Highlight the code segments in the image rendered for markdown

### ISSUE THREAD

**Issue by sudheesh001** [loklak/loklak_server#102]
In case a user posts content via 
`<pre><code>` and `</code></pre>`
It'd be great if the server can highlight the code segment while generating the image ?

Is there a library like `Highlight.js` available for Java which could do this ?

**Comment by Orbiter** [comment]
The code is now rendered using a different colour. everything between one or three backticks is considered as code.

**Comment by sudheesh001** [comment]
@Orbiter would it be possible to find out keywords in the code and color them differently ?

**Comment by mariobehling** [comment]
@sudheesh001 Let's progress to other things, please. There are tons of things to do that have a higher priority. Discussions are always interesting, but we are still hoping to see more code from you.
