### ISSUE TITLE
Move to gradle build, remove ant build

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_server#1022]
Today loklak builds are based on libraries we ship within the git repository.
We should use gradle builds exclusive in the future.

We already have a gradle build which uses these libraries
```
repositories {
  flatDir {
    dirs 'lib'
  }
}
```
We should move to a build using maven libraries like 
```
repositories {
     mavenCentral()
}
```

also, we should use gradle run as start method.
All cloud deployment options must be migrated to use the gradle build process as well.

If this works, the libraries in lib should be removed.

**Comment by yukiisbored** [comment]
We already have a start task on Gradle. Do you want to make it into run instead?
