### ISSUE TITLE
Create contributor guide page

### ISSUE THREAD

**Issue by AnaghHegde** [loklak/loklak_server#1023]
Currently `README.md` page contains lot of information, also contains some information related to contributors guide but its not solid. So its better to divide the `README.md` into : 

1.contributor-guide page and give a link from readme to contributor-guide page
     
   - This contains all the contents under the sub head `How to compile using Gradle?` and 
      `How do I install Susi: Download, Build, Run`.  
   
2.documentation page give a link from readme to documentation page 
   
   - This will have all the contents under the sub head `Where can I find documentation?` 

Remaining information will be there in `README.md` and it also contains links to both of of these pages.

Reasons to do so : 

* Looks good. 

* It will be easy to maintain.

* Removes unnecessary( not required in readme but in some other doc) contents from `readme.md`.

**Comment by yukiisbored** [comment]
Hello, We already have it on dev.loklak.org. Do you have any suggestions or what kind of documentations we should add?

**Comment by AnaghHegde** [comment]
@yukiisbored Even the `dev.loklak.org` has the same contents of `README.md` file. Its not organised. It contains irrelevant data. It looks good if its divided into multiple files. This applies to `readme` file also. 
It also doesn't contain any info on the branch policy.

**Comment by yukiisbored** [comment]
@AnaghHegde Euhm, look at the side panel

**Comment by AnaghHegde** [comment]
@yukiisbored ok then why does the home page of [](dev.loklak.org) contains all the information in readme?  Its repeated right ?. I am not saying contributor guide is not there. I am saying its just not organised. It needs refactoring in such a way that everything will be in a organised manner. None of them doesn't say anything about `How to contribute?` - creating PR, branch policy.  So i thought it will be good to have all those ?

**Comment by mariobehling** [comment]
@AnaghHegde There are always pros and cons of separating pages or keeping all info on one page. A reason for separation was often to reduce load times in the past. A reason for keeping it one page is to make it easier for mobile phone users sometimes. For the moment we have decided to keep info on one page.

A big improvement would be to get the documentation of all loklak components into one page. This is really what we need as the moment. Next step would be then to adapt the dev site to the style of the loklak services.

This would be an improvement benefiting project. It would be great, if you could help on this area. If we really want to change the md files, we can do that later at any time, but right now, we actually need help with the code. Please help solving some coding problems. 

Closing this issue therefore.

**Comment by AnaghHegde** [comment]
@mariobehling ok sure. I will work on that.
