### ISSUE TITLE
Automatic deployment to heroku failing

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_server#1029]
After the last update of the script the deployment to Heroku is failing. Please help to make it run again.

Check at http://loklak-server-dev.heroku.com

**Comment by jig08** [comment]
@mariobehling @yukiisbored Seems to pass now. Guess we can close it now..

**Comment by mariobehling** [comment]
Build failed
There was an issue building your app. Please ensure your app is deployable to Heroku and try again.
-----> Java (using Apache Ant 1.9.8) app detected
-----> Installing OpenJDK 1.8... done
-----> Installing Apache Ant 1.9.8..... [start]
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
 !     Push rejected, failed to compile Java (using Apache Ant 1.9.8) app.
 !     Push failed

**Comment by yukiisbored** [comment]
It looks like the link for Apache Ant on the build pack is dead. Since, we're going to move to Gradle now. We can use a gradle buildpack that I made while doing GCI. Here's the repo for it: https://github.com/yukiisbored/heroku_buildpack_gradle_loklak

**Comment by yukiisbored** [comment]
It's up now http://loklak-server-dev.heroku.com ✨👏

**Comment by mariobehling** [comment]
@yukiisbored Nice work! Please merge it to the buildpack repo and rename the repo in loklak. Let's have all project related stuff here.
