### ISSUE TITLE
Clean up unused files in html folder of repository

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_server#1032]
Please do the following:
* [ ] delete `/html/apps` except the accounting apps for the moment as they are not working on the apps page. We are hosting apps on http://apps.loklak.org already
* [ ] delete `/html/artwork`. It has been moved to its own repo already https://github.com/loklak/loklak_artwork
* [ ] delete other unused files, e.g. javadoc.html is already in dev.loklak.org, so not needed here

**Comment by KukkadapuSushma** [comment]
I would like to work on this issue @mariobehling

**Comment by KukkadapuSushma** [comment]
I have finished it, 
- Removed /html/apps (Except accounting apps)
- Deleted /html/artwork
- Deleted unused files. 

Here's the PR : https://github.com/loklak/loklak_server/pull/1037  (Along with other commit it is!)
