### ISSUE TITLE
Write an overview of loklak projects for about page

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_server#1033]
We have a number of loklak projects. The current about page does not cover all of these projects yet. Write a concise overview of the projects.

**Comment by mad3E7cat** [comment]
Do you need it for README.md or for the text on the main page of loklak.org?

**Comment by niccokunzmann** [comment]
I agree that one would want to see it in both locations.
I would say you can choose what you like best. We can reference it from the other locations. It can be moved if requirements change. Thanks for asking!

**Comment by mad3E7cat** [comment]
My idea is to look through all the READMEs and try to make it more informative. Is that what you wanted?

**Comment by yukiisbored** [comment]
No, this issue is to add overviews to other loklak projects like app.loklak.org, the loklak APIs, etc.

**Comment by yukiisbored** [comment]
https://github.com/loklak/loklak_server/commit/681736a52f274db5d6d3d01981cdd99900d442c9 still doesn't give an overview about loklak projects.
Sorry about that, I'm pretty sleepy atm.

**Comment by mad3E7cat** [comment]
I understand that, working now.
