### ISSUE TITLE
Fix Windows batch scripts

### ISSUE THREAD

**Issue by yukiisbored** [loklak/loklak_server#1035]
The windows batch scripts are broken due to the deletion of the lib folder. It should be modified to just use the uber JAR file located at `build/libs/loklak_server-all.jar`.

**Comment by yukiisbored** [comment]
I can't do this issue because I don't have a Windows machine.

**Comment by KukkadapuSushma** [comment]
I can work on this!

**Comment by KukkadapuSushma** [comment]
Yup i can fix this!

**Comment by KukkadapuSushma** [comment]
#1037 - PR

**Comment by yukiisbored** [comment]
@KukkadapuSushma To automatically close the issue when your commit is merged, just add `Closes <link to commit>` or `Fixes <link to commit>` in your commit message, preferably the botttom of it.
