### ISSUE TITLE
Test on Appveyor

### ISSUE THREAD

**Issue by jayvdb** [loklak/loklak_server#1038]
AppVeyor allows Windows testing.

**Comment by yukiisbored** [comment]
I think it's better to do https://github.com/loklak/loklak_server/issues/1036 first, but I don't see it blocking this.

**Comment by mariobehling** [comment]
Ok, could be nice, but we are currently focusing on deployment on Linux and this is out of scope of current dev focus. Please re-open if you are interested to take this issue up.
