### ISSUE TITLE
Would there be a performance increase with these java options?

### ISSUE THREAD

**Issue by smokingwheels** [loklak/loklak_server#104]
See [url]http://www.minecraftforum.net/forums/support/server-support/server-administration/1937726-java-7-8-command-line-options-for-minecraft[/url]
My minecraft CPU usage was around 40% just at idle now 3-4%.
Not to sure what all of them do so someone would have to test it because I don't have a Loklak server for the moment.
Also setting up the program to run in a small RAM disk would take some doing to store the data some where else.

Java 7:
-Xmn2G -Xss4M -Xms4G -Xmx4G -XX:+UseLargePages -XX:PermSize=256M -XX:+AggressiveOpts -XX:+UseFastAccessorMethods -XX:+UseStringCache -XX:+OptimizeStringConcat -XX:+UseCompressedStrings -XX:+UseBiasedLocking -Xincgc -XX:MaxGCPauseMillis=10 -XX:SoftRefLRUPolicyMSPerMB=10000 -XX:+CMSParallelRemarkEnabled -XX:ParallelGCThreads=10 -Djava.net.preferIPv4Stack=true

Java 8:
-Xmn2G -Xss4M -Xms4G -Xmx4G -XX:+UseLargePages -XX:+AggressiveOpts -XX:+UseFastAccessorMethods -XX:+OptimizeStringConcat -XX:+UseBiasedLocking -Xincgc -XX:MaxGCPauseMillis=10 -XX:SoftRefLRUPolicyMSPerMB=10000 -XX:+CMSParallelRemarkEnabled -XX:ParallelGCThreads=10 -Djava.net.preferIPv4Stack=true

What do you think?

**Comment by Orbiter** [comment]
By now there are no large performance issues. I believe compatibiliyt to many systems is in the foreground. Furthermore, we currently don't have a system to make custom startup options like it is in YaCy. At this time I would like to keep the startup option set as simple as possibe.
But thank you for the suggestion. I will maybe consider that later.
