### ISSUE TITLE
Searching emoji on loklak api does not work

### ISSUE THREAD

**Issue by vibhcool** [loklak/loklak_server#1040]
searching emoji with loklak api doesn't work.

this isn't working -> http://loklak.org/api/search.json?q=%20%F0%9F%87%BA%F0%9F%87%B8

but is working for -> https://www.google.co.in/?#q=%F0%9F%87%BA%F0%9F%87%B8

**Comment by jig08** [comment]
@vibhcool Would you like to take this up ?

**Comment by vibhcool** [comment]
i will like to take this up , but i need some guidance

**Comment by yukiisbored** [comment]
@vibhcool The search handler is on `org.loklak.api.search.SearchServlet`. Feel free to ask us on gitter if you're having an issue.

**Comment by singhpratyush** [comment]
The following links may be helpful -
https://jolicode.com/blog/search-for-emoji-with-elasticsearch
https://github.com/jolicode/emoji-search/tree/master/esplugin

**Comment by vibhcool** [comment]
@yukiisbored @singhpratyush thank you for the hints :D , i am exploring the code and seeing how i can fix it :)

**Comment by vibhcool** [comment]
If anyone wants to work on this may take up :) . 
I will not be able to work on this due to incapability issues.

**Comment by kavithaenair** [comment]
I think this is working perfectly fine.
i tried these queries:
http://loklak.org/api/search.json?q=%F0%9F%8E%88
http://loklak.org/api/search.json?q=%F0%9F%98%8A

**Comment by vibhcool** [comment]
It seems twitter has added capability to search emojis.
we shall close this issue 😄

**Comment by singhpratyush** [comment]
Great!
