### ISSUE TITLE
Line break the text content present in the map tile if longer than width

### ISSUE THREAD

**Issue by sudheesh001** [loklak/loklak_server#105]
eg. https://twitter.com/sudheesh001/status/628900854003699712

The small text version of the tweet that's present on the generated map tile image should ideally be broken into 2 lines if the complete text can't be placed on the image. There a very small portion of the tweet that doesn't appear here in the map tile.

**Comment by daminisatya** [comment]
@sudheesh001 Is this bug still open?

**Comment by sudheesh001** [comment]
Yes it still is 👍  @daminisatya

**Comment by mariobehling** [comment]
@sudheesh001 As you are part of the team, please confirm this still happens and help to solve it, if it is still required. Otherwise close this issue.

**Comment by mariobehling** [comment]
As loklak_search will take care of the front end, I am closing this.
