### ISSUE TITLE
Docker: Add volume path

### ISSUE THREAD

**Issue by niccokunzmann** [loklak/loklak_server#1051]
- Issue type: Bug report/Feature request 

### Short description

Currently, the docker image does not have a volume nor do i know where the data is stored that should be available when a new loklak version appears

### Expected behaviour

I would like to have a volume in

- [ ] Dockerfile
- [ ] docker-compose.yml

### Actual behaviour

There is no volume. I suppose, once the image is updated, all data is lost.

### Usecase

With the volume, I can update the docke rimage to the latest version automatically
### Description

There should be a volume for every folder that should be kept from image to image.
Steps to resolve:

- [X] read about docker volumes if they are updated to later versions  
  According to the documentation "Changes to a data volume will not be included when you update an image." - [source](https://docs.docker.com/engine/tutorials/dockervolumes/#data-volumes)
- [X] find all folders with data  
  The folder is "data" which translates to "/app/data" in the container
- add the folders as a volume
  - [ ] to Dockerfile 
    This allows persistence and saving the data when running one image
  - [ ] to docker-compose.yml
    This allows storing the data, when the image is updated to the latest version

**Comment by yukiisbored** [comment]
Every runtime generated data is always stored on `data/`.

**Comment by itspritish** [comment]
I's looking for a first-timer-only and found few, but i thought this one i could give a try as i have some hands on with docker. I could try if i get some help to reproduce this issue on my Ubuntu.

**Comment by niccokunzmann** [comment]
Sure, please go ahead. If you have any questions, you can ask!

**Comment by itspritish** [comment]
Ran loklak server as standalone and as a docker container. The folder that i see getting created/ updated are mostly in /loklak_server/data/ like index, dump folders. Also the data/loklak.log file grew pretty heavily. So is this the folder that need to be mapped to volume? 
If so this can be added in Dockerfile/ docker-compose.yml. BTW for some reason it doesn't allow me to just use /data as volume mapped folder. No folder gets created inside the container upon start. So I'm forced to add /loklak_server/data.

**Comment by niccokunzmann** [comment]
> are more?

yukiisbored suggested that folder. I assume it is the only one.

**Comment by itspritish** [comment]
Observed something (issue?) when i use docker-compose build/ up. It does not generate loklak.log file in loklak_server/data folder, it rather starts printing the log on the command console. I also tried docker-compose up -d option, no logs, neither in /data nor on the console. I initially thought it might be related to my changes, but its not. 
Did few trials, for me the happy path was build with Dockerfile or directly using the git url and then manual start of the webserver from within the container. Pls let me know if i've missed something.

Btw, i have my changes are ready in my fork for your reference, will raise PR.

**Comment by niccokunzmann** [comment]
Thanks, yes. Let us talk about the PR.
As far as I remember, the logs go to the output when we use docker.

**Comment by yukiisbored** [comment]
The `-d` or `--daemonize` flag in `docker-compose up -d` means it'll fork into the background. Meaning it'll leave your shell and stays in the background. Well, that's daemonizing in general. but in `docker-compose` case, it just runs it without giving you the outputs from the container.
