### ISSUE TITLE
Create introduction issues

### ISSUE THREAD

**Issue by niccokunzmann** [loklak/loklak_server#1056]
- Issue type: Feature request 

### Short description

I would like to see some issues for people who want to get into loklak development
Specifically #1051 is such an issue which is made easy, now.

### Expected behaviour

I would like to see issues labeled as "[first-timers-only](https://github.com/search?utf8=%E2%9C%93&q=label%3Afirst-timers-only+is%3Aopen&type=Issues&ref=searchresults)"

### Actual behaviour

I do not see such issues.

### Usecase

For people who want to contribute for the first time to loklak, having a number of issues which are solvable by a developer in under 3 minutes, allows introducing them.

### Description

- [x] create the first-timers-only label
- [x] tag at least 5 issues with it [count](https://github.com/loklak/loklak_server/issues?q=is%3Aissue+is%3Aopen+label%3Afirst-timers-only)
- [ ] document what it means
  - These issues should be let open but can be solved if they are important
  - 3 minutes to solve condition
- [x] link on http://up-for-grabs.net/

**Comment by niccokunzmann** [comment]
https://github.com/up-for-grabs/up-for-grabs.net/pull/575 - up for graps

**Comment by niccokunzmann** [comment]
Closing this as up-for-grabs/up-for-grabs.net#575 is beyond the reach of this project

**Comment by sudheesh001** [comment]
This sounds good ! 👍

**Comment by mariobehling** [comment]
This was great for GCI, but right now the number of contributors is limited and we are happy if anyone takes up any issues and just gets started. Also, "create an issue" is not really an issue itself, that should stay open for long. Thanks for the directions and intiative. Let's proceed from here.
