### ISSUE TITLE
Increase default Xmx value

### ISSUE THREAD

**Issue by yukiisbored** [loklak/loklak_server#1060]
Continuation of https://github.com/loklak/loklak_server/issues/1049.

Due to "first timers" problems regarding Loklak running out of memory is due to the fact the default allocated memory for Java is set to 600 MB by default (defined here https://github.com/loklak/loklak_server/blob/development/conf/config.properties#L102).

I think it should be increased because Loklak requires more than 600 MB and 600 MB is not enough to run Loklak for a day or two.

**Comment by vibhcool** [comment]
If no one is fixing this, can I see to this issue? :)

**Comment by yukiisbored** [comment]
@vibhcool sure, feel free to fix it :)

**Comment by vibhcool** [comment]
#1062 fixes this issue :)

**Comment by yukiisbored** [comment]
No need to mention it here. GitHub will show it if the issue link is mentioned inside the commit message.

**Comment by vibhcool** [comment]
Oops, sometimes I forget that this isn't pagure, it is github :D
