### ISSUE TITLE
Tweet URL in Markdown README is broken

### ISSUE THREAD

**Issue by rogersachan** [loklak/loklak_server#1067]
- Issue type: Bug report

### Short description

The Twitter tweet url in the README is broken

### Steps to reproduce

1. Navigate to repo on github

### Expected behaviour
Working button

### Actual behaviour
Image with broken URL

**Comment by niccokunzmann** [comment]
You provided a pull-request at #1066.

**Comment by rogersachan** [comment]
@niccokunzmann #1068
