### ISSUE TITLE
Include reverse geojson info if location is available.

### ISSUE THREAD

**Issue by fuksi** [loklak/loklak_server#107]
Example request: http://localhost:9000/api/user.json?screen_name=phucdn2005&following=100

One of the result:
```json
....
      "screen_name" : "codinghorror",
....
      "location" : "Bay Area, CA",
....
```

Is it possible that geo location can be calculated from the server and added to the result if `location` is not empty? A reverse geojson requested can be made but it's unnecessary from the client and the would be too many of them.

**Comment by Orbiter** [comment]
The reverse geocode is already made. If you don't get a coordinate, then possibly the reverse geocode lookup failed, like http://localhost:9000/api/geocode.json?data={%22places%22:[%22Bay%20Area,%20CA%22]} shows no results.
