### ISSUE TITLE
Improve Code Quality following the Codacy Metric

### ISSUE THREAD

**Issue by niccokunzmann** [loklak/loklak_server#1070]
- Issue type: Bug report 

### Short description

[Codacy][issues] shows a lot of issues with the current code.
Remove such an issue.

### Steps to follow

1. Go to the [Codacy issues][issues], you may sort them by file.
2. Remove an issue in the code without changing the behavior of the code.
3. commit:
  - Reference this issue
  - link to the codacy issue in the extended description (two newlines)
4. Create a pull-request to see if the issue was resolved and the codacy count increased.

### Usecase

Improving the code quality not only speeds up development.
It is also a great way for new contributors to enter the project (setup, workflow, community) without worrying too much about the complexity.

[issues]: https://www.codacy.com/app/sudheesh1995/loklak_server/issues?&filters=W3siaWQiOiJMYW5ndWFnZSIsInZhbHVlcyI6W251bGxdfSx7ImlkIjoiQ2F0ZWdvcnkiLCJ2YWx1ZXMiOltudWxsXX0seyJpZCI6IkxldmVsIiwidmFsdWVzIjpbIkVycm9yIl19LHsiaWQiOiJQYXR0ZXJuIiwidmFsdWVzIjpbbnVsbF19LHsiaWQiOiJBdXRob3IiLCJ2YWx1ZXMiOltudWxsXX1d

**Comment by vibhcool** [comment]
@yukiisbored , this issue has hundreds of codacy issues in it , I have just solved 4 python codacy issues. This issue isn't completely solved.

**Comment by jig08** [comment]
>@yukiisbored , this issue has hundreds of codacy issues in it , I have just solved 4 python codacy issues. This issue isn't completely solved.

Re-opening this.

**Comment by yukiisbored** [comment]
@vibhcool I didn't close it, GitHub did. *Sigh*, now they'll close every commit messages containing the issue link, huh?

**Comment by yukiisbored** [comment]
As far as I remember, GitHub only closes `Fixes <issue link>` and `Closes <issue link>`

**Comment by vibhcool** [comment]
@yukiisbored ,  oops, my bad, I didn't know that. I will take care next time. 
hehe, github loves automation :)

**Comment by singhpratyush** [comment]
This is not fixed yet.

**Comment by kavithaenair** [comment]
@daminisatya can you please reopen this issue.

**Comment by singhpratyush** [comment]
Not fixed yet. Please reopen.
