### ISSUE TITLE
Travis: remove download error

### ISSUE THREAD

**Issue by niccokunzmann** [loklak/loklak_server#1071]
- Issue type: Bug report

### Short description

Sometimes and unreliably, travis fails to build.
This seems to be due to a failure to download files.

### Environment

 - Operating system: Travis build

### Steps to reproduce

This is hard because it is not reliable. 
[log.txt](https://github.com/loklak/loklak_server/files/853656/log.txt)

1. Create a pull-request
2. Wait for travis to succeed
3. Restart travis until it fails.

### Expected behaviour

I would like travis to work reliably.

### Actual behaviour

Sometimes travis fails and needs to be restarted to become green.

[source](https://travis-ci.org/loklak/loklak_server/builds/212814148#L848) and [log.txt](https://github.com/loklak/loklak_server/files/853656/log.txt):
```
Download https://repo1.maven.org/maven2/org/springframework/spring-aop/4.0.0.RELEASE/spring-aop-4.0.0.RELEASE.pom
FAILURE: Build failed with an exception.
* What went wrong:
Could not resolve all dependencies for configuration ':compileClasspath'.
> Could not resolve org.antlr:antlr-runtime:3.5.
  Required by:
      project :
   > Could not resolve org.antlr:antlr-runtime:3.5.
      > Could not get resource 'https://repo1.maven.org/maven2/org/antlr/antlr-runtime/3.5/antlr-runtime-3.5.pom'.
         > Could not GET 'https://repo1.maven.org/maven2/org/antlr/antlr-runtime/3.5/antlr-runtime-3.5.pom'.
            > Connect to repo1.maven.org:443 [repo1.maven.org/151.101.44.209] failed: Operation timed out (Connection timed out)
```

### Usecase

A reliable CI allows us and new contributors to be sure about the build status.

### Description

I do not really know how to fix this.
I suppose you can add the maven files which are downloaded to a travis cache, so they are retrieved from travis and not from the internet with unreliable domain name resolution.

**Comment by mariobehling** [comment]
Yes, it is true, but this issue is related to travis not to loklak. Closing it therefore.
