### ISSUE TITLE
API returns link of post instead of image that is in the tweet text

### ISSUE THREAD

**Issue by vibhcool** [loklak/loklak_server#1072]
When we search for a keyword in loklak, it returns link of post having image (in tweettext) instead of image link

**Comment by vibhcool** [comment]
I am working on this issue

**Comment by niccokunzmann** [comment]
Can you post an example?

**Comment by vibhcool** [comment]
yep, exactly @Achint08 @niccokunzmann

**Comment by vibhcool** [comment]
Closing this issue, fixed by @Orbiter
