### ISSUE TITLE
HTML Liquid code not working on loklak homepage

### ISSUE THREAD

**Issue by aviaryan** [loklak/loklak_server#1078]
- Issue type: Bug report

### Short description
http://loklak.org homepage is unable to run dynamic code in HTML / liquid syntax is being outputted as is. This is what I see.
![screen shot 2017-03-27 at 10 21 19 am](https://cloud.githubusercontent.com/assets/4047597/24341418/28a3ac50-12d7-11e7-9309-b45457fc1ab9.png)

More specifically this -
```
{{(index.messages.size > 0) ? " hosting " + (index.messages.size | number : fractionSize) + " messages for " + (index.users.size | number : fractionSize) + " users." : ""}} 
{{(index.messages.size > 0 && index.mps > 0) ? "Collection Speed: " + index.mps + " message" + (index.mps > 1 ? "s" : "") + " per second; " + ((index.mps * 86400) | number : fractionSize) + " messages per day." : ""}}  
```

### Environment

 - Operating system: OSX El Capitan (Safari browser)
 - Software version: 
 - Software source: 

### Steps to reproduce
1. Open http://loklak.org

### Expected behaviour
Liquid syntax should be compiled on the server.

### Actual behaviour
Liquid syntax is getting printed as is, like if it isn't getting compiled.

**Comment by jig08** [comment]
@aviaryan Thanks for the report, but it seems to work just fine for me in the exact same environment.

**Comment by aviaryan** [comment]
@jig08 Well, now it is working here too.. 😕 Weird!! I tried refreshing the page multiple times earlier this day, but had no luck. And now it's fixed.
Btw, please feel free to close this issue.

**Comment by yukiisbored** [comment]
@aviaryan This happened due to the fact the Javascript isn't loaded properly. Most likely due to bad internet connection which causes delays/corruption to the scripts used.
