### ISSUE TITLE
Add API endpoint to serve mood related data

### ISSUE THREAD

**Issue by singhpratyush** [loklak/loklak_server#1086]
- Issue type: Feature request 

### Short description

There is an analyzer aleady in place. The aim is to provide a way to access information related to it.

### Usecase

* Provide aggregated data from analyzer.
* Also provide data based on location.
* Allow filtering of data based on classes assigned by analyzer.

### Description

I plan to use this endpoint for [/fossasia/labs.fossasia.org/#136](https://github.com/fossasia/labs.fossasia.org/issues/136). This can also be used in other projects of similar nature.

**Comment by sudheesh001** [comment]
A part of this feature already exists. https://github.com/loklak/loklak_server/blob/751ff729058833f4bea39c8e019490539c25a81d/src/org/loklak/data/Classifier.java

**Comment by singhpratyush** [comment]
The tweets returned from existing APIs do contain an emotion class with some accuracy measure. But there are no ways to request tweets based on these classes.

*My requirement* from this endpoint is to fetch statistical data about from this emotion classifier based on geographical location. As of now, I was thinking of some aggregated numbers that would give the number of Tweets in each category, and a relative score to each of the categories.

But I think that it can be more generalized. @sudheesh001: Please suggest something for this?

**Comment by yukiisbored** [comment]
@singhpratyush You can always use the search endpoint and just grab the geodata.

**Comment by singhpratyush** [comment]
@yukiisbored: Yes, we can get Tweet's geodata using search endpoint, along with an emotional class. We can also collect this data for some time on a client and generate results about the mood of people in different parts of the world.

But most of the clients (for the mentioned project) are not going to stay long enough to wait for data to come. Also, this technique will unnecessarily make the server serve redundant data to clients, most of which will not be used by it (like tweets' text if we just want to show the numbers).

A better approach for this would be making the server to store some curated information derived from the emotion classifier and serve it whenever a client asks for it.

**Comment by singhpratyush** [comment]
Added as `/api/classifier.json`.
