### ISSUE TITLE
Place name and location when using the /location parameter is buggy.

### ISSUE THREAD

**Issue by aneeshd16** [loklak/loklak_server#109]
For example, in this query: http://loklak.org/api/search.json?timezoneOffset=-330&q=%23windows10+%2Flocation#windows10 /location
A lot of tweets have the same Place name which seems highly unlikely. 
I am not sure about this but I think the place name for the first tweet in the results is being copied over to the next few tweets.

**Comment by mariobehling** [comment]
I cannot verify that this bug still exists. All seems to be fine and working now. Closing this issue therefore.
