### ISSUE TITLE
Deployment fails because of insufficient access rights

### ISSUE THREAD

**Issue by niccokunzmann** [loklak/loklak_server#1091]
- Issue type: Bug report 

### Short description

The current travis build fails because it can not push the documentation to the [dev.loklak.org][repo] repository.

### Environment

 - Operating system: [Travis][error]

[error]: https://travis-ci.org/loklak/loklak_server/builds/217449064#L1645

### Steps to reproduce

1. Visit the [error page][error]
2. restart the build

### Expected behaviour

I would like that travis can push the changes.

### Actual behaviour

Travis can not push to the github repository because it had insufficient access rights.
It seems the deploy key was not added to the [repository][repo]

[repo]: https://github.com/loklak/dev.loklak.org

### Usecase

This feature updates the documentation.

### Description

I would like the development loklak build to push the changes to [dev.loklak.org][repo]

**Comment by yukiisbored** [comment]
Oops, I forgot to add the deploy key. I'll add it ASAP.

**Comment by yukiisbored** [comment]
Oh wow, GitHub doesn't allow one key for multiple projects :(
Gonna generate a new one.

**Comment by yukiisbored** [comment]
Sorry for the really really really messy commits, probably due to myself being depressed atm. But, it builds :)
https://travis-ci.org/loklak/loklak_server/builds/217718841
