### ISSUE TITLE
Avoid scroll bar inside page on dumps page

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_server#1101]
The dumps page has an internal scroll bar. It should not have one.

![screenshot from 2017-04-14 11-09-37](https://cloud.githubusercontent.com/assets/1583873/25039326/4999588a-2103-11e7-83a9-66d0d67cc470.png)

**Comment by vibhcool** [comment]
@mariobehling this issue could be added as first-timer issue :)

**Comment by mariobehling** [comment]
@vibhcool Ok, so we had a lot of first-timer issues and no first-timers took it up. I now deleted the label.

Let's really get issues solved, whatever comes up. There are a lot of old issues. A lot of people applied for loklak GSoC. If people really want to do successful projects with loklak, then we need to see contributions and issues solved. I personally do not care if issues are easy or not. We hope to see things getting done and any contribution is appreciated. There has been a lot of discussions in some issues. We have other projects at FOSSASIA where there are some very focused discussions and not so much talk, but lots of code gets done. How can we get there in loklak? 

@vibhcool Maybe no need to respond, but rather fix the issue. 
Thanks.

**Comment by yukiisbored** [comment]
This is because it's just an iframe ...

**Comment by mariobehling** [comment]
@yukiisbored Yes, would be great to get a solution.

**Comment by singhpratyush** [comment]
This can be solved by injecting a JS eventlistener which would resize iframe on load. Shall I take it?

**Comment by Orbiter** [comment]
well, https://github.com/loklak/loklak_server/pull/1102 does not do the complete job because the event is not firing. I tested this on a Mac with Chrome and Firefox.

**Comment by singhpratyush** [comment]
@Orbiter: Sorry for the trouble.

Even `DOMContentLoaded` doesn't fires. So I added `onload` to the `iframe` and its working now ([LINK](https://github.com/singhpratyush/loklak_server/commit/0c36185255e307494aa79ae6392d62cc7fb4d907)).

How shall I proceed with this?

**Comment by Orbiter** [comment]
fixed with https://github.com/loklak/loklak_server/commit/cc0948865a80b1217d32a1776efc7139d7402ab9
