### ISSUE TITLE
Unify Readme.md and rst

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_server#1105]
Currently we have a Readme.md and Readme.rst. 

I am loosing track which one has the last version and where are difference. Please unify both files. Best would be to just keep the md file and use it in generating the documentation.

**Comment by pri22296** [comment]
@mariobehling We can setup an automatic conversion of README.md to README.rst in travis while generating the documentation. [pandoc](http://pandoc.org/) is a good tool for that.
