### ISSUE TITLE
Move Dockerfile-learnings.md to /docs and add it into documentation structure

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_server#1107]
The file Dockerfile-learnings.md has been added into the main folder. Expected: All documentation should go into /docs and be integrated into the documentation structure that is also deployed to dev.loklak.org.

**Comment by singhpratyush** [comment]
@mariobehling: I think that this was fixed in 52ce5bdaa3b3f2970ab672faacf149ae3ef3c955.
