### ISSUE TITLE
Fix any spelling mistakes in documentation

### ISSUE THREAD

**Issue by sudheesh001** [loklak/loklak_server#1108]
- Issue type: Bug report

### Short description
```
### How do I setup loklak on Eclipse?

To install loklak on Eclipes, please refer to the [loklak Eclipse readme](/docs/development/eclipseSetup.md).
```

Markdown content in ReadMe contains the wrong spelling of `Eclipse` this needs to be fixed. A good easy beginner patch.

**Comment by kavithaenair** [comment]
i will fix this @sudheesh001

**Comment by kavithaenair** [comment]
@sudheesh001  i have fixed the typos but i already have a existing PR , in which am asked to make some changes. So what can i do now for this issue? Should i create a PR?

**Comment by niccokunzmann** [comment]
@kavithaenair I believe, you can create a new pull-request so we can merge the changes.

**Comment by kavithaenair** [comment]
@niccokunzmann  But the existing PR isn't merged and am not able to create a new PR. The commit made by me now is also shown in the same PR.Can you help me out?

**Comment by sudheesh001** [comment]
@kavithaenair I've reviewed your patch on the pending Pull request. It now has 2 commits solving 2 seperate issues which is totally fine. But please remember from next time onwards send a pull request from a branch that you create than from the `development` branch itself.

**Comment by kavithaenair** [comment]
Thank You @sudheesh001 . I will definitely follow , what you've said.
