### ISSUE TITLE
Additional constraints for images,videos not giving results restricted to media

### ISSUE THREAD

**Issue by Achint08** [loklak/loklak_server#1112]
- Issue type: Bug report 

### Short description

Searching for Query /image /audio /video /place , it is expected results to get restricted to tweets which have attached images, audio, video or place.  Searching for http://api.loklak.org/api/search.json?timezoneOffset =-330&q=fossasia+%2Fvideo doesn't give tweets restricted to videos. Same goes for /image.

**Comment by vibhcool** [comment]
Please assign this issue to me. I want to work on this issue

**Comment by Achint08** [comment]
@vibhcool You can start working on it asap. This issue is important so that we can proceed on loklak search with more features. Thank you. :)

**Comment by daminisatya** [comment]
@vibhcool assigned!

**Comment by singhpratyush** [comment]
@Achint08: You should be searching for \image and not /image.
