### ISSUE TITLE
Add Gemnasium Button 

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_server#1123]
Please add a gemnasium button to the Readme.md.

**Comment by mariobehling** [comment]
This should be added to the rst file as well.

**Comment by kavithaenair** [comment]
I'll make changes in the rst file

**Comment by kavithaenair** [comment]
@mariobehling  is this fine? Because dependencies is not not getting fit in the same horizontal line.
![screenshot 29](https://cloud.githubusercontent.com/assets/18421291/25801868/46283596-340d-11e7-917f-c67222a82951.png)
