### ISSUE TITLE
New API call for Multi-Scraper output

### ISSUE THREAD

**Issue by vibhcool** [loklak/loklak_server#1129]
### Issue type: Question, Discussion

**At present**, calls like 'localhost:9000/api/search.json?q=fossasia' returns all tweets related to search query 'fossasia'

In my GSOC project, **I proposed to** also collect search results from other scrapers also.

Now there can be different approaches (that I thought of) whether to replace present system with the new one or we shall have a new API call for **multi-scraper output (output results from multiple scrapers )** to retain the present system and have both.

## Approaches I came with
**Now If we replace** :-
1) this call '/api/search.json?q=fossasia' will output results from multiple scrapers
2) there is a get attribute 'source' which can be used to get tweets, that is, source=twitter

**If we add new API call** :-
This will retain the present api call '/api/search.json?q=fossasia' and add a new one for multi-scraper.

## So with what approach we shall proceed with or any other approach we can use?

**Comment by Orbiter** [comment]
In https://github.com/loklak/loklak_server/blob/development/src/org/loklak/api/search/SearchServlet.java#L176 we have a decision which source should participate in the result computation. That is the access point to add more sources.

If you add another source, that must be added along the twitter source as done in 
https://github.com/loklak/loklak_server/blob/development/src/org/loklak/api/search/SearchServlet.java#L176

Furthermore, each source must contibute to the twitter search index and must be normalized in such a way that it fits into that. Then a search using the "all" source or "cache" source must produce results from that source as well. The difference between "all" and "cache" is, that "cache" does not actually accesses external resources but reproduces from the internal search index, while "all" searches simultanously all sources as well.

To make that possible all new sources must add a type in https://github.com/loklak/loklak_server/blob/development/src/org/loklak/objects/SourceType.java
That is also the flag for an index entry where that source came from.

In that context, both options from your proposal 1) and 2) are true. Queries without a source attribute are equal to source=all. And a selection for source must be done for 2) as well.

**Comment by Orbiter** [comment]
This is a complex task. Please try to move forward with small steps and easy-to review commits. The integration of new targets into the scraper framework is difficult, because it uses concurrency to make de-shortening of links while presenting already found tweets.

Please be very careful when changing existing code to prevent that something breaks and searching for bugs is time-intensive. Always check that existing features are still working at all times.

**Comment by vibhcool** [comment]
thank you @Orbiter, this clears a lot of things :smile:  

Yep, I will take care about these things and try to keep the commits easy-to review.

I have a doubt,

what is the use of SourceType.java , Is it only used as flag (whether to record or not) with QueryEntry that records the results searched related to a query? 
like here -> https://github.com/loklak/loklak_server/blob/9bb1a21a6d0acff92659f0e130c84b61fd6b9c9b/src/org/loklak/data/DAO.java#L1144
