### ISSUE TITLE
Output of image links is not correct

### ISSUE THREAD

**Issue by vibhcool** [loklak/loklak_server#1135]
- Issue type: Bug report

When we do api calls for '/api/search.json?q=query' , in image attribute (in json output), tweet post links also appear with image links.

Like for call loklak.org/api/search.json?q=fossasia , 

![screenshot from 2017-05-08 02-16-07](https://cloud.githubusercontent.com/assets/12577433/25785012/5d760508-3394-11e7-855a-585a4ea56bce.png)

**Comment by djmgit** [comment]
I would like to work on this :)

**Comment by singhpratyush** [comment]
[This](https://github.com/loklak/loklak_server/blob/development/src/org/loklak/harvester/TwitterScraper.java#L248) is where images are extracted. It uses `data-image-url` attr. Two image links are added means that there is an extra `data-image-url` that gets parsed.

For this, we need to check the HTML received while making the searches and make changes accordingly.

Another fix may involve restricting the image URLs that get added - if they do not match some pattern, they are rejected.

**Comment by djmgit** [comment]
Thanks a lot for the pointers, I will send a PR soon :)

**Comment by singhpratyush** [comment]
@djmgit: Make sure that @vibhcool is not working on it.

**Comment by daminisatya** [comment]
@djmgit Assigned the issue

**Comment by djmgit** [comment]
@singhpratyush I went through the code you referred. There as you mentioned image url is extracted using data-image-url attr then it is checked whether the image_url ends with jpg or png.If not it is reported as strange image link and also added to images set, and while extracting video thumbnail and animated gifs no check is done for gifs.
So  in case of image extraction I added an else clause where I added the image_url to images set only if it is not a invalid url. Here's a link to my fork where I did the change :  
https://github.com/djmgit/loklak_server/blob/imageoutput/src/org/loklak/harvester/TwitterScraper.java#L252

I also added a condition for checking gif in video thumbnail and animated gifs extraction.
Here is the change : 
https://github.com/djmgit/loklak_server/blob/imageoutput/src/org/loklak/harvester/TwitterScraper.java#L252

However a non image link is still getting added to the images set. Are images being added from somewhere else? Please do have a look at the changes which I made:
https://github.com/djmgit/loklak_server/blob/imageoutput/src/org/loklak/harvester/TwitterScraper.java
Thanks

**Comment by vibhcool** [comment]
try links like this -> http://127.0.0.1:9000/api/search.json?q=video&source=twitter
that is , add `&source=twitter` when testing.
does this work??

**Comment by singhpratyush** [comment]
> However a non image link is still getting added to the images set.

Probably because of pre-scraped data.

**Comment by singhpratyush** [comment]
I don't think that ignoring links based on the "seem-to-be" extension of a file is a good idea. There may be links that do not end with `jpg` or `png` but still return data with the mime type of an image.

What I suspect is that issue is arising here because of an extra `data-image-url` string in the HTML, which needs to be debugged.
