### ISSUE TITLE
No aggregation returned by the search API

### ISSUE THREAD

**Issue by Achint08** [loklak/loklak_server#1136]
- Issue type: Bug report

### Short Description
For some queries, no aggregations are returned by the `search.json` API although tweets are returned from the same API response.

**Comment by mariobehling** [comment]
Could you give an example, please?

**Comment by singhpratyush** [comment]
@mariobehling: It happens for all requests. For example http://api.loklak.org/api/search.json?q=ping.

Shall I look into it?

**Comment by Achint08** [comment]
@singhpratyush  You can proceed. :)

**Comment by vibhcool** [comment]
aggregation field remains empty, example here for api call http://api.loklak.org/api/search.json?q=ping -> 

file:///home/vibhcool/Pictures/Screenshot%20from%202017-05-09%2012-10-40.png

**Comment by vibhcool** [comment]
aggregation field remains empty, example here for api call http://api.loklak.org/api/search.json?q=ping -> http://pasteboard.co/ppRY488b.png

**Comment by sudheesh001** [comment]
http://api.loklak.org/api/search.json?q=ping%20since:2016-01-01%20until:2016-31-01&fields=mentions,hashtags&limit=6

The aggregations request needs the fields to aggregate on and a source and until time to perform any logical aggregations without that you can still perform aggregations like this with a minimal query.
http://api.loklak.org/api/search.json?q=bing&fields=mentions,hashtags&count=0&limit=6

Can someone please tell what exactly is the bug here and what's being tackled?

**Comment by Achint08** [comment]
@sudheesh001 If we supply these additional parameters, sometimes aggregations field remains empty.
For example, http://api.loklak.org/api/search.json?q=%23fossasia#fossasia&since:2016-01-01%20until:2016-31-01&fields=mentions,hashtags&limit=6 .

**Comment by sudheesh001** [comment]
@Achint08 Why is the query parameter wierd? what does `fossasia#fossasia` mean?

**Comment by Achint08** [comment]
@sudheesh001 I used this query parameter from loklak.org if I search for #fossasia from the search.

**Comment by djmgit** [comment]
@Achint08 try http://api.loklak.org/api/search.json?q=fossasia%20since:2016-01-01%20until:2016-31-01&source=cache&fields=mentions,hashtags&limit=6 
Its returning aggregation.
 You must set source=cache if you want aggregation

**Comment by Achint08** [comment]
@djmgit This was changed to `source=all` https://github.com/loklak/loklak_server/commit/aee580969e6f3e8c45cc1d3fdb788453abe2ec06aee580969e6f3e8c45cc1d3fdb788453abe2ec06

**Comment by singhpratyush** [comment]
@Achint08: Are you still facing this issue?

**Comment by Achint08** [comment]
@singhpratysh Just a proper syntax I would like to know for fetching aggregations.

**Comment by singhpratyush** [comment]
@Achint08: 
Example - 
http://api.loklak.org/api/search.json?q=github%20since:day&fields=mentions,hashtags&limit=5&count=0

To get aggregations, you **must** specify a time range. Mention the fields that you wish to perform aggregations on. Also, you can set `count=0` if you do not wish to have aggregations only and not the Tweets for the searched query.

`limit` defined the number of top aggregation results in each field.

**Comment by Achint08** [comment]
The same query but with filters returns no aggregation.
http://api.loklak.org/api/search.json?q=github%20since:day&fields=mentions,hashtags&limit=5&count=0&filter=image

**Comment by Achint08** [comment]
It is working now. Closing the issue.
