### ISSUE TITLE
Save custom data from IoT message

### ISSUE THREAD

**Issue by zyzo** [loklak/loklak_server#116]
Follow-up of previous discussions in https://github.com/loklak/loklak_server/issues/55#issuecomment-118917334 & https://github.com/loklak/loklak_webclient/issues/449 : there is need to save custom data field when pushing data to loklak. These fields vary greatly depending on the data type. For e.g., fossasia api data contain information about community blog, feed, irc.. Freifunk router wifi data contain information about router name, active status, etc..

@Orbiter To save these custom fields, is this possible to define a `rich_data` field in MessageEntry that stores an object ? Previously in #55, you mentioned appending data to `text` field as rich text, but I believe this is insufficient, because it is then impossible to identify which field is which (since all is text). Plus, we can construct rich text from `rich_data` field. What is your thought on this ?

**Comment by Orbiter** [comment]
I would like to answer this question from the view 'how do I search for rich data entities' and how do I display the data'. I know that it feels strange to just put the rich data as json into the text part, but I don't see a different option to have a better way to search content of the rich content. If you define a field 'rich_data', then how would you search content there? To make that proper, you would need to implement a search method for each of the imported data format which is not feasable.

So lets see this as a challence of a use case: is there any use case right now where you need that field `rich_data` which cannot be solved using a json representation in the rich text field? If not, process the content as described in https://github.com/loklak/loklak_server/issues/55#issuecomment-118917334

**Comment by zyzo** [comment]
You're right. What I'm looking for it's a loosely-type `rich-data` field that we can throw any object in. But apparently without mapping and field-definition it's very hard to search those field. I will append the rich content as json, & parse it in loklak client for further needs. That way minimal change is made for the server.
