### ISSUE TITLE
GithubProfileScraper doesn't return a user's email

### ISSUE THREAD

**Issue by SarishiNoHara** [loklak/loklak_server#1175]
- Issue type: Bug report 

### Short description

GithubProfileScraper doesn't return a user's email. 
The reason is
`Jsoup.connect("https://github.com/" + profile).get();`  doesn't return a valid `<li />` list for user's email, instead it returns a blank area.

### Steps to reproduce

Here is an example for this:
1. Click a user who has a public email address, such as [https://github.com/jasonlong]( https://github.com/jasonlong), and the email is listed in the right side information bar.
2. Click loklak server API([http://loklak.org/api/githubprofilescraper.json?profile=jasonlong](http://loklak.org/api/githubprofilescraper.json?profile=jasonlong)), email returns null.

### Expected behaviour

GithubProfileScraper should returns user's public email.
### Actual behaviour

User's email is null.
![](http://i.imgur.com/wfT8RhS.png)

### Description

1. I've tried to use GitHub [email API ](https://developer.github.com/v3/users/emails/) ([https://api.github.com/user/emails](https://api.github.com/user/emails)) grab user's email, but it needs authentication.
2. I've also tried to make a small python scraper(in beautifulSoup) to read the GitHub user page, the result is same(`<li />` for email is still blank).  
I guess GitHub preventing scraping by maybe hiding the email with CSS, and the CSS is automatically generated by JavaScript file. But the field of `Home location` and `blog or website` works fine. 
![](http://i.imgur.com/hUbsvdC.png)
So I still don't know the actual reason.

**Comment by vibhcool** [comment]
github doesn't output email address when one opens github profile wihout logging in, and scraper doesn't login, so it can't

**Comment by SarishiNoHara** [comment]
@vibhcool I see. So loklak server doesn't support login scraping right?

**Comment by vibhcool** [comment]
@SarishiNoHara , I mean githubprofilescraper scrape data from webpage without logging in to the website.
API as you will see is used if there is no profile we are searching for, then api is used.

**Comment by singhpratyush** [comment]
@SarishiNoHara: @vibhcool is right, you can't extract URL until you are logged in. So it is not possible with scraper.

**Comment by SarishiNoHara** [comment]
@vibhcool @singhpratyush Ok, thanks.
