### ISSUE TITLE
Too much log generated for TwitterScraper

### ISSUE THREAD

**Issue by singhpratyush** [loklak/loklak_server#1176]
- Issue type: Bug report

### Short description
As of now, `TwitterScraper` puts the collected HTML in the log file, which results in a larger log file than actual data. It also becomes difficult to keep track of logs when debugging locally.

It would be better to have a configuration for such things like `flag.debug.*`, which the users can configure based on their needs.

**Comment by singhpratyush** [comment]
@vibhcool @kavithaenair @djmgit @SarishiNoHara @SKrPl: Please comment on the validity of this issue. If this sounds reasonable, I shall proceed with it.

**Comment by SKrPl** [comment]
Seems valid to me

**Comment by vibhcool** [comment]
seems valid 👍

**Comment by SarishiNoHara** [comment]
Yeah, I think it is valid. The log should be categorized.

**Comment by singhpratyush** [comment]
Ok then, I will work on it.
