### ISSUE TITLE
Classify city and countries with similar names as one

### ISSUE THREAD

**Issue by prasht63** [loklak/loklak_server#118]
Since many people have added "Berlin" , "Berlin,Germany" , "Berlin,Europe" so all these get classified differently.I am proposing that while storing the followers data in Loklak a generic place name field to be added in the response which will map all variants of one city to its name and that shall be used.
Required for https://github.com/loklak/loklak_webclient/issues/508

**Comment by Orbiter** [comment]
I found a way to do this but an open question is: what is the normal form? I.e. should "Berlin, Germany" be translated to "Berlin" or should "Berlin" be translated to "Berlin, Germany"?

**Comment by mariobehling** [comment]
Examples are below:
Berlin, Germany > Berlin
Berlin, Georgia > Berlin, GA, USA

If people only write "Berlin", we should use the most common city with the largest number of people. So here this would be "Berlin in Germany".

**Comment by Orbiter** [comment]
- "use the most common city with the largest number of people" is already part of reverse geocoding.
- `Berlin, Germany > Berlin` was implemented in https://github.com/loklak/loklak_server/commit/e071313c8f15ff84e65778b346363b7a561671fe
