### ISSUE TITLE
Using blocking queue for KaizenHarvester

### ISSUE THREAD

**Issue by singhpratyush** [loklak/loklak_server#1189]
- Issue type: Question

### Short description
As of now, `KaizenHarvester` uses a simple queue in which queries to search for are stored. If there is a max size set for the queue, the harvester will not overshoot the number and cut off the new arriving queries when the queue is full.

A blocking queue would prevent threads from adding new queries to the queue until there is some room available.

The question: **Will this implementation will be advantageous over the current one?**

Related #1156.

**Comment by singhpratyush** [comment]
IMO, this will be good as we will not be dropping any queries and searching for each of them eventually. But we will also need to ensure that there is/are some thread(s) that will keep on consuming results from the queue, no matter what.

One way to tackle this can be adding the tasks in async fashion and allowing harvesters to keep on searching without waiting to put things in the queue.

@vibhcool @kavithaenair @djmgit @SarishiNoHara @SKrPl @yukiisbored @sudheesh001: What are your views?

**Comment by yukiisbored** [comment]
Currently, this is exactly what `KaizenHarvester` is doing as of now. Especially with the probabilistic system that's implemented in an earlier PR.

**Comment by singhpratyush** [comment]
Maybe I'm missing something, but `addQuery` [drops the queries when the queue is full](https://github.com/loklak/loklak_server/blob/development/src/org/loklak/harvester/strategy/KaizenHarvester.java#L77). This can be avoided by blocking the thread until some queries are taken out from the queue.

**Comment by yukiisbored** [comment]
AFAIK, Caretaker handles the threads of Harvesters. Also, I have no idea if using lists is even thread-safe, We probably need mutexes or a proper queue system that won't fail on multiple threads.

**Comment by yukiisbored** [comment]
But I like the new probablistic system, so may be create a class that extends from `KaizenHarvester` and override the ones you need to achieve this.

**Comment by singhpratyush** [comment]
I will try to implement it.

**Comment by singhpratyush** [comment]
@hemantjadon: Following up the discussion from #1210, I think that one way to do this would be using fixed length priority queue.

Priority of a query can be set by retweets and favourites count. Also, we can give more score to more frequent queries so that they stay ahead in the priority queue.

**Comment by hemantjadon** [comment]
@singhpratyush sorry for the late reply I totally forgot about this.
Yes Priority queue is the best case situation. If we have sufficient memory this will be the best situation, Even after prioritising the queries, they get dropped then let it be. We can make this go to the best situation, not to the optimal level.

**Comment by singhpratyush** [comment]
Ok. I'll create an issue for that.

Closing this one.
