### ISSUE TITLE
Loklak can't be accessed after deploying development on Kubernetes

### ISSUE THREAD

**Issue by singhpratyush** [loklak/loklak_server#1216]
- Issue type: Bug report

### Short description

The deployment of loklak on Google Cloud Platform with Kubernetes refuses to connect on the public IP address assigned. All the previous steps work fine.

##### Findings
1. The deployment works after reverting 1e0bcd5b353f9f54e65e49979c04e5998f6a3d38.
2. The deployment works after checking out 54841c297197b6ebbcc0671ddcde25fd2f8cb8dc (immediate commit before 1e0bcd5b353f9f54e65e49979c04e5998f6a3d38).

So it is possible that the build broke on that commit.

### Environment

 - Operating system: Google Cloud Platform.
 - Software version: Even with `development`.
 - Software source: Github repository

### Steps to reproduce
1. Follow the steps mentioned in the documentation and deploy on Kubernetes.
2. Try to open the resulting URL.

### Expected behaviour
The website should open.

### Actual behaviour
The website refuses to connect.

**Comment by SKrPl** [comment]
Looking into it, else the related commit can be reverted.
