### ISSUE TITLE
Add Scrapers to SearchServlet

### ISSUE THREAD

**Issue by vibhcool** [loklak/loklak_server#1231]
- Parent Issue: #1129
- Issue type: Feature request

This Issue has the following tasks:- 

1) Changes in SearchServlet so that Scrapers can be added to it to run concurrently.
2) Integrate scrapers with SearchServlet.
3) Combine result of both scrapers in `JsonArray`.

Implementation of 3 issues in order:- #1229 , #1230 and **this one** can work as First Version of the system.

**Comment by vibhcool** [comment]
@SarishiNoHara @djmgit @kavithaenair @vibhcool @Achint08 @hemantjadon @singhpratyush @SKrPl @mariobehling @Orbiter @sudheesh001 @yukiisbored @daminisatya 
Suggestions?

**Comment by singhpratyush** [comment]
This would require #1229 to be fixed first. Also, we will need to create appropriate ES index for each of these services and modify the API schema to support different services.

The details about ES index can go with the definition of `BaseScraper`, which would be configurable for each scraper. Also, the definition of fetching from `cache` will be different for different scrapers as the indices will have different structure now.

**Comment by vibhcool** [comment]
@singhpratyush yes, I thought creating basic version of BaseScraper and then implement it with QuoraScraper and make it side by side.

yes, cache fetching and indexing can also be done in this. I think this shall be implemented after this issue is completed. :)

**Comment by vibhcool** [comment]
I made some changes in issue heading and description

**Comment by vibhcool** [comment]
This Issue is completed and framework for this is set up. Closing this
