### ISSUE TITLE
Create Post interface for scrapers

### ISSUE THREAD

**Issue by vibhcool** [loklak/loklak_server#1235]
- Parent Issue: #1129 
- Related: #1229 , #1231 
- Issue type: Feature request

I want to propose to create Post interface for objects like TwitterTweet (objects that contain a post's data).

This is needed as:-

1) JsonObjects shouldn't be used as they are generic for all classes.
2) MessageEntry is specified for TwitterTweet object. It can't be used for objects(of all scrapers) as they have different vaiables(as I am comparing Quora and Twitter objects).

**Comment by mariobehling** [comment]
I am not entirely clear what kind of additional post's data you are referring to and what it means "create an interface". Could you be more specific, please?

**Comment by vibhcool** [comment]
@mariobehling 
> I want to propose to create Post interface for objects like TwitterTweet (objects that contain a post's data).

there is no additional post data, We can rephrase `Post` as an interface that can be implemented in classes like `TwitterTweet`.

By "post's data", I meant data extracted by the scraper and saved in objects (like objects of TwitterTweet).

**Comment by hemantjadon** [comment]
@vibhcool not able to undersand how this Post object will help us, I mean we need the new sources to produce the data in a similar JSON format, adding the data. I mean how are you approaching the Bypass of JSON, still not clear to me.

**Comment by vibhcool** [comment]
@hemantjadon , let a `data object` be object containing the data of a status(we can call this tweet for twitter or post for quora) extracted using scraper.

On scraping, these `data objects` are collected and fed to Timeline object. Timeline acts as an iterator and can iterate through these `data objects` and order them in the we want (at present functional only for tweets).

Now this `data object` can be specialized object(like TwitterTweet for TwitterScraper) that implements `Post` interface or it can be generalized JsonObject.

IMHO, we shall not use JsonObject as it is used for all the services in Loklak Server and we will not be able to modify it according to JsonObject.

Though at the time of output, data is fed into JsonObjects.

**Comment by hemantjadon** [comment]
@vibhcool I guess you are trying to say make an object of `Post` class whenever the data is generated by Data Objects, I guess this can be done but I am not so sure.
What I mean is we will need a uniform structure for the scraped by all the scrapers, this is necessary. As otherwise apps written on the backend can't filter those out. If you change the existing structure even a little all the applications written on loklak.

**Comment by vibhcool** [comment]
Fixed in PR #1250 , closing this
