### ISSUE TITLE
When loklak.org is under load loklak.net walls fail to reteive tweets.

### ISSUE THREAD

**Issue by smokingwheels** [loklak/loklak_server#127]
Not to sure where the problem is.

If I use wget loklak.org with JSON search as fast as it will go in a loop there are very few (no results) on a loklak.net's walls for the term I setup, the same search values in the loop.
Even with the interval of sleep interval of 10 seconds in the loop it seems to block results on the wall.

You can use my loklak server peer group for testing if you wish http://loklak.mnsnet.ca .
If you want I can add more frontend peers if needed for a short term test the above Url is only on Automatic update twice a day.

**Comment by mariobehling** [comment]
@smokingwheels We might not be able to discover what was the issue and priorities have changed away from loklak.net. So, I am closing this issue.
