### ISSUE TITLE
Java version

### ISSUE THREAD

**Issue by mpfeil** [loklak/loklak_server#128]
Hi guys,

what java version are you using.
I am trying to set up a Docker image for the loklak server.

Best,
Matthias

**Comment by sudheesh001** [comment]
@mpfeil I hope this is of help,
```shell
$ java -version
java version "1.7.0_71"
Java(TM) SE Runtime Environment (build 1.7.0_71-b14)
Java HotSpot(TM) 64-Bit Server VM (build 24.71-b01, mixed mode)
```

**Comment by Orbiter** [comment]
Hi Matthias,

loklak needs Java 7 but should not require Java 8.
