### ISSUE TITLE
Improve test cases for URL unshortener

### ISSUE THREAD

**Issue by singhpratyush** [loklak/loklak_server#1284]
- Issue type: Bug report/Feature request 

### Short description
The current shortened URLs tend to change in short periods of time, which is undesirable. It would be better to have more reliable test shortened URLs for this purpose.

Please add pairs of shortened and unshortened URLs as comments in this thread and we shall add them as tests.

**Comment by singhpratyush** [comment]
https://t.co/raRRie3ado

https://medium.com/javascript-scene/angular-2-vs-react-the-ultimate-dance-off-60e7dfbc379c

**Comment by singhpratyush** [comment]
http://bit.ly/2twLhTQ

https://help.github.com/articles/switching-between-monthly-and-yearly-billing-for-your-personal-account/

**Comment by singhpratyush** [comment]
http://bit.ly/2tAGXDG

https://help.github.com/articles/switching-between-monthly-and-yearly-billing-for-your-personal-account/

**Comment by vibhcool** [comment]
http://bit.ly/2tvkGa1
https://medium.com/@keekri17/my-adventures-at-foss-asia-d1a5d462b792

**Comment by singhpratyush** [comment]
http://ow.ly/P9SX30ddSTI

https://github.com/loklak/loklak_server/issues/1284

**Comment by vibhcool** [comment]
https://goo.gl/r4pNHk
https://www.youtube.com/watch?v=RRlOCHD-p8Q

**Comment by vibhcool** [comment]
http://tinyurl.com/loklak-server
https://github.com/loklak/loklak_server/wiki

**Comment by vibhcool** [comment]
https://is.gd/Lros16
https://twitter.com/lklknt

**Comment by vibhcool** [comment]
http://bit.do/blog-fossasia
http://blog.fossasia.org/

**Comment by vibhcool** [comment]
double shortened link:-
target: https://github.com/fossasia/
mid: http://ow.ly/bDRA30ddTiX
start: https://is.gd/gyk3VT

**Comment by singhpratyush** [comment]
I think we this would be enough.

**Comment by vibhcool** [comment]
adding this also
http://wp.me/sf2B5-shorten
https://en.blog.wordpress.com/2009/08/14/shorten/

**Comment by singhpratyush** [comment]
This was fixed in 3aef8be7a7c8aaa7d40e361ef4e89547e3a16b7e and can be closed.
