### ISSUE TITLE
Structure of Elasticsearch index on adding multiple scrapers

### ISSUE THREAD

**Issue by vibhcool** [loklak/loklak_server#1290]
Parent issue: #1129 
- Issue type: Feature Discussion

According to my stacktrace, the existing structure of `elasticsearch` can work with multiple scrapers.

Some changes I think that are needed are:-

a) presently there is IndexEntry object that acts as the interface between the ElasticSearch and the Scraper system. There is a need to change it's generic type's `superclass` to Post.

b) There can be 2 approaches: - 
    1) an index per scraper
     this will have Documents like messages_hour, messages_day, messages_week, messages, queries, users, accounts, import_profiles
    2) a Document per scraper in all indexes.

For both the existing structure can work (though more changes will be needed in 2nd). Some lines of code will be needed to be added to set this up.

On the basis of this, I want to propose to use 2nd approach as each scrapers having separate index will be more simpler.

**Comment by singhpratyush** [comment]
I think having a separate index for each service we scrape would be good. But I don't know if this would be optimal. Also, earlier versions would have been designed keeping the idea of "everything to index" in mind.

Maybe @Orbiter can guide us through this.

**Comment by vibhcool** [comment]
@sudheesh001 @mariobehling @Orbiter @Achint08 @djmgit @hemantjadon @kavithaenair @SKrPl @singhpratyush @daminisatya : views ??

**Comment by Orbiter** [comment]
as long as 'different indexes' have the same schema as the one loklak schema has, we should have only one index! The main reason is, that also different sources should be searchable with one query and facets which show how many hits are there can be shown for different data sources.

I also don't understand why separate indexes for other scrapers are easier to implement.

**Comment by vibhcool** [comment]
Got it, So I am adding indexing of various scrapers in existing structure. :)

**Comment by DengYiping** [comment]
@vibhcool A year ago I add the DAOWrapper into the data package, it should help you guys to wire the scraper into the system. Take a look.

**Comment by DengYiping** [comment]
@vibhcool @singhpratyush In the past couple month, I was busy with my high school graduation, sorry for the delay. As I mentioned before, inserting a scraped data into the index is straightforward and easy, and there are two way to do it.

Way 1:
Use `GenericJSONBuilder` by calling `DAOWrapper.builder()`, and use the builder to insert data, finally call `builder.persist()`

Way 2:
Implement the interface Insertable, and pass it into`DAOWrapper.insert(Insertable msg)`. On the lower-level, `insert(Insertable msg)` static method will create a builder and persist them.

**Comment by vibhcool** [comment]
@DengYiping , At present, I have Implemented `Post` object that acts as message holder for the messages. It is customized for different scrapers like some doesn't have `created_at` or `user`. But what is common in all scraper post objects is that each one has `post_type` (which tells whether it is a question or a user), post_id (supposed to be unique for each post), timestamp (time in long int format, when it was scraped), the scraper name (to which scraper does it belong). 
This Post object is a wrapper on JSONObject. Now how can I implement DAOWrapper in indexing?

**Comment by vibhcool** [comment]
Also I implemented `Timeline2`, which is roughly a clone of Timeline iterator for Post.

I came up with approach of executing the writetoIndex() method in that iterator concurrently when all messages are collected and are being outputted.

**Comment by DengYiping** [comment]
@vibhcool Hello. DAOWrapper is very flexible, and there are a lot of fields that is not necessary to store. About concurrency, I believe that we should leave it for the DAO object, neither the wrapper nor the scraper should concern about storing message concurrently.

**Comment by DengYiping** [comment]
@vibhcool If you reimplement it, it is great. DAOWrapper is just a temporary solution I implement last year, and if you think your wrapper works better, please feel free to remove the DAOWrapper.

**Comment by vibhcool** [comment]
Closing this issue, related PR is merged
