### ISSUE TITLE
Slow message collection rate

### ISSUE THREAD

**Issue by singhpratyush** [loklak/loklak_server#1296]
- Issue type: Bug report, Parent issue

### Short Description
Recently, two features were made more functional in loklak - 

1. **Redirect unshortening for shortened URLs (#1122)**
    Earlier, only one HTTP redirect status code was considered. This was changed to accept all the redirect status codes and resolve until a saturated URL was reached.

2. **FetchingTwitter video URLs using guest user API (#1206)**
    The feature was added to fetch video URL for Twitter videos that were embedded as iFrame by replicating the flow which Twitter's mobile version follows to play a video.

Since these two features required to make more number of HTTP requests before completing a query, they are reducing the message collection rate by a significant factor.

**Comment by Orbiter** [comment]
can this be made as an concurrent process?

**Comment by singhpratyush** [comment]
@Orbiter: We're working on moving the video fetching part to a new API endpoint (https://github.com/loklak/loklak_server/pull/1319). After this change, the video URL part will no longer be blocking the scraping part.

And for redirect shortening, the process is already concurrent (https://github.com/loklak/loklak_server/blob/12d7cda715f8e21238ee55b9cd5f69cfc9b8c14e/src/org/loklak/harvester/TwitterScraper.java#L436).

**Comment by singhpratyush** [comment]
Fixed in 4707358414856cc16c09cac13c0a46af1acacee3.
