### ISSUE TITLE
Fetching Twitter video takes too much time

### ISSUE THREAD

**Issue by singhpratyush** [loklak/loklak_server#1298]
- Issue type: Bug report

### Short Description

Parent issue: #1296.

Due to making multiple requests in order to get final videos for a Tweet, a lot of time is taken for a single Tweet. Due to this, the message collection rate has become too slow.

It was introduced in #1206.

#### Proposed Solution

We can introduce a new endpoint named as `/api/twittervideo.json` which would return the list of videos for a given Tweet ID and the TwitterScraper would not need to process the Tweet for video until it is explicitly requested.

The Tweet object, in turn, would contain a flag denoting that "there is a video for this Tweet and you can get it from `http://loklak.org/api/twittervideo.json?id={Tweet ID}`".

In later phases, we can improve this service by writing newly fetched URLs to the index and making concurrent fetches (scraper and index) if a given Tweet is requested.

**Comment by vibhcool** [comment]
Another solution
Instead of this we can add `api/fetchvideo/video_url=thisisurl.com/videoid` as generic and provide it's services in scrapers.

**Comment by singhpratyush** [comment]
For Twitter, we don't have anything like `thisisurl.com/videoid`. I'm not sure about this.

**Comment by vibhcool** [comment]
for twitter status' link is `twitter.com/status/{id}`
this service can be used to fetch video using `id`.

**Comment by singhpratyush** [comment]
Yes, that can be done.

**Comment by vibhcool** [comment]
@singhpratyush , this issue is solved, I guess shall we close this issue?
