### ISSUE TITLE
Weird Loklak URL in search API result ("text" param )

### ISSUE THREAD

**Issue by SKrPl** [loklak/loklak_server#1303]
- Issue type: Bug report 

### Short description

Weird Loklak URL is present in `text` key of some of the `status` object in JSONArray `statuses`, while using [search](http://loklak.org/api.html#search) API endpoint. The format of the URL is: `http://loklak.org/x?id=long_integer`. The URL is at the end of the text.

### Steps to reproduce

The search API URL used: https://api.loklak.org/api/search.json?q=python.

### Expected behaviour

The URL shouldn't be concatenated at the end of `text`. Only the actual `text` i.e `tweet` should be returned.

### Description

Screenshot, for reference:
![loklakbugreport](https://user-images.githubusercontent.com/12163892/27990906-6838e652-6483-11e7-85df-3b2917dce1a7.png)
Link of actual tweet: [https://twitter.com/vbb9871/status/883882041552621568](https://twitter.com/vbb9871/status/883882041552621568)

**Comment by SKrPl** [comment]
@singhpratyush @vibhcool Please look into this :smile: .

**Comment by singhpratyush** [comment]
That is not a weird text at all. You can visit the URL to get to the original link. It is very much like `http://t.co` for loklak.

```
$ http http://loklak.org/x?id=883890297410859008
HTTP/1.1 302 Found
CF-RAY: 37b8373ee67c17c2-SIN
Connection: keep-alive
Content-Length: 0
Date: Sun, 09 Jul 2017 03:32:24 GMT
Location: http://www.michaeljgrogan.com/k-means-clustering-python-sklearn/
Server: cloudflare-nginx
Set-Cookie: __cfduid=de97142393f108624fbe8e9ace7dbad521499571143; expires=Mon, 09-Jul-18 03:32:23 GMT; path=/; domain=.loklak.org; HttpOnly
```

See `unshorten` key in the `JSON`:
```json
unshorten: {
    "http://loklak.org/x?id=883890297410859008": "http://www.michaeljgrogan.com/k-means-clu..."
}
```

**Comment by SKrPl** [comment]
Thanks, closing the issue.
