### ISSUE TITLE
Master branch TravisCI build error 

### ISSUE THREAD

**Issue by vibhcool** [loklak/loklak_server#1312]
- Issue type: Bug report

logs (link: https://travis-ci.org/loklak/loklak_server/builds/250478429#L1812 )
```
>> Welcome to Loklak Automatic Deployer
>> Checking credentials ...
>> Pulling new changes ...
fatal: write error: No space left on device
fatal: index-pack failed
>> Failed pulling new changes. Exiting ...
Script failed with status 1
failed to deploy
```

**Comment by vibhcool** [comment]
@sudheesh001 @mariobehling @Orbiter @singhpratyush @hemantjadon @Achint08 @kavithaenair @SKrPl @djmgit . please see

**Comment by sudheesh001** [comment]
Looks more like the disk is full. @Orbiter are there other disks available?

**Comment by singhpratyush** [comment]
Latest build - https://travis-ci.org/loklak/loklak_server/builds/255289371..

**Comment by Orbiter** [comment]
What other disks?

**Comment by sudheesh001** [comment]
@Orbiter The latest build says that during the deployment the disk is full / no space left on disk
`fatal: write error: No space left on device`

Is the storage full ?

**Comment by vibhcool** [comment]
Build error is due to this line. It is supposed to fail. 
@sudheesh001 @Orbiter @mariobehling , what changes are needed to be done here?

**Comment by vibhcool** [comment]
closing this issue. not master build is passing on TravisCI
