### ISSUE TITLE
Add API endpoint to serve video URLs for various services

### ISSUE THREAD

**Issue by singhpratyush** [loklak/loklak_server#1318]
- Issue type: Feature request

### Short Description
The requirement is to add an endpoint that would serve video URLs for various services in loklak (whenever applicable), starting with Twitter.

Example request -
`http://loklak.org/api/videoUrlService.json?id=http://twitter.com/status/user1/status1&id=http://twitter.com/status/user2/status2`

Response - 
```json
{
    "metadata": {
        "ids": [
            "http://twitter.com/status/user1/status1",
            "http://twitter.com/status/user2/status2"
        ]
    },
    "videos": {
        "http://twitter.com/status/user1/status1": {
            "service": "Twitter",
            "status": 0,
            "message": "OK",
            "links": [
                "http://link.to/status/1_1.mp4",
                "http://link.to/status/1_2.mp4",            
            ]
        },
        "http://twitter.com/status/user2/status2": {
            "service": "Twitter",
            "status": 0,
            "message": "OK",
            "links": [
                "http://link.to/status/2_1.mp4",
                "http://link.to/status/2_2.mp4",            
            ]
        }
    }
}
```

**Comment by vibhcool** [comment]
this is wrong get parameters 😅 , fetching 1 url at a time would be more feasible 😅

**Comment by singhpratyush** [comment]
What if someone wants to parse the whole timeline at once? It would require multiple requests, which is not good I guess.

**Comment by vibhcool** [comment]
there can be different driver functions for request through api endpoint and for other scrapers in the project

**Comment by singhpratyush** [comment]
They can all be handled while processing the request in the servlet.

**Comment by vibhcool** [comment]
I don't understand what you mean 😅

**Comment by hemantjadon** [comment]
@singhpratyush Do we really need this?
How this is different from current `search.json,filter=video`. 
I am unable to understand this

**Comment by hemantjadon** [comment]
I read related issues but still the concern is how will this endpoint be used?
And it's comparision with `search.json`?

**Comment by singhpratyush** [comment]
@hemantjadon: As of now, we are requesting video URLs for every Tweet that we encounter. The idea is to postpone this until required.

After the implementation is complete, you'll get a field in returned JSON that will say about the presence of video for the Tweet. And once the user clicks to see the video, you can use this API to get video URL.

**Comment by hemantjadon** [comment]
What about preloading?
This I don't think is correct at all, What if I want to develop a loklak app with which I just want to share videos (Loklak Search - Videos tab) Then exactly 2x requests are sent out, which is not good in request is too large. This is the request just to get URL.
The 80% of the second request will just be headers etc, This is not good at all from the consumer of the API, The actual links should be present in the `/search.json` all time.
If we want to make video scraping a different process that's different. But a separate endpoint, which is almost always hit whenever there is Video in the `/search.json` doesn't seem good to me.
These are two API requests,

**Comment by singhpratyush** [comment]
> not good in request is too large. This is the request just to get URL.
The 80% of the second request will just be headers etc,

The endpoint supports handling of multiple Tweets in one request. So you can request the whole timeline at once.

> always hit whenever there is Video in the `/search.json`

This is not always the case. During processing of a search request, videos will be resolved while time allows (yet to open an issue). You'll need to request only the remaining ones.

And for the rest of it, what you are saying is correct. But if we keep extracting the video URL while scraping, we will never be able to collect the Tweets for a month. This slows down things drastically. We're already down from 43Mil to 25Mil Tweets at the backend.

Please let me know about your views here.

**Comment by hemantjadon** [comment]
@singhpratyush 
I agree about message count thing, I totally agree. 
But this still seems dubious to me in the sense that we have to make extra requests, I mean there should be mechanism to add to the search result if the they are scraped later. I don't know, more than the request count this is about the API design which will not be great if such a thing is implemented. It seems like a it will not be easy for a person who wants to start with the loklak application, or any rest client in general.

@sudheesh001 @mariobehling @Orbiter Your views on this?

**Comment by singhpratyush** [comment]
@hemantjadon: As far as introducing the API is concerned, I don't think that there is an issue with it.

If we want to change this flow, we would need to make changes elsewhere (as in not making it compulsory for the users to make requests to this endpoint). There is no harm if this endpoint is there in loklak.

So for the flow of fetching the video URL, I think we should continue the discussion at #1298.
