### ISSUE TITLE
Fix Master branch squash merge issue

### ISSUE THREAD

**Issue by vibhcool** [loklak/loklak_server#1320]
- Issue type: Uneven Branch issue

Commits from development branch can't be rebased on master branch as they are uneven.

The last PR to master branch #1281 was squash merged. Undoing this will help to continue the work on master branch. This can be done by co-developer with admin rights.

**Comment by vibhcool** [comment]
@mariobehling @Orbiter @daminisatya @sudheesh001 @jig08 , please see to this issue

**Comment by singhpratyush** [comment]
Fixed now.
