### ISSUE TITLE
Manual update caused import job to fail.

### ISSUE THREAD

**Issue by smokingwheels** [loklak/loklak_server#133]
I was processing a large message file and decided to do a manual update with the update.sh.
After it completed the messages_ file was moved into the imported folder.
Note my older install does not have Automatic update interval setting its been processing for the last 3 days ok.

It did survive a power failure no problem, it looked like it picked up where it left off on the import job.

Would it be Possible to disable automatic updates while doing an import?
I am running the import on a second PC will see how that goes was clean install 18-nov-15.

**Comment by Orbiter** [comment]
I checked the code for this purpose and found that automatic updates are scheduled with imports. That means an automatic update cannot interfer with the import. That does not apply for manual updates, they actually interrupt the import and they are moved to the process folder then.
