### ISSUE TITLE
Auto push docker images to Docker hub after build success at Travis

### ISSUE THREAD

**Issue by singhpratyush** [loklak/loklak_server#1339]
- Issue type: Feature request

### Short Description
Related #1224.

The requirement is to push the successfully built image to Docker hub, which will be used to update the images of various deployments (primarily Kubernetes).

The images will be of the form:
1. `loklak/loklak_server:$TRAVIS_COMMIT`
2. `loklak/loklak_server:development`
3. `loklak/loklak_server:master`

Images mentioned in 2 and 3 will always point to the latest version at respective branches.

**Comment by vibhcool** [comment]
Instead, trigger can be setup on Docker hub. It creates image when a new commit is added to the branch

**Comment by vibhcool** [comment]
see https://hub.docker.com/r/vibhcool/loklak_server/builds/

**Comment by vibhcool** [comment]
I have doubts related to some stuff.
for development branch, there is no need of this, Heruku has automatic deploy enabled. There is a need to modify config in `bin/heroku_start.sh`

**Comment by singhpratyush** [comment]
@vibhcool: The plan is to update deployment on Kubernetes with Travis. So we need to be synchronous with updating things here.

The flow would be -
1. This script would push the images.
2. Another script would update Kubernetes deployment once this script is complete.

In this way, we'll not need to wait for the build at Docker to finish. Also, getting notified for docker build to get finished can be tricky.

**Comment by vibhcool** [comment]
@singhpratyush see thishttps://www.google.co.in/url?sa=t&source=web&rct=j&url=/amp/s/www.brianchristner.io/how-to-automate-docker-builds-end-to-end/amp/&ved=0ahUKEwj1pdDvs5zVAhUTSo8KHQobCuYQFgh4MA4&usg=AFQjCNE7eRTIozl3LQFcFfPwouMIc_Wv2w

**Comment by singhpratyush** [comment]
@vibhcool: I'm not sure if adding more platforms as a dependency to this project is a good idea.

I believe that if we can achieve things with our current dependencies (Travis here), we should do so.

**Comment by singhpratyush** [comment]
> autodeploying autobuilt imag

Image is auto-built in this case too - Travis does it. And for updating the image on deployment, we can also use Travis. See open event to get an idea of how this would be done.
