### ISSUE TITLE
Build Error when creating a docker image

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_server#134]
root@9234e5dbf3ae:/loklak_server# ant
Buildfile: /loklak_server/build.xml
init:
build:
   [delete] Deleting directory /loklak_server/classes
    [mkdir] Created dir: /loklak_server/classes
     [echo] loklak: /loklak_server/build.xml
    [javac] Compiling 121 source files to /loklak_server/classes
    [javac] /loklak_server/src/org/loklak/geo/GeoNames.java:163: error: unmappable character for encoding ASCII
    [javac]                     if (name.length() < 4) continue; //1843908184=???????????? ????????????
    [javac]                                                                   ^
    [javac] /loklak_server/src/org/loklak/geo/GeoNames.java:163: error: unmappable character for encoding ASCII
    [javac]                     if (name.length() < 4) continue; //1843908184=???????????? ????????????
    [javac]                                                                    ^
    [javac] /loklak_server/src/org/loklak/geo/GeoNames.java:163: error: unmappable character for encoding ASCII
    [javac]                     if (name.length() < 4) continue; //1843908184=???????????? ????????????
    [javac]                                                                     ^
    [javac] /loklak_server/src/org/loklak/geo/GeoNames.java:163: error: unmappable character for encoding ASCII
    [javac]                     if (name.length() < 4) continue; //1843908184=???????????? ????????????
    [javac]                                                                      ^
    [javac] /loklak_server/src/org/loklak/geo/GeoNames.java:163: error: unmappable character for encoding ASCII
    [javac]                     if (name.length() < 4) continue; //1843908184=???????????? ????????????
    [javac]                                                                       ^
    [javac] /loklak_server/src/org/loklak/geo/GeoNames.java:163: error: unmappable character for encoding ASCII
    [javac]                     if (name.length() < 4) continue; //1843908184=???????????? ????????????
    [javac]                                                                        ^
    [javac] /loklak_server/src/org/loklak/geo/GeoNames.java:163: error: unmappable character for encoding ASCII
    [javac]                     if (name.length() < 4) continue; //1843908184=???????????? ????????????
    [javac]                                                                         ^
    [javac] /loklak_server/src/org/loklak/geo/GeoNames.java:163: error: unmappable character for encoding ASCII
    [javac]                     if (name.length() < 4) continue; //1843908184=???????????? ????????????
    [javac]                                                                          ^
    [javac] /loklak_server/src/org/loklak/geo/GeoNames.java:163: error: unmappable character for encoding ASCII
    [javac]                     if (name.length() < 4) continue; //1843908184=???????????? ????????????
    [javac]                                                                           ^
    [javac] /loklak_server/src/org/loklak/geo/GeoNames.java:163: error: unmappable character for encoding ASCII
    [javac]                     if (name.length() < 4) continue; //1843908184=???????????? ????????????
    [javac]                                                                            ^
    [javac] /loklak_server/src/org/loklak/geo/GeoNames.java:163: error: unmappable character for encoding ASCII
    [javac]                     if (name.length() < 4) continue; //1843908184=???????????? ????????????
    [javac]                                                                             ^
    [javac] /loklak_server/src/org/loklak/geo/GeoNames.java:163: error: unmappable character for encoding ASCII
    [javac]                     if (name.length() < 4) continue; //1843908184=???????????? ????????????
    [javac]                                                                              ^
    [javac] /loklak_server/src/org/loklak/geo/GeoNames.java:163: error: unmappable character for encoding ASCII
    [javac]                     if (name.length() < 4) continue; //1843908184=???????????? ????????????
    [javac]                                                                                ^
    [javac] /loklak_server/src/org/loklak/geo/GeoNames.java:163: error: unmappable character for encoding ASCII
    [javac]                     if (name.length() < 4) continue; //1843908184=???????????? ????????????
    [javac]                                                                                 ^
    [javac] /loklak_server/src/org/loklak/geo/GeoNames.java:163: error: unmappable character for encoding ASCII
    [javac]                     if (name.length() < 4) continue; //1843908184=???????????? ????????????
    [javac]                                                                                  ^
    [javac] /loklak_server/src/org/loklak/geo/GeoNames.java:163: error: unmappable character for encoding ASCII
    [javac]                     if (name.length() < 4) continue; //1843908184=???????????? ????????????
    [javac]                                                                                   ^
    [javac] /loklak_server/src/org/loklak/geo/GeoNames.java:163: error: unmappable character for encoding ASCII
    [javac]                     if (name.length() < 4) continue; //1843908184=???????????? ????????????
    [javac]                                                                                    ^
    [javac] /loklak_server/src/org/loklak/geo/GeoNames.java:163: error: unmappable character for encoding ASCII
    [javac]                     if (name.length() < 4) continue; //1843908184=???????????? ????????????
    [javac]                                                                                     ^
    [javac] /loklak_server/src/org/loklak/geo/GeoNames.java:163: error: unmappable character for encoding ASCII
    [javac]                     if (name.length() < 4) continue; //1843908184=???????????? ????????????
    [javac]                                                                                      ^
    [javac] /loklak_server/src/org/loklak/geo/GeoNames.java:163: error: unmappable character for encoding ASCII
    [javac]                     if (name.length() < 4) continue; //1843908184=???????????? ????????????
    [javac]                                                                                       ^
    [javac] /loklak_server/src/org/loklak/geo/GeoNames.java:163: error: unmappable character for encoding ASCII
    [javac]                     if (name.length() < 4) continue; //1843908184=???????????? ????????????
    [javac]                                                                                        ^
    [javac] /loklak_server/src/org/loklak/geo/GeoNames.java:163: error: unmappable character for encoding ASCII
    [javac]                     if (name.length() < 4) continue; //1843908184=???????????? ????????????
    [javac]                                                                                         ^
    [javac] /loklak_server/src/org/loklak/geo/GeoNames.java:163: error: unmappable character for encoding ASCII
    [javac]                     if (name.length() < 4) continue; //1843908184=???????????? ????????????
    [javac]                                                                                          ^
    [javac] /loklak_server/src/org/loklak/geo/GeoNames.java:163: error: unmappable character for encoding ASCII
    [javac]                     if (name.length() < 4) continue; //1843908184=???????????? ????????????
    [javac]                                                                                           ^
    [javac] /loklak_server/src/org/loklak/geo/GeoNames.java:240: error: unmappable character for encoding ASCII
    [javac]            // ??T: 19.109458,72.825842.
    [javac]               ^
    [javac] /loklak_server/src/org/loklak/geo/GeoNames.java:240: error: unmappable character for encoding ASCII
    [javac]            // ??T: 19.109458,72.825842.
    [javac]                ^
    [javac] /loklak_server/src/org/loklak/geo/OSMTile.java:146: error: unmappable character for encoding ASCII
    [javac]             // X goes from 0 (left edge is 180 ??W) to 2^zoom ??? 1 (right edge is 180 ??E)
    [javac]                                                ^
    [javac] /loklak_server/src/org/loklak/geo/OSMTile.java:146: error: unmappable character for encoding ASCII
    [javac]             // X goes from 0 (left edge is 180 ??W) to 2^zoom ??? 1 (right edge is 180 ??E)
    [javac]                                                 ^
    [javac] /loklak_server/src/org/loklak/geo/OSMTile.java:146: error: unmappable character for encoding ASCII
    [javac]             // X goes from 0 (left edge is 180 ??W) to 2^zoom ??? 1 (right edge is 180 ??E)
    [javac]                                                               ^
    [javac] /loklak_server/src/org/loklak/geo/OSMTile.java:146: error: unmappable character for encoding ASCII
    [javac]             // X goes from 0 (left edge is 180 ??W) to 2^zoom ??? 1 (right edge is 180 ??E)
    [javac]                                                                ^
    [javac] /loklak_server/src/org/loklak/geo/OSMTile.java:146: error: unmappable character for encoding ASCII
    [javac]             // X goes from 0 (left edge is 180 ??W) to 2^zoom ??? 1 (right edge is 180 ??E)
    [javac]                                                                 ^
    [javac] /loklak_server/src/org/loklak/geo/OSMTile.java:146: error: unmappable character for encoding ASCII
    [javac]             // X goes from 0 (left edge is 180 ??W) to 2^zoom ??? 1 (right edge is 180 ??E)
    [javac]                                                                                        ^
    [javac] /loklak_server/src/org/loklak/geo/OSMTile.java:146: error: unmappable character for encoding ASCII
    [javac]             // X goes from 0 (left edge is 180 ??W) to 2^zoom ??? 1 (right edge is 180 ??E)
    [javac]                                                                                         ^
    [javac] /loklak_server/src/org/loklak/geo/OSMTile.java:147: error: unmappable character for encoding ASCII
    [javac]             // Y goes from 0 (top edge is 85.0511 ??N) to 2^zoom ??? 1 (bottom edge is 85.0511 ??S) in a Mercator projection
    [javac]                                                   ^
    [javac] /loklak_server/src/org/loklak/geo/OSMTile.java:147: error: unmappable character for encoding ASCII
    [javac]             // Y goes from 0 (top edge is 85.0511 ??N) to 2^zoom ??? 1 (bottom edge is 85.0511 ??S) in a Mercator projection
    [javac]                                                    ^
    [javac] /loklak_server/src/org/loklak/geo/OSMTile.java:147: error: unmappable character for encoding ASCII
    [javac]             // Y goes from 0 (top edge is 85.0511 ??N) to 2^zoom ??? 1 (bottom edge is 85.0511 ??S) in a Mercator projection
    [javac]                                                                  ^
    [javac] /loklak_server/src/org/loklak/geo/OSMTile.java:147: error: unmappable character for encoding ASCII
    [javac]             // Y goes from 0 (top edge is 85.0511 ??N) to 2^zoom ??? 1 (bottom edge is 85.0511 ??S) in a Mercator projection
    [javac]                                                                   ^
    [javac] /loklak_server/src/org/loklak/geo/OSMTile.java:147: error: unmappable character for encoding ASCII
    [javac]             // Y goes from 0 (top edge is 85.0511 ??N) to 2^zoom ??? 1 (bottom edge is 85.0511 ??S) in a Mercator projection
    [javac]                                                                    ^
    [javac] /loklak_server/src/org/loklak/geo/OSMTile.java:147: error: unmappable character for encoding ASCII
    [javac]             // Y goes from 0 (top edge is 85.0511 ??N) to 2^zoom ??? 1 (bottom edge is 85.0511 ??S) in a Mercator projection
    [javac]                                                                                                ^
    [javac] /loklak_server/src/org/loklak/geo/OSMTile.java:147: error: unmappable character for encoding ASCII
    [javac]             // Y goes from 0 (top edge is 85.0511 ??N) to 2^zoom ??? 1 (bottom edge is 85.0511 ??S) in a Mercator projection
    [javac]                                                                                                 ^
    [javac] /loklak_server/src/org/loklak/geo/OSMTile.java:148: error: unmappable character for encoding ASCII
    [javac]             // the number 85.0511 is the result of arctan(sinh(??)). By using this bound, the entire map becomes a (very large) square.
    [javac]                                                                ^
    [javac] /loklak_server/src/org/loklak/geo/OSMTile.java:148: error: unmappable character for encoding ASCII
    [javac]             // the number 85.0511 is the result of arctan(sinh(??)). By using this bound, the entire map becomes a (very large) square.
    [javac]                                                                 ^
    [javac] /loklak_server/src/org/loklak/geo/OSMTile.java:153: error: unmappable character for encoding ASCII
    [javac]             // ytile = n * (1 - (log(tan(lat_rad) + sec(lat_rad)) / ??)) / 2
    [javac]                                                                     ^
    [javac] /loklak_server/src/org/loklak/geo/OSMTile.java:153: error: unmappable character for encoding ASCII
    [javac]             // ytile = n * (1 - (log(tan(lat_rad) + sec(lat_rad)) / ??)) / 2
    [javac]                                                                      ^
    [javac] /loklak_server/src/org/loklak/geo/OSMTile.java:158: error: unmappable character for encoding ASCII
    [javac]             // lat_rad = arctan(sinh(?? * (1 - 2 * ytile / n)))
    [javac]                                      ^
    [javac] /loklak_server/src/org/loklak/geo/OSMTile.java:158: error: unmappable character for encoding ASCII
    [javac]             // lat_rad = arctan(sinh(?? * (1 - 2 * ytile / n)))
    [javac]                                       ^
    [javac] /loklak_server/src/org/loklak/geo/OSMTile.java:159: error: unmappable character for encoding ASCII
    [javac]             // lat_deg = lat_rad * 180.0 / ??
    [javac]                                            ^
    [javac] /loklak_server/src/org/loklak/geo/OSMTile.java:159: error: unmappable character for encoding ASCII
    [javac]             // lat_deg = lat_rad * 180.0 / ??
    [javac]                                             ^
    [javac] /loklak_server/src/org/loklak/tools/bayes/Classifier.java:46: error: unmappable character for encoding ASCII
    [javac]  * basic probabilities ??? both category and feature probabilities. The classify
    [javac]                        ^
    [javac] /loklak_server/src/org/loklak/tools/bayes/Classifier.java:46: error: unmappable character for encoding ASCII
    [javac]  * basic probabilities ??? both category and feature probabilities. The classify
    [javac]                         ^
    [javac] /loklak_server/src/org/loklak/tools/bayes/Classifier.java:46: error: unmappable character for encoding ASCII
    [javac]  * basic probabilities ??? both category and feature probabilities. The classify
    [javac]                          ^
    [javac] 51 errors
BUILD FAILED
/loklak_server/build.xml:87: Compile failed; see the compiler error output for details.
Total time: 1 second
root@9234e5dbf3ae:/loklak_server#

**Comment by Orbiter** [comment]
fixed
