### ISSUE TITLE
Error in shortlinks for Twitter embedded links

### ISSUE THREAD

**Issue by vibhcool** [loklak/loklak_server#1346]
- Issue type: Bug report

For requests like: http://loklak.org/api/search.json?q=Fossasia&count=20

In the result shortlink shall be something like `http://loklak.org/x?id={any id}`, but outputs id=null
Like:-
`"unshorten": {"http://loklak.org/x?id=null": "http://artificial.fastfixco..."}`

**Comment by vibhcool** [comment]
working on this

**Comment by mariobehling** [comment]
Please use the endpoints of api.loklak.org instead of loklak.org.
