### ISSUE TITLE
Add more information for display in the Status Service API 

### ISSUE THREAD

**Issue by kavithaenair** [loklak/loklak_server#1350]
- Issue type: Feature request

### Short description
As of now StatusService.java do not display few configuration  parameters like Xmx, backend.loop, elasticsearch_cluster_size, etc.

### Use Case
To check the existing configuration details of the service and this can also be used as a profiler.
status.json now shows most of the config data, out of which few of the above are missing. These config should be present in the status service service API, as one do not have to dig into files instead just run the status.json API.

So am going to add the above mentioned fields to the API.

I would like to work on this.

**Comment by mariobehling** [comment]
What is the use-case? Who needs it? Please add more details.
