### ISSUE TITLE
Allow disabling of dump generator

### ISSUE THREAD

**Issue by singhpratyush** [loklak/loklak_server#1363]
- Issue type: Feature request

### Short Description

As mentioned in #1224, we should have a flag to switch off dump generation.

**Comment by mariobehling** [comment]
What is the use case? Why do we need this?

**Comment by singhpratyush** [comment]
@mariobehling: As mentioned by @Orbiter in #1224,

> We can also turn loklak into a full stateless microservice by:
>
> * using an external elasticsearch (thats possible right now), and
> * switching off the dump generation (that must be implemented with a flag).
