### ISSUE TITLE
Refactor MessageEntry implementation

### ISSUE THREAD

**Issue by vibhcool** [loklak/loklak_server#1365]
- Parent Issue: #1129 
- Issue type: Feature request

All the services related to TwitterScraper are implemented using MessageEntry. While trying to refactor TwitterScraper code, numerous error appears related to classes implementing MessageEntry.

Idea I came up with:-

1) Replace all MessageEntry implementations with TwitterTweet.
2) Remove MessageEntry as superClass of TwitterTweet. Replace with Post object.

This task is important as:-

1) to simplify the structure. 
2) To use TwitterScraper with other scrapers at `search.json` endpoint

EDIT 1 : 
Reference:- 

1) TwitterTweet is data object class of TwitterScraper . link: https://github.com/loklak/loklak_server/blob/12d7cda715f8e21238ee55b9cd5f69cfc9b8c14e/src/org/loklak/harvester/TwitterScraper.java#L656

2) MessageEntry is superclass of TwitterTweet that holds supportive methods which are used in it.
link: https://github.com/loklak/loklak_server/blob/a49728bb25feaf8d4f695fee4427b4a5adf8f984/src/org/loklak/objects/MessageEntry.java

**Comment by vibhcool** [comment]
Complete Solution is in PR #1368. I will divide and create small PRs to make it easy to review

**Comment by mariobehling** [comment]
What is a TwitterTweet?

**Comment by vibhcool** [comment]
TwitterTweet is the `data object` of TwitterScraper class. link to source of TwitterTweet: https://github.com/loklak/loklak_server/blob/12d7cda715f8e21238ee55b9cd5f69cfc9b8c14e/src/org/loklak/harvester/TwitterScraper.java#L656
