### ISSUE TITLE
Replace all MessageEntry implementations with TwitterTweet

### ISSUE THREAD

**Issue by vibhcool** [loklak/loklak_server#1374]
- Issue type: Feature request
- Parent Issue: #1365 

Task: 
Replace all MessageEntry implementations with TwitterTweet.

Why?
This PR simplifies project to make further changes in TwitterScraper code. After this all part of project using TwitterScraper will be directly dependent on it. Presently some parts use MessageEntry objects in the programs.

Use-Case
For Use Case, refer Parent Issue. This Issue is to divide the PR #1368  into small PRs to make it easy to review

**Comment by mariobehling** [comment]
Please add more details to the description. What is this needed for, what is the use-case?

**Comment by vibhcool** [comment]
@mariobehling added the details :)
