### ISSUE TITLE
Add a line which loklak version is deployed at the end of the document and make the top bar acting more smoothly

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_server#1438]
1. Below the last line of the start page add a line, which version is deployed with a link to the deployed state.

![screenshot from 2017-08-12 00-53-00](https://user-images.githubusercontent.com/1583873/29234655-dc284244-7ef8-11e7-87d9-bd2aa6f0fa82.png)

2. The top bar acts very abruptly. Please make it work similar to http://susi.ai

**Comment by singhpratyush** [comment]
@mariobehling: What should the version look like? Commit hash and link to Github at that point?

**Comment by vibhcool** [comment]
Version system shall be introduced instead, if we could :sweat_smile:

**Comment by mariobehling** [comment]
The Open Event server already has something similar. 
![screenshot from 2017-08-13 10-19-52](https://user-images.githubusercontent.com/1583873/29248155-019453c4-8011-11e7-8787-d40a590933f9.png)
* Show which version of the code is deployed. It does not need to be an official release. Just the PR status is sufficient.
* Also link to the commit hash

**Comment by singhpratyush** [comment]
Working on it.
