### ISSUE TITLE
Enhance api.loklak.org page

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_server#1439]
* Change "Distributed Social Media Message Search Server" to "Distributed API Search Server for Twitter & Social Media"
* Change "This is the Search Server for the Loklak Webclient hosting.." -> "This is the Open Source API Search Server for the Loklak Twitter and Social Media Search Engine hosting.."
* On Top Menu change "API" to api.loklak.org (itself) and delete api.html
* Link "About" to http://loklak.org/about and delete about.html
* Change the following links 
   * http://api.loklak.org/about.html#whyuse -> http://dev.loklak.org/server/index.html#why-should-i-use-loklak
   * http://api.loklak.org/about.html#distributed -> http://dev.loklak.org/server/index.html#distributed-peer-to-peer
   * http://api.loklak.org/api.html -> http://dev.loklak.org/server/development/api.html
* Add the ico like in all other loklak sites
* Sort the menu items in the following order: About, Search, Blog, Developers, API
* Add a footer same as on loklak.org
![screenshot from 2017-08-12 01-29-30](https://user-images.githubusercontent.com/1583873/29235265-bddbf344-7efd-11e7-9234-31fc5df77cd3.png)
* On the top left instead of using "loklak" as a text, add a "loklak cow logo" here and make the top bar disappear when a user scrolls up same as apps.loklak.org
* Use the same font as on apps.loklak.org for the top bar

**Comment by kavithaenair** [comment]
@djmgit Now am doing first five tasks.

**Comment by djmgit** [comment]
@kavithaenair alright I will do the next 5 :)
