### ISSUE TITLE
Hash symbol appended in front of hashtag set linked to a status and to the aggregations

### ISSUE THREAD

**Issue by Achint08** [loklak/loklak_server#1457]
- Issue type: Bug report

### Short description

The backend is returning all the entities with hash symbol appended, at the start of every string of hashtag set linked to a status and to the aggregations.
This behaviour is unexpected.

**Comment by vibhcool** [comment]
The required hashtag output is `hashtag` instead of `#hashtag`. Isn't it?

**Comment by Achint08** [comment]
Yes @vibhcool
