### ISSUE TITLE
Top bar appears/disappears abruptly

### ISSUE THREAD

**Issue by singhpratyush** [loklak/loklak_server#1458]
- Issue type: Bug report

### Short description

The top bar appears/disappears abruptly on scrolling. Also, there is a lot of flickering while doing so.

### Environment
 - Operating system: OS Independent
 - Software version: 6c7e5622c71a94e97b6e61c94181cc920916a9ee
 - Software source: Github Repository

### Steps to reproduce
1. Open the deployment on a browser
2. Scroll up and down

### Expected behaviour
The top bar should appear and disappear smoothly.

### Actual behaviour
The transition is not smooth.

**Comment by djmgit** [comment]
I am working on it

**Comment by singhpratyush** [comment]
Fixed in 2adef28fbfbb274a2e658e98061c14d1f544505a.
