### ISSUE TITLE
proxy.json

### ISSUE THREAD

**Issue by kngoledge** [loklak/loklak_server#151]
Can you supply more information about what the proxy.json does?

**Comment by sudheesh001** [comment]
@Orbiter Can you mention what the proxy.json has to be doing so that @kngoledge Would be writing the API documentation as a part of his GCI task.

**Comment by Orbiter** [comment]
the proxy.json API supports clients for loading of user-related assets from twitter. Either a ```url``` or a ```screen_name``` can be passed to the api, or both. The proxy.json loads the url and returns the content. If a screen_name is given, the url content is stored in a cache related to the given screen_name. If only the screen_name and no url is given, the proxy returns the image of that user. If only a url is given, the proxy.json tries to identify the url as user-related and loads the content.

This servlet was supposed to be used for any kind of user-related url, but actually it was enhanced only for user images.

**Comment by DengYiping** [comment]
@kngoledge Please close this issue.

**Comment by sudheesh001** [comment]
Thanks for helping in the clean up @DengYiping
