### ISSUE TITLE
API button on home page is not working

### ISSUE THREAD

**Issue by vibhcool** [loklak/loklak_server#1510]
- Issue type: Bug report

The API button at top-right in Loklak Server home page is not working. It redirects to the same page. Instead it shall redirect to the docs.

**Comment by S2606** [comment]
@vibhcool The documentation are already linked via Developer button.

**Comment by kavithaenair** [comment]
@vibhcool Check the 3rd point in the issue #1439 . The API has to be redirected to the same page.

**Comment by vibhcool** [comment]
closing this issue.
