### ISSUE TITLE
Update README with latest deployment details

### ISSUE THREAD

**Issue by singhpratyush** [loklak/loklak_server#1513]
### Short description
* The current README mentions deployment for development branch as https://loklak-server-dev.herokuapp.com/ while it can now be changed to https://staging.loklak.org/
* The Docker image badge needs to be updated to loklak/loklak_server.
* Replace Ant build command with Gradle.
* Correct link for "Where can I get the latest news about loklak?" section.

**Comment by vibhcool** [comment]
Is heroku deploy supposed to be removed?

**Comment by mariobehling** [comment]
@singhpratyush @vibhcool Please keep Heroku and simply add "staging" as the second option.
