### ISSUE TITLE
http://api.loklak.org/ showing error

### ISSUE THREAD

**Issue by bhaveshAn** [loklak/loklak_server#1538]
http://api.loklak.org/ showing me error when clicked on this from repository description
![screenshot from 2017-09-25 16-19-44](https://user-images.githubusercontent.com/22936570/30793492-ede3b59a-a1df-11e7-8eb6-ce94ecc0ed59.png)

**Comment by sudheesh001** [comment]
Currently the server is under maintenance, we'll notify once it's back up online.

**Comment by vibhcool** [comment]
Loklak server is up now, please close this issue :)
