### ISSUE TITLE
Prepare loklak for tweet sizes > 140; New limit is 280

### ISSUE THREAD

**Issue by sudheesh001** [loklak/loklak_server#1541]

**Comment by vibhcool** [comment]
Loklak Server TwitterScraper doesn't have any size restriction, isn't it?

**Comment by sudheesh001** [comment]
I agree it doesn't this issue is essentially to track in case we run into issues while collecting the data.

**Comment by mariobehling** [comment]
Closing this as there does not seem to be an issue now.
