### ISSUE TITLE
YoutubeScraper test fails

### ISSUE THREAD

**Issue by singhpratyush** [loklak/loklak_server#1555]
- Issue type: Bug report

### Short description

Here is the log from build - 

```java
org.loklak.TestRunner > org.loklak.harvester.YoutubeScraperTest.parseFromInputStreamTest FAILED
    java.lang.AssertionError: 
    Expected: is "[\"Iggy Azalea - Team (Explicit) - YouTube\"]"
         but: was "[\"YouTube\"]"
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.loklak.harvester.YoutubeScraperTest.parseFromInputStreamTest(YoutubeScraperTest.java:39)
```

### Environment

 - Operating system: Ubuntu 16.04LTS
 - Software version: 8d521a8461ef65a4b4ab5c8b90d5f5b43d0fbf23
 - Software source: Github repository

### Steps to reproduce

1. Get even with `loklak:development`.
2. `./gradlew build -i`
3. Look at the logs

### Expected behaviour
The test should pass.

### Actual behaviour
Test fails.

**Comment by S2606** [comment]
Claiming this.

**Comment by vibhcool** [comment]
@S2606 You may take up this issue:+1:

**Comment by singhpratyush** [comment]
@S2606: Any updates? Are you stuck somewhere?

**Comment by S2606** [comment]
@singhpratyush Yes i am stuck as i coudnt really find where `html_title` data is generated.I have already searched in YoutubeScraper as well as in BaseScraper

**Comment by vibhcool** [comment]
@S2606 , hint: there is a addRDF method in youtubescraper, check it
