### ISSUE TITLE
GithubProfileScraper test fails

### ISSUE THREAD

**Issue by singhpratyush** [loklak/loklak_server#1556]
- Issue type: Bug report

### Short description

Here is the log from build - 

```java
org.loklak.TestRunner > org.loklak.api.search.GithubProfileScraperTest.githubProfileScraperOrgTest FAILED
    org.junit.ComparisonFailure: expected:<http[s]://fossasia.org> but was:<http[]://fossasia.org>
        at org.junit.Assert.assertEquals(Assert.java:115)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at org.loklak.api.search.GithubProfileScraperTest.githubProfileScraperOrgTest(GithubProfileScraperTest.java:53)
```

### Environment

 - Operating system: Ubuntu 16.04LTS
 - Software version: 8d521a8461ef65a4b4ab5c8b90d5f5b43d0fbf23
 - Software source: Github repository

### Steps to reproduce

1. Get even with `loklak:development`.
2. `./gradlew build -i`
3. Look at the logs

### Expected behaviour
The test should pass.

### Actual behaviour
Test fails.

**Comment by S2606** [comment]
Can i work on this @singhpratyush ??

**Comment by vibhcool** [comment]
yep, you may 👍  @S2606
