### ISSUE TITLE
Videos and images not showing

### ISSUE THREAD

**Issue by Cam-B** [loklak/loklak_server#1561]
- Issue type: Bug report

### Short description
Videos and Images don't show up in the Loklak search results

### Environment
https://loklak.org/

### Steps to reproduce
1. go to https://loklak.org/
2. Search for "cats"
3. click on "videos" or images 

### Expected behaviour
see images and video thumbnails
### Actual behaviour
did not see images and video thumbnails

![cats](https://user-images.githubusercontent.com/31628918/34920578-d5bcdcca-f942-11e7-9aad-59073fc91cd0.png)

**Comment by vibhcool** [comment]
This issue is related to loklak_search , images appear on loklak api , check this -> `https://api.loklak.org/api/search.json?q=car&filter=image`

**Comment by Cam-B** [comment]
ok. Thank you. I found this open issue. https://github.com/fossasia/loklak_search/issues/624 Looks like the issue is only with https.

**Comment by singhpratyush** [comment]
@Cam-B: The issue may be due to the images being loaded over `http`. Please check if it is so.

If this is the issue, you'll need to allow unsafe scripts to get through.
