### ISSUE TITLE
Add Unit Test for UTF8.java file

### ISSUE THREAD

**Issue by neelanshsahai** [loklak/loklak_server#1580]
- Issue type: Feature request 

### Short description
Add a test for the UTF8 java class

### Usecase
While the gradle builds, the UTF8.java file will be tested

### Description

This will eventually increase the test coverage of Loklak_Server

**Comment by AlexanderVladimirov9090** [comment]
This could be done by me.

**Comment by simsausaurabh** [comment]
@AlexanderVladimirov9090 Sure go ahead 👍
