### ISSUE TITLE
Potential security problem(s)

### ISSUE THREAD

**Issue by intrigus-lgtm** [loklak/loklak_server#1641]
Hi, could you please create a new [draft security advisory](https://help.github.com/en/github/managing-security-vulnerabilities/creating-a-security-advisory) and 
[invite me](https://help.github.com/en/github/managing-security-vulnerabilities/adding-a-collaborator-to-a-security-advisory) to it?
Any other private communication channel would also be fine.
I think I've found a potential security problem.

**Comment by intrigus-lgtm** [comment]
Hey @Orbiter `loklak_server` contains a similar vulnerability as https://github.com/fossasia/susi_server/.
This vulnerability will be disclosed *soon*.
It should be straightforward to apply this fix to `loklak_server` as well, to prevent the fix for `susi_server` putting a spot-light on `loklak_server`.

**Comment by sudheesh001** [comment]
@intrigus-lgtm Created one for you and invited you to report the issue there in the drafts

**Comment by intrigus-lgtm** [comment]
This has been resolved in https://github.com/loklak/loklak_server/security/advisories/GHSA-7557-4v29-rqw6
