### ISSUE TITLE
Not able to view search result in elasticsearch

### ISSUE THREAD

**Issue by shashank-sharma** [loklak/loklak_server#168]
I have set up loklak server and also elastic search server too locally. But when I search any query in loklak page locally then it open one another page which is something /search.json so my question is how can I view it in elasticsearch home page ? This what it looks like when I go to http://localhost:9100/  So what should I do to make it working ?

![screenshot from 2015-12-28 14 07 01](https://cloud.githubusercontent.com/assets/9320644/12017974/1df35450-ad83-11e5-8ede-2ebe0c005e45.png)

**Comment by Orbiter** [comment]
loklak has an embedded elasticsearch which opens port 9200 and 9300. If you start another elasticsearch you will get a port conflict. There is also no need to start an external elasticsearch because it's already embedded.

**Comment by shashank-sharma** [comment]
I tried installing this [corse everywhere](https://addons.mozilla.org/en-US/firefox/addon/cors-everywhere/?src=search) which is a firefox plugin due to which I was able to enable CORSE and then I was able to view it. Now its working fine by me.
