### ISSUE TITLE
Can someone explain me how to install Loklak on XAMPP or WAMPP

### ISSUE THREAD

**Issue by YashKumarVerma** [loklak/loklak_server#174]
Please, I really need it.

**Comment by DengYiping** [comment]
Install docker, then ```docker build https://github.com/loklak/loklak_server.git```. It will create a docker image. Then you can do something like ```docker run YOUR_IMAGE_NAME -d -p 80:80 -p 443:443```. She should be right there.

**Comment by sudheesh001** [comment]
Hi  @YashKumarVerma The closest you could get to something like this is with a docker image, or else it's not really a XAMPP/LAMPP/WAMPP thing to run this. Maybe the readme file of the project can offer you instructions on how to set this up ?

Please close this if your issue is resolved.

**Comment by mariobehling** [comment]
Hi, there is some info here: https://github.com/loklak/loklak_server#how-do-i-install-loklak-download-build-run and there is an explanation how to set up a Docker image on Bluemix here: https://raw.githubusercontent.com/loklak/loklak_server/master/installation_docker.md If you have installation instructions for other systems, please feel free to create an installation file.
