### ISSUE TITLE
A problem with the dumps

### ISSUE THREAD

**Issue by d33tah** [loklak/loklak_server#175]
Not sure if it's the right repository to report that, but I took a look at your dump repository and found it's not valid JSON:

```
>>> s
'{"created_at":"2015-06-05T13:21:01.000Z","screen_name":"bildungkirche","text":"Die Kirchen Bern-Jura-Solothurn gehen in die Zukunft. Ihr Start-Video f\xc3\xbcr den Prozess "Vision Kirche 21" https://vimeo.com/129694062","link":"https://twitter.com/bildungkirche/status/606812974662197248","id_str":"606812974662197248","source_type":"TWITTER","provider_type":"REMOTE","provider_hash":"7ffffffe","retweet_count":0,"favourites_count":0,"images":[],"images_count":0,"place_name":"","place_id":"","user":{"name":"bildungkirche","screen_name":"bildungkirche","profile_image_url_https":"https://pbs.twimg.com/profile_images/478436365474885633/_5zoJJmK_bigger.jpeg","appearance_first":"2015-06-05T13:31:28.590Z","appearance_latest":"2015-06-05T13:31:28.590Z"}}'
>>> pprint.pprint(json.loads(s))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting , delimiter: line 1 column 168 (char 167)
>>> s[160:190]
'ozess "Vision Kirche 21" https'
```

You can see unescaped `"`. Found somewhere in http://loklak.org/dump/messages_201506_68404958.txt.gz.

**Comment by mariobehling** [comment]
@treba123 Would you like to help out and check if this issue still persists?

**Comment by treba123** [comment]
Will look into it

**Comment by treba123** [comment]
This is still the case (you can check by copy pasting content from a dump [here](http://jsonlint.com/)

There are two issues:
- No commata at the end of each line
- The dumps are just a collection of objects, an array basicly. So to be valid, there would need to be square brackets at the beginning and the end of the file. Don't know if we can guarantee that we will get it on at the end.

**Comment by treba123** [comment]
@Orbiter making the dump files valid json objects would mean a format change of dump files (see comment above).
If I get it right, that would require changes to dump writes, the dump importer and especially a mechanism to either convert old dumps or atleast to stay compatible with them.

Should I do that or is it enough to maybe write explanation how to handle the files?

**Comment by sudheesh001** [comment]
I think I brought this up very long back during the initial phases of the project, I believe that is by design. Not really sure. @Orbiter can answer better. :smile:

**Comment by treba123** [comment]
Oh never mind, I got this wrong. That is clearly by design. The bug report was about characters that are not allowed unescaped. Will recheck if this still persists.

**Comment by treba123** [comment]
Didn't encounter any issues regarding wrong encoding.
