### ISSUE TITLE
How can we check the number of tweets harvested by loklak?

### ISSUE THREAD

**Issue by yasoob** [loklak/loklak_server#180]

**Comment by gunvirranu** [comment]
Are you talking about how many tweets are returned when using search.json?

**Comment by sudheesh001** [comment]
Total number of tweets are shown on the loklak server's home page along with the harvesting speed.

**Comment by Orbiter** [comment]
http://loklak.org/api/status.json gives you the information. However, currently the loklak server fails to store more than ca. 60 million tweets and then it's update speed is lower than the push speed. This causes OOM at some point and I delete the search idex to be able to accept more tweets. The actual number of tweets right now must be more than 200 million.

**Comment by yasoob** [comment]
Thanks! My instance has over 3 million tweets then :)
http://yasoob.mybluemix.net/api/status.json

Kind regards,
Muhammad Yasoob Ullah Khalid <http://yasoob.me/>
Book: Intermediate Python <http://book.pythontips.com/>
Blog: Python Tips <http://pythontips.com/>
