### ISSUE TITLE
Offer more information through peers.api to allow creation of lists and gamification

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_server#182]
The API on http://www.loklak.org/api/peers.json already shows basic information about peers. In order to make this API more useful and allow the creation of lists, it would be great to include more info, e.g.:
- date peer went online originally
- time peer is running continuously
- number of tweets harvested
- number of accounts harvested
- twitter account of owner (optional)
- location of owner (Geolocation - so we can show where there are the most peers in the world)
- URL of peer

Related to this issue:
- Ping frequently https://github.com/loklak/loklak_server/issues/34
- add a request-command-api for p2p load distribution https://github.com/loklak/loklak_server/issues/73

**Comment by mariobehling** [comment]
This is related to https://github.com/fossasia/gci15.fossasia.org/issues/295

**Comment by Orbiter** [comment]
currently none of the information is stored persistant. That means some of the suggested metrics cannot be implemented in a simple way - persistent peer information would have to be implemented first. From my point of view the most important (but right now missing information) is not listed above:
- information if or if not the peer has an open server port and can be accessed directly

This could be used to distribute messages in a similar way as it is done with documents in YaCy

**Comment by Orbiter** [comment]
however, most of the information is persistent in the remote peer and can be submitted each time it connects to the backend.

**Comment by Orbiter** [comment]
I am currently working on this. Part of the result could also be another visible front-end page which shows all accessible peers. A test for accessibility will also be implemented to ensure that all listed peers are usable for the 'gameification' you have in mind.

**Comment by mariobehling** [comment]
There is an implementation of a student using the first version here http://gci15.fossasia.org/#loklak

**Comment by Orbiter** [comment]
wow, amazing! How can/should we integrate this?

**Comment by mariobehling** [comment]
@Orbiter I did not follow up in a timely manner. Sorry. I think we do not need to integrate the students work, but it would still be nice to have more information in the peers.api. At the moment there are only 24 peers online and I wonder if we are really covering all peers are actually online.

**Comment by mariobehling** [comment]
@Orbiter Not sure, if we could assign someone from the team to help with this.

**Comment by mariobehling** [comment]
@treba123 Wanna take this on?

**Comment by treba123** [comment]
@mariobehling sorry, but this is too similar to the tasks that were unassigned from me.

**Comment by mariobehling** [comment]
As dev teams focus has finished, I am classifying this as "wontfix". Anyone re-opening this topic should be willing to work on it.
