### ISSUE TITLE
Cannot perform raw queries on hashtags. 

### ISSUE THREAD

**Issue by DengYiping** [loklak/loklak_server#184]
E.g: http://loklak.org/api/search.json?q=#fossasia @sudheesh001 

This query does not contain any key word, just a hashtag, and it did not give us JSON data.

**Comment by DengYiping** [comment]
One possible solution is add the same key word as the hashtag in queries, like http://loklak.org/api/search.json?q= fossasia #fossasia. @Orbiter do you consider this a bug, otherwise we should modify our JSON API doc and add some specification.

**Comment by sudheesh001** [comment]
Blocks. https://github.com/fossasia/fossasia-loklak-webtweets/pull/1

Any views @Orbiter ?

**Comment by gunvirranu** [comment]
I'm sure you can just encode the hashtag when performing the query. For example:
http://loklak.org/api/search.json?q=%23fossasia

Unless you're asking specifically without encoding, then I can't help you there.

**Comment by codethejason** [comment]
I can confirm that what @gunvirranu said will fix the problem. The API only reads URL encoded text.

**Comment by Orbiter** [comment]
this is not a bug, the query is wrong. If you use a '#' in a url, it is ignored. The '#' must be urlencoded, like http://loklak.org/api/search.json?q=%23fossasia

**Comment by smokingwheels** [comment]
@DengYiping @gunvirranu @codethejason 
http://smokingwheels.mooo.com/forum/topic.asp?TOPIC_ID=99 
I think I have all the RSS Formats covered JSON should be similar.

**Comment by DengYiping** [comment]
Thank you @Orbiter @smokingwheels

**Comment by gunvirranu** [comment]
Also, for anybody confused by this:
http://www.w3schools.com/tags/ref_urlencode.asp
