### ISSUE TITLE
Inconsistency on port number when using docker

### ISSUE THREAD

**Issue by DengYiping** [loklak/loklak_server#187]
Docker may forward the port to a different port via ``` -p```. On peer API, my port is 80 and 443. However, my real port is 81.  Example:

My server IP: ```45.55.26.40``` 
My server's URL: [My loklak_server](http://geekinguniverse.com:81)
A link to peers API: [peers api](http://loklak.org/api/peers.json)
My server's info on peers api:

```
{
    "class" : "SuggestServlet",
    "host" : "45.55.26.40",
    "port.http" : 80,
    "port.https" : 443,
    "lastSeen" : 1452155593857,
    "lastPath" : "/api/suggest.json",
    "peername" : "anonymous"
  }
```

Maybe we should consider add a new key-value pair on the API to distinguish dockerized server from others. Then modify dockerfile to add extra info to settings so that loklak_server knows it is dokerized.

**Comment by Orbiter** [comment]
How can loklak know which port you used to forward port 80 to 81?

**Comment by smokingwheels** [comment]
Could you add a setting in the config file for port mismatch?
port.http=80 (for internal network)
port.http.real=81 (for external network to report to other peers in the suggest API)

From tests I have done lots of peers have a mismatch.

**Comment by Orbiter** [comment]
This would be a good enhancement. In YaCy there is something similar where we also consider that there is a different public IP - in case that you create a port forwarding around loklak/yacy.

**Comment by mariobehling** [comment]
> Could you add a setting in the config file for port mismatch?

If this is still a feature request, please open a dedicated issue with the request. The issue as mentioned in the headline has been cleared up before as loklak does not take care of port forwarding.
