### ISSUE TITLE
In a Peer Group have the Backend respect the Frontends speed

### ISSUE THREAD

**Issue by smokingwheels** [loklak/loklak_server#20]
Under high load the backend seems to ask a slow peer for a result too often.
A way around this is set the DoS settings of the backend to limit the request speed.
My rough formulator for a front Peers is the average response time + 800 ms - ping.

For backend timing.
 I Add 500 ms to (front peer time) and divide by the number of forward peers.
You will see a rare 503 error in a peer sometimes when there too close together.   

The program I use may work in Linux with url2file and QB64 but works as is on windows with url2file installed.
[Loklak tune] (https://github.com/smokingwheels/loklak_tune)

**Comment by Orbiter** [comment]
good hint, will implement this in the context of https://github.com/loklak/loklak_server/issues/32
