### ISSUE TITLE
Error 500 shown on clicking "show an example". 

### ISSUE THREAD

**Issue by anamika2910** [loklak/loklak_server#200]
On using loklak ,on my local server (localhost:9000) error 500 came up on clicking "show an exmaple" button on the index.html page.

![screenshot from 2016-01-10 15 25 22](https://cloud.githubusercontent.com/assets/11133538/12221002/e2a26234-b7ae-11e5-85b3-e4b600489fcd.png)

**Comment by DengYiping** [comment]
Completely reinstall will solve this problem. We are still investigating what cause the problem. @anamika2910

**Comment by DengYiping** [comment]
See [Issue 140](https://github.com/loklak/loklak_server/issues/140)

**Comment by DengYiping** [comment]
Please close this issue and report to the issue I mentioned above.
