### ISSUE TITLE
Empty response from Server

### ISSUE THREAD

**Issue by shaheenkdr** [loklak/loklak_server#205]
Working on the Loklak wall Android App, using Google Volley for network calls, however many a times the server returns empty response still with 200 code. Forcing volley to automatically go for onErrorResponse() , what's the best way to fix this issue, or any tips on tackling this?
https://github.com/shaheenkdr/loklak-wall/blob/master/app/src/main/java/com/fossasia/loklak/Activities/Adapters/MainActivity.java

**Comment by DengYiping** [comment]
It is because you do the query too frequently? The server has anti-DOS settings.

**Comment by shaheenkdr** [comment]
I see! Well, in that case, what's the interval by which I get a successful Output? Atleast, to test the app, is there anyway to get an API end point that does not have a DOS restriction? Trust me, I won't make a Denial of Service :D

**Comment by Orbiter** [comment]
the server distinguishes remote access and access by localhost. If you program something which does do many reuests in a small time, then you are doing something wrong. This DoS protection is not a bug and a force to either: run their programs either against their own instance of loklak (run it yourself, make all inks relative!) or think about your data structures and call loklak.org infrequently.

**Comment by shaheenkdr** [comment]
@Orbiter , well assume I created the app, and wouldn't the same happen if an end user queries for many items simultaneously,  which would give a negative feedback about loklak? I am just asking . And what's the time interval? I mean let X be the time I made a request to server, and at what time can I make a request again with the maximum probability of getting correct response without server throwing empty response?

**Comment by DengYiping** [comment]
@shaheenkdr In your case, the best solution is to set up your own server, and in the config file, you can turn off anti-DOS, import the dump from the main server and then you can do whatever you want.

**Comment by Orbiter** [comment]
the default times are given in the Settings file: https://github.com/loklak/loklak_server/blob/master/conf/config.properties#L31
That means default loklak will Blackout if requests come earlier than 100 milliseconds.

**Comment by shaheenkdr** [comment]
Thanks @Orbiter :)
