### ISSUE TITLE
Netty do not respond when running on low memory machine

### ISSUE THREAD

**Issue by DengYiping** [loklak/loklak_server#212]
I run loklak_server on a low memory AWS machine( 1G of memory with 4G of swap) and it do not respond after 5 or 6 hours. We are be able to establish tcp connection on port 80, but netty do not respond. It is working all right on higher memory machine, say 1.7G of memory.

I've try to run on AWS couple times. I run the docker container at night and I assign it as backend for another server; in the morning it stop responding.  This is the third time it happens. Memory should not cause this problem since I opened a swapfile.

By the way, the bottleneck of loklak_server appears to be CPU and memory instead of I/O. We should accelerate the harvester by managing a proxy pool and use free proxy to work around twitter.
CPU and memory usage should be lower to fit in small instance like AWS free tier instance.

**Comment by smokingwheels** [comment]
What version of Java are you using? @DengYiping

**Comment by DengYiping** [comment]
Java 1.8 @smokingwheels

**Comment by smokingwheels** [comment]
@DengYiping try going back to Java 1.7.
Does you server have SSD or HDD?

**Comment by mariobehling** [comment]
@DengYiping As the code base has changed a lot since this report, it is difficult to follow up. If the issue persists, please open a new issue and provide detailed info and any logs you find on the system. Thank you!
