### ISSUE TITLE
Implement data collection from Chinese twitter like service Shuoshuo

### ISSUE THREAD

**Issue by DengYiping** [loklak/loklak_server#218]
Shuoshuo is a social network nested in Tencent's Qzone. It currently has over 600,000,000 active user. We can implement it based on my crawler written in C++ [Shuoshuo Crawler](https://github.com/DengYiping/Shuoshuo_crawler).

**Comment by DengYiping** [comment]
Shuoshuo is very loose on their crawling rate. ( 20 -30 queries per second.)

**Comment by DengYiping** [comment]
Also see [Crawling Chinese Social Network — Shuoshuo (or QQ Kongjian 说说爬虫)](http://geekinguniverse.com/2015/11/16/crawling-chinese-social-network-shuoshuo-or-qq-kongjian/)

**Comment by DengYiping** [comment]
@Orbiter  I have some question about implement this. Should we connect to elastic search and write to ES, or we should push to through restful API to loklak, or we should something else. I have move part of my work to JVM(written in Scala), and I have two way to implement. Both ways are not hard to implement .

**Comment by DengYiping** [comment]
@Orbiter  I have consider several solution, and I hesitate about whether to reuse the current tweet schema or build my own schema(start a new type in current indexes). If we use the current schema, we have to do some modification on the current schema so that we can tell where it come from, like twitter, weibo or shuoshuo.

**Comment by Orbiter** [comment]
what would be the modification - new fields? We should do this in the message index, not a new one.
Please describe what you think makes the new fields necessary.

**Comment by DengYiping** [comment]
@Orbiter  I've update my rewrite my program in scala, https://github.com/DengYiping/shuoshuo_scala

I think we can start working on it. Modify the DAO layer and it will push to loklak automatically.

And maybe we should add a plugin in elastic search for better Chinese support.

 There is only one problem on it, the crawler needs at least on account's session to keep crawling, so we need to keep feed the``` add worker ``` api user account's session. I will crack this problem a little later.

**Comment by jig08** [comment]
Hey, [qqshuoshuo.com](http://www.qqshuoshuo.com/) is the exact link to the Chinese twitter service ?

**Comment by DengYiping** [comment]
@jig08 [qzone.qq.com](shuoshuo) I've several implementation , I haven't migrated it to loklak yet, feel free to check out my github account.

**Comment by jig08** [comment]
@DengYiping Sure, Doing the same :grinning: 
Thanks.

**Comment by jig08** [comment]
I have tried using the `JSoup` approach to extract text from [qqshuoshuo.com](http://www.qqshuoshuo.com/)  but testing takes lots of time as the result is retrieved in Chinese characters and if I copy paste the entire thing in _Google Translate_ it returns me a message `Text exceeds character limit.`.

I am testing it phrase-by-phrase or line-by-line and shall push the code soon.

**Comment by jig08** [comment]
QQ Recommended Talks  from [qqshuoshuo.com](http://www.qqshuoshuo.com/) stored as an array of Strings. 
Refer: https://github.com/jig08/loklak_server/pull/1/commits/476fb722e39fc577ecadb64743a03859785c96b0

Will be doing similarly for `Latest QQ talk` and `QQ talk Leaderboard`.

**Comment by DengYiping** [comment]
@jig08 You are working on a wrong website, the correct one is [qzone.qq.com ](shuoshuo)

**Comment by DengYiping** [comment]
@jig08 the website you are working on is just a CMS.

**Comment by jig08** [comment]
Oh, proves it. I had been unable to get its concept fully. Thanks. Will implement the same on 
[qzone.qq.com](http://qzone.qq.com/)

**Comment by jig08** [comment]
Even after translating via _Google Chrome,_ only Chinese characters are displayed :cry: 


![screenshot from 2016-06-03 18 36 54](https://cloud.githubusercontent.com/assets/9291400/15779477/42f748b6-29ba-11e6-85d3-b89439d30354.png)
![screenshot from 2016-06-03 18 36 21](https://cloud.githubusercontent.com/assets/9291400/15779478/42fd8780-29ba-11e6-9d9a-7ea0b117cd4a.png)

**Comment by DengYiping** [comment]
@jig08 [link](http://geekinguniverse.com/2015/11/16/crawling-chinese-social-network-shuoshuo-or-qq-kongjian/ ) Here is a link to a article about the crawler. This post is about a old version of the crawler, but it is still working. I can help you with the translation, also.

**Comment by DengYiping** [comment]
@jig08 On the second page, it asked you to login.

**Comment by jig08** [comment]
Thanks @DengYiping , translation would be very helpful :smiley: 

Also, the article [Crawling Chinese Social Network — Shuoshuo (or QQ Kongjian 说说爬虫)](http://geekinguniverse.com/2015/11/16/crawling-chinese-social-network-shuoshuo-or-qq-kongjian/) is informative . Maybe, we could use the similar code in Java and integrate in Loklak Server more easily ?

**Comment by jig08** [comment]
@DengYiping  Your comment _"@jig08 On the second page, it asked you to login.  https://github.com/loklak/loklak_server/issues/218#issuecomment-223592749_" I didn't  get it ...

**Comment by DengYiping** [comment]
@jig08 On the second picture, it asked you to login. In order to use shuoshuo, you have to have a qq account.

**Comment by jig08** [comment]
@DengYiping ohm the one with the QR code ? Can we proceed without login ?

**Comment by DengYiping** [comment]
@jig08 I have a version currently worked on Scala. It wouldn't be hard to store data in loklak.

**Comment by jig08** [comment]
@DengYiping Sure. We could test and then merge it after enhancing it  ?
