### ISSUE TITLE
Create an update.sh to read the config so that there is no down time after update.

### ISSUE THREAD

**Issue by smokingwheels** [loklak/loklak_server#22]
I was updating my server and by accident I forgot to stop it.
So I updated the other 5 with the servers running.
I still did a start and stop at the end to bring my new config file online.
It would need further testing because I had 1/6 that failed but its a really old PC though.

I was able to Clone Copy and Build without error.
I used these commands .

cd /var/loklak_server
git clone https://github.com/loklak/loklak_server.git
cp -r loklak_server/* /var/loklak_server
ant
bin/stop.sh
bin/start.sh

**Comment by Orbiter** [comment]
this was actually implemented a week ago. just run `bin/upgrade.sh`
