### ISSUE TITLE
Possible change in architecture

### ISSUE THREAD

**Issue by DengYiping** [loklak/loklak_server#223]
Also I have considered the possibility to change the architecture and get close to micro-service. For example, separate the elastic search from the loklak_server. 
I noticed that elastic search is running as a node together with loklak_server, it is a better solution to consider elastic search as a stand alone service. Integrity sometimes affect the scalability. In order to achieve that, we should use ES's java driver in client mode(no matter it is transport client or node client.). And we should separate RESTful API server and the harvester. There is a lot of stuff that we can run as stand alone service. 
At the age of Containers, micro service is not that hard to manage.
Although we separate them, loklak_server can still run together as a service by just simply run all of them on a single node, although it is not recommended to do so.
Current scalability solution is not good enough. In a lot of case, we only need one node that running the RESTful API, the rest of them should be simply harvester and elastic search.
With Cloud technology, there is no need to depend on a single, powerful node. When doing the update, we can simply let part of node running, and part of node updating, we will not face any data loss or have any down time.(The cluster has to be properly configured. If we want to update the RESTful API service, maybe a load balancer is needed, like nginx)

**Comment by Orbiter** [comment]
this was implemented in https://github.com/loklak/loklak_server/commit/0d38ba04002f911986f494486f1dadd44d5023ac as an option which you can configure. Please read the commit comment on how to do that
