### ISSUE TITLE
Image URL from the API

### ISSUE THREAD

**Issue by shaheenkdr** [loklak/loklak_server#225]
Consider this response from the API:
`{
    "created_at" : "2016-01-18T09:15:21.000Z",
    "screen_name" : "CricketAus",
    "text" : "Dhoni responds to 'selfish' criticism: http://www.cricket.com.au/news/ms-dhoni-virat-kohli-glenn-maxwell-australia-india-odi/2016-01-18?utm_source=twitter&utm_medium=social&utm_campaign=ausvind https://pic.twitter.com/BxK6bpqbWW",
    "link" : "https://twitter.com/CricketAus/status/689013192895389696",
    "id_str" : "689013192895389696",
    "source_type" : "USER",
    "provider_type" : "REMOTE",
    "provider_hash" : "6d414172",
    "retweet_count" : 1,
    "favourites_count" : 5,
    "images" : [ ],
    "images_count" : 0,
    "audio" : [ ],
    "audio_count" : 0,
    "videos" : [ ],
    "videos_count" : 0,
    "place_name" : "Fort Tondiarpet, Tamil Nadu",
    "place_id" : "236fe7c43d9dc36d",
    "place_context" : "ABOUT",
    "location_point" : [ 20.08164970208034, 45.04816050876312 ],
    "location_radius" : 0,
    "location_mark" : [ 20.081326048474654, 45.04794811239934 ],
    "location_source" : "ANNOTATION",
    "hosts" : [ "www.cricket.com.au", "pic.twitter.com" ],
    "hosts_count" : 2,
    "links" : [ "http://www.cricket.com.au/news/ms-dhoni-virat-kohli-glenn-maxwell-australia-india-odi/2016-01-18?utm_source=twitter&utm_medium=social&utm_campaign=ausvind", "https://pic.twitter.com/BxK6bpqbWW" ],
    "links_count" : 2,
    "mentions" : [ ],
    "mentions_count" : 0,
    "hashtags" : [ ],
    "hashtags_count" : 0,
    "classifier_language" : "english",
    "classifier_language_probability" : 2.7472697E-25,
    "without_l_len" : 38,
    "without_lu_len" : 38,
    "without_luh_len" : 38,
    "user" : {
      "screen_name" : "CricketAus",
      "user_id" : "17692554",
      "name" : "cricket.com.au<span class=\"Icon Icon--verified Icon--small\"",
      "profile_image_url_https" : "https://pbs.twimg.com/profile_images/597988132387102720/QzNZXhjX_bigger.jpg",
      "appearance_first" : "2016-01-18T13:17:47.479Z",
      "appearance_latest" : "2016-01-18T13:17:47.479Z"
    }
  },`

This is a tweet in which the user also has posted an image, and the link to the image provided is relative, ie `"links" : [ "http://www.cricket.com.au/news/ms-dhoni-virat-kohli-glenn-maxwell-australia-india-odi/2016-01-18?utm_source=twitter&utm_medium=social&utm_campaign=ausvind", "https://pic.twitter.com/BxK6bpqbWW" ]`

and this is the URL to the image : `https://pic.twitter.com/BxK6bpqbWW` . But using this, one cannot access the specific image, the correct URL to this image is : `https://pbs.twimg.com/media/CY_dpNPUMAAoWQp.jpg` .

**And is there a way** to get exact images from `pbs.twimg.com` URL with any tweak or hack with the API call?

**Comment by DengYiping** [comment]
My comrade, the link you are using is not a link to a image, although it has prefix `pic`. Just a timeline link. I've point it out to @Orbiter when I was doing reverse engineering on twitter and compare to the source code of loklak_server. When I read the code, I know it will not extract the image. Seem like he did not understand me. It is for sure a problem in loklak_server.[The file that the bug on is here.](https://github.com/loklak/loklak_server/blob/master/src/org/loklak/harvester/TwitterScraper.java) And you can look at my harvester [here](https://github.com/DengYiping/loklak-scala/tree/master/src/main/scala/org/loklak/crawler), I reimplemented the harvester because I want the picture. I am not very good at java( only read and write some small function since I can use java in scala.), so I cannot fix the problem by myself.

**Comment by shaheenkdr** [comment]
@DengYiping  Yeah, that's the closest path to the image! But see,  in the API there's an exact link that extracts the profile pic,  How's this done?  And scala? :/ I am developing the Twitter like wall for Loklak on Android, so image seems like a vitality! :(

**Comment by DengYiping** [comment]
@shaheenkdr Scala is a programming language on JVM. There isn't any solution right now. Give me some time I will fix it. I won't do any changes on @Orbiter 's code unless I understand it, otherwise it will cause more problem. Good luck with your project.

**Comment by DengYiping** [comment]
@shaheenkdr And also, you can do a little bit of reverse engineering on `https://pic.twitter.com/BxK6bpqbWW`, you may find the real links to the images.

**Comment by shaheenkdr** [comment]
@DengYiping  Yeah I know about Scala. I was speaking more from an Android perspective! Reverse engineering on the link, that's like an OK solution, I mean from mobile, the main API request itself takes a bit delay, and populating it on the View, and I was looking to minimize the time delay in all possible way, but doing this way would require another network call, anyway let me see if I can get an alternate solution to retrieve image! Thanks for replying :)

**Comment by Orbiter** [comment]
@DengYiping please point me to the exact line of your code where you do the reverse engineering on https://pic.twitter.com/BxK6bpqbWW to find the picture

**Comment by mariobehling** [comment]
@DengYiping A long time has passed since this issue was reported. Would be great to follow up and solve or close this issue very soon now.
> @DengYiping please point me to the exact line of your code where you do the reverse engineering on https://pic.twitter.com/BxK6bpqbWW to find the picture

Any info?

**Comment by DengYiping** [comment]
OK, here is my implementation:

https://github.com/DengYiping/loklak-scala/blob/master/src/main/scala/org/loklak/crawler/tweets/TweetComp.scala#L91-L110
```scala
class TweetImage(override val value:String) extends TweetComp with Downloadable{
  override val key = "img"
  override def toString = value
  override def url = value
}

object TweetImage extends LineFeature{
  override val pattern = """data-image-url="(http.*)"""".r

  def main(args: Array[String]): Unit ={
    val test = "data-image-url=\"https://pbs.twimg.com/media/CXTMLvQWQAEAZyG.jpg\""
    val info = this.extractor(test)
    println(info)
  }

  override def extractor(raw:String) = {
    val pattern(url) = raw
    new TweetImage(url)
  }
}
```
I just use regex to extract the data. 

In loklak, it check the tag. 
https://github.com/loklak/loklak_server/blob/master/src/org/loklak/harvester/TwitterScraper.java#L248-L261
```java
if ((p = input.indexOf("class=\"media media-thumbnail twitter-timeline-link media-forward is-preview")) > 0 ||
                (p = input.indexOf("class=\"multi-photo")) > 0) {
                images.add(new prop(input, p, "data-resolved-url-large").value);
                continue;
            }
            // we have two opportunities to get video thumbnails == more images; images in the presence of video content should be treated as thumbnail for the video
            if ((p = input.indexOf("class=\"animated-gif-thumbnail\"")) > 0) {
                images.add(new prop(input, 0, "src").value);
                continue;
            }
            if ((p = input.indexOf("class=\"animated-gif\"")) > 0) {
                images.add(new prop(input, p, "poster").value);
                continue;
            }
```

Those are the code that need to be changed. 

Please contact me if you need more help.

**Comment by DengYiping** [comment]
This issue is still pending here, any update? Need any help? @Orbiter

**Comment by mariobehling** [comment]
@DengYiping Please make a pull request, if possible.

**Comment by DengYiping** [comment]
@mariobehling I will do so.
