### ISSUE TITLE
Change the structure of source dir

### ISSUE THREAD

**Issue by DengYiping** [loklak/loklak_server#229]
Change the source dir so that it follow the rules of maven, gradle and set(same rules). Currently I write a shell script to solve the problem; however, it is necessary to follow those rules. It should also work when using ant.

**Comment by Orbiter** [comment]
please post your patch script so I can see what you expect exactly

**Comment by DengYiping** [comment]
Hello! @Orbiter The script has already been merged. I won't be able to code for a while since it's Chinese New Year.

**Comment by Orbiter** [comment]
seems to be closed regarding DengYiping latest comment.
