### ISSUE TITLE
Fork errors compiling with ant.

### ISSUE THREAD

**Issue by smokingwheels** [loklak/loklak_server#23]
I Forked a copy of Loklak and then modified 2 html files. At about 7 PM +8
I downloaded my fork and tried to compile it, lots of missing files.
https://github.com/smokingwheels/loklak_server
Just from looking at /var/loklak_server forkerror/src/org/loklak there is 7 files missing on an old working install.
What am I doing wrong?

Here is the list 20 errors.

Buildfile: /var/loklak_server/build.xml

init:

build:
   [delete] Deleting directory /var/loklak_server/classes
    [mkdir] Created dir: /var/loklak_server/classes
     [echo] loklak: /var/loklak_server/build.xml
    [javac] Compiling 43 source files to /var/loklak_server/classes
    [javac] /var/loklak_server/src/org/loklak/data/MessageEntry.java:34: error: package org.joda.time.format does not exist
    [javac] import org.joda.time.format.ISODateTimeFormat;
    [javac]                            ^
    [javac] /var/loklak_server/src/org/loklak/data/UserEntry.java:31: error: package org.joda.time.format does not exist
    [javac] import org.joda.time.format.ISODateTimeFormat;
    [javac]                            ^
    [javac] /var/loklak_server/src/org/loklak/api/client/SearchClient.java:35: error: package com.fasterxml.jackson.core does not exist
    [javac] import com.fasterxml.jackson.core.JsonFactory;
    [javac]                                  ^
    [javac] /var/loklak_server/src/org/loklak/api/client/SearchClient.java:36: error: package com.fasterxml.jackson.core.type does not exist
    [javac] import com.fasterxml.jackson.core.type.TypeReference;
    [javac]                                       ^
    [javac] /var/loklak_server/src/org/loklak/api/client/SearchClient.java:37: error: package com.fasterxml.jackson.databind does not exist
    [javac] import com.fasterxml.jackson.databind.ObjectMapper;
    [javac]                                      ^
    [javac] /var/loklak_server/src/org/loklak/data/QueryEntry.java:34: error: package org.joda.time.format does not exist
    [javac] import org.joda.time.format.ISODateTimeFormat;
    [javac]                            ^
    [javac] /var/loklak_server/src/org/loklak/data/MessageEntry.java:84: error: cannot find symbol
    [javac]             this.created_at = ISODateTimeFormat.dateOptionalTimeParser().parseDateTime(created_at_string).toDate();
    [javac]                               ^
    [javac]   symbol:   variable ISODateTimeFormat
    [javac]   location: class MessageEntry
    [javac] /var/loklak_server/src/org/loklak/data/UserEntry.java:60: error: cannot find symbol
    [javac]             this.appearance_first = ISODateTimeFormat.dateOptionalTimeParser().parseDateTime(appearance_first_string).toDate();
    [javac]                                     ^
    [javac]   symbol:   variable ISODateTimeFormat
    [javac]   location: class UserEntry
    [javac] /var/loklak_server/src/org/loklak/data/UserEntry.java:66: error: cannot find symbol
    [javac]             this.appearance_latest = ISODateTimeFormat.dateOptionalTimeParser().parseDateTime(appearance_latest_string).toDate();
    [javac]                                      ^
    [javac]   symbol:   variable ISODateTimeFormat
    [javac]   location: class UserEntry
    [javac] /var/loklak_server/src/org/loklak/api/client/SearchClient.java:50: error: cannot find symbol
    [javac]             JsonFactory factory = new JsonFactory();
    [javac]             ^
    [javac]   symbol:   class JsonFactory
    [javac]   location: class SearchClient
    [javac] /var/loklak_server/src/org/loklak/api/client/SearchClient.java:50: error: cannot find symbol
    [javac]             JsonFactory factory = new JsonFactory();
    [javac]                                       ^
    [javac]   symbol:   class JsonFactory
    [javac]   location: class SearchClient
    [javac] /var/loklak_server/src/org/loklak/api/client/SearchClient.java:51: error: cannot find symbol
    [javac]             ObjectMapper mapper = new ObjectMapper(factory);
    [javac]             ^
    [javac]   symbol:   class ObjectMapper
    [javac]   location: class SearchClient
    [javac] /var/loklak_server/src/org/loklak/api/client/SearchClient.java:51: error: cannot find symbol
    [javac]             ObjectMapper mapper = new ObjectMapper(factory);
    [javac]                                       ^
    [javac]   symbol:   class ObjectMapper
    [javac]   location: class SearchClient
    [javac] /var/loklak_server/src/org/loklak/api/client/SearchClient.java:52: error: cannot find symbol
    [javac]             TypeReference<HashMap<String,Object>> typeRef = new TypeReference<HashMap<String,Object>>() {};
    [javac]             ^
    [javac]   symbol:   class TypeReference
    [javac]   location: class SearchClient
    [javac] /var/loklak_server/src/org/loklak/api/client/SearchClient.java:52: error: cannot find symbol
    [javac]             TypeReference<HashMap<String,Object>> typeRef = new TypeReference<HashMap<String,Object>>() {};
    [javac]                                                                 ^
    [javac]   symbol:   class TypeReference
    [javac]   location: class SearchClient
    [javac] /var/loklak_server/src/org/loklak/data/QueryEntry.java:111: error: cannot find symbol
    [javac]         this.query_first = ISODateTimeFormat.dateOptionalTimeParser().parseDateTime((String) map.get("query_first")).toDate();
    [javac]                            ^
    [javac]   symbol:   variable ISODateTimeFormat
    [javac]   location: class QueryEntry
    [javac] /var/loklak_server/src/org/loklak/data/QueryEntry.java:112: error: cannot find symbol
    [javac]         this.query_last = ISODateTimeFormat.dateOptionalTimeParser().parseDateTime((String) map.get("query_last")).toDate();
    [javac]                           ^
    [javac]   symbol:   variable ISODateTimeFormat
    [javac]   location: class QueryEntry
    [javac] /var/loklak_server/src/org/loklak/data/QueryEntry.java:113: error: cannot find symbol
    [javac]         this.retrieval_last = ISODateTimeFormat.dateOptionalTimeParser().parseDateTime((String) map.get("retrieval_last")).toDate();
    [javac]                               ^
    [javac]   symbol:   variable ISODateTimeFormat
    [javac]   location: class QueryEntry
    [javac] /var/loklak_server/src/org/loklak/data/QueryEntry.java:114: error: cannot find symbol
    [javac]         this.retrieval_next = ISODateTimeFormat.dateOptionalTimeParser().parseDateTime((String) map.get("retrieval_next")).toDate();
    [javac]                               ^
    [javac]   symbol:   variable ISODateTimeFormat
    [javac]   location: class QueryEntry
    [javac] /var/loklak_server/src/org/loklak/data/QueryEntry.java:115: error: cannot find symbol
    [javac]         this.expected_next = ISODateTimeFormat.dateOptionalTimeParser().parseDateTime((String) map.get("expected_next")).toDate();
    [javac]                              ^
    [javac]   symbol:   variable ISODateTimeFormat
    [javac]   location: class QueryEntry
    [javac] 20 errors

**Comment by Orbiter** [comment]
sorry, forgot to add the libraries in build.xms. Just commited

**Comment by smokingwheels** [comment]
Thanks I will check it out soon
