### ISSUE TITLE
Add end-to-end or unit test to loklak_server.

### ISSUE THREAD

**Issue by DengYiping** [loklak/loklak_server#234]
Automatic test is necessary to detect some unknown bugs of the software. It will enhance the stability of the code. With travis-ci support, every push will be tested automatically. 
End-2-end test can be a temporary solution:
http://googletesting.blogspot.com/2015/04/just-say-no-to-more-end-to-end-tests.html

**Comment by smokingwheels** [comment]
- Automatic testing
It will be hard to test in a peer 2 peer network unless you setup you own little peer group first.

The Storage of the sub system effects the speed at which the backend peer can be run/Searched  at eg HDD, SSD or RamDisk.

I did crash loklak yesterday with a overloaded test to 10 other front peers from my pc running on a HDD, but I cant reproduce the problem yet with a fresh install.

**Comment by Orbiter** [comment]
Yeah @DengYiping you are right but there is limited time. A good starting point would be the https://github.com/loklak/loklakj_lib which contains the core code of loklak and should be tested in that way. loklakj_lib is not yet integrated in loklak but will be soon.

In loklakj_lib I already started with unit tests, would you like to join coding and add some more tests?
https://github.com/loklak/loklakj_lib/tree/master/test/org/loklak

**Comment by mariobehling** [comment]
Thanks for this initial input pushing everyone into the right direction! Travis and other CIs are integrated. If you have suggestions for more test suites, please open another issue.
