### ISSUE TITLE
GeoNames: Error when decompressing cities1000.zip! peer wont start

### ISSUE THREAD

**Issue by smokingwheels** [loklak/loklak_server#246]
Had a fresh clone yesterday on a Intel  quad core with old HDD 500 GB SATA drive running Ubuntu 14.04.
I added ~10 peers to my peer as frontends and had loklak.org as a backend.
I then proceded to search on the RSS interface/api, By using wget on a second PC with 50 or so subjects in a loop, I would open another terminal and execute the bash file several times until I got a Http Error 503 then kill all scripts and start 1 less so the the error did not happen. 
I had however lowered the DOS settings for the number of peers I had in front of me with no safety margin.
I did give my server a hard time though over 2 hours.
 
I did notice that my free memory was slowley reducing probally because the HDD was falling behind.

My peer did not start in a timely manner so see [Log Files](http://loklak.mnsnet.ca/first.7z)
GeoNames: Error when decompressing cities1000.zip!
2016-01-28 07:51:44.496:INFO::main: Waiting for elasticsearch yellow status

I did a fresh Clone today for further testing.

**Comment by sudheesh001** [comment]
I faced this issue when the cities1000.zip file was not complete in its download size, it had abruptly stopped. `data/external/dictionaries/cities1000.zip` I think a better option would be to add this to the repository and make a shell script during build copy the file from the location to the `data/` directory.

**Comment by smokingwheels** [comment]
Ok but my peer was fine for at least 2 hours before this crash. @sudheesh001

**Comment by smokingwheels** [comment]
Another thing I found is the API/peers.json list has duplicates.
Could this be the cause of my trouble?

**Comment by sudheesh001** [comment]
Maybe @Orbiter would know ?

**Comment by smokingwheels** [comment]
It starts fine now
