### ISSUE TITLE
Number of messages on my peer seems to be 20% Low.

### ISSUE THREAD

**Issue by smokingwheels** [loklak/loklak_server#247]
I processed 2 dump files from my peer, the front page reports 79133 messages at the time of saving the dumps.  The number I counted with my program comes out at 94887 messages on my loklak server.

The number of users reported on the front page is 51578. I counted 50969 users. Not too bothered about this one.  I used sort then uniq in linux to arrive at the users numbers.

**Comment by Orbiter** [comment]
maybe your peer was doing scraping meanwhile, so the numbers are higher with the users.
Did you also use uniq on the messages?

**Comment by smokingwheels** [comment]
No I did not use uniq on messages.
I just counted the number of lines in the message dump.

**Comment by mariobehling** [comment]
As the code base of loklak has changed a lot, it is difficult to track this issue now. If the issue persists, please open an issue with log files or anything else that could be useful to detect the root of issues.
