### ISSUE TITLE
My peer is mirroring stats on loklak.org

### ISSUE THREAD

**Issue by smokingwheels** [loklak/loklak_server#249]
After a fresh clone on my peer, it is picking up the front page stats of loklak.org see [Here](http://45.32.64.207:9000/index.html) 
The Dump page is mine.
I tried changing to port to 80 and the error is there as well.
I have a DNS URL redirection as well [Here](http://loklak.mnsnet.ca/)
I am not sure how to fix it but I did a java 8 install yesterday as well on debian 8

**Comment by Orbiter** [comment]
nice but where is the bug, I can't see a bug description?

**Comment by smokingwheels** [comment]
Sorry @Orbiter The bug is my peer is not displaying the correct message stats there coming from elsewhere.

**Comment by smokingwheels** [comment]
Did a old the old update method and the problem is gone.
[See](http://smokingwheels.mooo.com/forum/topic.asp?TOPIC_ID=80)
