### ISSUE TITLE
Implement a profanity filter for the tweets 

### ISSUE THREAD

**Issue by sudheesh001** [loklak/loklak_server#25]
Since `loklak_webclient` is going to be mainly used at conferences on a public wall, it'd be best to avoid outliers in the tweets (i.e. the ones which are unrelated / the one with profanity ) What could be a possible option is to have a flag during the query
`/api/search.json?q=<string>&profanityFilter=false`
Filtering such content should be on by default unless explictly mentioned as above with the query.

I think this enhancement will help the event organizers avoid embarassing situations / trolls who want to sabotage the twitter wall at a conference.

Any other views, @loklak/owners ?

**Comment by Orbiter** [comment]
yes we need the option to filter tweets at the tweet wall. The administration of such filters shall be possible for wall owners. We will implement user accounts based on twitter authentication and then those users, who defined the wall shall have a filter administration page where it should be possible to block users or words.

**Comment by Orbiter** [comment]
The new account servlet can be used to push an 'apps' object attached to the authentication credentials. This object shall carry a json property list where each property contains the setting to one application. One of that applications is the wall, and we must formulate a filter language which will then be attached to the wall property to store the filter.

To trigger the filter, the client must read the filter from the accounts api and submit it as attachment to the search request as addition to the query. Like: if no tweets from a user @baduser shall be shown, then the search must be extended by the term "AND NOT from:baduser". The backend must be able to parse such expressions.

**Comment by Orbiter** [comment]
It is now possible that a query can exclude words, users and hashtags using the '-' for all modifiers and constraints that we have, see https://github.com/loklak/loklak_server/commit/d27ef841abdb4259c9c29d5af4b7543c8dd2f710
Together with the apps setting, the profanity filter can be realized from the loklak_webclient

**Comment by Orbiter** [comment]
I consider implementation of a bayesian filter to implement this so search requests can simply add a `-/profanity` to exclude profanity (and therefore also see *only* profanity with `/profanity` :wink: )

**Comment by Orbiter** [comment]
implemented in https://github.com/loklak/loklak_server/commit/1f1bb73d8f9150336409834f99ccffad87cbfcec
