### ISSUE TITLE
Question: On data rendered by API  (Creating twitter wall using loklak API)

### ISSUE THREAD

**Issue by sopu** [loklak/loklak_server#250]
1. Instagram images should just be included in links (only and not in images) IMO. (e.g.) https://www.instagram.com/p/BBTNcGJO7sAY7wAWKC2ZGC5oJ6R15I_6KdTBzI0/ load a page and not the image. 
2. Links are not rendered correctly as the closing tag is incomplete " \<a> ...data.... </a". Is this meant to be like this. If yes, then it would be great if someone could explain the reason for this.
3. Some of the suspended accounts are being included in results.

PS: You can see the social wall prototype on https://github.com/sopu/loklak_server 
![screenshot from 2016-02-02 20 21 31](https://cloud.githubusercontent.com/assets/6399612/12779327/6f6ebb18-ca8d-11e5-8e1d-41f75c6b26de.png)

**Comment by Orbiter** [comment]
wow, amazing!

**Comment by Orbiter** [comment]
Would you like to add your social_wall to loklak as an loklak app? Please see https://github.com/loklak/loklak_server/blob/master/html/apps/apps.md on how to do that. I believe it would just be necessary to move some code. Please give me a pull request for this!

**Comment by sopu** [comment]
Thanx @Orbiter I would do it ASAP.

**Comment by Orbiter** [comment]
Hey sopu, next week is FOSSASIA in singapur and I would like to show your social wall at the stage, can you do this in the next seven days?

**Comment by sopu** [comment]
@Orbiter: I have submitted a PR #275

**Comment by sudheesh001** [comment]
I think this issue can be closed now ? It looks like the wall has been merged. As discussed on gitter, maybe the next thing one could enhance this with is the load new tweets features.
