### ISSUE TITLE
Bad Gateway 502 followed by 504 while retrieving tweets

### ISSUE THREAD

**Issue by aayusharora** [loklak/loklak_server#257]
![important1](https://cloud.githubusercontent.com/assets/12194719/13121940/8a413c10-d5da-11e5-8269-c4e35aabb219.png)
![important2](https://cloud.githubusercontent.com/assets/12194719/13121941/8a5842f2-d5da-11e5-875d-02a32363eeba.png)

**Comment by aayusharora** [comment]
When opening loklak.org at the same time shows 504 error.This happens five times in a single day for about 2 minute.

**Comment by smokingwheels** [comment]
@aayusharora What sort of delay are you using between GET requests?

**Comment by aayusharora** [comment]
@smokingwheels ,Please tell more about your question .But my point was nginx server is going down again and even loklak.org official website iis down from whole day  http://loklak.org/.

**Comment by smokingwheels** [comment]
@aayusharora How often do you request information from loklak.org?
Also have you setup your own loklak server to use incase the main site is down?
See [Here](http://loklak.org/download.html) or [Here](http://smokingwheels.mooo.com/forum/topic.asp?TOPIC_ID=80)

**Comment by Orbiter** [comment]
I believe this should not happen again after https://github.com/loklak/loklak_server/commit/bb53a68d3bba062205c768c73c1197bf0f6678d9
