### ISSUE TITLE
Incompatibility with Kibana

### ISSUE THREAD

**Issue by rkgudboy** [loklak/loklak_server#259]
I am trying to use Kibana (v 4.4.1) as Search front end in current version of Loklak.
Loklak has v 2.1.1 of Elasticsearch coupled with it, that is not supported by latest builds of Kibana.

On using pervious versions of Kibana ( I tried 4.3.1, 4.3.1, 4.1.5) I am getting Title bar of Kibana interface with blank screen, no content.
![screenshot from 2016-02-19 13 52 21](https://cloud.githubusercontent.com/assets/3122870/13170155/13e0e372-d710-11e5-9061-03a870334d00.png)

**Comment by Orbiter** [comment]
latest kibana is supported with https://github.com/loklak/loklak_server/commit/43d7f64dfb2ced5e690078d990e7878e5ea50fed
