### ISSUE TITLE
Twitter Authorization: Backend Requirements

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_server#26]
we already discussed the Option, that a Twitter user shall be able to authentify within loklak with his/her twitter account which would turn loklak into an Twitter app for that user.

What we need is
- a web page which takes the log-in data from Twitter
- a servlet which authentifies the user against twitter and establishes a user authentication against the loklak back-end
- a framework for loklak web pages which uses that authentication, how is this done in angular.js?

We must discuss what you would expect from the server backend for authentication. Can you describe details?

**Comment by Orbiter** [comment]
This was implemented in https://github.com/loklak/loklak_server/commit/4f2b31ea5f8d524332edfb8c9b267cb1f670090e and documented in https://github.com/loklak/loklak_server/commit/817eb7d335fc1356f040a2f5514608429c1d9d1d
