### ISSUE TITLE
Address to files is not correct in applist/index.html

### ISSUE THREAD

**Issue by SilentFlame** [loklak/loklak_server#262]
Index.html
https://github.com/loklak/loklak_server/blob/master/html/apps/applist/index.html

**Problem** : address of `about.html`, `index.html`, etc not correct.

**Solution** : Need to provide proper path to the files.

**Comment by SilentFlame** [comment]
I just checked via server, the previous one also works.
But for better understanding we should keep the path properly.

Hence here it's my opinion to use the above PR's way to give path.

**Comment by SilentFlame** [comment]
once PR #268 is merged this issue can be closed.

**Comment by Orbiter** [comment]
https://github.com/loklak/loklak_server/pull/268 is merged
