### ISSUE TITLE
Server does not shutdown

### ISSUE THREAD

**Issue by shivamMg** [loklak/loklak_server#265]
Even after issuing `bin/stop.sh` at the terminal the server keeps on running at `localhost:9000`. A message that loklak has been terminated is displayed but service is still available at localhost.

```
$ bin/start.sh 
starting loklak
loklak server started at port 9000, open your browser at http://localhost:9000

$ bin/stop.sh 
shut down of loklak
loklak has been terminated

$ bin/stop.sh 
shut down of loklak
cat: loklak.pid: No such file or directory
loklak has been terminated
```

**Comment by sudheesh001** [comment]
It's probably just the cache, did you try opening up a private browsing with the same localhost url and seeing if it works ?

**Comment by shivamMg** [comment]
It's not the cache. I opened it in private browsing and it's running.

**Comment by SilentFlame** [comment]
@shivamMg  Initially I got the same error.
but when I used the private window opening as mentioned by @sudheesh001 , It works fine for me though.

**Comment by SilentFlame** [comment]
@sudheesh001 can we do something regarding the cache thing here?

**Comment by shivamMg** [comment]
Ok, got it. Whenever we run `bin/start.sh`, it starts a java server. The PID of this server is stored at `data/loklak.pid`. Now when we run `bin/stop.sh` it takes the PID of the existing server instance from the file and kills it. The problem appears when you start the server with `bin/start.sh` but do not stop an existing instance of it. If this happens, `bin/start.sh` overrides the existing PID with the PID of the new instance, and if you stop it with `bin/stop.sh` now, the new server instance is stopped but the older PID is now lost. So if you keep on executing `bin/start.sh` you will have multiple server instances with lost PIDs except the latest one.

Solution is simple. We can check if there is already a running instance of loklak, remove it, if it exists, and start a new instance again.

**Comment by shivamMg** [comment]
@sudheesh001 I have fixed the bug and will publish the changes. I have an older PR https://github.com/loklak/loklak_server/pull/266 if you can review it.

**Comment by Orbiter** [comment]
The right behavior should be
- do not start a new process if one is running already
- do not overwrite the pid
- show a message that the process is already running

**Comment by SilentFlame** [comment]
Either we are done here with the server, or we can create a new file for restart of the server.
which first quits the running server and then starts the new server.
@sudheesh001 @Orbiter @shivamMg 

what you guys say?

**Comment by smokingwheels** [comment]
@SilentFlame @sudheesh001 @Orbiter @shivamMg
I have had times where it wont start because the Eleastic search ports are tied up some how an actual Reboot of the host OS server fixes it.

**Comment by shivamMg** [comment]
I would second that. Came across the same situation and had to do a restart.

**Comment by Orbiter** [comment]
behaviour fixed with https://github.com/loklak/loklak_server/commit/bfa134f0b295f1fe8a53ad9f74cdefc0b1da9f83
