### ISSUE TITLE
Create a Disk buffer to cut IOPS on a Harddrive Ext4 format

### ISSUE THREAD

**Issue by smokingwheels** [loklak/loklak_server#274]
The Journal Overhead seems to be a problem with loklak with Ext4 partions.
By using a program iotop lets you see what is going on with the hdd.

The Journal process  **jbd2/vda 1-8** and **swapping java 8** uses approx half the Disk IOPS avalible in my system with a HardDisk in use.
See [Pic.](http://smokingwheels.mooo.com/loklak.jpg)
I create a linux system with Ext2, no Journal to test as well and the IOPS where less but you have an unstable system if the power goes off unexpectedly

Is it possible to create a Disk buffer with the loklak server?
See Diskio [pic](http://smokingwheels.mooo.com/diskio.jpg)

**Comment by Orbiter** [comment]
this is a good hint but from my experience with YaCy I knew that IO should be prevented as possible. There is no bad code which I implemented that could cause this - because loklak does not even write much during operation. All write processes are made by lucene within elasticsearch.

We should have a look to elasticsearch settings if this IO can be reduced somehow. Can you please have a look for such settings?

**Comment by smokingwheels** [comment]
Ok I will look into it and try to implemt Merge to ~ max_bytes_per_sec to 10mb for the ES

**Comment by smokingwheels** [comment]
I may have a fix.
I am open to comments for higher powered peers to try out. 
@Orbiter @mariobehling @julianfox @pguth 

I think we should have a config for the server mode (Backend or Frontend) then if it is on a Hardisk or SSD.

I found this [site](https://www.elastic.co/guide/en/elasticsearch/guide/current/indexing-performance.html) that recommends settings 


In my config.properties in Loklak I added this.

My setting for old or low power single CPU Peers with Media of type HDD
# elasticsearch.indices.store.throttle.type =all =merge =none
elasticsearch.indices.store.throttle.type=all

# elasticsearch.indices.store.throttle.max_bytes_per_sec =250kb (for old computer or frontend harvester you could use this if you are using your own SSD and just expermenting) 
elasticsearch.indices.store.throttle.max_bytes_per_sec=250kb

# elasticsearch.index.merge.scheduler.max_thread_count=1 (used when on HDD media comment out if on SSD)
elasticsearch.index.merge.scheduler.max_thread_count=1

Change depending on your need for Realtime data in the Elastic Search
# elasticsearch.index.refresh_interval=10s  (Default 10s For Backend Frontend Peer set to 2m)
elasticsearch.index.refresh_interval=2m

My Peer is doing Harvesting Speed: 17 messages per second; 1,468,800 messages per day.
See [pic](http://smokingwheels.mooo.com/aftermod948.png)

The Average Load on my single CPU peer was approx 1 now 0.25 to 0.35.
It seems the Journal process on the HDD was keeping the CPU Busy.
