### ISSUE TITLE
More complex web apps

### ISSUE THREAD

**Issue by leonmak** [loklak/loklak_server#278]
Hi, I created this tweet wall using MeteorJS, was wondering if it's considered an 'app' under the front end.
http://meteortweetwall.meteor.com/
https://github.com/leonmak/meteor-twitterwall

**Comment by Orbiter** [comment]
Hey, thats a great thing!
We I don't know how much stuff is inside your MeteorJS environment which must be moved to the loklak app zone as well. Just try to integrate it and give me a pull request.

**Comment by leonmak** [comment]
it requires node so it can't be hosted on github, can i just link to the repo?

**Comment by leonmak** [comment]
Could I just link to the repo? There's a server part to it and it requires the user to download meteor

**Comment by leonmak** [comment]
#279 Since it has a server the option is for users to run it locally

**Comment by sopu** [comment]
@leonmak: AFAIK the main focus of creating front-end apps with loklak server is to explore how users can take help of loklak's capabilities in their apps. 
It would be great if user is able to use this app like ``http://loklak.org/apps/<appname>``

**Comment by leonmak** [comment]
@sopu ok, for now I guess don't accept it as it doesn't fit the current structure

**Comment by mariobehling** [comment]
Closing this as the project has advanced and there is a dedicated wall project.
