### ISSUE TITLE
Loklak says publicly accessible port is 9100 instead of 9000

### ISSUE THREAD

**Issue by daminisatya** [loklak/loklak_server#281]
The loklak server runs on port 9000 but the architecture documentation mentions it as 9100 in the following page, This needs to be changed to 9000
http://loklak.org/architecture.html

**Comment by sudheesh001** [comment]
Good catch. Would you like to send a pull request to fix this ? https://github.com/loklak/loklak_server/blob/65b076e8e81cc3dd9c4219073582d6509cb1bc52/html/architecture.html#L113

**Comment by daminisatya** [comment]
#282

**Comment by sudheesh001** [comment]
Fixed via https://github.com/loklak/loklak_server/commit/e45f6099b84ff02d20cdd2fc20768076394c19f8
