### ISSUE TITLE
CPU usage maybe lowered with ufw firewall and Defending SYN Flood Attack settings

### ISSUE THREAD

**Issue by smokingwheels** [loklak/loklak_server#283]
ufw allow ssh port and 9000 + whatever else if using elastic search see [here](https://www.digitalocean.com/community/tutorials/how-to-setup-a-firewall-with-ufw-on-an-ubuntu-and-debian-cloud-server)

See Defending SYN Flood Attack down the page a bit [here](http://linoxide.com/firewall/snapshot-syn-flood-attack/)
see nano /etc/sysctl.conf

The setting net.ipv4.netfilter.ip_conntrack_tcp_timeout_syn_recv=45 did not work on Ubuntu 14.04.
There are also other types of attacks I haven't looked into yet.
My VM cpu average load went from 1.2 load per core to 0.25 per core with less spikes after implementing changes.
Feel free to comment.

**Comment by mariobehling** [comment]
Thank you. Unfortunately, there are not sufficient resources to work on this. Have to close it therefore.
