### ISSUE TITLE
Don't let 404s be the end of the road for the user.

### ISSUE THREAD

**Issue by sudheesh001** [loklak/loklak_server#286]
404 pages are what users really hate, it'd be nice to ensure that these pages do not frustrate users with log failure messages but instead take the opportunity to put users in the right direction again. loklak server lacks a custom 404 page. I gave it a shot here. Image credits open clip art: https://openclipart.org/detail/171518/grasseating-cow

<img width="1440" alt="screen shot 2016-04-12 at 11 45 28 am" src="https://cloud.githubusercontent.com/assets/4545925/14451347/122152b6-00a4-11e6-9753-85d064950ab0.png">

This is the initial attempt, I am open to more ideas about the text that could be used and the image. @mariobehling what do you think ?

@Orbiter I've read the jetty [custom error pages](https://wiki.eclipse.org/Jetty/Howto/Custom_Error_Pages) documentation but wasn't able to write the error codes with the `web.xml` file so that the server could automatically redirect to the 404 page if it hits the error.

Is the error handling happening here for the 404 pages too ?
```java
ErrorHandler errorHandler = new ErrorHandler();
errorHandler.setShowStacks(true);
servletHandler.setErrorHandler(errorHandler);
```

Can this be extended as documented here ?
> ## Custom error handler class
A context may be configured with a custom error handler class that extends either ErrorHandler for generic contexts, or ErrorPageErrorHandler for webapp contexts.
The following methods may be implemented to control the appearance of the error pages:
```java
void handle(String target, HttpServletRequest request, HttpServletResponse response, int dispatch) throws IOException
void handleErrorPage(HttpServletRequest request, Writer writer, int code, String message) throws IOException
void writeErrorPage(HttpServletRequest request, Writer writer, int code, String message, boolean showStacks) throws IOException
void writeErrorPageHead(HttpServletRequest request, Writer writer, int code, String message) throws IOException
void writeErrorPageBody(HttpServletRequest request, Writer writer, int code, String message, boolean showStacks) throws IOException
void writeErrorPageMessage(HttpServletRequest request, Writer writer, int code, String message, String uri) throws IOException
void writeErrorPageStacks(HttpServletRequest request, Writer writer) throws IOException
```

**Comment by Orbiter** [comment]
the default error handler is instantiated here: https://github.com/loklak/loklak_server/blob/master/src/org/loklak/LoklakServer.java#L287-L289
I actually don't understand why we should have a custom error page. An error is an error. People should not do anything on error pages. Instead they should prevent to link to error pages. We don't link to error pages either.

**Comment by sudheesh001** [comment]
@Orbiter I agree, these are pages that shouldn't ever be hit and I agree with the fact that we don't link to 404 pages, but from a design perspective, these errors are something that we don't want 

Taking from the following [article](http://designshack.net/articles/inspiration/what-makes-a-great-404-error-page/) about design and [why we should have 404](https://www.searchenginejournal.com/importance-of-404-error-page-top-404-designed-pages/64899/) I think it's best to go with a customer error page. Though these aren't meant to be hit, we need to have a good error page so that we can retain the users.

> What a 404 page should not have is a bunch of technical jargon. (You don’t want to scare users, do you?) In all reality, you probably should not even use the headline “404 Error” because many of your users won’t have any idea what that means. Stick to something with more meaning, such as “The page can’t be found.”

**Comment by daminisatya** [comment]
@sudheesh001 it would be better if the page just shows the error with a button taking to the home page. A search option on the error page wouldn't be that great

**Comment by sopu** [comment]
A sample error page is necessary but it should not have search options. 
Most sites have a basic error template pertaining to the theme which @sudheesh001 has used. 
Extra information is not required IMO

**Comment by sudheesh001** [comment]
@daminisatya @sopu Thanks for the feedback, dropping the search option.
