### ISSUE TITLE
User profile app is not showing up.

### ISSUE THREAD

**Issue by daminisatya** [loklak/loklak_server#291]
![selection_071](https://cloud.githubusercontent.com/assets/6227784/14520219/f143005a-0240-11e6-9775-cc07f12b0306.png)

The link looks broken

**Comment by daminisatya** [comment]
#292

**Comment by sudheesh001** [comment]
Fixed via https://github.com/loklak/loklak_server/commit/6d5c309f01f56fb1303c0d46946bba78b03b2cd4
