### ISSUE TITLE
Have SSL encryption for the loklak_server with lets encrypt

### ISSUE THREAD

**Issue by daminisatya** [loklak/loklak_server#294]
https://letsencrypt.org/

**Comment by sudheesh001** [comment]
Sounds like a great idea @daminisatya 

It looks like there is official documentation for this available at [nginx](https://www.nginx.com/blog/free-certificates-lets-encrypt-and-nginx/)

Potential impacts:
- Might break all the language based client API wrappers.
     - python
     - node.js
     - ruby

**Comment by treba123** [comment]
This sounds great and very important imo. I'll have a look into this

**Comment by jig08** [comment]
@treba123 Sure. Should we assign this issue to you then ? 
And welcome aboard @loklak :)

**Comment by shivenmian** [comment]
I'd also want to have a look into this too. @treba123 give your ideas though.

**Comment by jig08** [comment]
Can't assign this to @treba123 , @Orbiter @sudheesh001 could you pls add him to the team ?

**Comment by treba123** [comment]
@jig08 yes, totally. And thank you :)
@shivenmian of course, didn't mean to 'steal' it :)
i'll just start with it to get going

**Comment by shivenmian** [comment]
Yeah of course. You can work on it. Just wanted to know what you think about what needs to be done.

**Comment by treba123** [comment]
@shivenmian alright it looks like the server doesn't yet care for the port.https config option at all.
I'd suggest we add options for
- use https (yes/no/only)
- path to private key
- path to certificate

and make the server use it. (im digging around in the code for this right now)
Direct support for letsencrypt could then realised as a plugin imo

**Comment by treba123** [comment]
I'd also like to mention that this ticket is mandatory to support http2 (maybe not of big importance right now, but nice)

**Comment by treba123** [comment]
Alright, I have the options working in my fork https://github.com/treba123/loklak_server
To add the redirection i had to add another handler-layer to the server, hope that it won't make any problems.

I'd appreciate any comments on the code and will add a few more lines of documentiations.
When it's ok, I'd suggest to merge it.

**Comment by shivenmian** [comment]
Make a pull request?

**Comment by treba123** [comment]
Yeah you're right :)

**Comment by treba123** [comment]
Ok the pull request #336 now has support for key/cert files as given by letsencrypt. So it's easy now to create a certificate and use it with loklak.
I'll now have a look if it's managable/desireble to have direct letsencrypt client integration.

**Comment by Orbiter** [comment]
Good work so far! I am really happy that you care about the dsl stuff, I was stuck somewhere when I tried this...

**Comment by treba123** [comment]
I'll close this issue as ssl support is ready now. Letsencrypt integration should happen in another issue
