### ISSUE TITLE
Widgetize the loklak_webclient with services to major CMS platforms [TRACKER]

### ISSUE THREAD

**Issue by daminisatya** [loklak/loklak_server#295]
As discussed in the gitter channel, i think this should be one of the first steps towards micro services.

**Comment by daminisatya** [comment]
As discussed in the gitter channel, i think this should be one of the first steps towards micro services.

**Comment by sopu** [comment]
I believe we have several basic parts of loklak_webclient that could act as a widget (e.g.):
1. Search
2. Wall
3. User Report
4. Maps

These can act as a proper standalone widget referring loklak API.

**Comment by daminisatya** [comment]
@sopu Yes! absolutely. The main aim is to port all these microservices as plugins.

**Comment by sudheesh001** [comment]
Since Github has rolled out multiple assignments feature lets add more developers working on the CMS plugins/components

**Comment by mariobehling** [comment]
I am closing this feature. We should follow up in specific issues for CMS.
