### ISSUE TITLE
loklak services for drupal as plugins

### ISSUE THREAD

**Issue by sudheesh001** [loklak/loklak_server#298]
Depends on: #295 

Needs:
- loklak-php
- https://www.drupal.org/
- apache / web servers running PHP

**Comment by sudheesh001** [comment]
Drupal isn't taken up yet by anyone, lets focus on one at a time. Unassigning this so that we could get back to this later. The current focus is on
- Joomla (@daminisatya)
- Wordpress (@sopu)

**Comment by mariobehling** [comment]
This is a topic outside this repository now.
