### ISSUE TITLE
Potential extensions/plugins/widgets to port to loklak in major CMS platforms

### ISSUE THREAD

**Issue by sopu** [loklak/loklak_server#299]
Wordpress: 
https://wordpress.org/plugins/search.php?q=twitter

Joomla: 
http://extensions.joomla.org/extensions/extension?searchall=twitter&filter%5Btags%5D%5B%5D=&filter%5Bcore_catid%5D=&filter%5Bincludes%5D=&filter%5Bversions%5D=&filter%5Btype%5D=&filter%5Bhasdemo%5D=&filter%5Bnewupdated%5D=&filter%5Bscore%5D=&dir=DESC&limitstart=&controller=filter&view=extension&layout=list&Itemid=145&clearorders=0&clearfilters=1

Drupal:
https://www.drupal.org/search/site/twitter

Requires loklak-php API. It could act as an extension to #295.

**Comment by sudheesh001** [comment]
Closing as duplicate. Check #295 Which is the tracker
#296 
#297 
#298 

You can add the required plugin links in the respective issues filed.
