### ISSUE TITLE
IoT Protocol Support

### ISSUE THREAD

**Issue by GeorgeHahn** [loklak/loklak_server#307]
It would be good to support IoT specific protocols to leverage loklak as an IoT datastore.

I propose that we add support for [MQTT](http://mqtt.org/) and [CoAP](http://coap.technology/). Are there any other protocols we should support?

I'll create individual issues for each protocol once a consensus has been reached.

Before development, some protocol-specific architecture discussion will be necessary. (For example, how to translate between MQTT topics and loklak data.) We can have that discussion here or in future issues. Ultimately, these architectural decisions hinge on decisions currently being discussed in #280.

**Comment by mariobehling** [comment]
@sudheesh001 Any chance we can still see this going forward during GSoC?

**Comment by sudheesh001** [comment]
As decided before I don't think we'd be seeing this, I had suggested the use of Paho library for MQTT before but there were decisions being made on automatic index generation and ability to make generic pushes.
