### ISSUE TITLE
Scalingo one click deploy failing on build because of missing javac compiler

### ISSUE THREAD

**Issue by daminisatya** [loklak/loklak_server#317]

**Comment by shivenmian** [comment]
http://i.imgur.com/XaXU2jV.png

**Comment by shivenmian** [comment]
The issue has been fixed. @sudheesh001 @daminisatya 

https://loklaksm.scalingo.io/

Closing this.

**Comment by sudheesh001** [comment]
https://loklak-scalingo-beta.scalingo.io/
