### ISSUE TITLE
NullPointerExeption in DumpImporter.run

### ISSUE THREAD

**Issue by treba123** [loklak/loklak_server#332]
Since today i get wierd errors when launching loklak from master.
In data/loklak.log i get the following error so often that the logfile actually fills up my harddrive after some time (which is maybe something we should change, too. Or is there already a way to limit log size?)

`2016-05-10 14:04:50.198:WARN::Thread-13: DumpImporter THREAD
java.lang.NullPointerException
	at org.loklak.DumpImporter.run(DumpImporter.java:67)`

Does anybody experience this, too?
I'm using openjdk version "1.8.0_91"

**Comment by treba123** [comment]
Hm never mind, somehow it works again as expected. Comming back to this if it happens again.

**Comment by leonmak** [comment]
Yea I experienced it for a while also
