### ISSUE TITLE
Specifying compatible kibana version

### ISSUE THREAD

**Issue by leonmak** [loklak/loklak_server#335]
The download page shows:
"Download Kibana from http://www.elasticsearch.org/overview/kibana/installation/"
It links to Kibana 4.5.0, which requires Elasticsearch 2.3x

The one that worked for me was [Kibana 4.4.1 ](https://www.elastic.co/downloads/past-releases/kibana-4-4-1
) referenced in #259. 
I'm not sure how to update Elasticsearch from 2.2.0 to 2.3.0, tried changing the /lib files, .classpath, and build.xml, as in 43d7f64, but `curl -XGET 'http://localhost:9200/_nodes?pretty=true'` still shows version 2.2.0.

**Comment by sudheesh001** [comment]
@leonmak Wouldn't it be nice to bundle Kibana along with loklakserver than having a standalone kibana, that would probably resolve the problem and would also be nice to have. I haven't used kibana much before but do you think this would be possible ?

Maybe @Orbiter could help here, should we have Kibana integrated into loklak_server ?

**Comment by Orbiter** [comment]
kibana runs on nodejs as far as I know. We should not bundle this, it becomes too complex.
About compatible version: we try to use the latest elasticsearch, therefore always the latest kibana!

**Comment by leonmak** [comment]
yea kibana is quite large in size, and may add on to the start time
