### ISSUE TITLE
Aggregations results shown as empty dictionary { } on loklak.org

### ISSUE THREAD

**Issue by sudheesh001** [loklak/loklak_server#338]
Works on localhost, but queries made on loklak.org show aggregations empty

**Comment by Orbiter** [comment]
Wait until I push my latest cleanup changes for a retest

**Comment by shivenmian** [comment]
@sudheesh001 Can't emulate this, this seems to be working. Could you send me a screenshot?

Try http://localhost:9000/api/search.json?q=spacex%20since:2015-04-01%20until:2015-04-06&source=cache&fields=mentions,hashtags

**Comment by shivenmian** [comment]
@sudheesh001 This seems to be working fine I think. Can you show me a case where it isn't?

http://i.imgur.com/gBa0T0r.png

**Comment by shivenmian** [comment]
@Orbiter @sudheesh001 should we close this or is there a legit bug?

**Comment by sudheesh001** [comment]
http://loklak.org/api/search.json?timezoneOffset=-330&q=fossasia&source=cache&count=0&fields=mentions,hashtags

504 timeout error

**Comment by shivenmian** [comment]
Nope, I'm not getting 504 on this, loaded fine @sudheesh001 

<img width="1280" alt="screen shot 2016-05-25 at 11 20 07 am" src="https://cloud.githubusercontent.com/assets/14081800/15529414/be2af4e4-226a-11e6-95cd-f3d5176e2461.png">

**Comment by sudheesh001** [comment]
lets wait until a few others also test this, then it's good to close

**Comment by shivenmian** [comment]
Tested thoroughly, works for me too, closing it.
