### ISSUE TITLE
ping frequently

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_server#34]
every peer shall ping the back-end frequently (like: once every 5 minutes) to make the peer availability visible even after a restart of the peer. We need this since we don't store a peer map or list anywhere.

**Comment by mariobehling** [comment]
@treba123 Could you help with this feature? It is on the list for a super long time.

**Comment by mariobehling** [comment]
Apparently we don't have resources to work on this. Closing it therefore.
