### ISSUE TITLE
Unsave downloads

### ISSUE THREAD

**Issue by treba123** [loklak/loklak_server#340]
There are a couple of points in the code which I feel somewhat bad about and might be doors to break into loklak installations.

First of all in [ClientConnection.java](https://github.com/loklak/loklak_server/blob/master/src/org/loklak/http/ClientConnection.java#L101) it seems like bad ssl connection get accepted by default. I can understand that in special conditions this might be desireble, but maybe we can find another way for that.
For example the new way to do this seems to be to use system defaults, so if the system is configured to allow a certain self signed certificate, loklak would do so, too.

Secondly, in the  [DAO.java](https://github.com/loklak/loklak_server/blob/master/src/org/loklak/data/DAO.java#L261) init function (which gets called on every loklak starts), if a certain file is not available it gets downloaded over a insecure connection. This is actually also a problem from the other side, geonames.org has no working https right at the moment.

I'll try to fix these issues, but I'd like to ask @all to have an eye on issues like this

**Comment by treba123** [comment]
@Orbiter I contacted geonames.org about a save download option but they say that's for premium accouts only. As all their work seems to be under [CC-license](http://creativecommons.org/licenses/by/3.0/), do you think we could host the file [cities1000.zip](http://download.geonames.org/export/dump/cities1000.zip) at loklak.org and have a ssl certificate installed? We would have to add a section somewhere were we give credit and a link to them though

**Comment by Orbiter** [comment]
It is intended to accept such kind of unsave connections. They are everywhere. To accept only save connection would restrict us from many sources.
