### ISSUE TITLE
Wikipedia: Add location data privided by GeoData API

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_server#342]
This was previously discussed here: https://github.com/loklak/loklak_webclient/issues/221

The API provided by wikipedia allows the user to see articles near an area https://www.mediawiki.org/wiki/Extension:GeoData#API

We can have something like this,you click at a location and you see a pop up of famous people who lived or died nearby. People will want to click at random points on the world map to see which famous personality is related to that.

**Comment by jig08** [comment]
@mariobehling Sounds like a cool idea.

I'd like to start with integrating this [Wiki GeoData API](https://www.mediawiki.org/wiki/Extension:GeoData#API ) first.

**Comment by mariobehling** [comment]
@jig08 Ok, please start and assign the milestone. Break down issues into several issues if they take longer than a day.

**Comment by jig08** [comment]
Sure @mariobehling :+1:

**Comment by jig08** [comment]
@mariobehling @Orbiter I have made a JS controller for Wiki GeoData API here https://github.com/jig08/loklak_webclient/commit/b3ae522ffb4ae135595fd67ef7a58fe8c9564d84 for [loklak.net](http://loklak.net/)
This returns a JSON object of a list of articles around the given point (determined by coordinates and radius) whose one of the parameters `pageid` can be used to access the Wiki Article via `https://en.wikipedia.org/?curid=<pageid>`

**Comment by jig08** [comment]
@mariobehling @Orbiter I am planning to work on making a console service utility for SUSI using this API. Should I go ahead ?

**Comment by mariobehling** [comment]
@jig08 I am not clear, what it would entail. At the moment, we have a lot of ways to define rules and we only have a few questions that can get answers. Could you help first and make the rules for the upcoming days a priority, please? We need some outcome in the short-term before going to next steps.

**Comment by Orbiter** [comment]
Geo data is already in Susi. Ask where is. It also gives you a link to a map

**Comment by jig08** [comment]
@mariobehling Yes, Adding rules in SUSI , almost daily :grinning: .

@Orbiter The plan was to include a list of Wiki Articles tagged with that location using this API.

For Instance: When asked `Where is Berlin ?` along-with the response `Berlin is a place with a population of 3426354. Here is a map: https://www.openstreetmap.org/#map=13/52.52436820069531/13.41053001275776` it also gives a list of articles on wikipedia having the location of Berlin.

**Comment by jig08** [comment]
@Orbiter Hey, any update on this issue ?

**Comment by Orbiter** [comment]
+1 yes implement the Wiki GeoData API

**Comment by jig08** [comment]
@Orbiter Implemented.

**Comment by jig08** [comment]
@Orbiter Implemented :)
