### ISSUE TITLE
Add crawler for Instagram messages with a photo

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_server#343]
Please develop a crawler that collects data from Instagram and adds the info into loklak where we define the photo title as a a tweet and the photo itself as an attachment. Also add other data into the loklak data structure, e.g. user.

**Comment by jig08** [comment]
@DengYiping In this case too, majority of the information is inside the `<script>...</script>` tags. 
On exploring. `JSoup`+ manual Parsing of the javascript seems to be a feasible option. 
Any pointers on this one ?

**Comment by DengYiping** [comment]
@jig08 Take a look at helper function for Weibo. Maybe it will help you.

**Comment by jig08** [comment]
@DengYiping [loklak_server/src/org/loklak/api/search/WeiboUserInfo.java](https://github.com/loklak/loklak_server/blob/development/src/org/loklak/api/search/WeiboUserInfo.java) here , this one ?
