### ISSUE TITLE
IoT: Add support for postages tweeting location data

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_server#344]
Implement support for postal services. I think we can get single tracking items out of DBs, but how about showing a map with lots of points where postages are? How much info can we get from providers like UPS for example? Would not it be awesome if postages could tweet?
https://www.usps.com/business/web-tools-apis/technical-documentation.htm

This issue was first mentioned here: https://github.com/loklak/loklak_webclient/issues/222

**Comment by sudheesh001** [comment]
I think this should be possible and also possible from susi. Taking this and starting with FedEx

**Comment by jig08** [comment]
> I think this should be possible and also possible from susi. Taking this and starting with FedEx

@sudheesh001  Kindly elucidate ?

**Comment by jig08** [comment]
@sudheesh001 Cool.

>URL Query samples: https://www.fedex.com/apps/fedextrack/?action=track&tracknumbers=920241085725456

Exactly. Are you working on this ? If not, I could contribute

**Comment by jig08** [comment]
@mariobehling @sudheesh001 
Here I am adding the sample URLs for tracking:

- [ ] FedEx: [ https://www.fedex.com/apps/fedextrack/?action=track&tracknumbers=<-tracking-id->]( https://www.fedex.com/apps/fedextrack/?action=track&tracknumbers=920241085725456)
- [ ] DHL: [http://www.dhl.com/en/express/tracking.html?AWB=<-tracking-id->&brand=DHL](http://www.dhl.com/en/express/tracking.html?AWB=10007d1213241&brand=DHL)

**Comment by mariobehling** [comment]
What about the samples? How should I test them?

**Comment by jig08** [comment]
@mariobehling Sample tracking numbers for FedEx.

![screenshot from 2016-07-23 10 53 59](https://cloud.githubusercontent.com/assets/9291400/17075992/0145ff94-50c4-11e6-926d-2af4d353ab72.png)

**Comment by mariobehling** [comment]
What do do with this information? Is it available in loklak/Susi now? Where do you store the info in the index? Usually there is also geolocation info available for each stop. Please add this as well.

**Comment by jig08** [comment]
@sudheesh001 Have you started with FedEx tracking , now that we a pool of test data ?

**Comment by jig08** [comment]
@mariobehling This was a set of sample data I found online. I will explore for more test datasets with geo-location info as well.

**Comment by sudheesh001** [comment]
@jig08 Yes i've started with it

**Comment by jig08** [comment]
Sample tracking numbers for UPS.
![screenshot from 2016-07-27 06 30 15](https://cloud.githubusercontent.com/assets/9291400/17160611/cc9b6ea2-53c3-11e6-91c6-a5cb28bd4222.png)

**Comment by jig08** [comment]
@sudheesh001 updates on this ?

**Comment by sudheesh001** [comment]
This is pretty vague, i've been facing failures on the searches continuously and have been hitting blank endpoints.
<img width="1440" alt="screen shot 2016-08-14 at 4 48 13 pm" src="https://cloud.githubusercontent.com/assets/4545925/17648765/ef173144-623e-11e6-888f-cce820d01404.png">

Can you give this a shot @jig08

**Comment by mariobehling** [comment]
As apps are now hosted elsewhere and this could be classified as IoT, we can follow up on this idea elsewhere, if it becomes relevant again.
