### ISSUE TITLE
Add IoT Services to Loklak

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_server#345]
Add support for
* [x]  Weather information from US National Weather Service Reference: http://graphical.weather.gov/xml/
* [x] Thingsinspace, website data and info on https://github.com/jeyoder/ThingsInSpace
* [x] Public Transport Data An example of an interesting service is here: http://tracker.geops.ch, Technologies: http://geops.de/blog/technologien?language=en, Github is here: https://github.com/geops
* [ ] Airplane/Flight data, Websites like Flightradar (http://www.flightradar24.com) show plane data. There are resources that offer these data (apart from flightradars private/commercial data collection). The How to page (http://www.flightradar24.com/how-it-works) mentions the Federal Aviation Authority of the US for example (https://www.faa.gov/data_research/aviation_data_statistics/).
* [ ] Marine Traffic like http://www.marinetraffic.com/en/ais-api-services
* [ ] Data from EU Environmental Agency http://discomap.eea.europa.eu/home.html
* [x] Yet Another Haze Index (Yahi) http://rolandturner.com/yahi/ | http://rolandturner.com/yahi/developers | https://github.com/rolandturner/yahi
* [ ] Japan Radioactivity Map: http://japan.failedrobot.com/ | http://blog.safecast.org/data/
* [x] Freifunk-Karte http://www.freifunk-karte.de/ | https://github.com/ffansbach/nodelist
* [ ] Sahana Eden Disaster Management: E.g. http://nepal.sahana.io/eden/req/req
* [ ] Ebola Data Availability: http://eden.sahanafoundation.org/wiki/Deployments/Ebola#Data
* [ ] Data.org http://www.data.gov/developers/ | https://github.com/GSA/data.gov | http://ckan.org/features/
* [ ] German Open Data https://www.govdata.de
* [ ] Open Data Berlin: http://daten.berlin.de
* [x] Earthquake Data : http://earthquake.usgs.gov/earthquakes/feed/v1.0/geojson.php
* [ ] Safecast Data: https://api.safecast.org/en-US/home
* [x] NMEA / GPS Devices Tracking Data: http://www.brickhousesecurity.com/category/gps+tracking/best+selling+tracking+devices.do

**Comment by mariobehling** [comment]
@sudheesh001 Any progress on any of these? Would be great to get an update.

**Comment by sudheesh001** [comment]
@mariobehling This is in progress, the json data that's available here is present at the following link and an API endpoint can be created for the same. http://stuffin.space/TLE.json

Most data sets here deal with GPS or geolocation specific data, the support for which has been added with NMEA

**Comment by sudheesh001** [comment]
Also directly related to #504 since these options will be the tiles over there.
