### ISSUE TITLE
Add crawler for meetup.com

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_server#347]
Reference http://meetup.com

**Comment by jig08** [comment]
Begun work here https://github.com/jig08/loklak_server/pull/2/commits/044f4949f7bf955d677910080cfbd8eb2f762003

**Comment by jig08** [comment]
@mariobehling @orbiter

Information viz Group Name, Group Description, Group Topics & Recent Meetups (Date, Time, Reviews, Introductory Lines etc.) from [Meetups.com](http://www.meetup.com/) has been parsed using `JSoup`

Refer https://github.com/jig08/loklak_server/commit/e5272a4406292b38e7ca16bf5f7d74ef0f086242

**Comment by mariobehling** [comment]
@jig08 How does this information fit our data model? How to integrate it?

**Comment by jig08** [comment]
@mariobehling
As @Orbiter mentioned, he is working on a framework to integrate external non-twitter-like data into the loklak message structure. It shall then work for us as a template to add the `meetup` and other `wordpress` or `instagram` parsers as well.

Till then, we can collect information from these sources using HTML parsing. 

I hope that answers your query :)
