### ISSUE TITLE
Data not collected - @user disappears

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_server#348]
![screenshot from 2016-05-14 08 13 29](https://cloud.githubusercontent.com/assets/1583873/15266620/f9223d68-19ab-11e6-9116-b9cce1193977.png)

![screenshot from 2016-05-14 08 14 16](https://cloud.githubusercontent.com/assets/1583873/15266622/fbad0b44-19ab-11e6-99a2-2237dafd8d16.png)

**Comment by smokingwheels** [comment]
Not sure if it related but when you run your own server you get more results for the same quire and frequency as compared to loklak.org. The loss is about 75% when using loklak.org from the semiprivate test I have run.
Does Loklak.org have any forward peers?
Some TCP packets splatted somewhere by someone using there mobile phone??

**Comment by leonmak** [comment]
I think it is because of the uploaded picture, seems to change the text and links

**Comment by leonmak** [comment]
This seems to happen only when there are uploaded pictures
