### ISSUE TITLE
make screenshots of all loklak apps

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_server#355]
- open each app in http://loklak.org/apps/applist/index.html and make a not-too-large screenshot of each app, showing a nice result of the app
- crop the screenshot to a 640x640 pixel image, name it 'screenshot.png' and add it to each of the app to the apps in https://github.com/loklak/loklak_server/tree/master/html/apps

**Comment by Orbiter** [comment]
this is a requirement for https://github.com/loklak/loklak_server/issues/356

**Comment by daminisatya** [comment]
Sure! Will do it

**Comment by daminisatya** [comment]
#381

**Comment by Orbiter** [comment]
thank you!
