### ISSUE TITLE
extend the applist app to show screenshots

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_server#356]
extend the app in https://github.com/loklak/loklak_server/tree/master/html/apps/applist to show screenshots made with https://github.com/loklak/loklak_server/issues/355

If you want to, re-design the applist design in such a way that it shows the screenshot as 160x160 tile (or 80x80, depending on size, or make it re-sizable) in a tile-matrix -- as you expect how it should look like in an app store.

**Comment by Orbiter** [comment]
this is a follow-up for https://github.com/loklak/loklak_server/issues/355

**Comment by daminisatya** [comment]
@Orbiter I need to add another key called "Image" to every app.json. For rendering the image i need to convert it into Byte arrays and vice versa. This is my approach. Is there any other possible way for it?

**Comment by daminisatya** [comment]
@Orbiter ok i found an easy way (Y) to just render them by forming their path from app's name !

**Comment by sudheesh001** [comment]
Looks like this is complete @daminisatya But the small issue being that there's no link to move to the app. I think i'lll open that as a new issue. Closing this as merged in adf265761866b17a80218a64a8b8d8c49c939ffd
