### ISSUE TITLE
make an 'My Account' app stub

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_server#357]
using the framework of https://github.com/loklak/loklak_server/blob/master/html/apps/apps.md, make an app which shows an 'Sign up' message. People should be able to sign up using an email address and a password.

- make to input fields "Email Address" and "Password".
- add a 'Sign up' button.
- when the Sign up button is pushed, the app calls just '#' at this time - because this is a stub implementation.
We will add a registration API with another feature issue.

**Comment by Orbiter** [comment]
The credentials submitted with this feature will be used with https://github.com/loklak/loklak_server/issues/358
We need further discussion to define how data is stored in a secure way. It will probably require a server-side process to store the passoword in a hased form in such a way that it can be used with https://github.com/loklak/loklak_server/issues/358
Please discuss.

**Comment by treba123** [comment]
hej @shivenmian, if i get it right Michael wants us to decide how to save the passwords. 
Afaik, in such situations we need to 
- create a random salt for each user
- create a hash (sha3?) of password+salt (concatenated)
- store email, hash and salt in a database

That's basicly it, or did i miss something?

**Comment by shivenmian** [comment]
I think so @treba123. We need to use the accounts servlet in loklak.org for the database or what?

**Comment by shivenmian** [comment]
Also @Orbiter, even though this task can be done, I want to ask you, just to be clear.

Isn't it mentioned in the architecture that loklak doesn't have user accounts? And besides, loklak.net uses twitter login. What's the requirement of this application then?

**Comment by treba123** [comment]
Maybe for cases where we need some kind of restriction, like dump downloads

**Comment by Orbiter** [comment]
Yes, it is mentioned right now that loklak does not have user accounts. We will change that a bit. Look at http://loklak.org/api.html - there you see three access classes: green=no limitation, red=for localhost only, yellow=for everyone, but limited. We will distinguish the yellow case in the future, granting rights on accounts will enable such users to expand the yellow case to green.

I prepared a service level environment for this, have a look at https://github.com/loklak/loklak_server/blob/master/src/org/loklak/server/APIServiceLevel.java
There you will see four access classes; 'product' will be the class which is a 'granted limited'. I will work on the servlets to assign them the access class.

This issue is just about the Sign-In stub. Just implement this first we will discuss authentication details in https://github.com/loklak/loklak_server/issues/358

**Comment by treba123** [comment]
@shivenmian yes, POST or GET should be it. I think GET is also fine as it's localhost only anyways. I'll just write how I understand it right now, please correct me

On sign-up, you do a

`http://localhost:9000/api/account.json?action=update&data={"screen_name":"user@domain.org","source_type":"LOCALACCOUNT","apps"                  :{"credentials":{"hased_pw" : "asoteuhsaoetihoaeuthaoeusnth","salt":"pyfgctmaboeuhd"}}}`

to create an object:
`{
  "screen_name"           : "user@domain.org",        // emailaddress
  "source_type"           : "LOCALACCOUNT",     // don't now if this is nessecary
  "oauth_token"           : "",         // is that optional?
  "oauth_token_secret"    : "",         // ------ " --------------
  "authentication_first"  : "2015-06-07T09:39:22.341Z",        // optional
  "authentication_latest" : "2015-06-07T09:39:22.341Z",        // optional
  "apps"                  : {"credentials" : {
                                               "hased_pw" : "asoteuhsaoetihoaeuthaoeusnth",
                                               "salt" : "pyfgctmaboeuhd"
                                    }
     }
}`

For login we would then do a
`http://localhost:9000/api/account.json?screen_name=user@domain.org`
although I have to do this via DAO.searchLocalAccount()

**Comment by Orbiter** [comment]
Thats good, but I believe "apps" should be a list of objects, not a single object -- as far as I remember.

**Comment by shivenmian** [comment]
@Orbiter @treba123 Check #364

**Comment by shivenmian** [comment]
Closing this issue, Step 2 is in #358.

**Comment by Orbiter** [comment]
see https://github.com/loklak/loklak_server/pull/364#issuecomment-220018546

**Comment by shivenmian** [comment]
Sure. I'll submit another PR shortly.

**Comment by shivenmian** [comment]
Also @Orbiter I checked the other apps. All of them had removed the sections (i.e the menu on top) like I did, so that only their app is on the screen.

I should keep it though, right? And do I make the background black etc as well?

**Comment by Orbiter** [comment]
https://github.com/loklak/loklak_server/blob/master/html/apps/apps.md recommends to use the boilerplate
I recommend that too :)

**Comment by shivenmian** [comment]
@Orbiter There is a problem with the boilerplate. The themes don't work, nor do the links in the html. I'm sending a PR to rectify this, please see to it ASAP.

**Comment by Orbiter** [comment]
Oh I thought the boilerplate is ok. Thank you for fixing!

**Comment by shivenmian** [comment]
@Orbiter Fixed the SignUp app according to boilerplate, please check #368

**Comment by shivenmian** [comment]
@Orbiter, this part is done, so should we close this?

**Comment by Orbiter** [comment]
good work!
