### ISSUE TITLE
add basic http authentication to the loklak server

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_server#358]
We should have a basic http authentication in loklak. Add such a method in the http server. To verify an authentication, the information (email address as log-in and a hashed authentication credential) must be taken from the accounts index.

The account data will be written with the account app in https://github.com/loklak/loklak_server/blob/master/src/org/loklak/api/server/AccountServlet.java
Please read http://loklak.org/api.html#account to learn how user-related data is stored in loklak. Every account will have an objects in "apps". This will contain also authentication credentials. We should discuss details here.

The server must read the user account credentials using DAO.searchLocalAccount() and take out the user login credentials.

**Comment by Orbiter** [comment]
This will use passwords stored with https://github.com/loklak/loklak_server/issues/357
Please discuss how this should be stored in a secure way

**Comment by Orbiter** [comment]
The Basic Authentication Scheme requires a ```base64-user-pass``` which is encoded as
```base64(userid + ":" + password)```, see https://tools.ietf.org/html/rfc2617#page-5
However, this is not secure as it exposes all user credentials. That should mean that we only accept basic authentication requests using ssl connection.

See http://www.eclipse.org/jetty/documentation/current/embedded-examples.html#embedded-secured-hello-handler for an example of an embedded secure handler.

What we need to store a ```base64-user-pass``` is a hash of such a string. That hash should be stored in the account index. I will provide further information about how to do this.

**Comment by treba123** [comment]
Do you want the basic auth for the whole server or do we need specific subfolders/files do be protected by it?
About the hash, shouldn't we store something like
- userid
- hash(password + salt) (for the hash: bcrypt? sha3?)
- salt

**Comment by Orbiter** [comment]
we want that for the whole server. The target is to implement a user authorization based on an provisioning process as documented in https://github.com/loklak/loklak_server/issues/363

**Comment by Orbiter** [comment]
However, that does not mean that api servlets which are accessible right now are not accessible any more. This issue should not implement a 403 response for unauthorized clients.

It should work like this: if the user goes to the log-in app, a 401 is issued to tell the user to log-in. If the log-in is successfull, the browser will continue to send the basic authentication credentials, even if the server does not send a 401 (as far as I know). Then we can pass that information to each servlet and provide extended access grant rights.

**Comment by shivenmian** [comment]
Okay so the stub is added. What do we do next? I think I'll set a milestone on this because we already did one part, what say?

**Comment by treba123** [comment]
@Orbiter ah alright, that's were we're heading. Is there a special reason why you need basic_auth then? Because these things could probably much better handled with cookies...
Or do you need it to allow tools like curl to get access?

**Comment by Orbiter** [comment]
cookies are good as well, but not a good solution for scripts. To make the API accessible for scripts we would need much more complex mechanisms like OAuth. I know that this is not really a good solution but we get somewhere soon.

Btw, good job!

What I need as well: authentication should be required only of the servlet demands. Is that possible?

**Comment by Orbiter** [comment]
I also like ```https.mode=redirect```! Very good!

**Comment by treba123** [comment]
@Orbiter thank you :)
What do you think about the following:
- login in is usually done via cookie
- for scripts, we provide an option to send login credetials as POST/GET payload
I think this is how most modern apis work

**Comment by Orbiter** [comment]
Cookies are in the EU a bit tricky since the EU Law considers them as personal data and requires the publisher of a web site with cookies to declare a data privacy statement and furthermore notice the user that cookies are used and that the user has the right to opt-out of cookies completely.
See http://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32016R0679 section (30) and (32). There are lawyers who try to automatically find web pages which do not follow this requirement.
Therefore I would like to do not use cookies at all.

The http_auth as it is is fine. I will add a commit soon which makes clear where and how log-in restrictions can be applied.

**Comment by treba123** [comment]
Hm sorry, I don't really get that point. 
Under german law, you would also have to have an "impressum", other countries have other cracy laws. So right now, plain loklak installations are "illegal" in many countries.
Personally I'd say this is out of scope of loklak and something the administrators have to deal with.
Also, I's really not hard to make an optional little notice about the cookie (compared to what's nessecary to make http_auth work the way you want it to)

Also, if i get the law right, even the data sent with the http_auth would probably fall under the it. It's not only about cookies but about any kind of information like this (also flash cookies, html5 storage)

**Comment by Orbiter** [comment]
ok I did not know that session cookies are excluded from the rule.
So how would you implement the cookie-based authentication? How would you setthe cookie? If this is a session key: we would need to maintain a list of sessions and decide how to store that in a persisten way. Maybe we can use **https://github.com/loklak/loklak_server/issues/373** to store sessions.

The next question would be: how do we implement a session-handover for load-balanced peers?

**Comment by treba123** [comment]
Hm yes I will think about it. Jetty has session management build in, so we can use that for a single instance. Loadbalancing is indeed a bit more tricky.

**Comment by treba123** [comment]
For the first part of the question:
- We have a sign-in servlet which get the login data
- it queries the local api as discussed in #357 and checks if they're valid
- it then sets a cookie which contains a hash of certain things only we and a valid user can know (like userid, hashed password as stored in our database, random salt) and the salt
- depending on whether the user checked a "stay loged in" checkbox, set expire time to not more than a few hours or forever
- write this expire time to user account data
- on each request to the website, check for the cookie. If set, check the hash and expire time for validity, reset expire time in cookie and database

I think this is how most php projects do it, if i didn't forget something

**Comment by treba123** [comment]
Alright, I was busy to make #384 ready, so now I'll come back to this again.
I'd suggest we have a little class that handles authentication checks, which can be used by all servlets that need restrictions. I'll post more on this tomorrow.

**Comment by treba123** [comment]
We changed the concept for the login, so close this
