### ISSUE TITLE
Double gz archive in dumps

### ISSUE THREAD

**Issue by smokingwheels** [loklak/loklak_server#359]
Had Server off for a day then started it again.
Its no big deal but to extract the messages you unzip once then rename the messagesXX.txt to a .gz and unzip again.
Im using windows winrar to unzip it.

**Comment by Orbiter** [comment]
please check that the renamed txt file has actually gz content, don't trust winrar on "not complaining"

**Comment by smokingwheels** [comment]
When you extract on the first go the size and packed are the similar number of bytes.
Do you have the message dumps from the start of this project I think they have had the problem in windows. Not sure about linux though.
If you open the file on first go it contains lots of funny char.

**Comment by mariobehling** [comment]
Thank you!
