### ISSUE TITLE
Provisioning Process

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_server#363]
Having accounts in loklak will enable us to assign special rights to each user which is logged in.
The publication of such special rights is called 'provisioning' - read about it in https://en.wikipedia.org/wiki/Provisioning

This means in our environment: the 'apps' array of objects in our account store should host one special object which is called 'authorization'. That object should contain again objects for each service that the user is allowed to do. At this point we don't know what it would be, but it could i.e. be the permission to query a specific number of search results in the search api, i.e. 10000 instead of 100).

This issue should be used to discuss and to do a documentation of the provisioning objects that we want to implement.

Parent issue to 
#362 #386 #426 #439 #449 #467 #547

**Comment by Orbiter** [comment]
The provisioning process is part of the AAA concept:
AAA - Authentication, Authorization, Accounting
- Authentication asks the question, "Who or what are you?"
- Authorization asks, "What are you allowed to do?"
- Accounting wants to know, "What did you do?"
In this context, provisioning carries the rights for authorization and the model for accounting.

Accounting is very special: it can have many uses, i.e. it could be used to collect or spend 'points', i.e. increase trust level if a user does something trustworthy or it can be used to decrease account deposits, like service tokens ("a user may do something 10 times, not more").

**Comment by treba123** [comment]
This is pretty cool and we should probably bring this togother with #/353
In the end, users and other loklak peers are kinda similar, both are authenticated (or not) and both can get previleges.

For the login functionality, that would mean that there're three ways to authenticate yourself:
- via website cookie (set by login formula)
- via username and password in request (for scripts)
- via public key (challage response like ssh) for loklak peers

**Comment by Orbiter** [comment]
Related issues: https://github.com/loklak/loklak_server/issues/362 https://github.com/loklak/loklak_server/issues/386 https://github.com/loklak/loklak_server/issues/426 https://github.com/loklak/loklak_server/issues/439 https://github.com/loklak/loklak_server/issues/449 https://github.com/loklak/loklak_server/issues/467

**Comment by Orbiter** [comment]
As part of the provisioning process we already discussed user roles in https://github.com/loklak/loklak_server/issues/547#issuecomment-224622063
To perform the activities according to the user roles, we must implement user stories.

As a user for one of the following roles
- Administrator: is allowed to do everything (currently: localhost access), including assignment of rights
- Moderator: has rights to use all services and to assign user rights, up to moderation rights
- Service Manager: has right to use all services and change service level settings, also for specific users
- User with Identity: has rights as assigned
- Anonymous user: has lowest rights as everybody has. This can be managed like a special user with ‘anonymous’ identity.

.. I can:

1. subscribe to get an account
2. Assign every user any user right, if the user has administration rights
3. Assign every user any user right except administration if the user has moderation rights
4. Change the rights assigned to services that are required to acces specific services if the user is either an administrator moderator or service manager
5. As an administrator, moderator or service manager I can view AAA Lists of subscribed users. That includes all non-administrator users, i.e. such which have subscribed using auto-subscribe from the shop.
6. As an administrator, moderator or service manager I can change and/or modify and/or delete the authentication and authorization lists lists. 

Lets make single Apps for each of these points. We already have implemented (1). We need administration apps for the remaining activities.

**Comment by mariobehling** [comment]
Basic accounting is implemented, but the plan is to separate the accounting system. So, I am closing this issue.
