### ISSUE TITLE
store public and private settings

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_server#374]
add two JSONFile objects in DAO to store a dynamic setting in the file ```data/settings/public_settings.json``` and ```data/settings/private_settings.json```.
Name these objects public_settings and private_settings.

We will need this for secure peer hashes.

**Comment by Orbiter** [comment]
this requires https://github.com/loklak/loklak_server/issues/373 first

**Comment by Orbiter** [comment]
@shivenmian please join in

**Comment by treba123** [comment]
TODO: set private file private on filesystem level

**Comment by Orbiter** [comment]
we have a method for that already, I just can't find it now...

**Comment by Orbiter** [comment]
found it: ```OS.protectPath(path);```

**Comment by treba123** [comment]
https://github.com/loklak/loklak_server/pull/416
