### ISSUE TITLE
create a secure peer key and a peer hash

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_server#375]
We need to ability to publish a public key and encrypt data from other peers with their public key.

Therefore each peer must create - if not already done - a public/private key pair.

To do:

- this uses the private and public settings from https://github.com/loklak/loklak_server/issues/374 do that first
- when the DAO class is initialized, look if a public key with name 'public_key' is stored in the public_settings. If not, create the key pair
- if you create the key pair, write the public key to public_settings.public_key, the encryption method as string into public_settings.public_key_method and the private key into private_settings.private_key

**Comment by treba123** [comment]
As public_settings and private_settings are actually json-objects, shouldn't this be public_settings.get("public_key") instead of public_settings.public_key? Otherwise we duplicate data.

**Comment by treba123** [comment]
Ok bullshit. We want to get key objects.

**Comment by treba123** [comment]
Ok, to make the workflow more clear I added the function getPublicKey(), getPrivateKey() getKeyMethod() and getPeerHash() instead of direct acces of the variables.
Together with the corresponding set-functions

**Comment by treba123** [comment]
see above
