### ISSUE TITLE
extend the '/api/hello.json' servlet - return the public settings

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_server#376]
change the return value of the 'hello' servlet:
- instead of returning the static 'ok' property, return the content of the DAO.public_settings JSON

**Comment by Orbiter** [comment]
this requires https://github.com/loklak/loklak_server/issues/374 first

**Comment by Orbiter** [comment]
@shivenmian please join in

**Comment by treba123** [comment]
see above
