### ISSUE TITLE
every Timeline must contain the creators peer hash and public key

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_server#378]
extend the class https://github.com/loklak/loklak_server/blob/master/src/org/loklak/objects/Timeline.java 
and add two more metadata lines in Timeline.toJSON
- set peer_hash to DAO.public_settings.peer_hash
- set peer_public_key to DAO.public_settings.public_key

**Comment by Orbiter** [comment]
do https://github.com/loklak/loklak_server/issues/377 first

**Comment by treba123** [comment]
I'll also put key_method, as it is needed to use the key

**Comment by treba123** [comment]
see above

**Comment by treba123** [comment]
@Orbiter i don't exactly get why we should put the public key and the hash in the timeline. The hash can be easily calculated from the key, so it's just more to bits to carry. 
Wouldn't it make more sense to actually attach a signature for the content of the timeline and the hash? 
With the hash we can find the peer and ask him for his public key (which is pretty big) and the signature would make sure the content wasn't altered by third parties.
That would actually be like a email with signature

**Comment by Orbiter** [comment]
Yes thats right, OK!

**Comment by treba123** [comment]
Ok, i'll only write the hash for now and later do the signature
