### ISSUE TITLE
auto-subscribe an user account when verified by download order

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_server#386]
This is just an idea how we could handle a woocommerce downlad link.
Background: it's possible to sell digital goods in woocommerce; upon order of a digital good the user gets a download link. That download link gets automatically attached some query attributes, which are:
- 'download_file': the product_id
- 'order': the order_key,
- 'email':  the user_email
- 'key': a verification key

To see how these attributes are composed, see https://github.com/woothemes/woocommerce/blob/master/includes/admin/meta-boxes/views/html-order-download-permission.php

A servlet could be able to verify a valid download link by using this data to read the order from the wordpress database. An example can be seen here: https://github.com/angelleye/hightail-for-woocommerce/blob/master/download_file.php

This requires a mysql data connection to the wordpress database, which means that loklak_depot (or a separate component) runs on the same server.

To communicate with the customer, it is required that the download link goes to a html page which explains to the person that an subscription to loklak_depot has been done and how to proceed.

**Comment by treba123** [comment]
The mysql-server doesn't need to be on the same server, the connection always goes over the network (in many cases localhost of course)

Anyway, cool idea!

**Comment by mariobehling** [comment]
Woocommerce was a nice idea, but it actually adds too much complexity and we basically need a more simple approach for now. Also, Stripe for example has a good documentation and we can use this service pretty quickly to add payment capabilities. Closing this issue therefore.
