### ISSUE TITLE
Create an openstreetmap tile-pattern with location tag painted in the center

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_server#39]
A new API path 'vis' shall be created to host visualization servlets. One of these servlets shall provide OSM maps with information painted on it. Information shall be:

- marker in the center
- OSM license at the bottom
- optional: date and headline at the top

The libraries added with https://github.com/loklak/loklak_server/commit/875b68388cb922b2fe643b3de367e68097cbc237 https://github.com/loklak/loklak_server/commit/448d34e23c89db73835f6403ea29be180752a971 and https://github.com/loklak/loklak_server/commit/40a7bc8d1e6fe2bde2fb84fd14617e47fc509ee5 shall be used. The servlets shall take the following attributes:

- left, top, right bottom coordinates
- text which will be added as message
- flag which allows to print date of the message as well

**Comment by Orbiter** [comment]
added a stub implementation with https://github.com/loklak/loklak_server/commit/af0b7ac648e06fb7edbb73d1a31ecf4f4b299a40
This allows the creation of a tile map image with text on it to be used as image for cross-posting.
Example:
http://localhost:9100/vis/map.png?text=Test&mlat=1.28373&mlon=103.84379&zoom=18&width=512&height=256

The attributes are:
text: an optional text on the map which is shown in the top-left corner as headline
mlat: latitude of point on the map, to be used for a marker
mlon: longitude of point on the map, to be used for a marker
zoom: a zoom factor; maximum is 19
width: a width of the image, optimum is 512 for the smallest map
height: a height of the image, optimum is 256 to the smallest map.

Because the size of OSM tiles is 256x256 pixel, the optimum minimum size of a map image is 256 width or height. The best image size is where width = 2 * height, therefore the optimum setting for width and height is: width=512, height=256.

**Comment by sudheesh001** [comment]
@Orbiter Does the application have to send markers for converting them to an image to post to Twitter or should we use the twitter API to send the geo coordinates directly to twitter ? They have a {lat:"", long:""} option

**Comment by Orbiter** [comment]
When sending the tweet to twitter, please attach the lat/long values as the Twitter api provides them. Also, attach the image from the /vis/map.png API. Then, post the tweet to loklak again and set the following values:

place_name:leave this empty
place_id:leave this empty
place_context:either "ABOUT" or "FROM" according to the action of the user. If the user is using the currently location (i.e. taken from the browser), then set this to "FROM". If the user selected a position on the map, use "ABOUT"
location_point: the geolocation as array of double values, [longitude, latitude]
location_radius: 0 (as type: integer)
location_mark: same as location_point
location_source: "USER"

**Comment by Orbiter** [comment]
with https://github.com/loklak/loklak_server/commit/2bc440bedd5ed52cd5a364ed2adafd134f41675d:
locations with special source can be selected using the `/location`constraint in the following way:
The option can be attached to /location as single value, i.e.:

`q=biergarten /location=USER`

would select all beer gardens where a user annotated the location with a rich-tweet. Compare with:

`q=biergarten /location=REPORT`
(i.e. for IoT locations) and
`q=biergarten /location=ANNOTATION`
for auto-discovered coordinates when a location mame is given in the message text.

The source attribute can also be given as fifth parameter if four bbox values are given as option to `/location`, i.e.:
`/location=1.2,3.4,5.6,7.8,USER`

**Comment by Orbiter** [comment]
The remaining functionality of this feature which was implemented as stub will be handled in https://github.com/loklak/loklak_server/issues/87 - paint the marker.
