### ISSUE TITLE
Advanced query generator integration into loklak server

### ISSUE THREAD

**Issue by sudheesh001** [loklak/loklak_server#391]
This is an enhancement. There are a lot of features that are present in the search, We have a basic tweet query search in the homepage itself but there are a lot of features that we have for the features like `from`, `until`,`since`, `count` etc.., Added to these we also have aggregations possible for hashtags etc.., Having these as checkboxes and the `since`, `until` as datepicker's we can have an advanced search page where the queries could be made as the user wants.

**Comment by daminisatya** [comment]
@sudheesh001 This can be done as a loklak app.

**Comment by leonmak** [comment]
I accidentally clicked, wanted to say that I was planning to do this for the visualisations apps also

**Comment by Orbiter** [comment]
make this as an app please

**Comment by sudheesh001** [comment]
Yes @Orbiter This will be made into an app, as mentioned in the scrum today, it'll be renamed LQL for (Loklak Query Language) 😄
