### ISSUE TITLE
Suggest loklak plugins for popular CMS and shortmessage clients and list existing plugins suitable for adopting for loklak

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_server#392]
The goal of the project is to offer loklak services to users of popular CMS and clients (e.g. twitter clients). Please suggest loklak plugins for popular CMS and shortmessage clients and list existing plugins suitable for adopting for loklak. Provide links and describe features to be implemented through loklak. It is perfectly fine to start with e.g. existing Wordpress plugins and adopt them to use loklak (instead of twitter or additionally as an alternative option).

**Comment by sopu** [comment]
1. https://wordpress.org/plugins/rotatingtweets/ 
2. https://wordpress.org/plugins/twitter-stream/  
3. https://wordpress.org/plugins/recent-tweets-widget/ 
4. https://wordpress.org/plugins/twitter-tweets/ 
Above are some plugins which are mostly like different takes on a "tweet wall" + "user timeline" + "tweet-stream".
Looking for other tags!

**Comment by sopu** [comment]
We can somewhat imitate the https://www.drupal.org/project/twitter for `drupal`.

**Comment by sopu** [comment]
I have started work on a search_plugin for Wordpress. 
Closing this for now.
