### ISSUE TITLE
generic topmenu

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_server#394]
all the html files in loklak have a top-menu navigation with looks like (here: architecture.html):
```
<div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="index.html">Home</a></li>
            <li><a href="about.html">About</a></li>
            <li><a href="showcase.html">Showcase</a></li>
            <li class="active"><a href="architecture.html">Architecture</a></li>
            <li><a href="download.html">Download</a></li>
            <li><a href="tutorials.html">Tutorials</a></li>
            <li><a href="api.html">API</a></li>
            <li><a href="dump.html">Dumps</a></li>
            <li><a href="apps/">Apps</a></li>
          </ul>
```
If a new menu item is created or deleted, all menu entries in all html files must be changed. This shall be changed using angular and the new topmenu servlet introduced in https://github.com/loklak/loklak_server/commit/5177b4df4b42dfdc7e545afbed853decc7b9365b

currently /cms/topmenu.json creates:
```
{"items": [
  {"Home": "index.html"},
  {"About": "about.html"},
  {"Showcase": "showcase.html"},
  {"Architecture": "architecture.html"},
  {"Download": "download.html"},
  {"Tutorials": "tutorials.html"},
  {"API": "api.html"},
  {"Dumps": "dump.html"},
  {"Apps": "apps/"}
]}
```

- change all html files with top-menue (including all apps!)
- read /cms/topmenu.json
- all html files must identify the own html pages name and write an ```class="active"```into the ```li``` options
- if this requires additional js code, write it into https://github.com/loklak/loklak_server/blob/master/html/js/loklak.js

**Comment by daminisatya** [comment]
@Orbiter For identifying the active tab we can set routes for each tab. I guess we need to include a separate routes.js file, IMO.

**Comment by Orbiter** [comment]
What should routes.js contain? I wanted to make this as simple as possible. I believe each html for each web page can call the code for the angular process using the name of the own servlet. That would not need any other setup code.

**Comment by daminisatya** [comment]
@Orbiter it's difficult to change for all the apps. since they have their own JS files with ```ng-app```

**Comment by sudheesh001** [comment]
Reopening this, in case further changes to apps must be discussed, the requirement then would be a directive.
