### ISSUE TITLE
Create a front-end app which consumes the Peers API 

### ISSUE THREAD

**Issue by daminisatya** [loklak/loklak_server#398]
- [x] Add all the buttons, with proper UI

- [ ] Add a force directed graph

- [ ] Implement a simple leaderboard triggering every submission of the deployment link.

**Comment by Orbiter** [comment]
What do you mean with "Add all the Buttons"? I would consider this as a list-view.

**Comment by daminisatya** [comment]
@Orbiter Yes it is a list view!

**Comment by daminisatya** [comment]
Divided this issue into chunks, seems to be a bigger application #451

**Comment by daminisatya** [comment]
#452
