### ISSUE TITLE
Test the updated buildpack URLs. 

### ISSUE THREAD

**Issue by daminisatya** [loklak/loklak_server#399]
Please test for the following deploys

- [x] Heroku

- [x] Bluemix

- [x] Scalingo

**Comment by daminisatya** [comment]
#396

**Comment by shivenmian** [comment]
Yes, doing it @daminisatya @sudheesh001

**Comment by shivenmian** [comment]
@daminisatya @sudheesh001 Heroku works, http://loklaktest.herokuapp.com. Testing the others.

**Comment by daminisatya** [comment]
@shivenmian What about the Bluemix deployment?

**Comment by sudheesh001** [comment]
Bluemix works, just deployed http://loklak-server-dispensary-1049.mybluemix.net/
