### ISSUE TITLE
RSS Feed Generator Returns zero bytes

### ISSUE THREAD

**Issue by smokingwheels** [loklak/loklak_server#4]
About 5.5 hours ago the error occurred on loklak.org
Was working for at least 1 day before with the loads I was giving it.
150 searches every 10 min various yacy VM's.
24 searches every 5 min from feeddemon .
![rss feed error](https://cloud.githubusercontent.com/assets/11748913/6999011/f60cc1a0-dc28-11e4-9378-fc05826b6cd5.JPG)

**Comment by Orbiter** [comment]
I don't know how to reproduce this. I believe you that you see a problem but bug reports must describe situations which must be reproducible.
