### ISSUE TITLE
create images with text on it using markdown syntax in input texts

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_server#40]
the markdown rendering library added in https://github.com/loklak/loklak_server/commit/afda741a4f6402930c54f73373a8c54006a3b872 shall be used to print texts not into html but on images using the library added in https://github.com/loklak/loklak_server/commit/40a7bc8d1e6fe2bde2fb84fd14617e47fc509ee5
the purpose of such images is to create preview images for enriched text messages

**Comment by Orbiter** [comment]
a stub for this feature is commited with https://github.com/loklak/loklak_server/commit/daf3f7b599f6de7e6617781c179d05bb356f6121
It is now possible to render texts as images. Example:
http://loklak.org/vis/markdown.png?text=hello%20world%0Dhello%20universe&color_text=000000&color_background=ffffff&padding=3

The GET/POST (preferred: POST) parameters are:
text:the markdown text; must include line breaks for line breaks in the resulting image
color_text: RGB color of the text
color_background: RGB color of the text background
padding: number of pixels around the text (leave empty for default number 3)
uppercase:boolean (default true) - the 5-pixel font includes lowercase chars but they don't look good.

this implementation is incomplete at this point because markdown is not yet supported. Only the rendering of the text in clear text is supported. A markdown interpretation will be added later.

**Comment by sudheesh001** [comment]
@Orbiter Can you add this to the documentation of the server too ?

**Comment by Orbiter** [comment]
yes, done with https://github.com/loklak/loklak_server/commit/8fe4ddec40944ee08f19f3c14c6fb753cdcd4727

**Comment by Orbiter** [comment]
Here is the process on how to show rich-text tweets, which is regulated with the message form convention for rich-text tweets in https://github.com/loklak/loklak_server/issues/66:
- for each message: check if the string `\n***\n` appears. If it appears, the message is a rich text tweet.
- separate the text into two parts: the text in front of `\n***\n` is the normal tweet message which shall be displayed as such. The text behind `\n***\n` is the rich text.
- the rich text must be displayed with a rich-text-to-html library below the message, not with the markdown servlet! We want to show this in a nice format in our own interface. The usage of the markdown servlet is only for cross-posting to twitter!

**Comment by Orbiter** [comment]
the stub has been completed
