### ISSUE TITLE
Enhance the Leaderboard application using search aggregations. 

### ISSUE THREAD

**Issue by daminisatya** [loklak/loklak_server#410]
This can be done for a better count result, eventually transform the difference into a tutorial app for understanding the functionality better.

**Comment by Orbiter** [comment]
+1

**Comment by daminisatya** [comment]
Closing this in favor of #523 and [f852d5f ](https://github.com/loklak/loklak_server/commit/f852d5fbfcc5938f697181bbd92b2e46479a637e)
