### ISSUE TITLE
IP Blacklist fails to deny access to the IP addresses listed

### ISSUE THREAD

**Issue by sudheesh001** [loklak/loklak_server#413]

**Comment by treba123** [comment]
Ah alright, I already anticipated this.
Will have a look into it

**Comment by treba123** [comment]
@sudheesh001 I think it works now, could you do a test from this branch: https://github.com/loklak/loklak_server/tree/fixIpBlacklisting ?

**Comment by treba123** [comment]
Fix works for me, please report again if it doesn't
