### ISSUE TITLE
Create Joomla component boilerplate for adding Loklak plugins. 

### ISSUE THREAD

**Issue by daminisatya** [loklak/loklak_server#414]

**Comment by mariobehling** [comment]
We can create boilerplates for different systems, but could you state first, please what you want to develop? 

What plugin will you develop for Joomla? 

Could you also find existing plugins? We could simply change existing plugins instead of starting a new plugin that we might not be able to maintain.

**Comment by daminisatya** [comment]
- http://extensions.joomla.org/extensions/extension/social-web/social-display/custom-twitter-display-widget

- http://extensions.joomla.org/extensions/extension/social-web/social-display/twitter-timeline-genius

- http://extensions.joomla.org/extensions/extension/social-web/social-display/advanced-twitter-display

- http://extensions.joomla.org/extensions/extension/social-web/social-display/simple-twitter-embed

- http://extensions.joomla.org/extensions/extension/social-web/social-display/twitter-search-widget

- http://extensions.joomla.org/extension/bizkniz-twitter-feed-display

**Comment by daminisatya** [comment]
@mariobehling Sounds great! Will startoff with Twitter timeline!

**Comment by mariobehling** [comment]
@daminisatya Ok, sounds ok, though our focus is Wordpress and Drupal as they have a much larger user base. Let's also follow up on your project definition by email.

**Comment by mariobehling** [comment]
This topic needs to be followed up outside of this repository at a later time.
