### ISSUE TITLE
stop.sh doesn't work after two starts

### ISSUE THREAD

**Issue by treba123** [loklak/loklak_server#417]
When running start.sh two times in a row, the second start righly aborts (although not stated in output)
But when I then run stop.sh, I can't stop the running instance anymore and have to kill it via taskmanager.

Steps to reproduce:
- run start.sh two times
- run stop.sh two times
- check if there's still a runnig loklak instance in taskmanager

This lack of output and checking is sometimes really confusing and I think it happens many of us from time to time.

See #337

**Comment by shivenmian** [comment]
Ah, I've experienced this too. Will try to fix it.

**Comment by treba123** [comment]
see above
