### ISSUE TITLE
Implement CAPTCHA in Sign Up page

### ISSUE THREAD

**Issue by shivenmian** [loklak/loklak_server#426]
In the Sign Up page in #357, the form just has three fields viz. Email, Password and Confirm Password. Such a simple form can be easily spammed with random entries by bots, and will flood the database. To prevent this, we need CAPTCHA support. @Orbiter @treba123 views?

**Comment by sudheesh001** [comment]
Sounds good

**Comment by Orbiter** [comment]
Thats a good idea, however my experience with captchas for my YaCy forum (forum.yacy.de) is very bad. There are human captcha-solving 'bots' which spammers rent to get access. I have very good results with a challenge-response mechanism which uses a 'cultural gap' to prevent solving the challenge. Like: if you want to log-in into a german forum, ask "who was german chancelor in the year 2000". Everyone knows that.
However, that technique may not be applicable. Using a remote captcha service is not something I like to have. We can also use our markdown servlet as poor mans captcha
http://loklak.org/vis/markdown.png?text=poor%20mans%20captcha&color_text=00ff00&color_background=fff0000
maybe with some changes

**Comment by shivenmian** [comment]
@Orbiter I came across [this](https://www.funcaptcha.com/security/). Looks pretty secure to me. Should I use their API for the captcha? Or should we use our own?

**Comment by treba123** [comment]
The problem is, for many of this api based capchas you'd need an api key that we can't share across loklak installations.
That's fine as sign up should probably be deactivated by default anyways and only be activated if some admin chooses to. But just to have that in mind.

**Comment by Orbiter** [comment]
I would like to postpone this. It's more important to get things working first, we should have this, but not now. Meanwhile we can collect ideas.

**Comment by shivenmian** [comment]
@mariobehling the Sign Up system is already secure and working, I think enhancing security using CAPTCHA can come later
