### ISSUE TITLE
Server account says submitted data is not well formed for perfectly well formed JSON

### ISSUE THREAD

**Issue by sudheesh001** [loklak/loklak_server#43]
```
HTTP ERROR: 400

Problem accessing /api/account.json. Reason:
submitted data is not well-formed: account data must either contain authentication details or an apps setting
```

![screen shot 2015-06-06 at 6 57 09 pm](https://cloud.githubusercontent.com/assets/4545925/8019788/fa63a112-0c7d-11e5-8ab0-34bf6e398c85.png)

I have the latest build at af0b7ac648e06fb7edbb73d1a31ecf4f4b299a40
ran `ant` and then `bin/start.sh`

Temporarily there's an error handler here but the session is maintained.
https://github.com/loklak/loklak_webclient/blob/0678b3f5196470f9b366c14141cf909bf6850bca/server/index.js#L67

**Comment by Orbiter** [comment]
I tested the account servlet and wrote a documentation in https://github.com/loklak/loklak_server/commit/817eb7d335fc1356f040a2f5514608429c1d9d1d
Please test with the urls given in the documentation

**Comment by sudheesh001** [comment]
```
java.lang.IllegalStateException: No ObjectCodec defined for the generator, can only serialize simple wrapper types (type passed java.util.HashMap)
```
and sometimes
```
java.lang.NullPointerException
```

**Comment by Orbiter** [comment]
what did you submit to the server?

**Comment by sudheesh001** [comment]
```
http://localhost:9000/api/account.json?action=update&data={%22screen_name%22:%22test%22,%22apps%22:{%22wall%22:{%22type%22:%22horizontal%22}}}
```

Surprisingly the services are running on 9100 and 9000 even after stopping all the processes, restarting the system and trying again.

the basic query `?q=` for tweets works on 9100 and the updation of accounts works on 9000 but the query of the account info back works from 9100. Query of account info from 9000 fails and updation from 9100 fails. This is strange.

**Comment by sudheesh001** [comment]
Also @Orbiter The loklak server is still serving after stopping the services ....
```sh
[16:45:29] sudheeshsinganamalla:loklak git:(master) $ bin/stop.sh
[16:59:18] sudheeshsinganamalla:loklak git:(master) $ bin/stop.sh
cat: loklak.pid: No such file or directory
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
rm: loklak.pid: No such file or directory
```
See the time difference, the servers are still running on 9100 and 9000

**Comment by Orbiter** [comment]
I believe with all the strange does-not-work things and services running on a port that is not bound that something very strange is going on on your server. Please have a look at Class LoklakServer line 103 and decide yourself if it is actually possible that still a service is now running on port 9100. In other words: there is no way that I can fix a phantom on your server. Please pull the power plug of your machine, delete the loklak_server repository and start over again.
