### ISSUE TITLE
Make signatures on JSONObjects

### ISSUE THREAD

**Issue by treba123** [loklak/loklak_server#448]
For #378 it would be nice to have signatures on the every timeline as also on every other json object if needed

**Comment by Orbiter** [comment]
Please implement this.

**Comment by treba123** [comment]
Alright, will work on it tomorrow

**Comment by treba123** [comment]
Alright, so from what I understand, there is a standard for signing json objects called [jose](http://jose.readthedocs.io/en/latest/), but it is much much bigger than what we actually need.

So for now I will implement a much simpler method which can directly used without interfering with any other loklak component.
It will as simple as adding a `signature` field to the object, which contains a signature of the sha256 hash of the object (without the signature itself of course).

The main issue will probably be to make sure the hash is deterministic (that is, as json objects are not necessarily ordered, the hash must always be the same as long as the content is the same)

**Comment by treba123** [comment]
Implementation here: https://github.com/treba123/loklak_server/commits/signatures
Needs some more testing if the signature stays valid under various circumstances.

@Orbiter should I add this to the timelines? The creation of signatures and the verification?

**Comment by Orbiter** [comment]
Is there a lot of computation required, or space? If not, give it a try.

**Comment by Orbiter** [comment]
Is there a lot of computation required, or space? If not, give it a try.

**Comment by treba123** [comment]
https://github.com/loklak/loklak_server/pull/837
