### ISSUE TITLE
Login authentication in AbstractAPIHandler

### ISSUE THREAD

**Issue by treba123** [loklak/loklak_server#449]
The authentication of a user should be checked in AbstractAPIHandler
see https://github.com/loklak/loklak_server/issues/439

We probably should consider the inbuild security features of HTTPServlets and use the login() method

**Comment by Orbiter** [comment]
if it's possible to move that to AbstractAPIHandler: +1

**Comment by Orbiter** [comment]
for details see https://github.com/loklak/loklak_server/issues/439

**Comment by treba123** [comment]
Done, see #439
