### ISSUE TITLE
enrich tweet with geolocation

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_server#45]
geolocation coordinates shall be attached to tweets. The source of these coordinates can be:
- import from geoJson or similar resources
- auto-detection from tweet locations using a location dictionary
- auto-detection from tweet text using a location dictionary

The source of the locations will be set in the tweet json to make it possible to distiguish exact locations from imports or self-assigned coordinates from dictionary lookups.

**Comment by Orbiter** [comment]
first implementation done with https://github.com/loklak/loklak_server/commit/af965f4ac54c83361abfc8590740e593237e56ce

To test this, load the file from
http://www.paris-streetart.com/test/map.geojson
re-name it to map.json and copy it to data/external/geojson/import

Then start loklak_server, wait until the file is imported (watch the log) and then do a search for '/location'. There had been also a new search constraint implemented which selects only records with locations.

**Comment by prasht63** [comment]
I am getting a 404 on /location
I did 
git pull origin master
ant
bin/start.sh
The server is running but I dont see /location

**Comment by Orbiter** [comment]
/location is not a path, its a search modifier! It restricts search results to only those, which have locations attached. Just *search* for /location

**Comment by Orbiter** [comment]
Thats the complete test URL:
```
http://localhost:9000/api/search.json?timezoneOffset=-120&q=/location&source=cache
```

**Comment by prasht63** [comment]
Got it! Thanks

**Comment by Orbiter** [comment]
the automatic enrichment with geolocation is now implemented.
