### ISSUE TITLE
Introduce leaderboard to the peers app based on the number of deployments

### ISSUE THREAD

**Issue by daminisatya** [loklak/loklak_server#452]

**Comment by Orbiter** [comment]
interesting idea. How would you measure the number of deployments of a single user. Which identity would the leaderboard name?

**Comment by daminisatya** [comment]
@Orbiter Once the userlogin functionality and sessions are implemented, every time the user clicks on the button and deploys, he should deploy and come back to that page, then enter the URL of the server that he deployed. Then the count is incremented by one in the database. the database will store a new record of the deployment for every deployment that the user runs

**Comment by Orbiter** [comment]
you may probably store the number of deployments in settings/peers.json, see https://github.com/loklak/loklak_server/issues/470

**Comment by sudheesh001** [comment]
Closely related to https://github.com/loklak/loklak_server/issues/458 Should be blocked

**Comment by daminisatya** [comment]
This issue is a follow up for #458 Where in we an have two different ways to implement it .
* By making use of the accounts_depot for getting the username into the leaderboard. 
* By making a separate service to take the username from user whenever there is a deployment.

**Comment by mariobehling** [comment]
Apps will be part of the loklak_search client and not in the server anymore.
