### ISSUE TITLE
Check peer hashes for validity, signatures and DDOS

### ISSUE THREAD

**Issue by treba123** [loklak/loklak_server#456]
We now have peer hashes in every timeline, but we also have to check them and do something on error (like a warning or so).

Edit: Actually we don't have to do any extra checking if we have signatures on pushed data anyways. If we can verify the signature with the right public key, we can just check if the hash matches the public key. 

So we definitly should make signatures and some kind of handshake so the verifying party has the public key.
The problem here: signature checking is more work than creating random stuff. So this opens a door to ddos us more easily.

I'd suggest we create another file in data/settings, like "known_peers" where we save the hashes and corresponding public keys.
On the first connection with the backend, each peer first should call some "handshake" api, (maybe the hello.json?), where we can check that a peer really has the private key to a corresponding hash/key.

On succesful handshake, the peer recieves a token it can now include into queries.
Queries that don't have a valid token can just be thrown away without further checking, saving us lot's of cpu time.

A ddos attacker can therefor only attack the handshake api, which in turn can be secured by a further proof-of-work by the client.
I have to think about how to make this efficient enough to make sure the work on the server side is small enough. 
For example we could only allow only a very limited amout of handshake requests by one ip, automatically banning them afterwards.

Furher notes:
- a token should be valid only for one source ip. On ip change, a new handshake has to be done. If we get alot of requests from a wrong ip or invalid tokens, we can ban the source ip
- Tokens become invalid if not used for some time, a new handshake has to be done then.
  We can reply with a corresponding error code so a good client nows it has to do another handshake and doesn't get banned by accident
- Long running peer have almost no overhead as they can use their token as long as they run. They just have to include the token in each query

This is one further idea in the context of #353

**Comment by Orbiter** [comment]
Is it true that we consider a handshake as valid as long as the IP address of the peer where we made the handshake with did not change?

I would consider a file 'peers.json' in settings, maintained by a JsonFile class, which stores known peers and their verification state. The primary key should be the peer hash.

**Comment by treba123** [comment]
Yep, that should do. Then we have to save the public key, the token, the ip and some timestamp when it was last used or when it becomes invalid.
That should do. The token can be verified in AbstractAPIHandler.

For the role out of this we maybe need a config switch for this, disableing the check for some time until all peers are upgraded.

**Comment by Orbiter** [comment]
with https://github.com/loklak/loklak_server/issues/470 the information about public keys is stored persistent in settings.json
That data shall be used in favor of a retrieval of the public key to prevent too many calls to api/hello.json

**Comment by mariobehling** [comment]
Some progress had been made on this, but as loklak is not used in a productive company environment currently I am classifying this as "wontfix". This is a rather commercial feature to ensure a service runs continuously. It is important, but we don't have the resources to solve it currently. Anyone re-opening this topic should be willing to work on it.
