### ISSUE TITLE
Check for the validity of the deployment for peers app.

### ISSUE THREAD

**Issue by daminisatya** [loklak/loklak_server#458]

**Comment by Orbiter** [comment]
Please describe this with a small process abstract

**Comment by daminisatya** [comment]
@Orbiter I will use the hello.json to test whether the deployment is working or not!

**Comment by sudheesh001** [comment]
I don't think the validity of checking and leaderboard could be done until the login / some form of session and account tokens is present in the server. I am hereby marking this as blocked for the meanwhile until the server can support this implementation
