### ISSUE TITLE
sort tweet search results on fields retweet_count and favorite_count

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_server#46]
To get a 'top tweet' functionality we need tweet lists in differnt order than by time. See https://github.com/loklak/loklak_webclient/issues/125

**Comment by smokingwheels** [comment]
Just an idea for top tweets.
1. Create a small stack for the messages content of the searched subject on the server.
Look at the frequency of each user posts to the wall, I suggest 60 seconds or greater between tweets to be hidden from top tweets. The time frame would have to vary depending on how quickly the tweets are flowing. 

2. Compare content of tweets in the stack and only use ones with a higher character/word difference.
Spammers usually change the @username but have the same text tweets like this should not be in top tweets.

**Comment by Orbiter** [comment]
implemented with https://github.com/loklak/loklak_server/commit/d6cbac30a2a77b8446784f6889a9c704e79070e9

For each search, an optional attribute "order" can now be given.
Three values are possible: crated_at (default), retweet_count,
favourites_count. The sort direction is always descending.

Example:
http://localhost:9000/api/search.json?timezoneOffset=-120&q=fossasia&sort=favourites_count&source=cache
