### ISSUE TITLE
Make JsonFile syncronized and the IO asyncronous

### ISSUE THREAD

**Issue by treba123** [loklak/loklak_server#466]
As we're using JsonFiles in DAO and in the AbstractAPIHandler, they will potentionally get used by many different threads. To avoid that we better make it syncronized and think about potentional problems on this side.

On the other hand, to avoid bad performance if many servlets make changes and therefor trigger IO options, we should try to make the commit() asyncronous, being done by a different thread, as IO operations can be encredible slow

**Comment by treba123** [comment]
Ok I made the Class syncronized to avoid the ugliest bugs. Performance enhancements (or a move to a real database) can be made later

**Comment by Orbiter** [comment]
implemented with https://github.com/loklak/loklak_server/commit/515e013b7af83b79555394d896beb3a05d03d8cf and https://github.com/loklak/loklak_server/commit/a3bdb990d2ef7b161036b8df486e016c28eaaa7c
