### ISSUE TITLE
Add Email Server for Password Recovery

### ISSUE THREAD

**Issue by shivenmian** [loklak/loklak_server#467]
We need three things:

- [x] On clicking of "Forgot password", lead user to a page where he enters his email ID for password recovery in the Login page (see #443). Create this page.

- [x] A server which sends an email to that email ID with a recovery link (autogenerated). The link has to have a hash, url will be something like ```/passwordreset/<hash>```.

- [x] That link leads to a "Set new password" page. Create this page and the aforementioned server.

I will use the class made in #424 for the server and create the relevant webpages as well.

**Comment by shivenmian** [comment]
Anything more you'd want me to add @Orbiter?

**Comment by shivenmian** [comment]
For the email server, I came across two options as of now:

* [Spring](http://docs.spring.io/spring-integration/reference/html/mail.html)
* [JavaMail](http://www.oracle.com/technetwork/java/javamail/index.html)

Both have clear docs and seem to be secure, and can be implemented into the Java code well.

For password recovery, what I think should be done is this:

1. In the "Forgot Password" page, user enters his email ID (which we will check from database if it exists). 

2. If it exists, we will create an autogenerated recovery link (something like ```/passwordreset/<hash>``` and mail it to the user on that ID. The recovery link leads to a reset password page (which I will create), wherein user chooses the new password and it is written onto the database.

@Orbiter What email server do you prefer? Is the idea fine? And should I get started on this?

**Comment by Orbiter** [comment]
JavaMail would also be my choice!
The process you describe is also what I would believe could be the correct way.

**Comment by shivenmian** [comment]
@Orbiter nice. So should I start on this?

**Comment by Orbiter** [comment]
yes!

**Comment by smokingwheels** [comment]
For what its worth my Provider Blocks Port 25 so would it be possible to use Yahoo, Gmail or other as the SMTP Server you need to put a custom port in and user name as Email address and matching password.

**Comment by shivenmian** [comment]
This could take me a day or two.

**Comment by mariobehling** [comment]
Ok, we should not take care of this. Please check how to make use of phplist.com. The CEO is a friend of mine and they will offer a large free plan for loklak.

**Comment by mariobehling** [comment]
@shivenmian Did you have a chance to check phplist out? How much does it help us achieving this goal? What is your opinion? Should we head this way and integrate?

**Comment by shivenmian** [comment]
@mariobehling I'll let you know in a bit, probably by this evening.

**Comment by shivenmian** [comment]
@Orbiter @mariobehling I think we do need a server for this. As I figured out, non-server emails can't really be sent by JavaMail. For that to happen you'd have to hardcode your password in the code.

For now, I'll give the user the option to select his server. I'm going to add the SMTP settings (host, port etc) as fields in the config file. Also, the user will have to add his username and password in the file.

**Comment by shivenmian** [comment]
Ok, I have found a temporary customisable solution wherein I have used the config file and it caters for all types of server authentications. I will submit PR tomorrow @mariobehling.

**Comment by shivenmian** [comment]
@mariobehling @Orbiter The accounts system has been done now.
