### ISSUE TITLE
Fix Spaces and Gaps on Apps Page

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_server#468]
The Apps page has a tile layout, with:
- gaps between the columns (thats good!)
- no gaps between the rows (they should be there and as wide as the gaps between colums)
- too much space on the left side and the right side:

<img width="1531" alt="apps" src="https://cloud.githubusercontent.com/assets/238730/15606881/31520fca-240f-11e6-827f-50906d1ea97f.png">

To fix this, do:
- add space between the rows
- show *four* columns instead of *three*
- make the gap on the left and right side of the tile matrix as big as the gap bewteen the columns
- keep the ability to re-size the tiles as the window width is changed.

**Comment by daminisatya** [comment]
![image](https://cloud.githubusercontent.com/assets/6227784/15607171/8b361fda-242e-11e6-830f-1fddc0f964e3.PNG)

**Comment by daminisatya** [comment]
@Orbiter The tiles are responsive to any size.

**Comment by Orbiter** [comment]
yes I know. I just wrote that down to make sure that feature does not disappear when doing the other things.

**Comment by daminisatya** [comment]
@Orbiter Noted!
