### ISSUE TITLE
create a peers.json in data/settings and a Peer class to maintain peer informations

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_server#470]
This is related to many other issues here:
https://github.com/loklak/loklak_server/issues/462 Read the peers.json and convert it into a CSV file as required for forming FDG
https://github.com/loklak/loklak_server/issues/456 Check peer hashes for validity, signatures and DDOS
https://github.com/loklak/loklak_server/issues/452 Introduce leaderboard to the peers app based on the number of deployments
https://github.com/loklak/loklak_server/issues/458 Check for the validity of the deployment for peers app
https://github.com/loklak/loklak_server/issues/353 Trust system and automatic defense
which all require a database of peers. There is already a stub for this: There is a static DAO.peers object which contains Peer objects. That must be extended:
- Turn the org.loklak.objects.Peers object into an etension of JsonFile. Store the file in data/settings/peers.json
- extend the org.loklak.objects.Peer object, make it similar to the Authorization object, it should hold a JSONObject for payload.
- Peer objects in Peers shall be retrieved by their peer hashes. Peer hashes are the key Strings in org.loklak.objects.Peers
- in org.loklak.objects.Peer make setter and getter for:
  - public keys
  - latest known IP and port number
  - latest contact time
  - everything which hello.json returns

**Comment by shivenmian** [comment]
Would like to contribute to this @Orbiter

**Comment by shivenmian** [comment]
@Orbiter I shall definitely come back to this and the robots.txt issue once the accounts system has been made (which should hopefully be by this week), so I have postponed it to the next milestone.

**Comment by shivenmian** [comment]
@treba123 @Orbiter I'll probably come to this issue now that the accounts system is more or less done. What all is needed in this right now? I see one of the issues you mentioned has been closed.

**Comment by treba123** [comment]
I think there's still alot to do for the AAA system, see for example https://github.com/loklak/loklak_server/issues/547
But if you feel like it, go for it.

**Comment by shivenmian** [comment]
Had a chat with Robert, he said some stuff is left for the AAA and it's a bit more complex than we assumed it is, so we decided this issue can wait. Have postponed it to a later milestone.
