### ISSUE TITLE
Add a category navigation to the applist app

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_server#472]
Currently all apps are listed in one big list. We want to separate the list into categories. Each app has an category assignment. With https://github.com/loklak/loklak_server/commit/661e71253041ab4d9b1aec0d41d7860982e1c3f3 this assignment is used to add two more json objects to http://localhost:9000/api/apps.json:
```
  "categories": [
    "About project",
    "Demo",
    "Message Search",
    "Tweets analytics",
    "Message Visualizer",
    "Accounts API",
    "Peers API",
    "Suggestion Search",
    "Tweet search",
    "Users API"
  ],
  "category": {
    "About project": ["applist"],
    "Demo": [
      "barchart",
      "boilerplate",
      "bubblecharts",
      "tweetfeed"
    ],
    "Message Search": [
      "ducphanduy",
      "yasoob",
      "yathannsh",
      "zhidkovseva"
    ],
    "Tweets analytics": ["fossasia-histogram"],
    "Message Visualizer": ["histogram"],
    "Accounts API": [
      "loginpage",
      "signup"
    ],
    "Peers API": ["oneClickDeploy"],
    "Suggestion Search": ["querybrowser"],
    "Tweet search": ["social-wall"],
    "Users API": [
      "tweetsleaderboard",
      "userprofile"
    ]
  }
```
This shall be used to add a category navigation to the left column:
- remove the "Front-End contributions." hint on the left side
- list the 'categories' names in the left column as links. These links shall go to  ```/apps/applist/index.html?category=*category-name*```, i.e.  ```/apps/applist/index.html?category=Demo```
- if a link like ```/apps/applist/index.html?category=Demo``` is clicked, the app shall list only the app tiles from the requested category
- the "Read the loklak app primer to learn how you can contribute a loklak app!" hint shall be noted below the category list
- the category list shall be overwritten with the headline "Categories"
- make it beautiful!

**Comment by daminisatya** [comment]
#506
