### ISSUE TITLE
Provide a settings servlet for loklak_webclient

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_server#48]
Main purpose for such a servlet is, that application keys must be shared. We want to host such key in loklak_server and loklak_webclient can use the same keys too.

It shall work like this:
- the loklak_webclient reads settings from their custom_configFile.json
- it then reads a json from /api/settings.json. The json contains properties in the same format as custom_configFile.json. Every entity thats inside those properties from the server overwrites the settings as read from custom_configFile.json

**Comment by aneeshd16** [comment]
Currently, `js/constants.js` reads constants from the custom_configFile.json. It needs to be modified to read the json from /api/settings.json. Properties will be added/overwritten as appropriate.

**Comment by Orbiter** [comment]
Implemented with https://github.com/loklak/loklak_server/commit/9d12a22d6f79b1df82a6d2fb4c6b57b88d7393b8 


To propagate settings to the /api/settings.json servlet, set those
settings within the conf/config.properties file with a prefix 'client.'.
That key prefix will be truncated when settings are transmitted within
the servelet.
