### ISSUE TITLE
Dashboard for users after sign-up (or log-in)

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_server#488]
I believe "something" must happen after the signup, but I don't know what yet. However, people must see a kind of 'home' where they know that they are logged in.

Please suggest your ideas.

**Comment by daminisatya** [comment]
@Orbiter I have the following ideas. But still need suggestions. 
* We can have two tabs showing links to Loklak.org, Loklak.net and "proceed to home page"
* The right division can have two metrics. A stock chart showing the nTumber of tweets being indexed over a certain period of time. Other metric is to show the number of commits to Loklak_server and loklak_webclient. 
* The middle div can project the Loklak apis in different languages. 
Will provide the wireframe for easy visualization.

**Comment by daminisatya** [comment]
![selection_057](https://cloud.githubusercontent.com/assets/6227784/15655557/d040dea0-26bb-11e6-9956-66b94b392c4a.png)

**Comment by daminisatya** [comment]
@Orbiter We can place a button called "Go to Home page" which would redirect to the Loklak landing page.

**Comment by treba123** [comment]
- Any servlet that extends AbstractAPIHandler can now query `rights.getIdentity()` to know the own identity.
- We could have a redirect from the login to that dashboard described from @daminisatya 
- @shivenmian wants to implement the login into the topmenu (https://github.com/loklak/loklak_server/issues/498) so we can display some stuff there (like here on github)

**Comment by Orbiter** [comment]
two thoughts which may contradict a bit but maybe we get this together:
- we are not far away from the ability to do loklak-created tweets. In twitter if you are logged in, you see your timeline. We don't have a timeline yet, but lets keep that in mind
- we will hava a shop in loklak_depot and after the log-in you see the products within the shop. But the shop will be created with the app infrastructure, therefore the landing page is the applist (in the shop: the product list, which is the same as the product will be expressed with apps)

So the easiest way to make a landing page would be to just modify the applist page to show also some status information about the active user.

**Comment by sudheesh001** [comment]
<img width="1028" alt="screen shot 2016-06-02 at 4 53 21 pm" src="https://cloud.githubusercontent.com/assets/4545925/15747420/49527730-28e3-11e6-85bc-8aad8d19b621.png">

**Comment by daminisatya** [comment]
@sudheesh001 Is the left column all about the user's profile? I'm not sure about what we could display in the timeline column!

**Comment by sudheesh001** [comment]
The timeline column will have the past tweets of the user which we can retrieve by taking `search.json?q=@userprofile` and there's quite a bit of information available in the `/user.json` to fill up the user profile, added to the user profile, we can have links to different other apps over there creating an app ecosystem for loklak. 

The orange `+` button will open up a tweet modal and allow users to tweet on Loklak. As @Orbiter said, we are not far away from having people post tweets

**Comment by mariobehling** [comment]
@Orbiter @sudheesh001 Let's not re-create the loklak webclient of last year again. The shop should not be related to twitter only and I do not think people even need a twitter account for the shop. We need to define the goal of the shop first.

**Comment by Orbiter** [comment]
As a temporary solution, lets set the app list as dashboard. We can modify that later.

**Comment by shivenmian** [comment]
@Orbiter that's like a single line of code, because the apps list already is existent at ```html/apps/applist.html```.

**Comment by Orbiter** [comment]
no, don't copy, jsto forward to the applist.html

**Comment by shivenmian** [comment]
Okay sure, will do.

**Comment by shivenmian** [comment]
I think this is already in place because of Susi, we just need to add Susi to the homepage + other things probably.

**Comment by mariobehling** [comment]
This will be taken care of from the new loklak_search client.
