### ISSUE TITLE
add a YouTube parser

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_server#491]
parse youtube video pages

**Comment by Orbiter** [comment]
I already have a parser for such pages, but yet unpublished. Please @all don't do anything here, I will integrate this code.

**Comment by sudheesh001** [comment]
Blocker on Susi : https://github.com/loklak/asksusi_com/issues/8

**Comment by mariobehling** [comment]
I think the status is pretty advanced. @Orbiter Please let us know, if/when you have added it. Cheers.

**Comment by Orbiter** [comment]
The Youtube Scraper is already implemented, see https://github.com/loklak/loklak_server/blob/development/src/org/loklak/harvester/YoutubeScraper.java
To use this as a console service there is no search api service required. Should be ready to be implemented as console service. Please go ahead and implement that.
