### ISSUE TITLE
Plugin System for Additional Parser/Indexer

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_server#493]
If we consider loklak as a system for collecting data on the web from different sources, how could we simply add other sources? Would it be possible to have a simple way to plugin new parsers/indexers?

**Comment by mariobehling** [comment]
This is related to issues like this one https://github.com/loklak/loklak_server/issues/491

**Comment by Orbiter** [comment]
maybe organized like the apps?
To push generic data to the index (and the dumps!) we already have the /api/push.json api.

**Comment by Orbiter** [comment]
There comes also another question up: even if we can parse other content, how can we harvest that? Would we collect with queries, the same way we do with tweets?

**Comment by Orbiter** [comment]
I have a concept now that is almost complete, but not the time to implement. Will do until saturday.

**Comment by DengYiping** [comment]
#751 Consider close this issue due to duplication.
