### ISSUE TITLE
Add long living cookie to login

### ISSUE THREAD

**Issue by treba123** [loklak/loklak_server#497]
To enable users to stay logged in over longer periods, we need to give them a long living cookie.
That's only done if the "remember me" checkbox on the login page in selected, as said below.

Due to some regulations, we might have to add a hint to the checkbox, that the user agrees to have a cookie set and we don't use it for tracking.
@shivenmian can you have that in mind when you work on the login frontend?

**Comment by Orbiter** [comment]
please add a issue body and describe what this issue is about in a little more detail

**Comment by shivenmian** [comment]
@Orbiter I'm not sure but I think this is for "Remember me" functionality in the login.

**Comment by treba123** [comment]
done, https://github.com/loklak/loklak_server/pull/511
