### ISSUE TITLE
Rewrite SignUp and Login in angular.js

### ISSUE THREAD

**Issue by shivenmian** [loklak/loklak_server#498]
This has to be done to integrate it into the topmenu, which I believe will be necessary. Once the entire system has been made and works fine, migrating to Angular won't be a big issue then. I will take it up myself, will get to work with Angular in the process :)

**Comment by shivenmian** [comment]
@mariobehling The SignUp and login is functional on loklak.org, so this issue is not a priority right now. I'd just call this an enhancement.

**Comment by mariobehling** [comment]
Good. Closing this issue then. It this becomes necessary, the issue can be reopened.
