### ISSUE TITLE
My IP is Reported to do lots of request frequency is too high.

### ISSUE THREAD

**Issue by smokingwheels** [loklak/loklak_server#499]
Had this 503 error your IP request frequency is too high for over a week now when doing a search even though I do not have any Loklak Server running.
I have have run WireShark and confirmed no IP traffic to Loklak.org but still get the error.
I can think of a few causes will let you know if needed.

**Comment by Orbiter** [comment]
I blacklisted you because you DoSd the service beyond any responsibility. I know that you like to do performance testing, but please do that on your own peer.
