### ISSUE TITLE
Apostrophe shows up as 9 in JSON.

### ISSUE THREAD

**Issue by Low012** [loklak/loklak_server#5]
One of my tweets contains the word **it's**, but in the JSON I retrieved from loklak it shows up as **9**. See screenshots below for illustration.

 
![clipboard01](https://cloud.githubusercontent.com/assets/11596220/7019356/700378d2-dd0f-11e4-9360-ee4f0e53960c.png)

![clipboard02](https://cloud.githubusercontent.com/assets/11596220/7019359/76995658-dd0f-11e4-92f3-e44f45f29210.png)

**Comment by smokingwheels** [comment]
It's the same for RSS eg Intel9s PC

**Comment by Orbiter** [comment]
I've seen this also right from the beginning but I do actually not know where this comes from. I did not put any code inside which could cause that. I already thought that this might be a fancy new way to write things. It's really strange. Any idea where that comes from?

**Comment by smokingwheels** [comment]
Did a txt dump of my twitter page and in the msg box of what's happening I see Whatâ€™s happening? in word pad and word But normal ' show up ok once have been tweeted.

![asoperty](https://cloud.githubusercontent.com/assets/11748913/7292124/5b01de7e-e9cb-11e4-8ad3-b56dc60b45de.JPG)

**Comment by sudheesh001** [comment]
@Orbiter Can this also be fixed

**Comment by Orbiter** [comment]
that was a bad decoing of unicode-encodings. Mixed up decimal with hexadecimal...
