### ISSUE TITLE
Identify conversation details in the scraper

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_server#50]
check if the tweet representation contains such details. Then write the relation to the new field from https://github.com/loklak/loklak_server/issues/49

**Comment by Orbiter** [comment]
if there is a solution, check https://github.com/loklak/loklak_webclient/issues/122

**Comment by mariobehling** [comment]
@jig08 As your main project is data crawler and parser, could you please follow up on this issue that is open for too long already.

**Comment by jig08** [comment]
@mariobehling Okay.

@Orbiter Do we need to identify the type of tweet (or a reply ?)  in this case ? 


Reference:  
https://github.com/loklak/loklak_webclient/issues/122#issue-85734919
https://github.com/loklak/loklak_webclient/issues/122#issuecomment-111865908

**Comment by jig08** [comment]
@Orbiter I am still not clear about this issue, any updates pls.
