### ISSUE TITLE
Restrictions on signup (server side)

### ISSUE THREAD

**Issue by treba123** [loklak/loklak_server#501]
We have to include checks on the server side of the signup (email validity, password lenght) and possibly have the frontend query for it.
For example the password restrictions should be made at one point only, so if we make changes (e.g. requirering 10 instead of 6 characters) we don't have to chage the login app independently.

**Comment by shivenmian** [comment]
I have made password restrictions at client side @treba123 for the signup. Only those passwords who pass the restrictions go to the database.

**Comment by treba123** [comment]
Yes, but client side restriction is only for the client. He can easily bypass them if he wanted. It's only javascript, run by his browser. He can just send whatever request to signup.json, that's why we have to make checks there.

**Comment by shivenmian** [comment]
@treba123 Okay. You can put the following restrictions:

1. Password has to be more than 6 characters.

2. Password cannot be same as email ID / username (if username is ```x@y.z``` then password != x or ```x@y.z```)

3. Email has to satisfy the regex. You can use the following regex:

```/^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/``` (@daminisatya you can verify if this is ok)

I have implemented 1 and 3 in client side, shall implement 2 also today.

**Comment by shivenmian** [comment]
@treba123 For the email validity, I'm thinking I'll make the email validity function in LoklakEmailHandler a separate function which can be used by you in the SignUpServlet. For password, the only rule is that length should be >=6 as of now.

**Comment by treba123** [comment]
https://github.com/loklak/loklak_server/pull/563

**Comment by treba123** [comment]
see above
