### ISSUE TITLE
Dashboard for IOT Devices connected to Loklak

### ISSUE THREAD

**Issue by sudheesh001** [loklak/loklak_server#504]
Loklak will soon be getting a dashboard for the logged in users. So we can maintain the sessions for users, similarly we need a dashboard for the users to handle the devices that he's connected to loklak.

Milestone 12

**Comment by shivenmian** [comment]
@sudheesh001 Something like Facebook has right? There's an "Active Sessions" panel wherein it gives you the list of devices you're logged into, and you can log out of other active sessions from that panel.

**Comment by mariobehling** [comment]
This is a great idea, but should be implemented in an external app. Loklak server can provide the data.
