### ISSUE TITLE
Beautify the Apps Page

### ISSUE THREAD

**Issue by daminisatya** [loklak/loklak_server#507]
- [x] Add css animation to the tiles while loading

- [x] Add proper css to the side nav bar

**Comment by Orbiter** [comment]
Good idea, I just wanted to open an issue as well. Please do as well:
- [ ] Headline over apps must be like category name if category is listed. Exception is: listing of all apps.
- [ ] selected category must be marked as if selected with mouseover.  This applias also to the default-all listing.
<img width="936" alt="categoryb" src="https://cloud.githubusercontent.com/assets/238730/15734243/e9186adc-288d-11e6-8580-aac0170639be.png">

**Comment by daminisatya** [comment]
@Orbiter Will do it !

**Comment by daminisatya** [comment]
#506 , [6d945ef](https://github.com/loklak/loklak_server/commit/6d945ef29df7645637b1bab1067f4416527591c3)
