### ISSUE TITLE
session information not available after log-in

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_server#508]
every api servlet now returns the identity of the user, if the user is anonymous it looks like:
```
  "session": {"identity": {
    "anonymous": true,
    "type": "host",
    "name": "0:0:0:0:0:0:0:1"
  }}
```
So when I log in with an account I just created, I expect that I see my identity there.
That is not the case.
To test this, i.e. call:
http://localhost:9000/api/apps.json
or
http://localhost:9000/api/hello.json
where you now have the identity object

**Comment by treba123** [comment]
For me it works fine when using parameters. Did you use the login app? Because it's not yet finished/adapted to some changes we have made. But if you login via the parameters, it fine.

**Comment by treba123** [comment]
should be alright now

**Comment by Orbiter** [comment]
ok now it's working
