### ISSUE TITLE
If loading of user avatar through the proxy fails, try to identify new url through twitter

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_server#51]
This is a follow-up to https://github.com/loklak/loklak_server/issues/31 and connected to the idea in https://github.com/loklak/loklak_webclient/issues/59#issuecomment-112408650

In case that the loklak_webclient retrieves an avatar picture using the proxy api and the proxy fails to load the picture, it might be possible that the user has meanwhile changed the image and a new url is valid. In that case the server shall use the user's authentication to retrieve the latest avatar url from twitter directly, update the account information (set the new url), download the image and return it.

**Comment by mariobehling** [comment]
@Orbiter This is quite a work around for this feature. How about giving the user the possibility to upload his own photo as well? 

What priority does this feature have? In order to get loklak rolling it is maybe not the top priority for me, but if it does not take so long time to implement.

**Comment by Orbiter** [comment]
Uploading own images is more complex that retrieving the latest url from twitter. The most work is integration of a twitter api library, but that is required anyway. However, the feature has low priority compared to other API requirements at this time.

**Comment by mariobehling** [comment]
Twitter might change the structure of the photos. Personally, I would say, supporting Gravatar und uploads of profile pics has a higher priority.

**Comment by Orbiter** [comment]
but that does not solve the current problem

**Comment by Orbiter** [comment]
implemented with https://github.com/loklak/loklak_server/commit/1dab8816261cbf1c3cf824a5e293dfd40ca91754
