### ISSUE TITLE
Clean up of json files

### ISSUE THREAD

**Issue by treba123** [loklak/loklak_server#510]
The json-files we use for the AAA system currently never get cleaned up, making them grow forever and saving user data (like ips) in clear text.

As I need some kind of cleaup system for the DAO.authentication file anyways, I'd like to implement a cleanup function (has to be thread-save) that removes all entries with a `valid_until` key that holds a timestamp smaller then the current one.
It has to be triggered by a thread that wakes up maybe every ten minutes or so, triggering the cleanup for the corresponding files.

Edit: to be future save, we should use long as the timestamp format.

**Comment by Orbiter** [comment]
We should not store data in the AAA files which then have to be cleaned up. This effect is circumvented with https://github.com/loklak/loklak_server/commit/dc5712152e0fe293abc132529672c54ece6dbb0e where volatile information is never stored in the json files.
