### ISSUE TITLE
Installation page

### ISSUE THREAD

**Issue by treba123** [loklak/loklak_server#519]
We're getting more and more features that can or should be customized by the admin of a loklak installation.
Maybe we should get a simple installation page sooner or later, going through the settings on first run, like many php projects like wordpress do.
Shouldn't be to much work and can make it much easier to discover certain features

I'm thinking things like:
- send mails via smtp (email address, server, login)
- installation name
- admin name and password (as soon as we have real accounts)
- backend server
- https settings (are you behind a ssl-proxy?)
- ...

**Comment by shivenmian** [comment]
Yes.

**Comment by Orbiter** [comment]
+1
I would consider that this can be seen in the context oft personal settings for each user where the admin has more setting options, most oft them you already mentioned.

**Comment by treba123** [comment]
@shivenmian @Orbiter @mariobehling The installation page is now functional, but i've got some questions before we can merge it:

1. Should the installation page be displayed by default (on first run)? 
  - One problem with that would be the one-click deployments, as one would have to make sure to complete the installation so no stranger does it.
  - What happens with installations that just do an upgrade? Should they also be forced to make the installation? Would probably make sense.

2. Should the installation page provide a 'restart' button, that reloads the config and restarts all services? Or should the user have to do that himself? I'd say a restart button would be helpful for beginners.

3. Should the installation service be the only service being started at first run? That would make sure everything is set up before normal operation begins.

4. Would you like to have additional features?

The current features are:
- admin account creation
- a user registration setting
- general settings like host- and shortlink url, peername, backend settings
- smtp settings (with test option)
- https settings

**Comment by mariobehling** [comment]
How does the page look like? Any screenshot?

**Comment by mariobehling** [comment]
I am not clear on your idea of the implementation, but as of now the service always restarted itself after an update/upgrade. And as loklak is constantly providing updates/upgrades the goal was always to provide upgrades that work without the need of any user actions. Do I understand you correctly, that this is no longer possible in the way you propose it here?

**Comment by treba123** [comment]
It's totally possible. The question is, how do we want it. If you say installation should not happen on upgraded installations, I'll try to make it that way.

Here are some fast screenshots:

![installation0](https://cloud.githubusercontent.com/assets/6313774/17365089/75d14238-5984-11e6-9679-f498b17071f1.png)
![installation1](https://cloud.githubusercontent.com/assets/6313774/17365088/75cd2d60-5984-11e6-9282-0ae15f36d79b.png)
![installation2](https://cloud.githubusercontent.com/assets/6313774/17365090/75d41602-5984-11e6-913e-e6cd522f2d71.png)
![installation3](https://cloud.githubusercontent.com/assets/6313774/17365091/75d8cb02-5984-11e6-8f21-1d373ab27b83.png)
![installation4](https://cloud.githubusercontent.com/assets/6313774/17365092/75dbf5d4-5984-11e6-9e65-8a134af8c436.png)
![installation5](https://cloud.githubusercontent.com/assets/6313774/17365093/75dec7dc-5984-11e6-9644-4102531430d9.png)

**Comment by treba123** [comment]
Ok, I would propose the following:
- the installation is launched with an extra start script. If it's started, only the webserver will start, only with the installation
- the normal start.sh will prompt if the user wants to do the installation (if not done already). It will provide 'yes', 'no' and 'ask next time' and remind the decission in some extra file. It will time out after 10-20 seconds (defaulting to 'no')
- when the installation is finished, it will stop the webserver and, in case 'start.sh' triggered the installation, continue to start the loklak-server (with the new settings)

That means:
- the installation will not interfere with one-click installations (they will just time out  once) or upgraded systems (the user can choose to do/not do the installation or just wait for a timeout)
- it's easy for users to start the installation

**Comment by Orbiter** [comment]
implemented
