### ISSUE TITLE
Create a Twitter wall using the Loklak services

### ISSUE THREAD

**Issue by daminisatya** [loklak/loklak_server#520]

**Comment by mariobehling** [comment]
@daminisatya It looks like often there is no description in your info unfortunately. We already work on a twitter wall in the loklak web client. How does your idea here differ? What technologies you plan to use?

**Comment by daminisatya** [comment]
@mariobehling Will design the wall using AngularJS and poll the requested tweets. It's just an app, where the user can use it after login. It's no where related to the web_client's walls. But still would follow your suggestion.

**Comment by mariobehling** [comment]
@daminisatya We already have an Angular.js wall in the web client. There is also a metorjs wall. I do not understand why we duplicate work. We can move the code of the web client and add it as an app here later. No need to duplicate really.

**Comment by daminisatya** [comment]
@mariobehling Agreed! Closing it to avoid duplicate work.
