### ISSUE TITLE
The background in apps page needs to be lighter on mouse hover. 

### ISSUE THREAD

**Issue by daminisatya** [loklak/loklak_server#525]
![selection_067](https://cloud.githubusercontent.com/assets/6227784/15804758/8088ab0c-2b31-11e6-982c-3eaf3abca3e0.png)

**Comment by daminisatya** [comment]
Not able to find a way to fix it.

**Comment by sudheesh001** [comment]
<img width="1440" alt="screen shot 2016-06-07 at 7 25 33 pm" src="https://cloud.githubusercontent.com/assets/4545925/15866195/4fd56746-2ce6-11e6-8b3c-9da8d513cd9c.png">

**Comment by sudheesh001** [comment]
the highlight is now lighter on click and also works on hover.
