### ISSUE TITLE
Add crawler for Wordpress sites

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_server#527]
Wordpress sites are a major part of the web. In our data structure we could regard elements like the title similar to a tweet text and post and media in Wordpress as attachments.

Propose and implement a crawler for Wordpress sites.

**Comment by jig08** [comment]
@mariobehling Surely, we could do this.
Which all sites do we need to consider ?

- [ ] [blog.loklak.net](https://loklaknet.wordpress.com/)
- [ ] [newsroom.fb.com](http://newsroom.fb.com/) (Powered by Wordpress)

.... _more to be added soon_

**Comment by jig08** [comment]
A little exploration led to the fact that the `blog-post` information can be found in the HTML source and thus `JSoup` could be used to parse the required information in a "tweet"-like card.

![screenshot from 2016-06-06 23 33 09](https://cloud.githubusercontent.com/assets/9291400/15832304/3cc551c2-2c3f-11e6-921b-9f83d14ff653.png)
