### ISSUE TITLE
Add crawler for Hackernews

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_server#528]
Hackernews is a major resource for technologists. The format of many posts is similar to tweets. Propose and implement a crawler for the service: http://news.ycombinator.com

**Comment by jig08** [comment]
@mariobehling
Again, `JSoup` can be used to extract the news headlines on [HackerNews - news.ycombinator.com](https://news.ycombinator.com/)
I have done a bit exploration, and shall push its code soon.

![screenshot from 2016-06-09 21 23 49](https://cloud.githubusercontent.com/assets/9291400/15936397/7c18a63a-2e88-11e6-9414-23205455b8cd.png)

**Comment by Orbiter** [comment]
they have an rss stream: https://news.ycombinator.com/rss
We should not waste energy parsing special peages if we could just get the rss stream.

**Comment by jig08** [comment]
@Orbiter Yes, okay.

We could make use of [ROME, The Java Framework](https://rometools.github.io/rome/) to parse the RSS or Atom feeds of different news links like Hackernews or Open Source News (wrt https://github.com/loklak/loklak_server/issues/557 ) and others.

**Comment by Orbiter** [comment]
I don't know that framework, just use it if it's lightweight and simple.

**Comment by jig08** [comment]
Okay @Orbiter :+1:  Shall implement a RSS/Atom feed reader using `ROME` and push the code soon.

**Comment by jig08** [comment]
Closing it, PR  #624 does this task.
