### ISSUE TITLE
Create an app which is similar to Diffbot

### ISSUE THREAD

**Issue by daminisatya** [loklak/loklak_server#531]
- Input : URL to a HTML page

- Output : JSON object which primarily focuses on the following fields [icon,  title, sitename, tags, language, pageURL]

- The basic app must be able to take in the URL of the HTML page and display the JSON object containing the above mentioned fields. This is the first version of the app.

**Comment by shivenmian** [comment]
@daminisatya Since diffbot is a crawling service, would making this not actually solve issues like #217 etc?

**Comment by jig08** [comment]
@daminisatya @shivenmian @mariobehling If it helps with crawling other websites, this could be of a fantastic help !

**Comment by sudheesh001** [comment]
@daminisatya @jig08 @shivenmian I think for the initial rounds, this diffbot can implement a generic scraper.

**Comment by jig08** [comment]
@sudheesh001 Okay, Cool. We could enhance and customize then on..

**Comment by mariobehling** [comment]
As far as I understand Diffbot also uses specific parsers for specific websites. @Orbiter What is your idea?

**Comment by daminisatya** [comment]
Breaking this app into sub issues. The base scraper API is being added.

**Comment by daminisatya** [comment]
Closing this wrt #594
