### ISSUE TITLE
create a canonical_id field for cross-posting

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_server#54]
when a rich-content tweet is generated, that tweet is cross-posted to twitter as well. That means for each rich-tweet, two tweets are generated within loklak: one which we assign ourself with rich content and another which is (possibly!) retrieved from twitter. In such cases, we must identify the rich tweet and the cross-posted tweet from twitter. our own tweet will get assigned a canonical_id field, which contains the id of the cross-posted tweert from twitter. To sort out double-tweets in search results, we just must follow the canonical-id and kick out all tweets with the id from that field.

To-do: add a canonical_id field. This field must be filled with a new API which accepts rich tweets from the webclient.

**Comment by Orbiter** [comment]
the field `canonical_id` was added with https://github.com/loklak/loklak_server/commit/0c73caa76a5e8390b34a98de07882a15479c4032
still needs to be tested with the /api/push.json api to see if pushed canonical_id will reach the index

**Comment by Orbiter** [comment]
The client implementation is desribed in https://github.com/loklak/loklak_webclient/issues/437

**Comment by Orbiter** [comment]
If the loklak_webclient creates a new message and sends it to twitter, the cross-posted image within loklak does not have a id. loklak receives the canonical_id and generates a new id out of it using the `canonical_id`attached with a suffix.

**Comment by mariobehling** [comment]
As we are following a different approach, this issue should be reformulated following the latest architecture. Closing this issue therefore due to inactivity. Please open new issues, when issue becomes relevant.
