### ISSUE TITLE
Too many push's to backend returns 504

### ISSUE THREAD

**Issue by sudheesh001** [loklak/loklak_server#544]
experience on loklak_wok issue https://github.com/loklak/loklak_wok_android/issues/7#issuecomment-224386357

**Comment by mariobehling** [comment]
@sudheesh001 Could you take care of this issue or who would be best to help out here?

**Comment by sudheesh001** [comment]
I am not sure if this is still reproducing. @Low012 can you please confirm ?

**Comment by sudheesh001** [comment]
Load tested with updates in https://github.com/loklak/loklak_python_api/pull/52
1000 push objects simulated into loklak in a threaded manner. Doesn't break. Good to close
