### ISSUE TITLE
Allow explicit whitelisted users to perform action=update in account.json

### ISSUE THREAD

**Issue by sudheesh001** [loklak/loklak_server#545]
@Orbiter The account.json has access only to `localhost` clients, It'd also be great if the update actions could be performed to a set of explicitly whitelisted IP addresses. This would be useful for #280 too since `apps` already can accept dynamic JSON entries.

This will allow devices acting as users to update their information in their account as an app.

**Comment by treba123** [comment]
Maybe we can simply use the login system for that. If account.json extends AbstractAPIHandler, we can just register each device as a user.
You can use the api simply adding `signin=....` and `password=...` to the query

**Comment by sudheesh001** [comment]
Absolutely, with the authentication, this should be really amazing, what do you think about it @treba123 since we already have the signup servlets and the login servlets ready

**Comment by treba123** [comment]
We just didn't yet discuss yet how to structure the authorizations, but basicly it's all there. Will create an issue for that, shouldn't be such a big deal

**Comment by Orbiter** [comment]
instead of a whitelist we should operate with roles and as @treba123 suggests use the authentication system. Yes lets do that with https://github.com/loklak/loklak_server/issues/547
