### ISSUE TITLE
New Push API with support for other data formats

### ISSUE THREAD

**Issue by zyzo** [loklak/loklak_server#55]
This Push API is different from current [push.json](https://github.com/loklak/loklak_server/blob/master/src/org/loklak/api/server/PushServlet.java) in several points : 
* it supports others formats than search result's one (geojson, ..)
* In POST parameters, users provide a link to their data file, not the data itself
* For geojson type, a `maptype` parameter must be specified to map attributes in geojson property fields. The maptype consists of simple map rules `geojson-field:loklak-tweet-field`, separated by commas.

Related : 
https://github.com/loklak/loklak_webclient/issues/205
https://github.com/loklak/loklak_webclient/issues/206
https://github.com/fossasia/api.fossasia.net/issues/45

**Comment by Orbiter** [comment]
Please support this feature with some example input records, if available. I.e. how would a single geojson event from fossasia api look like?

**Comment by zyzo** [comment]
@Orbiter This is the public link to fossasia api geojson file http://api.fossasia.net/map/ffGeoJsonp.php

Typically, the `properties` field will contain, if available, all informations enlisted here, except for location : 
https://github.com/loklak/loklak_webclient/issues/206#issuecomment-114064797

**Comment by Orbiter** [comment]
interesting to see the `mtime` attribute there, because a reference time would be something which can be used to compose a unique ID for each message together with the location coordinates. This is needed to identify double-entries in subsequent submission of same records. We don't want to have several entries for the same event as messages, only one.

So I tend to say that giving a date in the property is obligatory, because otherwise a ID computation is not possible. Would you agree to that?

**Comment by zyzo** [comment]
Yeah it's a good idea. The `mtime` is copied from `lastchange` attribute in our original json data. Maybe @andi will have more inputs on this. 

And when the file is updated (`mtime` changes), will the old file be discarded / overridden ? I guess that isn't the case for twitter tweets.

**Comment by Orbiter** [comment]
we don't want to overwrite messages for the same location with a new date to be able to browse through time when visualizing this on a map. The idea is, that the map gets also a time-slider. Therefore the time is essential for the identification of the tweet.

On the other hand, I would like to give uploaders the opportunity to fix their mapping after an upload by just uploading again with a new mapping. In case that only the mapping has changed but not the records, they must be recorgnized with an ID which is independent from the given mapping.

**Comment by andibraeu** [comment]
```lastchange``` is an attribute a community sets to their file, when they change anything in there
```mtime``` is set by the collector when we build the aggregated file. it's the timestamp of the last access of an api file

if we can't load the file, mtime won't be refreshed

**Comment by Orbiter** [comment]
sounds like `mtime` is not a good way to distinguish that something has changed, so not good for an ID either. This brings me to the conclusion, that the tweet text itself should be used to create a hash for an ID. If the message content does not change, the message also has not changed. Would that be true?

**Comment by zyzo** [comment]
> if we can't load the file, mtime won't be refreshed

Doesn't it mean `mtime` changes only when file changes ? The problem is that with FOSSASIA API data, there is no tweet text. Everything it's just an info about the community. More generally the geojson format doesn't require a `message` property either. 

I suggested in #56 that we should make `text` property mandatory, but now that I think about it it's a lot of constraints to user who just want to dump in their geojson file, to visualize it on loklak map, or to benefit from the well-established search engine.

**Comment by Orbiter** [comment]
I have a nice idea about the possibility to append *everything* from the property field to our concept of 'rich tweets' (tweets with more content than twitter allowes, i.e. large texts):
Using the convention from https://github.com/loklak/loklak_server/issues/66 we can render the properties as rich text attachment: write it out as markdown text, attached to a headline text, separated by `\n***\n`.

Then this message not only preserves the original content, it also can be cross-posted to twitter using our markdown-to-png image attachment method.

**Comment by zyzo** [comment]
Interesting. Now what I do is appending all properties field to the root of the message, which are ignored if they are not valid tweet fields. 

Here's my question : what to append as rich-text, is case-dependent ? Importers of FOSSASIA API data will prefer other fields to be appended than importers of Wikipedia data. Therefore we should let users choose what to append, with a parameter in api request. The users should be able to modify this after from web_client UI as well.

**Comment by Orbiter** [comment]
yes thats a good idea, that will actually restrict the number of entries that are to be appended.

**Comment by mariobehling** [comment]
@zyzo Regarding "let the users choose what to append" the idea would be to handle this similar to services like mailchimp, where the user can define fields him/herself and match fields of imports him/herself (http://kb.mailchimp.com/lists/growth/import-subscribers-to-a-list#Match-Your-Fields). Does this work for you here?

**Comment by Orbiter** [comment]
@mariobehling this was implemented with @zyzo 's /api/push/geojson.json api using mapping parameters. I would like to see some examples to get a feeling how and if that works. We should define some geojson sources and @zyzo provides example mapping import calls for this.

**Comment by mariobehling** [comment]
Data to be imported:
nodes: https://ninux.nodeshot.org/api/v1/nodes.geojson?format=json
links: https://ninux.nodeshot.org/api/v1/links.geojson?format=json

https://location.services.mozilla.com/downloads

**Comment by zyzo** [comment]
Push api calls with mappings : 

Fossasia API : 

http://localhost:9000/api/push/geojson.json?url=http<span></span>://cmap-fossasia-api.herokuapp.com/ffGeoJsonp.php&source_type=FOSSASIA_API&map_type=shortname:screen_name,shortname:user.screen_name,name:user.name,name:text,url:link

Ninux nodes : 
http://localhost:9000/api/push/geojson.json?url=https<span></span>://ninux.nodeshot.org/api/v1/nodes.geojson?format=json&source_type=NINUX&map_type=name:screen_name,user:user.screen_name,user:user.name,details:link,description:text,updated:mtime

Ninux links can't be pushed (yet) since they don't have modification time (related : https://github.com/loklak/loklak_server/pull/77#issuecomment-121219647)

Mozilla location service isn't compatible either since it's not in geojson format. They seem to have json api services http://mozilla-ichnaea.readthedocs.org/en/latest/api/index.html, which can be interesting but require api key and enforce daily limits.

@Orbiter is there ways to use this map_type parameter to map fields to rich text attachment ?

**Comment by zyzo** [comment]
Implemented in #56.
