### ISSUE TITLE
Elasticsearch logging

### ISSUE THREAD

**Issue by treba123** [loklak/loklak_server#552]
Right now, we don't log the output of elasticsearch, leaving us without a clue why it sometimes breaks. The reason for that is probably, that it by default uses log4j for logging, which we don't initialize, therefor dropping all output

I'll try to make it use our general log4j2 backend

**Comment by Orbiter** [comment]
+1

**Comment by treba123** [comment]
https://github.com/loklak/loklak_server/pull/572
