### ISSUE TITLE
Add crawler for Open Source News 

### ISSUE THREAD

**Issue by jig08** [loklak/loklak_server#557]
Developing in and for an open environment, it would be great for the developers to skim through the latest news from [opensource.com/tags/open-source-news](https://opensource.com/tags/open-source-news)

We could crawl _opensource.com_ include the top ten news headlines & content snippet in a tweet-card like format in _Loklak_ .

@mariobehling @Orbiter Views pls ?

**Comment by Orbiter** [comment]
news pages should maybe not be crawled, instead we should read rss streams if they are provided. Having a rss reader would open up opportunities to all such news places

**Comment by jig08** [comment]
@Orbiter Okay, Shall implement a RSS reader for this using [ROME, The Java Framework](https://rometools.github.io/rome/) to parse, next...

**Comment by jig08** [comment]
Closing this, PR  #624 does this task.
