### ISSUE TITLE
Retain object fields while updating in accounts

### ISSUE THREAD

**Issue by sudheesh001** [loklak/loklak_server#558]
Is there a way to add multiple objects to a single key value in the apps object of account.json ?
I am testing out the IBM Home automation code where there's a simple integration of device statuses being sent to the server. So an object like

```
{"d": {"LightStatus":0, "intruder":0},"ts":"2016-06-07T22:18:12.022855+03:00"}
```

Adding to accounts.json as "Alarm" results in

```
{
  "search_metadata": {
    "count": "0",
    "client": "0:0:0:0:0:0:0:1"
  },
  "accounts": [{
    "authentication_first": "2016-06-08T19:20:10.476Z",
    "authentication_latest": "2016-06-08T19:20:10.476Z",
    "screen_name": "test",
    "source_type": "TWITTER",
    "apps": {"Alarm": {
      "d": {
        "LightStatus": 0,
        "intruder": 0
      },
      "ts": "2016-06-07T22:18:12.022855 03:00"
    }}
  }],
  "session": {"identity": {
    "type": "host",
    "name": "0:0:0:0:0:0:0:1",
    "anonymous": true
  }}
}
```

but any other changes made, removes the "Alarm" object in the apps, i.e. like adding a new app object, call it Alarm2 maybe ?
Since the information is streamed, It would be nice to store the information it's sending out, so It'd be nice to have a format like

```
{
    "apps": {"Alarm": [{
      "d": {
        "LightStatus": 0,
        "intruder": 0
      },
      "ts": "2016-06-07T22:18:12.022855 03:00"
    },{
      "d": {
        "LightStatus": 1,
        "intruder": 0
      },
      "ts": "2016-06-07T22:45:12.022855 03:00"
    }]}
  }],
}
```

and so on
Would this be possible ? Also would it be possible not to remove the added apps during an update operation when the apps has a new key value i.e. if i add Alarm2, Alarm shouldn't be removed. but apps should have both Alarm and Alarm2.

**Comment by leonmak** [comment]
@sudheesh001 Sorry but I'm not sure why adding a new app object would remove the previous one? I did store the walls in an array also, wouldn't adding one object just be pushing to the array? I was using mongodb for the backend so it might be different

**Comment by sudheesh001** [comment]
@leonmak This is for the /accounts.json API So if we run two commands for update as
- http://localhost:9000/api/account.json?action=update&data={"screen_name":"test","apps":{"wall":{"type":"horizontal"}}}
followed by
- http://localhost:9000/api/account.json?action=update&data={"screen_name":"test","apps":{"wall2":{"type":"horizontal"}}}

This will remove the `wall` and will now contain `wall2` but we should be having both `wall` and `wall2` ideally

**Comment by leonmak** [comment]
Is it possible to assign a new property to the apps field? In mongoose, I would change the schema to use the ['mixed' property type](http://mongoosejs.com/docs/schematypes.html#mixed) if there were dynamic changes in the schema. Not sure if there is something similar for java.

**Comment by mariobehling** [comment]
Classifying this as "wontfix" as no-one took up this issue.
