### ISSUE TITLE
Update documentation for push data which creates and stores a new index

### ISSUE THREAD

**Issue by sudheesh001** [loklak/loklak_server#559]
since we can now have custom indexes, the push API needs to be updated with the details on how to 
- [ ] Push data to the new index.
- [ ] Query data from the new index.
- [ ] Push and update existing data to the index

**Comment by sudheesh001** [comment]
Superset of #558

**Comment by mariobehling** [comment]
Some progress had been made on this, but as loklak is not used in a productive company environment currently I am classifying this as "wontfix". It is important, but we don't have the resources to solve it currently. Anyone re-opening this topic should be willing to work on it.
