### ISSUE TITLE
Make IBM Home Automation using Watson push the data parallely to the loklak service

### ISSUE THREAD

**Issue by sudheesh001** [loklak/loklak_server#560]
```
/api/push.json needs to be extended in the python API for the same.
```
IBM Watson Developer: https://developer.ibm.com/iotfoundation/recipes/raspberry-pi/
Github: https://github.com/DIYhacking/IoT

Part to update: https://github.com/DIYhacking/IoT/blob/master/server1.py#L27
To do:
- Multithread over here so that one thread sends to loklak while the other continues operations uninterrupted
- Add the python loklak library
- Update documentation

Depends on : #559

**Comment by Orbiter** [comment]
+1

**Comment by sudheesh001** [comment]
Implemented [loklak/loklak_IBM_Home_Automation](https://github.com/loklak/loklak_IBM_Home_Automation)
