### ISSUE TITLE
Collect questions we could answer with the data loklak collects

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_server#574]
The idea of this collection is to define, which apps we can build to make use of loklak data in loklak depot.

https://docs.google.com/document/d/1-r5lJsV_Ag1ZRtvsrld9CplPQh7EFvVCNM3g9EcaYfk/edit

**Comment by Orbiter** [comment]
this is part of https://github.com/loklak/loklak_server/issues/575

**Comment by Orbiter** [comment]
It is now possible to implement a subset of the collected questions into https://github.com/loklak/loklak_server/blob/master/conf/susi/susi_cognition_000.json
Please go ahead and try to add simple answers .

**Comment by shivenmian** [comment]
@mariobehling we are already adding questions in Susi so can this be closed now?
