### ISSUE TITLE
Creating an initial list of (regex, query, rendering) tuples for Q & A App

### ISSUE THREAD

**Issue by jig08** [loklak/loklak_server#579]
With respect to https://github.com/loklak/loklak_server/issues/574 &  https://github.com/loklak/loklak_server/issues/575 , an initial list of `(<regex for question>, <query formula>, <rendering method>)` needs to be created in order to build a `Q & A App` helping to answer the user questions.

User would then also be able to add their `(<regex for question>, <query formula>, <rendering method>)` tuples to this list.

**Comment by jig08** [comment]
@mariobehling @Orbiter Could start off by helping making this list

**Comment by Orbiter** [comment]
@daminisatya I am working on a template for this. I iam doing that because there is a syntax that I want to invent to describe visualization methods in combination with regex and query, and also a meta-setup for the query (like different query languages). Will commit this soon.

**Comment by daminisatya** [comment]
@Orbiter Sure. Will start on it as soon as the template is available. Im currently working on Weibo scraper.

**Comment by Orbiter** [comment]
The template is now available in https://github.com/loklak/loklak_server/blob/master/conf/susi/susi_cognition_000.json
Pleas try to add more entries.

**Comment by jig08** [comment]
@Orbiter Surely, will contribute more to it...

**Comment by Orbiter** [comment]
solved and described in http://blog.loklak.net/all-about-susi/
