### ISSUE TITLE
Loklak App to add a new (regex, query, rendering) tuple to the list

### ISSUE THREAD

**Issue by jig08** [loklak/loklak_server#580]
With respect to https://github.com/loklak/loklak_server/issues/574 &  https://github.com/loklak/loklak_server/issues/575, Creating a Loklak app which allows the user to add another `(<regex for question>, <query formula>, <rendering method>)` tuple to the list created in #579 . 

This app could be created just like other apps in http://loklak.org/apps/applist/index.html being looked over by @daminisatya

**Comment by sudheesh001** [comment]
Why can't this be sent as a pull request just the way DDG does ? Why do we have to expose the instant answers regexes for update operations ?

**Comment by Orbiter** [comment]
@sudheesh001 that would be the easiest way to start and maybe we will also accept that method in the future. But it could be possible to address much more people who do not have github accounts but may be able to create such Q&A apps just by putting some simple lines in a front-end.
So yes, pull requests are ok but a GUI would be nice to have as well!

**Comment by Orbiter** [comment]
We should store user-generated rules in files in data/susi/
Each time a new rule is created it can be added to the Q&A app Memory by calling DAO.susi.add(JSONObject json) wit a complete data set like in https://github.com/loklak/loklak_server/blob/master/conf/susi/susi_cognition_000.json
We can add another method to add single rules as well.

**Comment by Orbiter** [comment]
Our rules syntax is now already a bit more complex beyond this requirement. Damini described the basic examples in http://blog.loklak.net/all-about-susi/ so this can be closed
