### ISSUE TITLE
Create a Q&A Framework app which has an user input page and a result rendering page

### ISSUE THREAD

**Issue by daminisatya** [loklak/loklak_server#583]

**Comment by Orbiter** [comment]
As an result of some side-effect thoughts we should have the result rendering as something that can be embedded elsewhere, but appears in loklak as App.

**Comment by Orbiter** [comment]
You can now continue with this work, the required API Skeleton is there. Please try the example URLs provided in https://github.com/loklak/loklak_server/commit/ece2e622589bf287e494478ef984dd0ea2b059c1

**Comment by Orbiter** [comment]
I named the Q&A framwork api now susi. Here is a typical call to susi:
```
http://loklak.org/api/susi.json?q=hello
```

and a typical answer:

```
{
  "session": {"identity": {
    "type": "host",
    "name": "119.81.6.246",
    "anonymous": true
  }},
  "count": 1,
  "answers": [{
    "metadata": {
      "hits": 1,
      "offset": 0,
      "count": 1
    },
    "data": [{
      "0": "hello",
      "1": "",
      "2": ""
    }],
    "actions": [{
      "type": "answer",
      "expression": "Hello!"
    }]
  }]
}
```

The framework app would send queries to the susi.json api and renders it's response. There response may have a bit more complex content, but that would be an extension of this example.

**Comment by daminisatya** [comment]
#655 

Opening another issue for getting the response from the susi json. Probably after adding more rules and phrases.
