### ISSUE TITLE
no log in eclipse terminal

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_server#586]
since the change in logging I get the following lines in the eclipse terminal:
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

Can we have default loglevel settings so that we see again whats happening?

**Comment by treba123** [comment]
Oh, my fold. Didn't think about that eclipse needs all libs in the classpath (in contrast to ant). Will readd them.

**Comment by treba123** [comment]
I had to add a log4j2 configuration file to the classpath, done 
https://github.com/loklak/loklak_server/pull/587
