### ISSUE TITLE
[Generic Scraper] Add more fields to GenericScraper.java

### ISSUE THREAD

**Issue by daminisatya** [loklak/loklak_server#598]
When compared to Diffbot, which scrapes only the basic information from a given URL, the current API is able to provide the following details. 

- Language
- Links 
- images
- title
- source files
- Text in the link tags

Further enhancements would be better if it is able to scrape most deeply parsed data. I want suggestions on this. These are one's from my side. 

- [ ] Video links
- [ ] Social media links
- [ ] Content of the meta tags
- [ ] inline scripts
- [ ] page URL

Along with some other generic fields we can have options(as shown below) where specific data can be retrieved accordingly.

- [Article API](https://www.diffbot.com/dev/docs/article/) (Extracts all details about the articles and other blog posts)
- [Product API](https://www.diffbot.com/dev/docs/product/) (Extracts all details about the product from a given E commerce website)
- [Image API](https://www.diffbot.com/dev/docs/image/) (Extracts all the images and their attributes)
- [DiscussionAPI](https://www.diffbot.com/dev/docs/discussion/) (Extracts all the discussion threads, comments and likes) 

The above APIs are the services currently being offered by Diffbot. The links are to their docs and sample JSON objects which they have implemented.

**Comment by daminisatya** [comment]
@mariobehling @Orbiter any more suggestions?

**Comment by sudheesh001** [comment]
Implemented with boilerpipe library for NLP
