### ISSUE TITLE
Log file of 30 Gb "java.lang.IllegalArgumentException: Illegal group reference"

### ISSUE THREAD

**Issue by smokingwheels** [loklak/loklak_server#6]
Does not seem to affect results but system gradually slows.
Running Loklak and Yacy on 2 Gb ram Debian 7.8.
Wrote a QB 64 program to dump records out when into raw data 500 000 lines
File size 31,718,676,586 bytes now deleted on loklak server but I have a copy.

"java.lang.IllegalArgumentException: Illegal group reference"
"at java.util.regex.Matcher.appendReplacement(Matcher.java:808)"
"at java.util.regex.Matcher.replaceFirst(Matcher.java:955)"
"at org.loklak.scraper.TwitterScraper$TwitterTweet.<init>(TwitterScraper.java:282)"
"at org.loklak.scraper.TwitterScraper.search(TwitterScraper.java:165)"
"at org.loklak.scraper.TwitterScraper.search(TwitterScraper.java:70)"
"at org.loklak.DAO.scrapeTwitter(DAO.java:519)"
"at org.loklak.api.server.SearchServlet$1.run(SearchServlet.java:89)"
"java.lang.IllegalArgumentException: Illegal group reference"
"at java.util.regex.Matcher.appendReplacement(Matcher.java:808)"
"at java.util.regex.Matcher.replaceFirst(Matcher.java:955)"
"at org.loklak.scraper.TwitterScraper$TwitterTweet.<init>(TwitterScraper.java:282)"
"at org.loklak.scraper.TwitterScraper.search(TwitterScraper.java:165)"
"at org.loklak.scraper.TwitterScraper.search(TwitterScraper.java:70)"
"at org.loklak.DAO.scrapeTwitter(DAO.java:519)"
"at org.loklak.api.server.SearchServlet$1.run(SearchServlet.java:89)"
"java.lang.IllegalArgumentException: Illegal group reference"
"at java.util.regex.Matcher.appendReplacement(Matcher.java:808)"
"at java.util.regex.Matcher.replaceFirst(Matcher.java:955)"
"at org.loklak.scraper.TwitterScraper$TwitterTweet.<init>(TwitterScraper.java:282)"
"at org.loklak.scraper.TwitterScraper.search(TwitterScraper.java:165)"
"at org.loklak.scraper.TwitterScraper.search(TwitterScraper.java:70)"
"at org.loklak.DAO.scrapeTwitter(DAO.java:519)"
"at org.loklak.api.server.SearchServlet$1.run(SearchServlet.java:89)"
"java.lang.IllegalArgumentException: Illegal group reference"
"at java.util.regex.Matcher.appendReplacement(Matcher.java:808)"
"at java.util.regex.Matcher.replaceFirst(Matcher.java:955)"
"at org.loklak.scraper.TwitterScraper$TwitterTweet.<init>(TwitterScraper.java:282)"
"at org.loklak.scraper.TwitterScraper.search(TwitterScraper.java:165)"
"at org.loklak.scraper.TwitterScraper.search(TwitterScraper.java:70)"
"at org.loklak.DAO.scrapeTwitter(DAO.java:519)"
"at org.loklak.api.server.SearchServlet$1.run(SearchServlet.java:89)"

**Comment by Low012** [comment]
I can top that 30GB, I got 838GB!

It started out of the blue on 2015-04-16 22:50:36 (UTC+2).

![clipboard01](https://cloud.githubusercontent.com/assets/11596220/7201228/33878bb6-e505-11e4-83c2-527c810ac479.png)

**Comment by smokingwheels** [comment]
Wow you hold the record. If you delete the log file when Loklak is running it will never fill up, but no logs though.

**Comment by Low012** [comment]
New record! 

![clipboard01](https://cloud.githubusercontent.com/assets/11596220/7407663/efab327a-ef14-11e4-8ecd-afbdd16a4f01.png)

**Comment by smokingwheels** [comment]
Wow a new record.
@Low012 Have you updated recently? 
If you overwrite the log file then wait a little while and stop server,  download it you can see whats causing the problems.
Hopefully the latest update which does not check the index results to see if it exists is a fix.

**Comment by Low012** [comment]
I had to delete the file since I had no space left on my server. I have not updated in a while, but I have the latest code running now.

**Comment by smokingwheels** [comment]
I am not seeing the performance increase.
Have you tried cd /myloklak_server
git clone https://.....
cp -r loklak_server/* /myloklakserver
ant
eg clone to a sub folder in loklak_server and copy or move it back and recompile.

**Comment by Low012** [comment]
You were right, I did not run the latest code. Note to myself: Always read error messages of git! ;-)

**Comment by Orbiter** [comment]
the bug was fixed with todays commit
