### ISSUE TITLE
Integrate loklak as a goodie into duck duck go !

### ISSUE THREAD

**Issue by sudheesh001** [loklak/loklak_server#600]
When there's a search which says `twitter: #fossasia` DDG should show the topmost query
For every hashtag / mention etc.., `twitter: #fossasia`, `twitter: @mariobehling` etc.., and we should see one tweet shown in the quick shows of DDG powered by Loklak

**Comment by daminisatya** [comment]
@sudheesh001 How is this realted to IoT?

**Comment by sudheesh001** [comment]
Data streams are to be integrated into loklak, so we can try pulling the information from DDG towards loklak. Hence under IoT, what should be more importantly being focused on is the integration to DDG than focusing on how it falls under IOT.

**Comment by daminisatya** [comment]
I dont feel it is relevant.

**Comment by mariobehling** [comment]
No need. This will just cost us server resources.
