### ISSUE TITLE
Create the loklak instant answers application which will be the placeholder for the rest of the queries

### ISSUE THREAD

**Issue by sudheesh001** [loklak/loklak_server#601]
Implement
- [ ] Top tweet `twitter: #fossasia`
- [ ] Most favorited: `twitter: +favorite #WWDC`
- [ ] Compare `compare #apple and #google`

Please extend this list, These are bound to be initial framework designs for front end which can be extended.

**Comment by daminisatya** [comment]
@sudheesh001 How is this different from #589 ? and also refer the following issues #579 #580 #583 ?

**Comment by sudheesh001** [comment]
@daminisatya @jig08 What I understand from https://github.com/loklak/loklak_server/issues/583 is that it's going to be framework endpoints using which the other instant answer APIs can be integrated into the loklak server. This can then be extended to reply as needed. So it'll follow the fly weight design pattern

![flyweight_example](https://cloud.githubusercontent.com/assets/4545925/16105445/29824aa0-33a8-11e6-9031-8a0a5cd3e7d8.gif)

Using such a system we can have a regex builder as a factory which will integrate all the other questions (weights), The main factory will build and request to the required weight and return with the response from the weight, Using such a fashion would mean we don't have to compare the query given to hundreds of regexes but only to a few grouped and classified together.

**Comment by daminisatya** [comment]
The intend is the same with all the previous issues. There is a very minor distinction between each of these. I feel you must rearrange the issues, with more clarity and description.

**Comment by sudheesh001** [comment]
Please move this to the framework issue. Closing this for #583 updated

**Comment by sudheesh001** [comment]
@daminisatya I don't see a reason why this has to be open, if the team thinks it's closely aligned with #583 I wanted to explain the flyweight pattern here so that we could treat every new regex as a pattern and do a single query rather than comparing 100 different regexes to match and reply.

**Comment by daminisatya** [comment]
@sudheesh001 absolutely ! Will redirect this issue to #583. Thanks for the clarification.
