### ISSUE TITLE
Public/private key login

### ISSUE THREAD

**Issue by treba123** [loklak/loklak_server#604]
Additionally to userid/secret login, in some scenarios it might be handy to have a public/private key login, similar to ssh.

Especially for IoT devices, it's maybe nice if the devise can
- just create it's own key pair (or get deploit with it)
- sign up with it
- as soon as the sign-up is accepted by the administrator, the device can use it to make a handshake (to get an access token, as key verification on each call is not performant, see https://github.com/loklak/loklak_server/issues/603)
- it can then use the token on each request

**Comment by Orbiter** [comment]
+1

**Comment by treba123** [comment]
https://github.com/loklak/loklak_server/pull/714
