### ISSUE TITLE
Create a crawler for events implementing JSON output data as defined in Open Event API

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_server#607]
There are different kinds of JSON structures that we could use in loklak in future. An importer of Open Event could also use this data and on top of that also use the loklak API to display tweet like data.

It would be a wonderful use case to have a lot of loklak tweets on open events.

First step to achieve this is to get the relevant data from sites such as Eventbrite. Please implement a crawler, that collects the data and outputs each event into a folder with JSON files as defined in https://github.com/fossasia/open-event-orga-server/blob/development/docs/API.md

Please do as follows:
* [ ] Define fields and an example that can be parsed: https://github.com/loklak/loklak_server/issues/631
* [ ] Create one set of example JSONs with as much detail as possible (following the sample [here](https://github.com/fossasia/open-event-orga-server/tree/development/samples/ots16)) https://github.com/loklak/loklak_server/issues/632
* [ ] Propose a harvesting mechanism and how to fit it in the structure of loklak

**Comment by jig08** [comment]
@mariobehling Sure, I will give it  a try :+1:

**Comment by mariobehling** [comment]
More info on the APIs also here https://open-event.herokuapp.com/api/v2/

**Comment by mariobehling** [comment]
@jig08 Could you include the crawling of the event background images as well?

**Comment by jig08** [comment]
@mariobehling Okay, will give it a shot !

**Comment by jig08** [comment]
@mariobehling Okay.
I have included the `event-image-link` in the JSON Object being returned, there is no `background_image` that could be crawled from `eventbrite.com`
Could you pls point out , I will do the needful accordingly....

For instance: [eventbrite.com/fossasia-2016-tickets-17438255291](http://www.eventbrite.com/e/fossasia-2016-tickets-17438255291)

![screenshot from 2016-06-20 07 43 33](https://cloud.githubusercontent.com/assets/9291400/16181593/b58d6c68-36ba-11e6-87f5-adc7a3f440c2.png)

**Comment by mariobehling** [comment]
Looks like this is an old page. The new design has a background image. Please try to get the image if there is one. If there is none, leave it empty.

Compare here https://www.eventbrite.de/e/rise-of-ai-human-coexistence-with-machines-tickets-24985479241?aff=erellivmlt

**Comment by jig08** [comment]
@mariobehling, okay. Will give it a try :v: 
Seems like I would have to modify the crawler for the new version also.

**Comment by jig08** [comment]
Also, different events on `eventbrite` have different HTML formats (Basically, there are two)

For the time being, I was working on the older version (supposedly), shall modify it according to the newer one and accommodate both version probably. 

***

Link 1: [eventbrite.sg/e/why-are-they-smiling-tickets-25775779049?aff=ehomecard](https://www.eventbrite.sg/e/why-are-they-smiling-tickets-25775779049?aff=ehomecard)

![screenshot from 2016-06-20 20 56 54](https://cloud.githubusercontent.com/assets/9291400/16200097/89655b90-3729-11e6-9149-88adf7f22a3b.png)

***

Link 2: [eventbrite.com/e/drinkentrepreneurs-at-new-hub-singapore-in-cuppage-terrace-tickets-5339893766?aff=ehomecard](http://www.eventbrite.com/e/drinkentrepreneurs-at-new-hub-singapore-in-cuppage-terrace-tickets-5339893766?aff=ehomecard)

![screenshot from 2016-06-20 20 53 32](https://cloud.githubusercontent.com/assets/9291400/16200129/9fcec858-3729-11e6-89db-204930ff4451.png)

**Comment by jig08** [comment]
Trying to extract image link from [eventbrite.com](https://www.eventbrite.com/)'s latest version currently using `JSoup`....
For instance:  [view-source: eventbrite.de/rise-of-ai-human-coexistence-with-machines-24985479241](https://www.eventbrite.de/e/rise-of-ai-human-coexistence-with-machines-tickets-24985479241)

**Comment by mariobehling** [comment]
What is the update here? If issues take longer than a day, please create subissues and link them here. Do you have sample JSON files of the data you extracted so far?
