### ISSUE TITLE
Scrape a users following and followers information from the user list we currently have

### ISSUE THREAD

**Issue by sudheesh001** [loklak/loklak_server#61]
Everytime we scrape a new user, we can also move to the following links

Followers: https://twitter.com/&lt; twitter handle &gt;/followers
Following : https://twitter.com/&lt; twitter handle &gt;/following

And link them to the Followers and Following information of the users we have. Both these pages,
Can we deal with the scroll to load new followers problem ?

**Comment by Orbiter** [comment]
this is now subsumed with https://github.com/loklak/loklak_server/issues/64
