### ISSUE TITLE
JsonFile and JsonTrays

### ISSUE THREAD

**Issue by treba123** [loklak/loklak_server#612]
Our current JsonTray/JsonFile combo implementation is quite good in avoiding IO, but has some disadvantages:
- we have to differentiate between persistent and not persistent data -> complex and a lot of data loss on restarts (currently all cookies and email verification links get deleted when the server restarts)
- only writing non-persistent data is IO friendly
- persistent data has to be handled with care -> IO unfriendly
- if we use child objects of persistent data, we have to call the commit function (or hope that it happens at some other point). Complex and sometimes confusing, lot's of code.
- we can't see non-persistent data in the files
- it does not solve the problem that we still need some process which cleans them up (AFAIK there's a maximum size for non-persistent data, but what does happen when it reaches that point?)

So I though we can maybe drastically reduce the complexety of the whole story by having a backgroud thread which does everything for us  in a fixed interval:
- commit the data
- clean up expired data

So all we need to do is register all JsonFiles we need in an array in DAO.
The thread will then call `cleanUp()` and `commit()` on each of that every, lets say, ten minutes and **on exit** (which is the only moment where we really need to write data to a file. In between, it just helps to not lose data on crashes).

The normal put and remove commands would not commit on their own anymore and we could also remove a lot of code from some of our classes which always check if they have to commit changes or not.

That would even more reduce IO and really reduce code complexity.
We can also split that up from each other, having one commit and one cleanup thread, but i guess we can more easily combine them.

@Orbiter do I have your ok?

More context: I'm sometimes experiencing issues with data not written to the files (potentially because of race conditions). Having a completely asyncronous thread doing it will hopefully solve that.

**Edit:** I'd say do split this up into two arrays: one for commit, one for cleanup.
The thread just interates through them and calls the respective functions.

For cleanup, I'd create a new interface which specifies a cleanup function. So we could use that not only for jsonfiles but also for other objects if we need it.

**Comment by Orbiter** [comment]
The disadvantages you describe above are actually advantages (i.e. to differentiate persistence, beeing IO-friendly). If we do not write if data must be persistent and do this only with a cyclic process, the data store does not fullfill its purpose in case of a crash.

I also don't see a pressure point: having the responsibility to call a commit is not really hard.

You considered some 'gaps' in the monitoring; yes it would be good to have some monitoring for non-persistent data. Lets consider this as an enhancement.
Lets keep the functionality as it is.

**Comment by treba123** [comment]
Well, in case of a crash we do have data loss anyway (the whole elasticsearch database also does not write directly).
That is an acceptable risk for basicly all projects which use embeddet databases or database cache mechanisms (which is basicly all bigger projects). Especially if we choose to small time intervals (10-30 seconds would still be very performant).
And if we have sensitive data we need to make sure to be written, we can still have a way to force a commit.

The problem with the current implementation is that
- it really complicates things (I know because I use them all the time) because 
 - we can't just use child objects without caring if they need to be written to disk, therefor always needing to pass that information
 - we have to care what information we write where (as we have to be extra careful to not create high IO)
- it's also very fragile (as it requires manual commits all over the place)
- it is not very performant as soon as we have many users
- capsulation is THE reason why object orientation is nice. The current concept is the opposite of capsulation, it requires constant thinking about what happens in the background

**Comment by treba123** [comment]
Reopened.

The two main points which we have to solve is
-  to have a way to be able to write persistent data without creating high IO pressure for data we can afford to lose in the rare occasion of a crash.
- to clean up the JsonTrays (even if in ram)

There're probably many ways to achive it, but we need one.

One more idea how to solve the first point would be to have an addition `commit` function which caches multiple commits before it writes and is also called when the server shuts down.

We could then use that one for not so important data

**Comment by Orbiter** [comment]
We do not have rare occasions of a crash, unfortunately.
And elasticsearch writes always directly into the translog to have a backup in case of a crash.
Pleas end discussions here, we don't really have a pressure point.
There is more important work to do.

**Comment by mariobehling** [comment]
@treba123 Let me butt in here. There are tons of ways to improve all parts of the system. The current question is: How can we make some cool features, that people like and get attention to get more devs and users. Let's not end up with this project like lots of projects before: We try to make it perfect and we loose the energy to actually do it.

**Comment by treba123** [comment]
Sorry but that's the whole point of the discussion. I'm currently using the JsonTrays (as I'm working on the authorization system) and it does complicate my work alot. So yes, there's a pressure point and I am feeling it (in contrast to you who are currently not working with them AFAIK)
So I'm just trying to find a solution for what I'm currently doing.

I'm not asking you to do the work, I'm just asking to let me do my work good.
And the whole AAA system is an important future I guess.

I'm not saying this whole thing out of the blue and I'm currently wasting more energie trying to work with the JsonTrays instead of having a better system.

I'm sorry to say that, but 

> Pleas end discussions here, we don't really have a pressure point.
> There is more important work to do.

is plain ignorant.
