### ISSUE TITLE
Scraping the Weibo pages using JSoup.

### ISSUE THREAD

**Issue by daminisatya** [loklak/loklak_server#613]
- [ ] @Orbiter Is there any efficient way of scraping the Weibo pages? Looks like the JSoup cannot support nested tags scraping. I wrote a small scraper(under api and registered as api/usersWeibo.json) to scrape the user profile pages. Tried using the selectors to get the nested value. But before trying further I would like to know the other possible solution to harvest the weibos.
- [ ] Will the [Weibo Java SDK](http://open.weibo.com/wiki/SDK#Java_SDK) be of any help? 
- [ ] This the [sample API](http://open.weibo.com/wiki/Users/show/en#Java_Example), the java code by Weibo for accessing the User's profile. 

I want suggestions for this else will continue with JSoup.

**Comment by jig08** [comment]
Follow up of **https://github.com/loklak/loklak_server/issues/217 Implement data collection from Chinese twitter like service weibo.com**

**Comment by DengYiping** [comment]
Be careful about crawling rate. Jsoup is a good solution, you are on the right track.

**Comment by daminisatya** [comment]
@DengYiping Yes, i guess it will block after certain rate?

**Comment by daminisatya** [comment]
This is a follow up for making the scraper work. and queue the service. Using @DengYiping 's patch.

**Comment by Orbiter** [comment]
I don't have  recommendation here because I don't know JSoup

**Comment by mariobehling** [comment]
As Weibo requires accounts and the dev teams focus has finished, I am classifying this as "wontfix". Anyone re-opening this topic should be willing to work on it.
