### ISSUE TITLE
Javadocs

### ISSUE THREAD

**Issue by treba123** [loklak/loklak_server#628]
I personally would really like to have the javadocs build automatically with the application and accecible from the webserver.
That would make development (for us and for outsider) easier and also maybe push us to documentate everything better.

**Comment by Orbiter** [comment]
You can make a javadoc ant task for that, but do not include this in the 'all' process (if this is regarding to ant). Building the javadoc every time when compiling the code will increase turnaround-times for development.

**Comment by treba123** [comment]
Yes that's true. There's a way to publish javadocs on github.io from the repo, will try to make that work

**Comment by Orbiter** [comment]
+1

**Comment by treba123** [comment]
Alright, the I have the automatic build working on my fork. It only triggers when something gets merged/pushed to the master branch. It then builds the javadocs and pushes them to the gh-pages branch, which is then displayed on github.io. Travis has a cool feature to make sure it only happens then, not when somebody who forget the repo does a push there.

You can have a look here: https://treba123.github.io/loklak_server/

@Orbiter to make it work for the loklak repo, I need a little bit assistence from you:
- in the repo settings, under options there's a button 'Launch automatic page generator'
- just click through it (Continue to Layouts, Publish). That will create a gh-pages branch and publish it on github.io

That should do I hope (maybe there's another step that has to be done by the repo owner, but I think not).

**Comment by Orbiter** [comment]
I enabled the github pages

**Comment by treba123** [comment]
Nice, thanks.
Alright, javadocs are now automatically published on http://loklak.github.io/loklak_server/
