### ISSUE TITLE
[Weibo] Scrape user profile page and find profile user pages of followers and following

### ISSUE THREAD

**Issue by daminisatya** [loklak/loklak_server#634]

**Comment by DengYiping** [comment]
Hi! @daminisatya Have you started yet. I've just implement scraping user info page, but it requires a logined account. I will post it tomorrow if you need.

**Comment by daminisatya** [comment]
@DengYiping I got stuck with other work item which were marked as high priority, You can create a PR for the following  :)

**Comment by DengYiping** [comment]
@daminisatya 

Could you explain a little bit about how to push to the back-end? 
Right now I have implement decoder (Weibo put html in `<script></script>`), and parsing html becomes really easy.  
[https://github.com/DengYiping/WeiboSpider/blob/master/src/main/scala/com/sd/spider/DecodeWeibo.scala](url)

**Comment by daminisatya** [comment]
@DengYiping The code base is in Java, Im not sure if .scala fits along with other scrapers.

**Comment by DengYiping** [comment]
@daminisatya I know, what I am thinking of is push to the RESTful service.

**Comment by DengYiping** [comment]
@daminisatya I also have Java implementation, so it won't be a problem, but I haven't figure out how to push to the backend.

**Comment by daminisatya** [comment]
@DengYiping You can place your code [inside this folder,](https://github.com/loklak/loklak_server/tree/development/src/org/loklak/api/search) and register the API endpoint in the [LoklakServer.java](https://github.com/loklak/loklak_server/blob/development/src/org/loklak/LoklakServer.java). Hope this is what you wanted!

**Comment by DengYiping** [comment]
@daminisatya 
I post a helper function here. I will keep working on it.
#735 

How about login credentials?

**Comment by mariobehling** [comment]
@DengYiping 

> How about login credentials?

For what? To login where?

**Comment by DengYiping** [comment]
@mariobehling Login is required to scape weibo information. I've tried multiple implementation to bypass it. Non of it actually works.

**Comment by mariobehling** [comment]
@DengYiping Well, this is a problem then, cause it means our distributed peer to peer model would not work. Let's say we have 100 peers, it would mean that they all login with a pre-configured account, that we would have to define. Weibo servers would block us after a short period of time apparently. What do you think? Is there a solution to this?

**Comment by mariobehling** [comment]
The only solution I see is, if we could implement auto registration, which is probably prevented through catpcha or other ways by weibo.

**Comment by DengYiping** [comment]
@mariobehling If we could manage a account pool, I think it will work. I am still experimenting on this issue.

**Comment by mariobehling** [comment]
@DengYiping Account pool could be partly a solution. We could see, if it works continuously. What about the documentation of Weibo parsing here: https://github.com/loklak/loklak_server/blob/development/docs/parsers.md I missed if this parser is also parsing the results from the search page of weibo and continuously searches terms just as we do for twitter. @daminisatya @jig08 Could you please help to complete the documentation?

**Comment by jig08** [comment]
@mariobehling Sure. I will add the required details in _parsers.md_

**Comment by daminisatya** [comment]
@mariobehling @jig08 Please keep the documentation for weibo on hold. The parser is not available yet. I made a PR and it requires some change with @DengYiping 's patch.

**Comment by jig08** [comment]
@daminisatya Okay..
