### ISSUE TITLE
Importing JSON Files from #640 to test Open Event

### ISSUE THREAD

**Issue by jig08** [loklak/loklak_server#642]
This was tested as desired but an `Internal server error` error is encountered on clicking `Create Event` at [open-event.herokuapp.com/events](http://open-event.herokuapp.com/events/) while importing the zipped folder containing  `JSON Files` (written out in #640) locally which have the event details extracted from [eventbrite.com](https://www.eventbrite.com/)

Reference:-
![screenshot from 2016-06-29 08 53 18](https://cloud.githubusercontent.com/assets/9291400/16439561/5daca760-3dd7-11e6-86bb-7776741084cf.png)

**Comment by rafalkowalski** [comment]
@jig08 do you have any logs from heroku. If not please use "heroku logs"?

**Comment by aviaryan** [comment]
@jig08 please make sure that the json files are at the root level of the zip. That is, when you open event.zip, you see event.json, sessions.json etc .., not a folder. Related https://github.com/fossasia/open-event-orga-server/issues/1323
Also can you give the link to zip that you tried to import, that would be helpful.

**Comment by rafalkowalski** [comment]
@aviaryan 
[EventBriteInfo.zip](https://github.com/loklak/loklak_server/files/339501/EventBriteInfo.zip)

**Comment by aviaryan** [comment]
@rafalkowalski @jig08 I moved the json files at the root of the zip and imported it. Now the error is "end_time missing in event.json".

**Comment by jig08** [comment]
@aviaryan Yes, I was trying the same. It doesn't handle `null` values ?

**Comment by aviaryan** [comment]
@jig08 No. It handles null values. `end_time` is a reqd field, it can't be null.

**Comment by jig08** [comment]
@aviaryan Okay, got that. I'll find a workaround on how not to send `null`. Thank You.

**Comment by jig08** [comment]
@aviaryan The sample data was updated accordingly in PR https://github.com/fossasia/open-event-orga-server/pull/1358 but the `internal server error` persists. 

Tried uploading this sample data: [EventBriteInfo_LoklakScraper.zip](https://github.com/loklak/loklak_server/files/342835/EventBriteInfo_LoklakScraper.zip)

**Comment by jig08** [comment]
@rafalkowalski @aviaryan Any updates on this ?

**Comment by aviaryan** [comment]
@jig08 I have fixed it and merged the patch. Can you please check again ? If it works, please close https://github.com/fossasia/open-event-orga-server/issues/1421

**Comment by jig08** [comment]
@aviaryan Unfortunately, the error still persists....

**Comment by aviaryan** [comment]
@jig08 I checked and it is because of another PR merged today. I'll fix it.

**Comment by jig08** [comment]
@aviaryan Yes, Pls.

**Comment by aviaryan** [comment]
@jig08 Opened PR https://github.com/fossasia/open-event-orga-server/pull/1430 with the fixes

**Comment by jig08** [comment]
@aviaryan :v: Let know when it is merged and we'll test it again.

**Comment by aviaryan** [comment]
@jig08 PR merged

**Comment by jig08** [comment]
@aviaryan Thanks. Works perfectly !
