### ISSUE TITLE
Accounting addRequest does not work

### ISSUE THREAD

**Issue by treba123** [loklak/loklak_server#643]
When trying to use the addRequest method of an accounting object, a ClassCastExeption occurs:
`
java.lang.ClassCastException: org.json.JSONObject cannot be cast to java.util.TreeMap
	at org.loklak.server.Accounting.addRequest(Accounting.java:62)
`

**Comment by Orbiter** [comment]
fixed with https://github.com/loklak/loklak_server/commit/10c77ea2ac682486fca46525e2fafac509a76fff
