### ISSUE TITLE
Retrieve the rules as response from the Susi JSON and make the chat dynamic.

### ISSUE THREAD

**Issue by daminisatya** [loklak/loklak_server#656]

**Comment by daminisatya** [comment]
#583 Extension of this issue

**Comment by Orbiter** [comment]
This may be a misunderstanding of the task: all you have to do is:
- call the susi api, i.e. http://localhost:9000/api/susi.json?q=the%20reddit%20articles%20about%20loklak
- render the answer line in the already existing chat stub of susi.

**Comment by daminisatya** [comment]
#681

**Comment by daminisatya** [comment]
#702 Fixed.
