### ISSUE TITLE
Improve Workflow with branch policy and heroku

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_server#692]
Let's improve our workflow. 

Best is to only keep two branches to make it easier to contribute
a) development
b) master

All PRs should go to development. Master can be merged once per week. Developers should keep their own development in their own repository.

@daminisatya Please delete all branches after checking that they are needed anymore.

Also set up a Heroku instance e.g. loklak-server-dev.herokuapp.com and automatically deploy the development version there.

**Comment by daminisatya** [comment]
fix got resolved.
