### ISSUE TITLE
Integrate TwitterAnalysis app with Susi

### ISSUE THREAD

**Issue by shivenmian** [loklak/loklak_server#694]
@mariobehling @Orbiter The screenshots of the TwitterAnalysis app (#622) are [this](https://files.gitter.im/loklak/loklak/FLKG/Screen-Shot-2016-07-14-at-1.09.50-PM.png), [this](https://files.gitter.im/loklak/loklak/FAhj/Screen-Shot-2016-07-14-at-1.09.59-PM.png) and [this](https://files.gitter.im/loklak/loklak/3BYk/Screen-Shot-2016-07-14-at-1.10.07-PM.png). I implemented the app in #683. The app works fine and gives a lot of data.

Since this is a Twitter profile analyser, one can ask Susi a lot of questions which this servlet can answer. Questions like "in what tweet did @shiven_mian get max likes", "what is the average number of likes of @justinbieber", "in which month did @justinbieber tweeted the most", "at what time of the day does @justinbieber tweeted the most" and many more can be answered from the servlet. The answers to these questions can be particularly interesting as well because these are analytics.

I wish to integrate the app into susi and add rules for all possible questions that can be asked to Susi (which this servlet can answer).

**Comment by Orbiter** [comment]
- To integrate with susi, first turn the TwitterAnalysis servlet into a service. Then that service should return a 'SusiThought' object.
- next add a console service to retrieve data from the service
- finally, rules in Susi can access the analysis app using the terminal

**Comment by shivenmian** [comment]
Yes I will do exactly this

**Comment by shivenmian** [comment]
I have already integrated the app into susi yesterday, I just need to add more questions, so closing this.
