### ISSUE TITLE
Input box too small on mobile devices

### ISSUE THREAD

**Issue by sudheesh001** [loklak/loklak_server#7]
![screen shot 2015-04-10 at 5 29 53 pm](https://cloud.githubusercontent.com/assets/4545925/7087286/4ec3658e-dfa7-11e4-806f-cbfed91e5e77.png)

I think its a good option to make the input box appear at the full length on the screen, and put the JSON and RSS button together in the next line.

**Comment by Orbiter** [comment]
I know that this looks bad, but this is not really important compared to features in the front-end development. I consider this as nice-to-have and ask you to fix that if you like to after other high priorized items are finished

**Comment by sudheesh001** [comment]
Sure I'll fix this up after a few patches to the `loklak_webclient`

**Comment by sudheesh001** [comment]
Tested the setup which runs clean on
1. Ubuntu 
2. Fedora

Only breaks on Mac OS X with the following error
```sh
npm ERR! notarget No compatible version found: nomnom@'douglasduteil/nomnom#next'
npm ERR! notarget Valid install targets:
```
