### ISSUE TITLE
Support get location info feature by getting IP or GPS data through browser or mobile

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_server#70]
The idea is, that every tweet has a location info. The question is, what should be stored in loklak? Relevant are IP-Address and Mac-Address. Anything else? So loklak could store a) location info of the tweet and b) a map attached with geolocation info. These are two different items.

Relevant is: https://github.com/loklak/loklak_webclient/issues/292

**Comment by Orbiter** [comment]
> The idea is, that every tweet has a location info. The question is, what should be stored in loklak? Relevant are IP-Address

Hi Mario, I don't like to store IP addresses. To identify tweets issued from the same location, every tweet contains a hash of the IP.

>  and Mac-Address. Anything else? 
Storage of MAC-addresses is EVIL. And we don't get such things through http, which is good.

> So loklak could store a) location info of the tweet
We have location information if the user wishes to include this. The information can be either a 'place' (a name of a location, name of a city or an address) or 'location' (which is a geocoordinate) or both.

> and b) a map attached with geolocation info. These are two different items.
as far as I see, we have all of that already
