### ISSUE TITLE
Add auto-update function of server software

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_server#71]
loklak shall be able to update itself. The update must be part of the startup-process to ensure that bad updates are overwritten each time a restart attempt is made.
The process can be simple like `git pull origin master;ant` but requires that loklak was installed using a git clone. Therefore the process must be able to check if the copy of loklak is a clone or not.

**Comment by smokingwheels** [comment]
Is there a way to use git pull origin master and force and update eg a fresh download?

**Comment by Orbiter** [comment]
this already exists with the script `bin/upgrade.sh`!

This feature shall implement a process that goes further: a running loklak server should stop itself, run this script and starts up again on a frequent basis. This process will be configurable (by default on).

**Comment by mariobehling** [comment]
Closing it as this is already possible.
