### ISSUE TITLE
Unexpected results in AskSUSI.com

### ISSUE THREAD

**Issue by jig08** [loklak/loklak_server#711]
According to the rule defined in [conf/susi/susi_cognition_000.json#L187](https://github.com/loklak/loklak_server/blob/master/conf/susi/susi_cognition_000.json#L187) the query **I am #** should return **Hi #.** , but the results aren't as expected.

![screenshot from 2016-07-18 05 13 10](https://cloud.githubusercontent.com/assets/9291400/16903840/d995241e-4ca6-11e6-8cdd-cb17ee1afb00.png)

**Comment by jig08** [comment]
Result of [http://loklak.org/api/susi.json?q=I am Jigyasa](http://loklak.org/api/susi.json?q=I%20am%20Jigyasa) API call is as:

![screenshot from 2016-07-18 05 20 00](https://cloud.githubusercontent.com/assets/9291400/16903858/58cc7282-4ca7-11e6-99bd-6de92b29193f.png)

**Comment by Orbiter** [comment]
Check the score

**Comment by jig08** [comment]
@Orbiter Score defined is `1`.

The rule is defined as:

```
{
			"score"  :1,
			"phrases":[	{"type":"pattern", "expression":"I am *"} ],
			"process":[],
			"actions":[	{"type":"answer", "select":"random", "phrases":[
							"Hi $1$."
					  ]}]
		},
```

@daminisatya Do we have a detailed doc for scores in SUSI ?

**Comment by Orbiter** [comment]
The rule with highest score fires first. The first rule that produces a result is the one which delivers

**Comment by jig08** [comment]
@Orbiter Yes, I changed the score to `1000` locally and it works fine.
So that we don't get unexpected results, what way are we assigning the scores ?

**Comment by Orbiter** [comment]
I believe we should have hierachy of scores which are appropriate to a given set of rules, each for a specific goal. We should have a scored-goal advise. I already thought about that but right now thats not finished. For this issue I believe this is solved because we know that the current score system works.

**Comment by jig08** [comment]
@Orbiter Sure. I think we should start with `score` hierarchy , any plans for this soon ?
