### ISSUE TITLE
Wordpress console utility not working with SUSI

### ISSUE THREAD

**Issue by jig08** [loklak/loklak_server#713]
The word-press console utility works fine. Link: [http://localhost:9000/api/console.json?q=SELECT%20*%20FROM%20wordpress%20WHERE%20url=%27https://jigyasagrover.wordpress.com/%27;](http://localhost:9000/api/console.json?q=SELECT%20*%20FROM%20wordpress%20WHERE%20url=%27https://jigyasagrover.wordpress.com/%27;)

![screenshot from 2016-07-18 19 29 51](https://cloud.githubusercontent.com/assets/9291400/16917153/03425346-4d1e-11e6-85dc-cbfbbf59d311.png)

When the rule for the same is added in [conf/susi/susi_cognition_000.json](https://github.com/loklak/loklak_server/blob/master/conf/susi/susi_cognition_000.json)
```
{
			"keys"   :["wordpress"],
			"score"  :1,
			"example":"Susi, Read wordpress blogs from https://jigyasagrover.wordpress.com/",
			"phrases":[ {"type":"pattern", "expression":"* read * wordpress * from *"}
					],
			"process":[ {"type":"console", "expression":"SELECT * FROM wordpress WHERE url='$3$';"}],
			"actions":[ {"type":"answer", "select":"random", "phrases":[
							"Here are the blogposts .."
						]}, {"type":"table"}]
		},
```
The API Call [http://localhost:9000/api/susi.json?q=Susi,%20Read%20wordpress%20blogs%20from%20https://www.jigyasagrover.wordpress.com](http://localhost:9000/api/susi.json?q=Susi,%20Read%20wordpress%20blogs%20from%20https://www.jigyasagrover.wordpress.com) returns unexpected results:

![screenshot from 2016-07-18 19 25 47](https://cloud.githubusercontent.com/assets/9291400/16917431/36651d2a-4d1f-11e6-8ce6-e0ee34251d80.png)

**Comment by jig08** [comment]
@Orbiter I tried keeping a high value of `score` too in this case, but doesn't seem to work fine. 
Any pointers ?

**Comment by Orbiter** [comment]
Bug: it must be $4$, not $3$. It's the fourth pattern

**Comment by jig08** [comment]
@Orbiter It was a typo.

I have tried with this as well

```
{
            "keys"   :["wordpress"],
            "score"  :160,
            "example":"Susi, Read wordpress blogs from https://jigyasagrover.wordpress.com/",
            "phrases":[ {"type":"pattern", "expression":"* read * wordpress * from *"}
                    ],
            "process":[ {"type":"console", "expression":"SELECT * FROM wordpress WHERE url='$4$';"}],
            "actions":[ {"type":"answer", "select":"random", "phrases":[
                            "Here are the blogposts .."
                        ]}, {"type":"table"}]
        },
```

No luck.

**Comment by shivenmian** [comment]
@jig08 Modify it to $4$ in your PR though. The reason the utilities aren't working is cuz of the score system which is a known problem I think.

**Comment by jig08** [comment]
@shivenmian Which PR are you referring to ?

**Comment by shivenmian** [comment]
Oh okay. I thought the wordpress rule was already there in the file. Nothing, ignore.

**Comment by jig08** [comment]
Issue with scores. Fixing Issue https://github.com/loklak/loklak_server/issues/767 (Susi Rule-Score Hierarchy Brainstorming ) will resolve this automatically.
