### ISSUE TITLE
How can we simplify the cognition file of Susi

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_server#717]
Let's assume we get a lot of contributors and they all make rules. The current file is relatively long already and if it gets longer, it could make it difficult to go through the code. Many commits can result in numerous merge conflicts as well.

https://github.com/loklak/loklak_server/blob/master/conf/susi/susi_cognition_000.json

I suggest to split the file therefore. What would be the best option to do this, e.g. according to source?

**Comment by daminisatya** [comment]
+1

**Comment by smokingwheels** [comment]
Have some sort of import function for the people.

**Comment by mariobehling** [comment]
From chat:

> The Susi cognition file can easily be splitted. Just clone the structure into another file and move the rules which belong together to the cloned structure. All new json files in the Susi path will be recognized automatically. That also applies during runtime. No restart restart of loklak required after changes to Susis files.

**Comment by jig08** [comment]
Referring to the above, Maybe we could split the files according the `keys`. 

Similar type of rules (for example: the ones related to RSS or Eventbrite or Youtube etc.) go in a single `JSON` file pertaining to the theme of that rule.
