### ISSUE TITLE
Password recovery incomplete

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_server#720]
I tested successfully that loklak can send me an email to reset my password.
In the email I get a recovery link. After clicking on the link I get the reset app /apps/resetpass/
There I set my new password, but after clicking on "Reset password" _nothing_ happens. That means: no message, no change nothing.
Tested witgh Firefox.

**Comment by shivenmian** [comment]
@Orbiter I worked on the Password Recovery. Let me check.

Are the following working?:

1. Sending of email once you fill the email ID in password Recovery Form
2. The email you get has a recovery link
3. Clicking on recovery link opens up the Password Reset form (i.e where you set new password)

If the above 3 are working, is the only problem that filling up the Reset form gives you no response?

**Comment by Orbiter** [comment]
as I described in the issue: all 3 are working, there is only no response.

**Comment by Orbiter** [comment]
Here is a javascript error message

<img width="818" alt="pwrecover" src="https://cloud.githubusercontent.com/assets/238730/16983313/935769a6-4e74-11e6-97f9-55e0c628a46f.png">

**Comment by shivenmian** [comment]
solved with #721 @mariobehling @Orbiter
