### ISSUE TITLE
Will loklak pick up Public Groups?

### ISSUE THREAD

**Issue by smokingwheels** [loklak/loklak_server#723]
Please close this Issue if already does.
[TweetKalgoorlie/lists/everything-and-everyone-k](https://twitter.com/TweetKalgoorlie/lists/everything-and-everyone-kl)

**Comment by mariobehling** [comment]
Not sure, if that really needs to be covered. The example does not work for me:

![screenshot from 2016-07-20 19 14 35](https://cloud.githubusercontent.com/assets/1583873/16995723/3a771fe0-4eae-11e6-9212-1b823ee55b05.png)
