### ISSUE TITLE
Add few generic rules to Susi

### ISSUE THREAD

**Issue by daminisatya** [loklak/loklak_server#726]
This issue aims at adding more generic questions which we come across daily chat, for example, 

- How was your day?

- How are things going on?

- How to deal with situations when I'm stressed? 

- I need some help 

- Susi please help me with my math. 

Currently these generic questions are being retrieved from urban dictionary or wikidata, but having a specific answer is useful and will increase the identity of Susi(we can make these rules to work by increasing the score).

**Comment by daminisatya** [comment]
@Orbiter I need your views on this and suggestions.

**Comment by daminisatya** [comment]
The answer we get when we ask Susi the question [```How was your day?```](http://loklak.org/api/susi.json?q=how%20was%20your%20day?) is this
```To the law enforcement men & women gettin' off work for the day, or goin' to work for the night: Thank you for your service. Merica.``` and it is variable. Instead adding such generic rules can help in giving the best humanly answers.

**Comment by jig08** [comment]
+1 for this .

**Comment by daminisatya** [comment]
#727
