### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_server#728]
We need to make it easier for people to contribute. Please add more relevant info to 
* [x] Readme.md
* [x] Docs folder
* [ ] Contributing.md

**Comment by jig08** [comment]
@mariobehling We already have a [docs](https://github.com/loklak/loklak_server/tree/development/docs) folder. 

We can add other information like.. maybe

- [ ] How to add rules, categories , fillers and synonyms etc to _SUSI_
- [ ] A tutorial on how to make a new console service for _SUSI_

**Comment by daminisatya** [comment]
@jig08 Also write a blog post on adding new console services, that would help a lot.

**Comment by jig08** [comment]
@daminisatya , well that is exactly the theme of my next blog post !

**Comment by daminisatya** [comment]
@mariobehling Are you planning to update any doc for the newly added APIs? other than the blog. 
There are many scraper APIs and services which are being added to the server. I feel there must be a proper documentation on all these.

**Comment by jig08** [comment]
If required (least priority) we could use [gitbook.com](https://www.gitbook.com/) to make a lucid documentation.

**Comment by mariobehling** [comment]
Yes, gitbook is nice. Let's collect more content first.
