### ISSUE TITLE
add a request-command-api for p2p load distribution

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_server#73]
a distributed search on loklak peers is restricted by the fact that remote loklak peers do not necessarily have a server port open. To access remote servers, a different way must be choosen.
There shall be a new API servlet where any peer can ask for remote commands. The servlet blocks until a remote command is created within the local peer and the servlet returns with the parameter of that command. A command consist in
- a class name
- the GET properties as string
- an access handle

The remote peer then calls the corresponding class with the given parameters. The result is again transmitted to the peer which submitted the command using the access handle to make it possible that a request is assigned to the result.

Each loklak peer which is not the back-end but has a back-end must then start a scheduler which starts a request to the command API and listens there until either a time-out occurs or a command is submitted.

**Comment by mariobehling** [comment]
Apparently we have outgrown this issue. Closing it therefore.
