### ISSUE TITLE
Research and propose a way to add Susi as a contact/friend to messenger services to enable chat communication

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_server#730]
The idea is to use the existing messenger infrastructure of other services and enable people to talk to Susi through their existing chat client. If Susi could be a contact in Telegram or a friend in Facebook people could talk to her directly. We need to understand what options and APIs there are to implement this.
* [ ] Telegram
* [x] Facebook
* [ ] Whatsapp
* [ ] Line
* [ ] Viber
* [ ] Google Hangout
* [ ] Slack
* [ ] RocketChat
* [ ] WeChat

**Comment by shivenmian** [comment]
@mariobehling also Slack.

**Comment by mariobehling** [comment]
@shivenmian Simple edit the list and add whatever messengers comes to your mind.

I am closing this issue in favor of https://github.com/loklak/asksusi_messenger/issues/1
