### ISSUE TITLE
The readme.md has broken badge images

### ISSUE THREAD

**Issue by daminisatya** [loklak/loklak_server#733]
The following badges are getting the badge images from this [host](https://img.shields.io/) which is currently broken.
- Docker pulls
- twitter badges

Try to get a reliable provider for these badges.

**Comment by daminisatya** [comment]
![selection_205](https://cloud.githubusercontent.com/assets/6227784/17007841/8a75f948-4f09-11e6-8722-93fdb65f2302.png)

**Comment by daminisatya** [comment]
Not a high priority work item, but can invest some time. If the shields.io is up, we can close this issue.

**Comment by sudheesh001** [comment]
Hopefully should be up soon.
Related to: https://github.com/badges/shields/issues/751

**Comment by jig08** [comment]
@daminisatya @sudheesh001 The server is up and the README badges are all fixed, guess we can close the issue for now.
