### ISSUE TITLE
Document Crawler/Parser Services

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_server#739]
As we are adding more parsers, we need to keep an overview about the implementation. E.g. parsing tweets is done by collecting search terms and the search page, but it is unclear how is data collected from Eventbrite? What is tracking the collection of event data?

Please document the following:
* [x] Create a list of implemented services in `docs/parsers.md`
* [x] Describe where the parser code is located and how parsing is triggered
* [x] Describe what other plugins are used to collect data
* [x] Outline the list of collected data
* [x] Describe how data is matched to the loklak data structure
* [ ] Add other relevant details to documentation

**Comment by jig08** [comment]
@mariobehling On it !

**Comment by jig08** [comment]
@mariobehling Started with it here : https://github.com/jig08/loklak_server/blob/documentation-parsers/docs/parsers.md
Feedback appreciated.

**Comment by jig08** [comment]
@mariobehling Feedback pls, is this issue good to close ?

**Comment by mariobehling** [comment]
@jig08 @daminisatya There is a list of points. Please go through each point and click on it, if it has been done.

At the moment, I do not see any info how these parsers are triggered. When do they collect information? How are they started? How is JSoup integrated into loklak now?

**Comment by mariobehling** [comment]
Is this data added to the loklak index? Are we constantly collecting data like we do from twitter? I do not see this.

**Comment by jig08** [comment]
@mariobehling `JSoup` is a java library which has been included in Loklak to parse the HTML pages. 
No, the data in not added to the Loklak index and neither are we constantly collecting data like we do from twitter. 
The connection to the required web page is made upon request (Susi Query or corresponding API call) and the web page is parsed and `JSONObject` returned.

**Comment by sudheesh001** [comment]
I think the documentation for a single level page scraper is actually good and available here https://github.com/jig08/loklak_server/blob/documentation-parsers/docs/parsers.md which was merged in https://github.com/loklak/loklak_server/pull/742

Adding the data to the loklak index is something that's left out, the harvester (i.e. what runs the scraper and pulls data and stores needs to be integrated) @jig08 Can you please open another issue for pushing data collected to an index.

I think this can be closed and the discussion can move there.

**Comment by jig08** [comment]
@sudheesh001 Here it is https://github.com/loklak/loklak_server/issues/751
