### ISSUE TITLE
Implement FOSSASIA API JSON validator to loklak

### ISSUE THREAD

**Issue by zyzo** [loklak/loklak_server#74]
After discussion with @mariobehling and @andibraeu, we think it would be best to have a json validator & converter, when pushing API messages to loklak. Right now, the user needs to provide a geojson data source. This raises several problems : 

* not every source is geojson.
* there's no constraint on the message format.
* most importantly, user is confused about what format they should use. Currently we have a [generator](http://api.fossasia.net/generator/index.html) that generates valid api json format, and our codebase is built around this format. If user provides valid api json, that makes it easy to import data from loklak -> fossasia. 

This doesn't apply solely to FOSSASIA API data, but other sources as well. The new workflow could look like this : 

* user pushes message, specifying that the message is for FOSSASIA API
* loklak_server calls corresponding validator. If the format is correct, call converter to convert into MessageEntry
* save the message into elastic

This model is extensible. I could build a validator layer that takes two files : a json specification ([example](https://github.com/fossasia/api.fossasia.net/blob/master/specs/1.0.1.json)), and a mapping file to map json field <-> MessageEntry field. Then, for each service that we want to provide closer support (like FOSSASIA), we just need to write these 2 files. 

@Orbiter what do you think about this proposal ?

**Comment by zyzo** [comment]
More about JSON schema http://json-schema.org/

**Comment by Orbiter** [comment]
We don not generate a *validator*. And of course not every source is geojson. We have to build a special import mechanism for each json schema that we want to import. When creating such an import mechanism, we look out for common formats where it is worth doing such an import process or we decide that the format is incompatible to your idea of having a message stream.

The FOSSASIA API schema describes events, therefore we can import them. But we need  special import process. Thats the reason I renamed your geojson api servlet into /api/push/geojson.json to have a concept where to add more import processes, like here it would be /api/push/fossasia.json.

We cannot have generic import processes, they must always consider the special background of the content of the json data. Therefore there is no use staring a discussion about validation etc. If we read json, it is alwys validated if the import process was able to import them. But that is not the point. The real point is the *evaluate* the data, not *validate* the data format.

**Comment by zyzo** [comment]
>  If we read json, it is alwys validated if the import process was able to import them. But that is not the point.

I think there's a misunderstanding on what "validation" means. For you it's mean it's a json file. For me, it's that the json is required to contains certain fields, and some fields are required to have certains data type (string, array, object, ..). For example, each geojson object is required to have `properties` and `geometry` field.  it is exactly what JSON schema http://json-schema.org/ does. (this applies to your question in #76 as well).

Without this kind of separate "validation" layer, the developer of future push servlets (geojson, fossasia, iot, ..) will have 2 choices : 

* inject some custom validation code to the servlet, like this [one](https://github.com/loklak/loklak_server/blob/master/src/org/loklak/api/server/GeoJsonPushServlet.java#L96)
* performs no validation, and the client will be met with a vague error message, like "There's an error with your data. Please check", or worse, the stack trace.

> But we need special import process. Thats the reason I renamed your geojson api servlet into /api/push/geojson.json to have a concept where to add more import processes, like here it would be /api/push/fossasia.json.

This strengthens my point : the geojsonpush servlet did two things - validate the data and convert it, if possible, to tweet and user entry. The fossasia servlet will do those 2 things, as well as all the future import mechanisms. What I'm proposing is a generalization of the process, so that each time a new data type is added, instead of writing new push servlet with verbose json parsing java code, only two meta-data files are needed : a json schema, and a mapping file to map json field <-> MessageEntry field.

> We cannot have generic import processes, they must always consider the special background of the content of the json data.

So with this solution, we WILL have a generic import process, but we only "enable" it for wanted data types : geojson, fossasia, ... via a servlet, that initializes and feeds the validator & converter with those two files.
 
This generalization is not easy, but it is a strong and scalable solution. Have said all this, I can simply write a new fossasia push servlet as well. That will result in much less work now, but probably more work later.

So please tell me which direction you want to take. I will implement it ASAP.

**Comment by zyzo** [comment]
The validator is implemented in #77 using json schema validator https://github.com/fge/json-schema-validator. Closing issue.
