### ISSUE TITLE
Including a parser for Github profile

### ISSUE THREAD

**Issue by jig08** [loklak/loklak_server#740]
Developing a console service by implementing a Github profile scraper

**Comment by sudheesh001** [comment]
We can also get a lot of information from the publicly rate limited github APIs without the need of a key, Please look into that too.

**Comment by jig08** [comment]
@sudheesh001 Yes. I was going through [developer.github.com/v3/rate_limit](https://developer.github.com/v3/rate_limit/) .

The rate_limited API can be easily integrated, should I go ahead and make a console service by using them or go the traditional way of parsing the HTML ?

**Comment by jig08** [comment]
> Sudheesh Singanamalla @sudheesh001
The traditional way but have the fallback in case of failure to the regular API 

@sudheesh001 Sounds good. Shall make changes to PR #746  accordingly ...

**Comment by jig08** [comment]
Resolved in PR #746
