### ISSUE TITLE
How to add APIs and Parser for loklak/Susi

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_server#741]
There are a a lot of possibilities to extend Susi. Apart from our own data engine, we can also add APIs and define rules when these APIs are used. There is already the example of the Urban dictionary that we are using.

What are the steps to connect the service with more APIs? And how can we add more parsers and trigger the parsers?

Could you outline a step by step instruction, please?

File to keep instructions: https://github.com/loklak/loklak_server/blob/development/docs/Services.md

**Comment by jig08** [comment]
@mariobehling As a side note, I was planning to write a blog-post on how to add new console services and using them in SUSI next.
Reference: https://github.com/loklak/loklak_server/issues/728

**Comment by Orbiter** [comment]
I have a huge backlog of ideas how Susi unfolds artificial intelligence. Only a subset of the opportunities are opposed through the rules and the existing api implemententations in the console.

There are several ways to be 'intelligent'. One way (which is not an intelligent thing at all in my opinition) is the ability to reproduce information. To do that in Susi whe have the option to access the console service. Adding more data sources to Susi goes throught the definition of data access in a console service.

That means to add data to Susi there are (at least) two steps:
- add console code like this: https://github.com/loklak/loklak_server/blob/development/src/org/loklak/api/search/ConsoleService.java#L181-L194 .. it is virtually possible to attach almost any service which uses a json api as it is common for angular.js. Just debug a web page using angular with firebug, identify the API call from angular and use that in the console code to produce a table-like result.
- The console service should use a 'SusiThought' object to return data from the foreign api. Then an SQL-like query can be made in a Susi rule to extract data from the foreign api through the console. A Susi rule can reflect both, the user input and the API retrieval result in a response line, as an example see https://github.com/loklak/loklak_server/blob/development/conf/susi/susi_knowledge_en.json#L3-L11

When a console service is available this should be used to generate a broad set of possible user input phrases which could be used as a query to ask for content from that resource.

**Comment by mariobehling** [comment]
Yes, it makes sense. What about the data collection in loklak? Querying other services could make Susi relatively slow. How can we continue our way of storing data on loklak and get a certain number of results faster?
