### ISSUE TITLE
General Scraper Console Service

### ISSUE THREAD

**Issue by jig08** [loklak/loklak_server#743]
Converting the general scraper ([loklak/loklak_server/src/org/loklak/api/search/GenericScraper.java](https://github.com/loklak/loklak_server/blob/development/src/org/loklak/api/search/GenericScraper.java)) to a console service for easy accessibility in _SUSI SU_

**Comment by daminisatya** [comment]
@jig08 I feel this must be on hold, as of now the scraper is not doing the expected job. I will let you know when I update the Generic scraper.

**Comment by jig08** [comment]
@daminisatya Okay, cool.

**Comment by jig08** [comment]
@daminisatya Okay, let know when it is updated.. I'll make a console service for the same.

**Comment by jig08** [comment]
@daminisatya Is the `generic web scraper` ready to be implemented as a console service now ?

**Comment by daminisatya** [comment]
@jig08 i dint submit any patch yet

**Comment by daminisatya** [comment]
@jig08 please refer #598. involes that extra work and engineering.

**Comment by daminisatya** [comment]
@jig08, its interesting to see this scraper as a console service. Cause i thought its main aim is to convert the source of webpages into structured data. Which is simply straighy forward. Can you give me a use of susi using it? Like what sort of questions it can ask? To the sevice, we need to give the URL of the website , which is similar to diffbot. Are you thinking about questions like ```susi give the structured data from http://google.com```?  Something like that?  If i was a User and had a requirement to convert a particular website into Json data, i would head towards ```webscraper``` app, which was solely developed for this.

**Comment by jig08** [comment]
@daminisatya Sounds legit. 
Was just planning to have all the scrapers as a console services in case of requirement by _SUSI_ at a later stage. If not necessary, I guess we can close this issue then ?

**Comment by jig08** [comment]
Closing this issue as the console service for this is no longer required, apparently :)

@daminisatya :v:
