### ISSUE TITLE
Propose and implement Amazon API

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_server#750]
There are product APIs (https://affiliate-program.amazon.com/gp/advertising/api/detail/main.html) and a number of other APIs (https://developer.amazon.com/). Which ones could be relevant for Susi?

* [x] List relevant APIs in this issue
* [ ] As a start implement an API that offers information on products

**Comment by shivenmian** [comment]
@mariobehling There's a full list of their APIs on their API Gateway. Had to make an AWS account for it. Filled the company as FOSSASIA but they were asking me for credit card info. Skipped that part. They said account will take up to 24h to activate.

**Comment by shivenmian** [comment]
@mariobehling They actually don't have a consolidated list of APIs anywhere. It's all in random places, but from what I could find, the Product API seems to be the only one of use.

**Comment by mariobehling** [comment]
@shivenmian Ok, good. So, please proceed to integrate the Product API.

**Comment by shivenmian** [comment]
@mariobehling do you want me to use the API or just scrape Amazon?

**Comment by mariobehling** [comment]
Use the API. Scraping Amazon is too complex and need to be planned out in detail. Use the API that where we could add our affiliate key. So, this could be one possibility to earn an income with Susi.

**Comment by shivenmian** [comment]
@mariobehling fixed in #800
