### ISSUE TITLE
Pushing data collected from other scrapers to an index

### ISSUE THREAD

**Issue by jig08** [loklak/loklak_server#751]
Currently the data collected from scrapers is not stored anywhere. 

The aim is to push the data collected from each of the scraper to an index , i.e. integrating the harvester.

---

_EDIT:_ Pushing scraped data for :- 
- [ ] Github Scraper
- [ ] Wordpress Crawler
- [ ] EventBrite Crawler

**Comment by sudheesh001** [comment]
I think the best way to have this would be to have a generic `pushtoindex` and `createindex`.
The `pushtoindex` could potentially be used by other scrapers in the future.

**Comment by jig08** [comment]
+1

**Comment by DengYiping** [comment]
I implement a wrapper class. Use it as a builder, and finally `persisit()` to store the data. @jig08

**Comment by jig08** [comment]
@DengYiping Using `DAOWrapper.builder().addField(key, value).persist();` for each field in `SUSIThought` shall work fine in case of addition.

Because `user_name` is unique, we can use `setUser()` method to push unique entries and then use `existsUser()` method to implement a check before scraping ?

**Comment by DengYiping** [comment]
@jig08 `setUserid()`

**Comment by jig08** [comment]
@DengYiping Oh Yes, implementing it ..

**Comment by jig08** [comment]
_Updates:_

* Pushing of Data Implemented using the DAOWrapper
* Retrieval of Data to be tested
* Overall testing left

@DengYiping Is helping out to do the needful.

**Comment by mariobehling** [comment]
Some progress had been made on this. Anyone following up on this topic should be willing to work on it.
