### ISSUE TITLE
[Loklak] Improve the example URLs in API documentation

### ISSUE THREAD

**Issue by daminisatya** [loklak/loklak_server#753]
There are few example URLs which point towards localhost, which is not suggested. The preferred change is to point all the URLs to loklak.org.

**Comment by daminisatya** [comment]
A quick fix can be made, cause without a local setup the URLs point towards 404.

**Comment by mariobehling** [comment]
@daminisatya could you just make it related to the local set up, please, e.g. ./api or whatever is the relevant internal link?

**Comment by sudheesh001** [comment]
Good catch, this has been pending since quite some time. There are a few APIs which are restricted and need ot be localhost only (eg. `settings.json`). Leaving the localhost only ones we need to move all to loklak.org whereever it supports
