### ISSUE TITLE
Add a /vis/ API for the piecharts parsing.

### ISSUE THREAD

**Issue by sudheesh001** [loklak/loklak_server#756]
Similar to how we have the /vis/map.png, we should also be haivng /vis/piechart.png which on passing the required JSON generates the image and provides to the user.

**Comment by shivenmian** [comment]
@sudheesh001 I recommend [charts4j](https://code.google.com/archive/p/charts4j/).

**Comment by Orbiter** [comment]
👎 
There are really good libraries to draw graphs, doing so in a server-side application is not only a lot of work, will produce less beautiful images but also does not solve any problem that I see makeing graphs.

**Comment by mariobehling** [comment]
@sudheesh001 Why should we use this instead of libraries? Is there any advantage for messenger services? Is it easier to integrate that in the FB messengers? Please tell us some more background.

**Comment by sudheesh001** [comment]
@Orbiter This would be used in places where susi cannot send interactive charts, like to accounts consuming susi services from chat clients like Whatsapp, Telegram, Slack, Facebook Messenger. The susi's data result will be converted into png images so that these services can see the piecharts, on the susi application as a whole, we'll behaving interactive charts either with d3 or highcharts.
