### ISSUE TITLE
Validate JSON data against JSON schema

### ISSUE THREAD

**Issue by zyzo** [loklak/loklak_server#76]
This is part of #74. The aim is to find a way to validate any given json data, against a given JSON schema. Any suggestion would be helpful.

A quick google lookup gives only two results : 

* https://github.com/fge/json-schema-validator (which seems great, but no longer maintained)
* implement it myself

**Comment by Orbiter** [comment]
I don't understand why you want to validate json when importing json. Either you can import that json, then the json is valid, or you cannot import that json, then it is not valid. Please don't let us get philosophical here to find a problem and answers to a problem that does not exist as a real task. Where is the actual task to ask such a question?
