### ISSUE TITLE
[Loklak Apps Page] IOT category not able to filter the app under it.

### ISSUE THREAD

**Issue by daminisatya** [loklak/loklak_server#762]
When clicked on the left nav bar for filtering the apps according to the categories the IOT section is not able to filter it. 

![selection_243](https://cloud.githubusercontent.com/assets/6227784/17221164/42747d9c-5510-11e6-834d-4720c5b2588a.png)

**Comment by mariobehling** [comment]
Thanks, but let's focus on Susi and get something running.
