### ISSUE TITLE
Is it possible to time each keystroke into the system?

### ISSUE THREAD

**Issue by smokingwheels** [loklak/loklak_server#766]
No Rush just have a look when you have time.
I wrote a program about money after I had Finished making my car a daily driver.
I'm unsure if you can time a keystrokes in Java.
You would then feed this information into parts of this program at [Western Blue Sky Mining](http://westernblueskymining.tripod.com/)
Happy to answer any questions.
Have Robot keyboard in arsenal, asleep at the moment, if required testing learning is needed. @smokingwheels on twitter.

**Comment by DengYiping** [comment]
@smokingwheels I do not get what you mean, and how it gonna affect loklak. Please explain it more specifically.

**Comment by smokingwheels** [comment]
@DengYiping Could you reference you education and experience in **general** terms so I have some idea where to start?
This is the document I used to design mine .[Here](http://www.computer-engineering.org/ps2protocol/)

**Comment by sudheesh001** [comment]
@smokingwheels Are you referring to the input from the console ? timing the duration of each keystroke, that is definitely possible, How can something like this affect loklak ?

**Comment by Orbiter** [comment]
Keystrokes can be measured with javascript. But we don not have an application for this. This is really OT.
