### ISSUE TITLE
Susi Rule-Score Hierarchy Brainstorming

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_server#767]
For Susi's score system, we need a hierarchy to assign good score values to the rules. To do so we should develop a hierarchy to find an easy system that can be used to assign scores to new rules.

Please add your suggestions below, as you add your ideas we will change a score hierarchy  suggestion below.

### Primary Consideration: Purpose
We have three kinds of purposes for Susi answers:
- (A) to answer on the users question
- (Q) to ask a question to the user in the context of an objective within Susi's planning to do a conversation
- (R) to answer on an answer of the user within the planning of Susi to do a conversation.
It appears clear that answers in the context of a Susi conversation strategy should have higher priority.

### Secondary Consideration: Patterns
We have two kinds of rules: such with patterns and others without. The meaning of such rules are:

without any pattern:
- (P-D) default answers if no other rule applies
- (P-O) overruling of other rules with patterns which would apply, but should not (in that exceptional case)

with pattern(s):
- (P+D) variables in patterns are ignored, a default answer if no other rule applies for that pattern
- (P+O) variables in patterns are ignored, an overruling answers for other patterns that apply
- (P+C) variables in pattern should be used for computation
- (P+LR) variables in pattern should be used for retrieval in internal Susi's log (reflection memory)
- (P+IR) variables in pattern should be used for retrieval in internal databases
- (P+ER) variables in pattern should be used for retrieval in external databases
- (P+LS) variables in pattern should be stored in Susi's memory to be used for reflection later
- (P+IS) variables in pattern should be stored in internal databases to be used for retrieval later
- (P+ES) variables in pattern should be stored in external databases to be used for retrieval later

### Combinations of Purpose and Pattern  Considerations:
To combine the various Pattern and Purpose types, we write the abbreviations of these items together, separated with a slash '/'. For example, we want to answer on a question of the user "Are you happy" with "Yes!, Are you happy as well?" which would be an rule of type Q/P-O. The combination of the  consideration types give 11x3=33 possibilities.

## Score Hierarchy
I believe there should be
- score(R) > score(Q) > score(A):
  to do a steering of conversations within a conversation plan.
- score(P-O) > score(P+?) > score(P-D):
  overruling of pattern-directed answers and default answers in case of pattern fail
- score (P+C) > score(P+?S) > score(P+?R):
  storing of information (= learning) is more important than answering
- score(P+L?) > score(P+I?) > score(P+E?):
  using local information is primary above external information. Reflection is most important.

This produces the following order (with decreasing score, first line has highest sore):

- Overruling of patterns:
 - R/P-O
 - R/P+O
 - Q/P-O
 - Q/P+O
 - A/P-O
 - A/P+O

- Pure computational tasks:
 - R/P+C
 - Q/P+C
 - A/P+C

- Answer on an Answer of the user using patterns, possibly learning, otherwise retrieving data:
 - R/P+LS
 - R/P+IS
 - R/P+ES
 - R/P+LR
 - R/P+IR
 - R/P+ER

- Asking the user a question with the purpose of learning with the users answer:
 - Q/P+LS
 - Q/P+IS
 - Q/P+ES
 - Q/P+LR
 - Q/P+IR
 - Q/P+ER

- Just giving an answer to the question of the user:
 - A/P+LS
 - A/P+IS
 - A/P+ES
 - A/P+LR
 - A/P+IR
 - A/P+ER

- Fail-over if no other rule apply to just answer anything, but try to start a new conversation:
 - R/P-D
 - R/P+D
 - Q/P-D
 - Q/P+D
 - A/P-D
 - A/P+D

**Comment by DengYiping** [comment]
Actually I believe that natural language processing will be a good idea. Instead of using our own rule, we will tuning a NLP engine and classify the question.

**Comment by smokingwheels** [comment]
What about Text to Speech on the output, just an idea?  
[Here ](http://freetts.sourceforge.net/docs/index.php)

**Comment by jig08** [comment]
+1

Once _SUSI_ is stabilized and has a wide scope, I think this is a good idea to go with..

**Comment by Orbiter** [comment]
@DengYiping NLP engines are complex, large, dictionary (and license)-dependent beasts which do not give much benefit in my opinion. I developed Susi's rule system as a direct approach to make it 'greedy' and easy.
@smokingwheels on a mobile app: sure!

**Comment by daminisatya** [comment]
@Orbiter @smokingwheels along with TTS, it would be cool to have STT too !

**Comment by Orbiter** [comment]
Using the classification as developed above as declaration elements in rules would give us the opportunity to compute a score automatically. Lets see what we need for that:

- ```purpose: {answer, question, reply}``` purpose would have to be defined
- ```pattern: {false, true}``` with/without pattern could be computed from the rule string
- ```prior: {false, true}``` overruling (prior=true) or default (prior=false) would have to be defined
- ```op: {computation, retrieval, storage}``` the operation could be computed from the rule string
- ```io: {ram, local, remote}``` the storage location can be computed from the rule string
- ```subscore``` a score in a small range which can be used to distinguish rules within the same categories

That would lead to six properties where only three of them have to be declared: purpose, prior and subscore.

**Comment by mariobehling** [comment]
As we split the Susi project I am closing this issue.
