### ISSUE TITLE
Fresh clone from Master wont start.

### ISSUE THREAD

**Issue by smokingwheels** [loklak/loklak_server#771]
Fresh clone from Master 3 times tested.
Log file Zero bytes.
No rush yet.
Minor spelling error no problem.

BUILD SUCCESSFUL
Total time: 7 seconds
root@Debian:/usr/loklak_server# bin/start.sh
starting loklak
cat: data/startup.tmp: No such file or directory
bin/start.sh: 47: [: =: unexpected operator
loklak server failed to start. See data/loklag.log for details
root@Debian:/usr/loklak_server#

**Comment by jig08** [comment]
@smokingwheels I tried cloning, building and running the `master` branch of Loklak and it works just fine for me.

```
jigyasa@jigyasa-HP-Pavilion-15-Notebook-PC:~/masterLoklak$ git clone https://github.com/loklak/loklak_server
Cloning into 'loklak_server'...
remote: Counting objects: 43272, done.
remote: Compressing objects: 100% (33/33), done.
remote: Total 43272 (delta 7), reused 0 (delta 0), pack-reused 43238
Receiving objects: 100% (43272/43272), 197.85 MiB | 2.78 MiB/s, done.
Resolving deltas: 100% (34929/34929), done.
Checking connectivity... done.
jigyasa@jigyasa-HP-Pavilion-15-Notebook-PC:~/masterLoklak$ cd loklak_server/
jigyasa@jigyasa-HP-Pavilion-15-Notebook-PC:~/masterLoklak/loklak_server$ git branch -a
* development
  remotes/origin/HEAD -> origin/development
  remotes/origin/development
  remotes/origin/gh-pages
  remotes/origin/master
jigyasa@jigyasa-HP-Pavilion-15-Notebook-PC:~/masterLoklak/loklak_server$ git checkout master 
Branch master set up to track remote branch master from origin.
Switched to a new branch 'master'
jigyasa@jigyasa-HP-Pavilion-15-Notebook-PC:~/masterLoklak/loklak_server$ ant
Buildfile: /home/jigyasa/masterLoklak/loklak_server/build.xml

init:

build:
    [mkdir] Created dir: /home/jigyasa/masterLoklak/loklak_server/classes
     [echo] loklak: /home/jigyasa/masterLoklak/loklak_server/build.xml
    [javac] Compiling 183 source files to /home/jigyasa/masterLoklak/loklak_server/classes
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.

BUILD SUCCESSFUL
Total time: 7 seconds
jigyasa@jigyasa-HP-Pavilion-15-Notebook-PC:~/masterLoklak/loklak_server$ bin/start.sh
starting loklak
loklak server started at port 9000, open your browser at http://localhost:9000
jigyasa@jigyasa-HP-Pavilion-15-Notebook-PC:~/masterLoklak/loklak_server$ 
```


As it says `loklak server failed to start. See data/loklag.log for details` could you kindly let know what exactly the logs say ? Maybe we can have a better insight.

**Comment by jig08** [comment]
@smokingwheels 

As it says `loklak server failed to start. See data/loklag.log for details` could you kindly let know what exactly the logs say ? Maybe we can have a better insight.

**Comment by smokingwheels** [comment]
@jig08 The data/loklak.log file is empty and also Cloud PC Loklak had never been installed before.
I am not asking you to Format anything you have.
It also has been running Yacy for over 20 days but Yacy is stopped.
I'm like thingking usual error?

**Comment by smokingwheels** [comment]
I managed to clone a copy locally and I had and upload to VM.
My Susi's address is [Here](http://mysusi.remote.mx/)
I have not changed any of the default rules Please Try.

**Comment by jig08** [comment]
@smokingwheels With `rules` you mean that Susi is not answering properly ? I didnt quite get your issue.

**Comment by smokingwheels** [comment]
@jig08 I had a clean system and cloned from the master branch and it did not start.
I’m not a man of many words.
I overcome the problem (Work around) and is now working then invited people to try it.
Hope that helps.

**Comment by treba123** [comment]
For some errors (when the log backend doesn't even start) there's a second log file at /tmp/loklak_(date) (we should probably move that somewhere or atleast give a hint).
Can you check that?

Also, i'm not sure if running as root is currently a good idea, as we don't yet have a mechanism to drop previleges at runtime.

**Comment by smokingwheels** [comment]
@treba123 Sorry Ive had to send the razor gang around to my cloud9, so I will think about when time permits.
I have dug out an old P4 1.8 GHz 512 MB Box and Loaded Debian 8.5 and have Loklak Server running currently in private mode it seems to work ok.
Cheers.

**Comment by sudheesh001** [comment]
This is good to close, since it's running and there are no problems of running the code from master / development branches.
