### ISSUE TITLE
Add rules wrt Wordpress Scraper

### ISSUE THREAD

**Issue by jig08** [loklak/loklak_server#781]
_SUSI_ can now use the console service for wordpress scraper as [http://loklak.org/api/console.json?q=SELECT * FROM wordpress WHERE url='http://ishothim.com/';](http://loklak.org/api/console.json?q=SELECT%20*%20FROM%20wordpress%20WHERE%20url=%27http://ishothim.com/%27;)

Task is to implement new rules wrt Wordpress Scraper to widen the scope of _SUSI_.

**Comment by mariobehling** [comment]
What does wrt mean?

**Comment by jig08** [comment]
@mariobehling **WRT** is an abbreviation that stands for **with respect to** or **with regard to**.
