### ISSUE TITLE
JavaFX not bundled with OpenJDK

### ISSUE THREAD

**Issue by treba123** [loklak/loklak_server#782]
https://github.com/loklak/loklak_server/commit/2f8184b2ba1c1c7dc4c48f051aac3182bec0a5ef imports JavaFX, which is fine for oracleJDK, which bundles it with jdk8, but not for openjdk, which is used by many linux distributions.

As the used functionality is rather trivial, we should better replace that lines.

**Comment by DengYiping** [comment]
@treba123 Thanks for mention. Fix is here: #788
