### ISSUE TITLE
[Susi] Pie chart response must be made more generic

### ISSUE THREAD

**Issue by daminisatya** [loklak/loklak_server#786]
Here is the sample JSON response giving a Pie chart response. 

```
{
  "session": {"identity": {
    "type": "host",
    "name": "10.67.93.57",
    "anonymous": true
  }},
  "count": 1,
  "answers": [{
    "metadata": {
      "hits": 21,
      "offset": 0,
      "count": 2
    },
    "data": [
      {
        "percent": 50,
        "president": "hillary2016"
      },
      {
        "percent": 50,
        "president": "trump2016"
      }
    ],
    "actions": [
      {
        "expression": "I believe the next president will be hillary2016 with a likelihood of 50.0 percent but I a not sure.",
        "type": "answer"
      },
      {
        "total": 100,
        "unit": "%",
        "type": "piechart",
        "value": "percent",
        "key": "country"
      }
    ]
  }]
}
```
The key along with the percentage must be made more generic to either name or label. ``` "president": "hillary2016"```

**Comment by daminisatya** [comment]
followup of [#5](https://github.com/loklak/asksusi_com/issues/5)

**Comment by Orbiter** [comment]
I don't understand what you need exactly when asking do be more generic. In this example the key shoud denote the word "president" where it currently contains the value "country". That is simply an error in the rule definition.

**Comment by sudheesh001** [comment]
@Orbiter I think @daminisatya was referring to
```json
"data": [
      {
        "percent": 50,
        "president": "hillary2016"
      },
      {
        "percent": 50, 
        "president": "trump2016"
      }
    ],
```
As you mentioned correctly, the `key` will change from `president` to `country` or depending on context, but the data set passed for charting visualizations so that we can leverage the library needs data in a `name` and `y` format thus requiring as
```json
"data": [
      {
        "y": 50,
        "name": "hillary2016"
      },
      {
        "y": 50, 
        "name": "trump2016"
      }
    ],
```
and as mentioned the `"key":"president"` so that we can pull the information to display as
```
|- For each item with the key <value>
|- the data object to visualize is <y>% for <name>
```

**Comment by Orbiter** [comment]
I still don't see any requirement for implementation changes. The 'percent' key name can also be changed in the rule using a different percent name assignment in the console query.

**Comment by Orbiter** [comment]
However, the piechart must have that flexibility, not the rule. The rule fully declares what should be shown in the piechart.
