### ISSUE TITLE
Other Susi's get redirected to asksusi.com 

### ISSUE THREAD

**Issue by smokingwheels** [loklak/loklak_server#798]
I have extra 2 installs = 3 
The link susi when click on in the apps page redirects to asksusi.com.
Haven’t a clue where to start!

**Comment by sudheesh001** [comment]
Similar issue here. https://github.com/loklak/asksusi_com/issues/14#issuecomment-238265855

The susi app has been moved out of loklak server and kept standalone, hence the redirect.
