### ISSUE TITLE
[Social Wall] Images are not displayed on the cards

### ISSUE THREAD

**Issue by daminisatya** [loklak/loklak_server#803]
Social wall is a wonderful twitter wall with proper masonry layout. There is a small bug where in the code is not able to display the images from the tweets. 

![selection_275](https://cloud.githubusercontent.com/assets/6227784/17468099/20dc64f8-5d42-11e6-95f7-1eeb0a2dad66.png)

**Comment by mariobehling** [comment]
Apps should go into a separate repository to keep the server set up neat. Therefore closing it.
