### ISSUE TITLE
[Weibo] Evaluate the source code under script tags

### ISSUE THREAD

**Issue by daminisatya** [loklak/loklak_server#805]
The Weibo source code is under the ```<script>``` ```</script>``` . The current weibo user scraper must compile the source code for getting the proper html.

**Comment by daminisatya** [comment]
@jig08 Please point out the possibilities.

**Comment by jig08** [comment]
@daminisatya Maybe you should utilize the helper function implemented (here: [WeiboInfoScraper.java](https://github.com/loklak/loklak_server/blob/development/src/org/loklak/harvester/WeiboInfoScraper.java) ) by @DengYiping to scrape information within the `<script>...</script>` tags

**Comment by DengYiping** [comment]
Please close this issue.
