### ISSUE TITLE
[Scrapers] The invalid URLs must be handled gracefully 

### ISSUE THREAD

**Issue by daminisatya** [loklak/loklak_server#807]
As of now the scrapers which are implemented are able to scrape data for a particular URL formats. If in case there is an unsupported input, the output should be handled gracefully instead of throwing a ```server error``` 

Here's a sample erroneous output on using genericscraper. 
![selection_276](https://cloud.githubusercontent.com/assets/6227784/17502772/636677f2-5e08-11e6-8eef-68d8e761afc5.png)

This is the case with every scraper, there must be a meaningful error message along with the expected url format.

**Comment by jig08** [comment]
+1
