### ISSUE TITLE
Console Service Source URL Collection

### ISSUE THREAD

**Issue by Orbiter** [loklak/loklak_server#808]
There are a lot of angular.js-driven web pages out there which we all could use as data source for Susi, implemented as Console Service. Lets collect a large number of urls as suggestion for add-on implementations. Please just add the host names, we can identify the API url later.

**Comment by Orbiter** [comment]
https://www.wolframalpha.com/
http://dict.leo.org/
http://stackoverflow.com/
https://answers.yahoo.com/
http://stackexchange.com/
https://voat.co/

**Comment by shivenmian** [comment]
@Orbiter @sudheesh001 What about wit.ai?

**Comment by smokingwheels** [comment]
@shivenmian There is a lot of terms and conditions that come with it.

**Comment by smokingwheels** [comment]
Is this What you are looking for?[
Here](http://techslides.com/over-2000-d3-js-examples-and-demos) 
Bubble visualisation of any web page [Here](http://www.infocaptor.com/bubble-my-page?url=http://loklak.org)

**Comment by mariobehling** [comment]
This is relevant for SUSI. Closing it for loklak.
