### ISSUE TITLE
Registering missing servelets in loklakserver.java

### ISSUE THREAD

**Issue by jig08** [loklak/loklak_server#813]
It has been observed that many services which have been successfully implemented as console services are not registered individually in `loklakserver.java`

- [ ] Github Profile Scraper
- [ ] Wordpress Scraper
- [ ] Instagram Scraper
- [x] RSS Reader
- [x] Event Brite Scraper
- [ ] Wiki Geo Data Provider
- [ ] Location Wise Time Provider
- [ ] Time an Date Service
- [x] Meetups Scraper

**Comment by shivenmian** [comment]
Er, they are there on loklakserver.java. look closely

**Comment by jig08** [comment]
@shivenmian Where to look closely ?

**Comment by shivenmian** [comment]
Check lines 490-526 and 535-593 in https://github.com/loklak/loklak_server/blob/development/src/org/loklak/LoklakServer.java. Servlets are registered here.

**Comment by jig08** [comment]
@shivenmian I dont see any `servletHandler.addServlet(..)` for them

**Comment by shivenmian** [comment]
Check lines 527-532, they are added in a loop.

**Comment by jig08** [comment]
Also, adding them in `Class<? extends Servlet>[] services = new Class[]{...}` is left, which I am pushing in the next commit.

**Comment by shivenmian** [comment]
No you're doing it wrong.

**Comment by shivenmian** [comment]
Just add the 5 remaining servlets on the list inside the Class extends servlet and you are done.

**Comment by jig08** [comment]
@shivenmian 
```
        for (Class<? extends Servlet> service: services)
            try {
                servletHandler.addServlet(service, ((APIHandler) (service.newInstance())).getAPIPath());
            } catch (InstantiationException | IllegalAccessException e) {
                e.printStackTrace();
            }
```

I get the point that they are being added in the loop. But I guess I need to add them in the list of `services` at least ?

**Comment by jig08** [comment]
@shivenmian That's what I meant, rectifying in the next commit.

**Comment by shivenmian** [comment]
490-526 exactly is the list of services. Just add them there.

**Comment by jig08** [comment]
@shivenmian Got that already :)
Thanks.

**Comment by jig08** [comment]
@shivenmian A new PR has been opened https://github.com/loklak/loklak_server/pull/815/files
