### ISSUE TITLE
Open Loklak in a non-deamon mode

### ISSUE THREAD

**Issue by DengYiping** [loklak/loklak_server#817]
Loklak is by default running on the background, and use log4j to do logging. However, if we could bring it to the front, and print the log directly, we will be able to use something like `docker logs`, and debugging will be easier.

**Comment by niccokunzmann** [comment]
To use `docker logs`, we can use `tail -f data/loklak.log` to monitor the log and let it look like it runs in foreground.

Once #861 is merged, I want to do this.

**Comment by DengYiping** [comment]
@niccokunzmann  Great suggestion. Please add a new Dockerfile and shell script to do so

**Comment by niccokunzmann** [comment]
@DengYiping Have a look at #867. It enables `docker logs`. Does it close the issue?  
@sudheesh001 Suggests that I create a commit which closes this issue.  
I am not sure.
