### ISSUE TITLE
Add DAO mock for testing

### ISSUE THREAD

**Issue by DengYiping** [loklak/loklak_server#818]
Right now me and @jig08 are developing scrapers. I implemented a DAO wrapper, which allows us to send non-Twitter data to backend.

 However, DAOWrapper do not have <b>any test because we cannot use DAO without startup.</b> Maybe considering adding a DAO mock class to the test folder, so that we could write unit test and do continuous integration.

**Comment by jig08** [comment]
+1.

Yes, there have been prevelant issues of testing the users's presence for instance.

@Orbiter Any help,  pls?

PS: Follow up of Issue #751

**Comment by jig08** [comment]
@Orbiter Help required, pls.

**Comment by mariobehling** [comment]
As we are not focusing on external scrapers currently, I am closing this issue as "wontfix". Anyone re-opening it should be willing to work on it.
