### ISSUE TITLE
Follower threshold count

### ISSUE THREAD

**Issue by aneeshd16** [loklak/loklak_server#82]
This corresponds to the follower threshold count mentioned here:
![image](https://cloud.githubusercontent.com/assets/5436027/8819183/56e2107e-3067-11e5-905a-65fd59e9d1bb.png)

It can be of the form of an extra parameter `follower_count=100`

**Comment by mariobehling** [comment]
Actually still an important feature as it would allow us to answer questions like "show my accounts that tweeted the hashtag xyz with more than 100 followers"
