### ISSUE TITLE
Console Errors when Loklak is running in Windows.

### ISSUE THREAD

**Issue by smokingwheels** [loklak/loklak_server#821]
Errors when starting and running in Windows.

Possible solution [Here](http://stackoverflow.com/questions/7896773/instantiationexception-on-simple-reflective-call-to-newinstance-on-a-class) Not sure though.
`<Picked up JAVA_TOOL_OPTIONS: '-Dfile.encoding=UTF-8'
ERROR StatusLogger No log4j2 configuration file found. Using default configurati
on: logging only errors to the console.
java.lang.InstantiationException
at sun.reflect.InstantiationExceptionConstructorAccessorImpl.newInstance
(Unknown Source)
at java.lang.reflect.Constructor.newInstance(Unknown Source)
at java.lang.Class.newInstance(Unknown Source)
at org.loklak.LoklakServer.setServerHandler(LoklakServer.java:538)
at org.loklak.LoklakServer.main(LoklakServer.java:245)
java.lang.InstantiationException
at sun.reflect.InstantiationExceptionConstructorAccessorImpl.newInstance
(Unknown Source)
at java.lang.reflect.Constructor.newInstance(Unknown Source)
at java.lang.Class.newInstance(Unknown Source)
at org.loklak.LoklakServer.setServerHandler(LoklakServer.java:538)
at org.loklak.LoklakServer.main(LoklakServer.java:245)>`

Errors when doing a JSON search.  [Here](http://sw.remote.mx/lokjson.txt)
Its quite long. I can past it here if needed.
Updated 6:14 14 Aug 2016
A work around could be if the JSON queries has a space add "%2520". or similar

**Comment by sudheesh001** [comment]
@smokingwheels I did a fresh install on a windows 10 system and it seems to be working fine. Just in case, can you do the following, generate the jar for loklak and execute the jar.
```
ant jar
java -jar dist/loklak.jar
```

Does this still throw an error for you ?

**Comment by smokingwheels** [comment]
Ok will give it a go in a few weeks, many thanks.

**Comment by mariobehling** [comment]
Thanks. Closing this for now then. @smokingwheels Please reopen if issue persists later. Cheers.
