### ISSUE TITLE
RSS feeds missing channel elements "description" and "link"

### ISSUE THREAD

**Issue by JeremyRand** [loklak/loklak_server#828]
RSS feeds from Loklak don't seem to be valid RSS, according to the W3C Feed Validation Service.  For example, see the following validation result: https://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Floklak.org%2Fapi%2Fsearch.rss%3Fq%3Dfrom%3Ayacy_search

It shows the following 2 errors:

```
Missing channel element: description

Missing channel element: link
```

I believe, but am not certain, that this is responsible for the feeds being rejected by Icedove.

**Comment by AdiChat** [comment]
This issue could be closed as #845 has taken care of this. 
@shivenmian
