### ISSUE TITLE
Please update Elasticsearch 

### ISSUE THREAD

**Issue by frankenstein91** [loklak/loklak_server#842]
The newest version of kibana requires Elasticsearch 2.4.0, please update.

At the moment it is Elasticsearch v2.3.5.

Thank you 

![error](https://cloud.githubusercontent.com/assets/2527348/18401175/7c843744-76d9-11e6-9854-0d3da9adbe2c.PNG)

**Comment by frankenstein91** [comment]
i also can't connect with elasticsearch-head.
No error shown.

**Comment by MisterX2000** [comment]
Same problem here

**Comment by Orbiter** [comment]
https://github.com/loklak/loklak_server/commit/fe7bd2a8b9852ee64b9699b8927a3c775e68c4fe
