### ISSUE TITLE
Propose alternatives to live queries to reduce load on server and increase result speed.

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_server#846]
Currently we query loklak for results live. This works well, if there is little load on the server, but also here results are not always superfast.

How can we speed up the result output? What about high load? What options do we have?
- Is there a way to cache common requests
- Could we make something like an index available instead of querying the live system? 
  - E.g. we give access to search the last dump. In this case we could create a new dump that can be searched e.g. every 5 hours. - We can then display something "Search results found on social networks until e.g. 17:25 UTC"
  - If there are no results for a given term we show "Unfortunately there are no results for this search yet, but we will start to index this search term now. Please check back later."

**Comment by Orbiter** [comment]
offline-search for specific time ranges in small indexes are already implemented. Example:

```http://loklak.org/api/search.json?timezoneOffset=-120&source=cache&q=potus+since%3Ahour```
searches for "potus" only in the search index which contains only tweets from the last hour.

We have specific small indexes for the time range "hour", "day" and "week". The limitation to the index-only (what you call cache) is actually addressed with the option ```source=cache```.

In contrast to the requirement, searching for somethin _only_ online can be addressed with i.e. 
```
http://loklak.org/api/search.json?timezoneOffset=-120&source=twitter&q=potus
```
This is neither fast nor slow.
When doing a search without any option, online and cached search is done concurrently.

**Comment by mariobehling** [comment]
> We have specific small indexes for the time range "hour", "day" and "week". The limitation to the index-only (what you call cache) is actually addressed with the option source=cache.

So, how about we implement this as a standard search in loklak_search and display a message "there are no results yet available, please check back later"?

**Comment by Orbiter** [comment]
the standard is currently, to search first in hour, then, if no results are found in hour and then in week. That happens if no modifier is given.

Anothen speed up is, to prevent the waiting for cached/internal search results if the remote (twitter) search result is faster. That is the case on loklak.org. The latest fix implents this.

**Comment by mariobehling** [comment]
Ok, understand.

Currently I get the result of http://loklak.fossasia.org/search?query=potus in about 4-5 seconds only.

**Comment by mariobehling** [comment]
Closing this as a number of specific issues are tackling this as well.
