### ISSUE TITLE
Loklak docker image stops

### ISSUE THREAD

**Issue by niccokunzmann** [loklak/loklak_server#849]
When I start lokak with 

```
docker start services_loklak_1
```

I get this output with `docker ps -a`:

```
067f2d546383        mariobehling/loklak:latest   "bin/start.sh"           14 minutes ago      Exited (0) 4 seconds ago                                              services_loklak_1
```

To me it looks like the docker image always closes. Can anyone reproduce this?

**Comment by mariobehling** [comment]
@niccokunzmann The build is failing.

On dockerhub it shows: Build failed: The command '/bin/sh -c ant' returned a non-zero code: 1

I have invited you to dockerhub. Please help to resolve this issue.

**Comment by niccokunzmann** [comment]
@mariobehling my name on dockerhub is niccokunzmann. Currently, I do not have administrative access to [https://hub.docker.com/r/mariobehling/loklak/](mariobehling/loklak).
