### ISSUE TITLE
New install jumps to 503 error on first lot RSS queries 

### ISSUE THREAD

**Issue by smokingwheels** [loklak/loklak_server#85]
Running Deb 8 64 bit Server installed 26-7-15 1:00 pm +8
Using a pile of wget commands the first run through gave http error 503 the second time I ran deb2.sh it worked as intended but with the & and time zone removed because wget does not seem to like that. 
I was intending to do a load test some time next month with a few of my forward peers.

Commands in terminal batch file.
wget http://192.x.x.x:9000/api/search.rss?q=smokingwheels

One fix I have used in the past is do a JSON search First.

Terminal Dump.
--2015-07-26 13:09:54--  http://192.168.2.108:9000/api/search.rss?q=youtube%0D
Connecting to 192.168.2.108:9000... connected.
HTTP request sent, awaiting response... 503 your (192.168.2.108) request frequen
cy is too high
2015-07-26 13:09:54 ERROR 503: your (192.168.2.108) request frequency is too hig
h.

--2015-07-26 13:09:54--  http://192.168.2.108:9000/api/search.rss?q=instagram%0D
Connecting to 192.168.2.108:9000... connected.
HTTP request sent, awaiting response... 503 your (192.168.2.108) request frequen
cy is too high
2015-07-26 13:09:54 ERROR 503: your (192.168.2.108) request frequency is too hig
h.

root@toshiba:/home/john/wget# ./deb2.sh

--2015-07-26 13:09:59--  http://192.168.2.108:9000/api/search.rss?q=katyperry%0D
Connecting to 192.168.2.108:9000... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/rss+xml]
Saving to: 'search.rss?q=katyperry%0D.7'

search.rss?q=katype     [ <=>                  ]  32.32K  --.-KB/s   in 0s

2015-07-26 13:10:05 (64.8 MB/s) - 'search.rss?q=katyperry%0D.7' saved [33094]

**Comment by Orbiter** [comment]
fixed in latest commit; the push to the back-end is now made as a bulk for at lest 100 messages and with a pause of 2 seconds after sending the query. Before this was fixed, a side-effect of the caretaker polling-on-messages job caused that the push was made right after the search interface queries the back-end. That had cause the back-end to return an error to prevent DoS.
