### ISSUE TITLE
Gradle: Include complete lib/ directory for jars instead of manually including jars.

### ISSUE THREAD

**Issue by sudheesh001** [loklak/loklak_server#855]
Follow up on https://github.com/loklak/loklak_server/issues/854

Similar for gradle files.

**Comment by yukiisbored** [comment]
May I work on this?

**Comment by kavithaenair** [comment]
@sudheesh001 should all the dependencies be in one file like in dependencies.gradle?

**Comment by sudheesh001** [comment]
I think this issue is obsolete as we moved towards gradle from ant.
