### ISSUE TITLE
Search should include account names with search term just like twitter

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_server#858]
Search for "mariobehling" only includes results of other accounts, but not of the account with the name "mariobehling" itself. The twitter search includes these results.

Expected behavior: Results of account name should be included.

Test at: http://api.loklak.org/api/search.json?timezoneOffset=-480&q=mariobehling

**Comment by Orbiter** [comment]
implemented with https://github.com/loklak/loklak_server/commit/df57ae5324f995ecf9ebac2966491ca6dd40e262
