### ISSUE TITLE
Hide shortener URL

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_server#859]
The shortened URL of the loklak server currently shows something like loklak.org/someURL. 

It should rather display the target URL.

If it is longer than 22 characters it should show the 20 characters an 2 dots "..".

The link should be the loklak URL shortener, but the displayed URL should be the target URL.

**Comment by Orbiter** [comment]
implemented with https://github.com/loklak/loklak_server/commit/427a88800878082699e1106ea0aee009c7479e53
and
https://github.com/loklak/loklak_server/commit/928ec1552efc735088b60fc274d3af9eca75e26b

front-end iplementation can be done with https://github.com/fossasia/loklak_search/issues/108
