### ISSUE TITLE
Its possible to start server more than once then unable to kill all proccesses

### ISSUE THREAD

**Issue by smokingwheels** [loklak/loklak_server#86]
Was playing around 26-7-15 with my server and I found that I started it 4 times.
Caused excessive swap-file usage and the system was very slow I could only terminate one instance.
The Java CPU usage was approx 54% and constant.
During system shutdown "shutdown -r now" command there where 4 stop LS killrfkill1234 messages in the screen of the PC. I waited for awhile the killed the power and did a reboot.
After starting Loklak again I gave it a request every 2-4 sec and the load varied from 114% to 14%.
During fault condition the one of the Loklak servers was still responding to requests.
See https://www.youtube.com/watch?v=D6EsAEKYBPk&feature=youtu.be for video.

**Comment by Orbiter** [comment]
the only right way to fix this, is, to prevent that two loklak are started at the same time. This is fixed with https://github.com/loklak/loklak_server/commit/1b566d1cb3ca6892d2b76f8a88b47af3b315cc1a

**Comment by smokingwheels** [comment]
Thanks for the minor tweak
