### ISSUE TITLE
Update Docker Documentation

### ISSUE THREAD

**Issue by niccokunzmann** [loklak/loklak_server#863]
> the shell file is located at docker/docker-cmd.sh , should this line be updated accordingly ?
>
> Since you have expliclty mentioned the dockerfile location as /docker/ is it taking it from the same directory ? If that's the case, this would also need a documentation update on how to do the same.

TODO:
- update the documentation for where the docker file is located  
    - in [installation_docker.md](https://github.com/loklak/loklak_server/blob/development/docs/installation_docker.md) and in README.md
        - [ ] Bluemix
        - [ ] Amazon AWS
        - [ ] google cloud
        - [ ] DigitalOcean
        - [ ] add automatically built image: mariobehling/loklak:latest
        - [ ] add how to build the container yourself
    - in docker-compose.yml:
        - [ ] update to new location
- there is a docker tag "latest" for development and a tag "stable" for master

**Comment by niccokunzmann** [comment]
@sudheesh001 do you see any other locations where we need a documentation update?

**Comment by sudheesh001** [comment]
No I think this looks great.

**Comment by niccokunzmann** [comment]
@sudheesh001 I read through all the documentation. It works so far.
The only thing left, as I see it, is #868 - updating the docker-compose.yml file.

**Comment by adarsh-ideal** [comment]
@niccokunzmann What else is left, sir?

**Comment by niccokunzmann** [comment]
I do not know. But I assumed partial fix does not imply the issue is solved.

**Comment by niccokunzmann** [comment]
@adarsh-ideal I checked and all seems fine. Closing it. You can comment if I forgot something. Thanks!
I also opened #968 for restructuring. What are your thougts on what it should look like?

**Comment by adarsh-ideal** [comment]
@niccokunzmann I said partial because I solved a part of it.

**Comment by adarsh-ideal** [comment]
I'll check the issue. Thank you.
