### ISSUE TITLE
Declaration of project names on Gradle

### ISSUE THREAD

**Issue by yukiisbored** [loklak/loklak_server#870]
The name of the project should be declared inside `settings.gradle`. The reason for this is the fact if it doesn't exist, Gradle will assume the folder as the name of the project. To ensure the generated JAR files are named as the absolute project name (which is `loklak_server`), It is mandatory to declare the project name inside `settings.gradle`.

The usual reason why people will rename the folder is to organize or rename it to something like `My Loklak Server`.

**Comment by jayvdb** [comment]
Note this is solved by https://github.com/loklak/loklak_server/pull/850 . I presume that makes it ineligible for GCI due to anti-plagiarism rules at least. (I'm still seeking clarification regarding prior work for a different org at https://www.mediawiki.org/wiki/Talk:Google_Code-in_2016/Mentors )
