### ISSUE TITLE
Declare source compability to 1.8 for Gradle

### ISSUE THREAD

**Issue by yukiisbored** [loklak/loklak_server#871]
Java has this feature where you can declare the minimum required version needed to run a Java application. This should be declared by the developers. The other reason is to tell the IDE to use 1.8 because usually IDEs assumes you want to use 1.5/1.6 which can cause a ton of errors.

This should be declared in `build.gradle` to tell Gradle that this source is made for 1.8 and should be run with 1.8

**Comment by jayvdb** [comment]
Note this is solved by https://github.com/loklak/loklak_server/pull/851 . I presume that makes it ineligible for GCI .  (I'm still seeking clarification regarding prior work for a different org at https://www.mediawiki.org/wiki/Talk:Google_Code-in_2016/Mentors )

**Comment by jayvdb** [comment]
@mariobehling , why was this issue closed?

**Comment by mariobehling** [comment]
Sorry, by mistake. I just read it "is solved". So, what are the next steps here?

**Comment by jayvdb** [comment]
@mariobehling , re-open and merge #851 ?
If you want , after re-opening the pull request, the commit can be amended so that this issue number can be added to the commit body, to comply with the recently added rules.
