### ISSUE TITLE
Add Gradle generated classes to classpath for start/stop scripts

### ISSUE THREAD

**Issue by yukiisbored** [loklak/loklak_server#873]
The start/stop scripts on Loklak doesn't use Gradle generated classes at all. It only uses the ones generated by Ant. Gradle generated classes should be added because not everyone have Ant or want to use it.

**Comment by jayvdb** [comment]
Note this is solved by https://github.com/loklak/loklak_server/pull/852 . I presume that makes it ineligible for GCI due to anti-plagiarism rules at least. (I'm still seeking clarification regarding prior work for a different org at https://www.mediawiki.org/wiki/Talk:Google_Code-in_2016/Mentors )
