### ISSUE TITLE
Add Loklak Google Code-In task - Programming

### ISSUE THREAD

**Issue by niccokunzmann** [loklak/loklak_server#874]
- Issue type: Feature request

### Short description
Currently, we are running the Google Code-In Contest.
There are [tasks for Loklak](https://codein.withgoogle.com/tasks/?sp-organization=6707477701722112&sp-search=loklak) but no development task.

### Expected behaviour
- [ ] I would like to see some issues tagged as GCI here on the loklak Issue tracker.
- [ ] I would like to see a task for loklak [here](https://codein.withgoogle.com/tasks/?sp-organization=6707477701722112&sp-search=loklak)

### Description
Possible Markdown Description:

**Description**

Loklak is a distributed search engine for tweets, IoT and more.

**Requirements:**

- Comment on an [issue](https://github.com/loklak/loklak_server/issues) that you want to do it. If you have solved several tasks on this game before, you can not solve issues that are too easy for you because we need them to give others an easy start.
- Create a pull request or something that resolves the issue [issue](https://github.com/loklak/loklak_server/issues) which is tagged as GCI

**Expected Outcome:** 

- The issue is resolved, post a link to it so we can see you were the cause.

**Links/Tutorials:**

- [loklak](https://github.com/loklak/loklak_server)
- [GCI issues](https://github.com/loklak/loklak_server/issues?q=is%3Aissue+is%3Aopen+label%3AGCI)

**Comment by mariobehling** [comment]
@niccokunzmann I have added more tasks and specifically this one: https://codein.withgoogle.com/tasks/6036955466825728/

Regarding tagging things GCI: In my mind all tasks are open to GCI students, but you can tag them anyways, if you like.
