### ISSUE TITLE
Document how to switch to "aggressive mode"

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_server#875]
It is possible to increase the number of collected tweets without getting blocked if you are using cloud services.

Please document how to switch to aggressive mode in the Readme.md.

**Comment by smokingwheels** [comment]
I would rather deploy lots of Front Ends to avoid the problem.

**Comment by shiri04** [comment]
Can I work for this documentation

**Comment by daminisatya** [comment]
@shiri04 get the context before taking up an issue. Please write here first on what you are going to document.
