### ISSUE TITLE
Implement a settings page for loklak

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_server#876]
There are a number of configuration options for loklak. These are not shown in the UI yet. Please implement a settings page at "http://loklak.org/settings" to show the configuration.

Configurations are stored in the folder /conf. Please use these for the settings. (https://github.com/loklak/loklak_server/tree/development/conf)

The next step after this issue will be to make the settings editable by admin users.

**Comment by BrainBuzzer** [comment]
I am working on this.

**Comment by djmgit** [comment]
Hi mario,
I would like to work on this.
So for now, the settings page will just show the various configurarion options available for loklak server, to make the users aware of them, right?

**Comment by mariobehling** [comment]
@djmgit Yes, correct.

Please query the config options and the status from the config file. Thank you.

**Comment by djmgit** [comment]
@mariobehling How should I query the config.properties file. Is there any api available for this or should I try to parse the file manually by keeping a copy in the html folder?

**Comment by mariobehling** [comment]
Having a manually parsed page is not a suitable solution. Please propose a solution.

**Comment by BrainBuzzer** [comment]
Using regex to do this would be easy. Take the file configuration and pass it through. Using angular or node, this would be quite easy

**Comment by yukiisbored** [comment]
Hello,
Where should I put the class for `SettingsServet`?
`org.loklak.api.tools`?

**Comment by yukiisbored** [comment]
Does Loklak have a templating system, like the one on Jekyll?
I can't find it.

**Comment by yukiisbored** [comment]
@mariobehling Is it okay if I modify `org.loklak.api.admin.SettingsServlet`?
I want to do something like `POST` will handle settings update and SettingServlet will have two context paths (`api/settings.json` and `settings.html`)

**Comment by yukiisbored** [comment]
Anyway, I'm gonna move this conversation to the gitter room.
