### ISSUE TITLE
Allow websites to find available loklak instances

### ISSUE THREAD

**Issue by niccokunzmann** [loklak/loklak_server#888]
- Issue type: Feature request

### Short description
Help websites find out which loklak instances run and are available

### Expected behaviour
Loklak is a distributed application, also hosted by the community. Not every loklak server may be available all the time. Websites should be able to function nonetheless.

### Actual behaviour
However, websites tend to hard-code the loklak instance they use. This leads to downtime.

### Usecase
I would like that websites are able to check for running loklak instances which work best for them.

### Description
I would like that there is a small JavaScript snippet which chooses among possible loklak instances and returns a working loklak instance.

- [ ] Create a file which has a url of a loklak server at each line. Including: https://loklak.org https://loklak.quelltext.eu
- [ ] check if we can use javascript to retrieve the file from an unrelated website (cross origin may block)
  - [ ] if it blocks: let [travis](https://github.com/loklak/loklak_server/blob/development/.utility/push-docs-to-gh-pages.sh#L38) build a javascript file calling a function with it
- [ ] add a javascript which checks all instances of loklak in this list if they run
- [ ] document that once a server runs it can be added to the list

**Comment by gaeun** [comment]
Could I work on this? It seems like the issue on the GCI website was solved, but other websites might still rely on https.

**Comment by mariobehling** [comment]
There have been different implementation of this. If you would like a small app for this, please add the issue to labs.fossasia.org as a mini-project. Cheers.
