### ISSUE TITLE
Minimize Docker Image

### ISSUE THREAD

**Issue by yukiisbored** [loklak/loklak_server#891]
The size of the docker image for loklak_server is pretty large. The size is `752 MB` and that's quite large. What we can do to minimize it is to remove the source code (and other unnecessary stuff) after it's compiled and use a minimal Linux distribution as the base (like Alpine Linux)

**Comment by niccokunzmann** [comment]
We can squash installation steps, that add packages and remove the cached packages.
Also, the question is if we need ant, we we switch of the compiling - this will be even smaller.

I suggest, we create a new Dockerfile for this and test it out.

**Comment by niccokunzmann** [comment]
We can still minimize the image much more. If we turn of the auto-updating, we can create the files with ant and remove almost all installations.
Also, we can use Alpine Linux as described.
