### ISSUE TITLE
Create Alpine Linux Docker File

### ISSUE THREAD

**Issue by niccokunzmann** [loklak/loklak_server#893]
Resulted from #891.

Using Ubuntu as a basis for the docker image makes it larger. Maybe we do not need the whole Ubuntu. There is an Alpine Linux available which is very small.

Task: Use a smaller Linux as a  basis and create a new docker file. If it does not work with any of the small Linuxes, please tell.

**Comment by yukiisbored** [comment]
Can this be a GCI task, please? I'd love to do this issue, but I already did https://codein.withgoogle.com/dashboard/task-instances/4893210574848000/.

**Comment by niccokunzmann** [comment]
@yukiisbored I created a more general task which is waiting to be published: https://codein.withgoogle.com/dashboard/tasks/5143294927437824/
