### ISSUE TITLE
Generate a documentation site from the md files in a gh-pages branch

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_server#895]
The idea is to have one stop resource for loklak tech questions at http://dev.loklak.org

Please autogenerate a simple documentation site on each new commit in the gh-pages branch.

There is already a site documenting java classes here http://loklak.github.io/loklak_server/

What is the best option to put the documentation together in one place?

**Comment by adarsh-ideal** [comment]
@mariobehling Yeah sure! I I'll do this.

**Comment by adarsh-ideal** [comment]
@mariobehling Completed the documentation site.

**Comment by mariobehling** [comment]
@adarsh-ideal I think I did not describe the goal entirely correctly. It seems like the site is not auto-generated from the md files in the development branch on each commit. This would be the goal.

Or is it done that way already? Then could you point me to the code that auto-generates it, please?

**Comment by Abhi2424shek** [comment]
I would like to work on it please

**Comment by mariobehling** [comment]
@Abhi2424shek Any updates?

**Comment by mariobehling** [comment]
Closing this issue in favor of https://github.com/loklak/loklak_server/issues/964
