### ISSUE TITLE
Add Gradle Wrapper

### ISSUE THREAD

**Issue by yukiisbored** [loklak/loklak_server#897]
Having gradle wrapper inside loklak_server really helps user who doesn't have `ant` or `gradle` installed on their machine. Because, gradle wrapper runs a local version of gradle without having to install it. So for users who just want to use and run loklak can do it easily without having the hassle of installing `ant` or `gradle`.

**Comment by mariobehling** [comment]
Very good idea. Could this also be relevant for the Heroku deployment? Currently it is not working. Would be great, if you could help with it.

**Comment by yukiisbored** [comment]
@mariobehling Can you give more detail about the heroku deployment, like logs?

**Comment by mariobehling** [comment]
@yukiisbored I have added you to the Heroku app. Please accept the invitation and have a look. The app should be working here https://loklak-server-dev.herokuapp.com/
