### ISSUE TITLE
Move loklak.org download page to docs/tutorials.md

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_server#902]
We want to keep all loklak developers info in one place. Therefore we need to move the information on http://dev.loklak.org/tutorials.html into the repository at docs/tutorials.md.

Please ensure a simple markdown is in place.

Once the information is moved, delete the architecture html in the repo and the top links.

**Comment by fatimarafiqui** [comment]
Can I do this?

**Comment by jig08** [comment]
Sure, go ahead.

**Comment by fatimarafiqui** [comment]
Just to be sure I am deleting html/tutorials.html and removing tutorials.html link from the Top Menu.
