### ISSUE TITLE
Fix parsing collection from twitter

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_server#903]
Twitter has changed their website. This causes challenges for the loklak parser and reduces the number of tweets collected. Please adapt the parser to work with the updated design.

Please see the error log below:

>  2016-12-23 15:48:32.672:WARN :Caretaker:Thread-102: CARETAKER THREAD java.lang.StringIndexOutOfBoundsException: String index out of range: -1 at java.lang.String.substring(String.java:1955) ~[?:1.8.0_45] at org.loklak.harvester.TwitterScraper$prop.<init>(TwitterScraper.java:352) ~[classes/:?] at org.loklak.harvester.TwitterScraper.search(TwitterScraper.java:205) ~[classes/:?] at org.loklak.harvester.TwitterScraper.search(TwitterScraper.java:115) ~[classes/:?] at org.loklak.harvester.TwitterScraper.search(TwitterScraper.java:66) ~[classes/:?] at org.loklak.data.DAO.scrapeTwitter(DAO.java:1080) ~[classes/:?] at org.loklak.Caretaker.run(Caretaker.java:189) [classes/:?]

**Comment by Orbiter** [comment]
fixed with https://github.com/loklak/loklak_server/commit/306fb56bfd81a48f2bd854ab5ab0e5b826632efb
