### ISSUE TITLE
Dashboard links incorrect

### ISSUE THREAD

**Issue by Velociraptor85** [loklak/loklak_server#906]
- Issue type: Bug report

### Short description
Links in the Dashboard reference to the local server with attached URL.

### Environment
 - Operating system: Linux
 - Software source: github clone

### Steps to reproduce
1. setup like discribed via ant 
2. install.sh
3. start.sh
4. look in the WUI and check the Links

### Expected behaviour
Dashboard with URLS correct to the local Server Or directly to loklak.org but not this mixed Link which does not work.

### Actual behaviour
Like described URLs are int the format <server>/http://loklak.org/<url>

See attached Image.
![bug](https://cloud.githubusercontent.com/assets/4143960/21471238/16b61754-caab-11e6-9b5b-31f1fd538994.PNG)

**Comment by yukiisbored** [comment]
I think it should use `/about.html` instead of `http://loklak.org/about.html`. This can be easily fixed, but I'm not quite sure if `/about.html` is their intention.

**Comment by Velociraptor85** [comment]
@yukiisbored yap what I thought, its to be fixed in the html/index.html also I am not sure if loklak.net is the correct URL but this might be a different issue

**Comment by mariobehling** [comment]
@yukiisbored Thanks. Please feel free to fix it. As we are separating documentation, search and other areas, the design will change as well soon. For now a quick fix would be fine as well.
