### ISSUE TITLE
Implement an admin role to change the configuration on the settings page

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_server#919]
The settings page already enables changes on localhost. Please also implement the ability of an admin on systems on the Internet.

* [ ] Use the account apps to administer roles
* [ ] Make settings viewable to anonymous users only
* [ ] Make settings editable by admin users
* [ ] Merge the dumps page in the settings page

**Comment by mariobehling** [comment]
The account apps were taken out some time ago when we moved the "apps" to http://apps.loklak.org. Please re-add the account apps in order to proceed. Compare to http://apps.loklak.org/#AccountsAPI

**Comment by yukiisbored** [comment]
Hi @mariobehling, Which GCI task can I do for this?

**Comment by Orbiter** [comment]
disabled in https://github.com/loklak/loklak_server/commit/9bb1a21a6d0acff92659f0e130c84b61fd6b9c9b

This was the main cause that api.loklak.org was unavailable in the last three months.
Every time I had to clean up the mess that the storage process had caused. Fortunately I had a back-up of the settings file. The stored file was a big mess, full of binary data and caused that loklak was then unable to start again.

**Comment by mariobehling** [comment]
@Orbiter We need a proper handling, maybe difference between config and settings file? How can we get this feature?
