### ISSUE TITLE
Move Javadocs to subfolder on gh-pages

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_server#921]
Javadocs are generated with travis through the script here: https://github.com/loklak/loklak_server/blob/development/.utility/push-javadoc-to-gh-pages.sh

Please change the deployment so, that the docs move into a subfolder "javadocs".

**Comment by fatimarafiqui** [comment]
Can I give it a try?

**Comment by mariobehling** [comment]
Sure.

**Comment by mariobehling** [comment]
Closing in favor of: https://github.com/loklak/loklak_server/issues/964
