### ISSUE TITLE
Implement one button deployment to Google Cloud

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_server#923]
We have one button deployments to a number of solutions. Please implement the one-button deployment to Google cloud and add the button to the readme.md.

**Comment by KukkadapuSushma** [comment]
I want to work on this task! @daminisatya

**Comment by daminisatya** [comment]
@KukkadapuSushma You can work, but for some reason I'm not able to assign a member to this issue. 

@mariobehling Please have a look.

**Comment by mariobehling** [comment]
@KukkadapuSushma I have invited you to loklak friends. Please accept the org invite and we assign you.

@daminisatya Only people who are organization members can be assigned to issues. Please invite people to the friends team as a starter.

**Comment by daminisatya** [comment]
@mariobehling Sure :D

**Comment by mariobehling** [comment]
Not required at the moment.
