### ISSUE TITLE
Create a page showing all users and their role for admins

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_server#929]
As loklak will have more features tied to user accounts in future, we need to get features for admins and specifically a users page.

Please create a page listing all users with a link to edit the user accounts for admins.

This page should only be accessible for admins.

**Comment by fatimarafiqui** [comment]
Can I take this?

**Comment by jig08** [comment]
@fatimarafiqui Sure you can, go one step (read: issue) at a time. Resolve the previous one and you can surely have this. Cheers :)

**Comment by fatimarafiqui** [comment]
@jig08 @mariobehling I am done with all my previously assigned issues. Now, Can I take this?
