### ISSUE TITLE
Establish consistent code style

### ISSUE THREAD

**Issue by yukiisbored** [loklak/loklak_server#934]
Currently the project has inconsistent code styles, it kills maintainability of the project, and makes it harder for everyone to contribute.

The reason to have a single and consistent code style is because:
1. It makes the code easier to read because if everything is using the same style we can read code faster and see the purpose/logic faster without having to read it bit by bit. 
2. It's easier to write code because you don't have to guess the variable/method names (unlike PHP where you have to remember it because it's a mess of camelCase, PascalCase, and SnakeCase)
3. Makes it readable, readable code is important because how can you know what I does if you can't even read it.

I'm proposing the usage of the [Google's Java style guidelines](https://google.github.io/styleguide/javaguide.html) because it's commonly used and it's easier to integrate to most Java IDEs (IntelliJ IDEA and Eclipse)

To enforce the code style and preventing changes that violates the code style, We can use `coala` with `CheckstyleBear` to enforce it.

**Comment by mariobehling** [comment]
Sounds good.

**Comment by sudheesh001** [comment]
Related to #251 This is definitely good to have.

**Comment by mariobehling** [comment]
Ok, so this kind of issue is pretty broad and solving this issue could be a huge tasks. Some improvements have been made, but which area to tackle exactly now? Let's focus on more specific tasks, that can be solved in the best case within a day.

If you want to add Coala, the simply add an issue "Add Coala.." and other more specific issues. Cheers.
