### ISSUE TITLE
Won't compile after upgrading old version 

### ISSUE THREAD

**Issue by smokingwheels** [loklak/loklak_server#95]
31-7-2015 3:10 PM +8
init:

build:
   [delete] Deleting directory /var/loklak_server/classes
    [mkdir] Created dir: /var/loklak_server/classes
     [echo] loklak: /var/loklak_server/build.xml
    [javac] Compiling 114 source files to /var/loklak_server/classes
    [javac] /var/loklak_server/src/org/loklak/Main.java:68: error: method init i
n class DAO cannot be applied to given types;
    [javac]         DAO.init(data);
    [javac]            ^
    [javac]   required: Map<String,String>,Path
    [javac]   found: File
    [javac]   reason: actual and formal argument lists differ in length
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 1 error

BUILD FAILED
/var/loklak_server/build.xml:67: Compile failed; see the compiler error output f
or details.

Total time: 9 seconds

**Comment by Orbiter** [comment]
not reproducible. I triple-checked this in different environments. Please `git pull origin master`.

**Comment by smokingwheels** [comment]
I had to backup and start again..all good now.
