### ISSUE TITLE
Prevent self-merging pull requests

### ISSUE THREAD

**Issue by yukiisbored** [loklak/loklak_server#953]
Anyway, this issue started to prevent something like https://github.com/loklak/loklak_server/pull/952 from happening again (I **really** regret that). Pull requests should be reviewed by other people and nobody should be allowed from merging their own PRs. 

We can utilize something like [rultor](http://www.rultor.com) to do the pull request merging for us instead of using the tempting big green button.

**Comment by yukiisbored** [comment]
@rultor hello

**Comment by Abhi2424shek** [comment]
@niccokunzmann or @mariobehling @rultor is awesome can you add him as a collaborator and use him to  merge and deploy

**Comment by Abhi2424shek** [comment]
Can we have it

**Comment by sudheesh001** [comment]
I am in favour of rultor for doing the merges, allows us for stronger reviews and better quality. Can someone set this up ? I'll add rultor to the contributors.

**Comment by Abhi2424shek** [comment]
Thanks

**Comment by Abhi2424shek** [comment]
Can we check it up

**Comment by daminisatya** [comment]
@sudheesh001 How can we progress with adding rultor, cause we should be able to integrate it before the gsoc period starts.

**Comment by Abhi2424shek** [comment]
@daminisatya i think it's integrated already.

**Comment by Abhi2424shek** [comment]
@rultor hello

**Comment by daminisatya** [comment]
@Abhi2424shek Then we are good to close this?

**Comment by Abhi2424shek** [comment]
@daminisatya we could try it on a PR try to make a simple PR and merge it. We should check it shouldn't we?

**Comment by yukiisbored** [comment]
No, it's not that simple. We require a configuration file to make it work properly.

**Comment by mariobehling** [comment]
Ok, some additional best practices have been defined in the FOSSASIA org in the meantime. Rultor also has access to this repo. Anyone would like to continue working on this area, please help, especially if you open an issue. Thank you.
