### ISSUE TITLE
Propose and implement deployment solution for loklak main server

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_server#956]
The current loklak main server resides on a IBM Bluemix server. The goal is to move it to the Google Cloud system.

**Comment by Orbiter** [comment]
The current home of the loklak.org server is a two-server system where each of the two servers has four physical disc drives with one terabyte each. With the current index of 1.6 billion tweets the disk state on the host000 (the first the the two servers) is
```
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda6       916G  449G  421G  52% /
/dev/sdb1       917G  396G  475G  46% /media/disk1
/dev/sdc1       917G  363G  508G  42% /media/disk2
/dev/sdd1       917G  331G  541G  38% /media/disk3
```
On the second server host001 the situation is similar, the second also hosts a full copy of all compressed tweets which takes up 200GB extra.

On each of the two servers one elasticsearch instance runs with 11GB RAM assigned. Each of these instances run four virtual internal instances which can be configured using the path.data value in the elasticsearch.yml file:
```
cluster.name: loklakcluster
node.name: host000_node0
node.master: true
node.data: true
discovery.zen.ping.multicast.enabled: false
discovery.zen.ping.unicast.hosts: ["host000", "host001"]
network.host: [_local_, _non_loopback_, _bond0_, _bond1_]
cluster.routing.allocation.same_shard.host: true
path.data: ["/home/loklak/node0/data", "/home/loklak/node1/data", "/home/loklak/node2/data", "/hom
e/loklak/node3/data"]
indices.fielddata.cache.size: 20%
```
Therefore we have eight instances for eight disks which should provide a perfect single IO tasks for each disk. We use oversharding to access the 8 instances using 16 shards for all indexes.
IO can therefore be balanced over 8 disks and CPU can be balanced over two physical servers.

The remaining RAM on the machines are taken by two loklak instances, which are balanced using a NGINX configuration. The nginx configuration chooses host000 as default and host001 as backup instance but it also chooses some more servers which I run as additional backup in case that the cluster on node000/node001 needs maintenance.

**Comment by Orbiter** [comment]
I added the hq-plugin to elasticsearch which enables monitoring of the search cluster. Here are screenshots:
<img width="1230" alt="hq_dash" src="https://cloud.githubusercontent.com/assets/238730/21748650/24b33014-d58a-11e6-9a51-8592daa8c0c4.png">
<img width="1232" alt="hq_diagnostics" src="https://cloud.githubusercontent.com/assets/238730/21748653/2b5697bc-d58a-11e6-8027-2d64268c02f9.png">
<img width="1232" alt="hq_tree" src="https://cloud.githubusercontent.com/assets/238730/21748655/2ede2b98-d58a-11e6-890a-e3c3db6ae42e.png">

The new installation should provide
- separate loklak installations (several, with fail-over configuration) without embedded elasticseach enabled
- an elasticsearch cluster consisting of at least 16 shards. configured with one replica shard.

**Comment by yukiisbored** [comment]
We can use two docker containers and I'm not quite sure how you scale Elastic, is there a way to make it remote?

**Comment by smokingwheels** [comment]
I'm no Linux admin.
1. Is it possible to plot Data Growth over time (julian days)?
If so estimate Data acceleration over time just on a graph by looking into the future?
From memory there was about ~80GB I had harvested in 4 months.
2. Test actual bandwidth between Data centers (Not at just at each end.) 
Use wget with resume options on a few GB test file. Put test in a loop pipe output to file >>.
Would not take to much to write script if you had listings of files in directories then transfer over on SSH. 

I will Tweet this Issue a few times over the coming days. [Tweet]https://twitter.com/smokingwheels/status/819625346324537344)

**Comment by mariobehling** [comment]
Closing this as there are other issues related to Google cloud and call for hosting open.
