### ISSUE TITLE
Autogenerate html documentation site from docs folder and put javadocs in subfolder

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_server#964]
Currently on each pull request there are javadocs automatically generated and everything gets deleted on the gh-pages branch.

Expected: 

* [ ] Create a site in dev.loklak.org (gh-pages branch) 
* [ ] Generate a site automatically from the /docs folders in the development branch
* [ ] Add the javadocs into the subfolder -> change the script that is used to generate the javadocs here: https://github.com/loklak/loklak_server/blob/development/.utility/push-javadoc-to-gh-pages.sh

**Comment by mariobehling** [comment]
Closing this issue in favor of https://github.com/loklak/loklak_server/issues/964

**Comment by mariobehling** [comment]
@jig08 Please follow up here, if you have questions: Closing this issue in favor of #964

**Comment by mariobehling** [comment]
ah sorry. I see.

**Comment by Abhi2424shek** [comment]
I have a query, should the site be built like a readme file that we on github or like a professional site enhanced with rich buti full material design ;)

**Comment by mariobehling** [comment]
@Abhi2424shek The source and structure of the site should come from the md files, but good design is the goal. What approach are you taking?

**Comment by Abhi2424shek** [comment]
I think I would use the readme files as it is with the help of material themes.

**Comment by yukiisbored** [comment]
IMVHO, we shouldn't care about designs and other unnecessary stuff. We should think about how to get this to work and get it to work properly. I recommend using read the docs or sphinx because we can use it to render viewable HTML pages.

**Comment by Abhi2424shek** [comment]
Here is my approach on the gh-pages branch we would place some layout information, including a theme. Then for each commit made in the development branch (commits can also include PR merge commits and not PRs) if it updates any of the documents, a new commit will be made to the gh-pages branch via Travis and a bot or my account with an access token! The index.md file would be updated which of course github pages gives the ability to place themes for.

**Comment by mariobehling** [comment]
@niccokunzmann Sorry, but this is issue is still pending. The gh-pages branch still only autogenerates the javadocs on commits. A CNAME dev.loklak.org has been added, that only shows javadocs at the moment, but is still lacking other information.

**Comment by yukiisbored** [comment]
@mariobehling that's because the script that updates it only runs when it's on master, want me to remove that condition?

**Comment by mariobehling** [comment]
@yukiisbored I think we should build a documentation site on each commit, development and master.
