### ISSUE TITLE
Merge docker build sections

### ISSUE THREAD

**Issue by niccokunzmann** [loklak/loklak_server#968]
There are two sections that should be merged or restructured:

https://github.com/loklak/loklak_server/blob/development/docs/installation_docker.md#get-a-loklak-docker-image

https://github.com/loklak/loklak_server/blob/development/docs/installation_docker.md#build-your-own-docker-container

Constraints:
- We need to know where to get an image from at the start of the documentation

**Comment by adarsh-ideal** [comment]
I'll restructure it.
