### ISSUE TITLE
Host documentation on readthedocs

### ISSUE THREAD

**Issue by niccokunzmann** [loklak/loklak_server#972]
The documentation is generated by sphinx #971. The next step is to use [readthedocs](http://readthedocs.org/) to show the documentation. benefits:

- There is a documentation for each branch.
- There is a badge for documentation build.
- We can go back and forth between docs and docs files.

**Comment by yukiisbored** [comment]
Isn't better if we use reStructuredText for the documentation instead of Markdown?
Other than the obvious reason that `docutils`, `sphinx`, etc supports it natively, it has cool features like directives, roles, etc and it has more things that we can do than Markdown, anyway. Also as of now the `sphinx` setup doesn't parse the table correctly.

**Comment by niccokunzmann** [comment]
Zes, this could be another issue.

**Comment by mariobehling** [comment]
Ok, let's discuss this a bit more. With Readthedocs we don't seem to have as much control over the site as with our own deployment in our own gh-pages branch. The documentation should be hosted on http://dev.loklak.org and the javadocs are already in the repo. So, we are now separating the documentation with the readthedocs approach, whereas the goal of the recent documentation efforts was to unify it in one place in the gh-pages branch and have it easily readable in GitHub itself as well as md files.

**Comment by mariobehling** [comment]
So, looking over this, I think there does not need to be an either or approach. We can have both: Documentation on Readthedocs and on the gh-pages branch. To make this sustainable the documentation should be kept in md-files though.

In the Open Event Orga Server we use the script here: https://github.com/fossasia/open-event-orga-server/blob/development/scripts/push_api_docs.sh to do the following:
- Files inside the doc folder on `development` are edited
- PR is submitted to `development`
- PR merged
- At one point, `development` is merged to `master`.
- At that point, `gh-pages` gets updated from the docs folder in `master`

**Comment by niccokunzmann** [comment]
I just found a tool for markdown: http://www.mkdocs.org/ @yukiisbored it is markdown. Maybe we can try it for the docs.

**Comment by mariobehling** [comment]
Documentation is now on http://dev.loklak.org
