### ISSUE TITLE
Documentation deployment is failing

### ISSUE THREAD

**Issue by yukiisbored** [loklak/loklak_server#977]
For some reason the deployment for the documentation page is failing

**Comment by mariobehling** [comment]
Please move the script to the repo itself. It might be related to this.

**Comment by yukiisbored** [comment]
@mariobehling The script on the server is for the google cloud deployment.

**Comment by mariobehling** [comment]
@yukiisbored Yes, would it be an option to host it here and to put the keys into travis? Did you follow a tutorial to create it? Link? Actually if the script would be in the repo, it would also allow others to use the same deployment method, would it? However, this is probably unrelated to this issue.
