### ISSUE TITLE
Move table of contents into main content area

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_server#981]
The Table of Contents of each page is visible on the left sidebar. Some pages have their own "hand-made" table at the beginning of the article. 

Please implement a common way: Move the Table of Contents from the sidebar to show up below the Title/Heading of each page.

Or: Is it better to create the table of contents manually?

![screenshot from 2017-01-14 14-17-07](https://cloud.githubusercontent.com/assets/1583873/21955124/b06f7fc0-da64-11e6-9814-8187224af5b1.png)

**Comment by mariobehling** [comment]
On second thoughts: Actually the sidebar with the Table of Contents is pretty nice in the API documentation page (http://dev.loklak.org/development/api.html). I am not familiar with Sphinx. Can we define "No Table of Contents" like in a wiki alternatively on specific pages?

**Comment by yukiisbored** [comment]
@mariobehling I don't think we can do that, I think it's better to remove the ToCs that the original file has because they're made before this was implemented.

**Comment by AnaghHegde** [comment]
@mariobehling @yukiisbored can i work on this ?. Can you please brief me a little ?.

**Comment by yukiisbored** [comment]
@AnaghHegde Loklak uses sphinx to generate the documentation and it's generated via CI. The script that does this is located inside the .utility folder, but I don't think that can solve this enhancement. The configuration for sphinx is inside the docs folder as a file named `conf.py`.

**Comment by AnaghHegde** [comment]
@yukiisbored I don't know sphinx. Is it required or just python is enough ?.

**Comment by yukiisbored** [comment]
@AnaghHegde Read the documentations on their site: http://www.sphinx-doc.org/en/stable/. Sphinx uses Python but I don't think you require a lot of Python knowledge (unless you're planning to create your own extension). Happy Hacking!

**Comment by mariobehling** [comment]
This issue will be tackled in a documentation project. Thanks.
