### ISSUE TITLE
Improve top bar with logo and add Search and Developers links to top menu bar

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_server#993]
* Please add the logo with the light pinkish background to the top bar on the left and set the link to the home directory. Use css to make it. loklak should use the font Courier New.
![screenshot from 2017-01-14 18-14-59](https://cloud.githubusercontent.com/assets/1583873/21956632/7a11ad1a-da85-11e6-9627-28778775d1c4.png)

* Also take out "Home"

* Add "Search" (http://loklak.net) and "Developers" (http://dev.loklak.org) to the top bar and implement the following order
   * Search
   * Apps
   * Developers
   * API
   * Dumps
   * About
   * Blog

**Comment by yukiisbored** [comment]
Are you talking about loklak.org?

**Comment by mariobehling** [comment]
Yes, on the server application itself which is on loklak.org/api.loklak.org.

**Comment by kavithaenair** [comment]
Please assign me this issue.I would like to work on this @mariobehling

**Comment by daminisatya** [comment]
@kavithaenair you can start working on this issue.

**Comment by daminisatya** [comment]
@mariobehling Im not able to assign @kavithaenair can you please assign her. thank you

**Comment by mariobehling** [comment]
@daminisatya New contributors have to join the organization first before we can assign issues to them. 

@kavithaenair Invited you.

**Comment by daminisatya** [comment]
@mariobehling Sorry i miss took it for fossasia org!

**Comment by kavithaenair** [comment]
PR - #1039
